### ISSUE TITLE
Supporting ASP.NET vnext 

### ISSUE THREAD

**Issue by devmondo** [JimBobSquarePants/ImageProcessor#100]
hi, 
i am trying to currently use the library in ASP.Net vnext project, but the problem is the use of System.Drawing, which is not supported in VNext, any advice ?

thanks in advanced.

**Comment by Gillardo** [comment]
Is this still working??  I have added a new project and need to reference System.Drawing, so i have this, but it says error

```
"frameworks": {
        "net50": {
            "dependencies": {
                 "System.Drawing": ""
            }
        }
    }
```

**Comment by JimBobSquarePants** [comment]
Hi Gillardo, what do you mean by "Still working"? Did you previously have it working? What was your error message?

**Comment by Gillardo** [comment]
No i didnt have it working at all, i couldnt get it to woek by referencing
Syste.Drawing

**Comment by JimBobSquarePants** [comment]
Do you have an error message. I haven't attempted to get this version working with vNext I've started a v3 branch for that.

**Comment by JimBobSquarePants** [comment]
I'm closing this for now as I will be supporting net core in the new V3 codebase.
