### ISSUE TITLE
Failing image

### ISSUE THREAD

**Issue by cosmo0** [JimBobSquarePants/ImageProcessor#113]
Hey :smile: 

This image is throwing an out of memory exception :
https://github.com/cosmo0/ImageProcessor/blob/failing-image/test5.jpg
It has a pretty big resolution (9387 x 12701) but a pretty medium size. I'm guessing it's a scanned photo.

Thanks :)

**Comment by cosmo0** [comment]
For information, it seems that the developers using the library were loading the image into a byte buffer, and then reading this buffer into a stream. So many data duplication! Reading the file directly into a file stream seems to be solving the issue.

I will keep you updated on the matter, but I think it's just an implementation problem.

**Comment by JimBobSquarePants** [comment]
Yup... That'll do it. That makes much more sense now. Thanks for the update.

**Comment by cosmo0** [comment]
Another failing image, this time reading directly from the file. It's a pretty heavy application (at that point it has already ~300Mb memory used and not even started to load the images), but it's the `ImageFactory.Load` part that triggers the `OutOfMemoryException`. I'm still investigating.

**Comment by cosmo0** [comment]
Since it's not related directly to the library I'll close the issue.
