### ISSUE TITLE
Gif padding not working

### ISSUE THREAD

**Issue by danbramall** [JimBobSquarePants/ImageProcessor#117]
Hi,

I'm using ImageProcessor to resize some company logos in Umbraco 6.2.4 (the version of ImageProcessor that is shipped with this by default - not sure how to find that out).  Anyhow, logos are being called like this: http://www.example.com/media/5233/filename.png?width=100&height=100.  This is outputting a 100x100 image, with padding added where it should.  All good.  However, where .gif files are used no padding is being added.

This could be an issue with the gif files uploaded by the client, but I wanted to post here in case someone could replicate and confirm the issue or not.

Thanks.

**Comment by danbramall** [comment]
This needs more investigating (on my part) as it does seem to relate to the specific images rather than a bug with ImageProcessor as far as I can tell.

**Comment by JimBobSquarePants** [comment]
Hi Dan,

ImageProcessor isn't shipped with any of the Umbraco v6 builds. It was added in v7.1.

You can always check what version is installed using the package.config or r-clicking the binary itself.

Could you upload a copy of one of the gif files so I can have a look anyway? I'd like to see what is going on.

Cheers

**Comment by danbramall** [comment]
Hey James.  You raise a very good point - this library isn't even included in v6 so it's actually using a completely different HTTP handler for image resizing.  #h5is :)  Thanks for your quick reply though, and keep up the stirling work on this (and your other O/S projects).

**Comment by JimBobSquarePants** [comment]
Haha, Thank you and no worries. :smile: 

ImageProcessor is actually perfectly usable with Umbraco v6 so if your other library is having trouble with gifs and you can't find a solution you can get it here. https://www.nuget.org/packages/ImageProcessor.Web/
