### ISSUE TITLE
RemoteImageService 'prefix' not working

### ISSUE THREAD

**Issue by kipusoep** [JimBobSquarePants/ImageProcessor#121]
I just updated ImageProcessor in one of our webapplications and found out the 'prefix' property of the RemoteImageService configuration isn't properly used anymore.
- Leaving it as '/remote.axd' works.
- Setting it to '/remote.php': the '/remote.php' URL doesn't work, the 'remote.axd' URL works
- Setting it to '/remote': the '/remote' URL doesn't work, the 'remote.axd' URL works

IP v2.1
IP.Web v4.1.4
IP.Web.Config v2.1

**Comment by kipusoep** [comment]
Just did a debug session and it seems like the 'Prefix' property isn't loaded from the configuration anymore (it was set to 'remote.axd', while I changed it in the config).

**Comment by JimBobSquarePants** [comment]
Do you have `autoLoadServices="false"` set in the configuration? 

I might get rid of that check so that if configuration is present it just loads.

**Comment by kipusoep** [comment]
No it's set to true.
Ps; get some sleep ;-)

**Comment by JimBobSquarePants** [comment]
Set it to false and it should start working as expected. Will do! :smile:

**Comment by kipusoep** [comment]
Oh lol, mindfuck :-p
Why is it set to true by default anyway?

**Comment by JimBobSquarePants** [comment]
Because I'm daft. The next release wont have the option. If the config file is present it will automagiclly kick in.
