### ISSUE TITLE
Feature request: Configure watermark plugin to override regex'es for each of the props

### ISSUE THREAD

**Issue by netaddicts** [JimBobSquarePants/ImageProcessor#123]
Currently bitten by restraint to not use comma char in watermark text. So, would be great if we could add our custom regex'es overriding the default ones as specified in Processing.config.

I'm not sure if that's the best place to put those custom regex'es.

Feedback appriciated!

**Comment by JimBobSquarePants** [comment]
To be honest I think we would be better off reworking the plugin to be less restrictive than add more complexity through regular expressions. 

I plan, one day to switch the whole thing to use a more Json style parsing method. This should remove most of the parsing complexity within the application.

**Comment by JimBobSquarePants** [comment]
Just to update. I'm replacing the parser in the next release with a much improved one. This will allow a watermark to be made from any url encoded string value.

**Comment by JimBobSquarePants** [comment]
Fixed in [v4.3.0](https://www.nuget.org/packages/ImageProcessor.Web/)
