### ISSUE TITLE
OutOfMemoryException on ImageFactory.Load(stream)

### ISSUE THREAD

**Issue by ilivewithian** [JimBobSquarePants/ImageProcessor#126]
I'm having a bit of trouble tracking down an issue where `ImageFactory.Load(stream)` throws an `OutOfMemoryException`.

The code I'm running is pretty simple, I take a stream of data from a web api endpoint and send it through to the following class.

    public class ImageOperations
    {
        private readonly byte[] _imageData;

        public ImageOperations(Stream imageStream)
        {
            using (var br = new BinaryReader(imageStream))
            {
                _imageData = br.ReadBytes((int) imageStream.Length);
            }
        }

        public Stream ScaleImage(int width, int height)
        {
            var outStream = new MemoryStream();
            
            using (var imageFactory = new ImageFactory())
            {
                using (var inputStream = new MemoryStream(_imageData))
                {
                    imageFactory
                        .Load(inputStream)
                        .Constrain(new Size(width, height))
                        .Format(new JpegFormat{Quality = 85})
                        .BackgroundColor(Color.White)
                        .Save(outStream);
                }
            }

            outStream.Position = 0;
            return outStream;
        }
    }

This runs fine for the most part, but about 3% of calls fail with an `OutOfMemoryException` what might I be doing wrong?

**Comment by JimBobSquarePants** [comment]
Hi there. Looking at the code I don't see anything obvious. How big are the images? Do you have any samples you could send me? 

@cosmo0 You've had some experience recently troubleshooting this kind of issue. Do you have any ideas?

**Comment by ilivewithian** [comment]
I have a few sample images, but the problem is that they don't always fail. Of about 1000 images uploaded over the weekend 36 failed. Reports from ours users say that his happens intermittently. I've attached a couple of samples.

I'm not sure if this makes any difference, but we use the code in the slightly wider context of:

        private async Task GenerateThumbnails(Stream stream, ImageDetail detail)
        {
            var operations = new ImageOperations(stream);

            var fullSizeImage = ConvertAndStoreImage(operations, detail, _sizes[0]);
            var largeSizeImage = ConvertAndStoreImage(operations, detail, _sizes[1]);
            var mediumSizeImage = ConvertAndStoreImage(operations, detail, _sizes[2]);
            var smallSizeImage = ConvertAndStoreImage(operations, detail, _sizes[3]);
            var tinySizeImage = ConvertAndStoreImage(operations, detail, _sizes[4]); 
            
            await Task.WhenAll(fullSizeImage, largeSizeImage, mediumSizeImage, smallSizeImage, tinySizeImage);

            detail.FullSizeURL = fullSizeImage.Result;
            detail.LargeSizeURL = largeSizeImage.Result;
            detail.MediumSizeURL = mediumSizeImage.Result;
            detail.SmallSizeURL = smallSizeImage.Result;
            detail.TinySizeURL = tinySizeImage.Result;
        }

        private async Task<string> ConvertAndStoreImage(ImageOperations operations, ImageDetail detail, ImageSizeInfo size)
        {
            var container = string.IsNullOrWhiteSpace(detail.Category) ? string.Format("Images-{0}", detail.Category) : "Images";
            var blobName = string.Format("{0}.jpg", Guid.NewGuid());

            var blob = await _storageContext.GetBlob(container, blobName);

            using (var image = operations.ScaleImage(size.Width, size.Height))
            {
                blob.Properties.ContentType = "image/jpeg";
                blob.Properties.CacheControl = "public, max-age=31536000";
                await blob.UploadFromStreamAsync(image);
                return blob.Uri.ToString();
            }
        }

![sample 1](https://cloud.githubusercontent.com/assets/422605/6018347/e81617ac-ab8d-11e4-813d-f80c9b956b8d.jpg)
![sample 1](https://cloud.githubusercontent.com/assets/422605/6018348/e8192708-ab8d-11e4-86b8-258a37c23e25.jpg)

**Comment by JimBobSquarePants** [comment]
I would have a good look to see if you are creating multiple copies of the stream. I'll do some tests against these images tonight.

Incidentally. You should actually be able to use the same stream for both input and output. I did some work recently to allow that.

**Comment by JimBobSquarePants** [comment]
Apologies for the slow reply. 

I did some tests against the images you provided and was able to resize them without issue. I didn't go over 54mb memory usage at any point

On a closer look at your code it looks like you are making 4 copies of the image on each instance. 

 1. `imageStream` globally
 2. `_imageData ` 
 3. `inputStream`
 4. `outStream `

Of the copies in objects that implement `IDisposable` It looks like you are only disposing of `inputStream ` Five instances of `outStream` are getting created and not destroyed for each set of dimensions.

I think you are leaking memory and causing an `OutOfMemoryException`. That it is intermittent backs up that idea. It's certainly not ImageProcessor anyway as all memory is released on disposal.
