### ISSUE TITLE
Cannot crop image

### ISSUE THREAD

**Issue by Radzhab** [JimBobSquarePants/ImageProcessor#133]
i want crop image but this code not work correctly
CropLayer cropLayer = new CropLayer(20,20,20,20, ImageProcessor.Imaging.CropMode.Percentage);
using (MemoryStream inStream = new MemoryStream(photoBytes))
            {
                using (MemoryStream outStream = new MemoryStream())
                {
                 
                    using (ImageFactory imageFactory = new ImageFactory(preserveExifData:true))
                    {
                        imageFactory.Load(inStream); 
								
						imageFactory.Crop(cropLayer); // this code not return error and dont crop image.
.....

**Comment by JimBobSquarePants** [comment]
It's because the number range from 0 to 1 If you want 20% use. `0.2`

I'll make the documents more clear.

Just so you know, you can chain methods.

e.g.

imageFactory.Load(inStream)
                      .Crop(cropLayer);

**Comment by JimBobSquarePants** [comment]
Actually. I'm going to make it so that the method accepts both styles. You're not the first to make this mistake so the API must be unintuitive.
