### ISSUE TITLE
Feature Request: Interface for supporting output for Cached Images - S3 support

### ISSUE THREAD

**Issue by joshua-stewart** [JimBobSquarePants/ImageProcessor#135]
I noticed you create an Azure blob cache plugin extension. Could this work be leveraged to create the same functionality for Amazon S3? Thanks in advance for your input/help.

**Comment by JimBobSquarePants** [comment]
Hi Joshua,

Yeah.. It certainly could, the interface is designed to allow caching on any resource.

Unfortunately I don't have access to an S3 account to build and test against. I was hoping someone in the community would help and step up to help achieve this.

**Comment by JimBobSquarePants** [comment]
Just to update. There is a plugin that has been constructed to do this by a third party. We are waiting for permission from their client to open source it.

**Comment by joshua-stewart** [comment]
Awesome! Thanks for the update.

Regards,

Joshua D. Stewart

On Apr 16, 2015, at 5:07 PM, James South <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to update. There is a plugin that has been constructed to do this by a third party. We are waiting for permission from their client to open source it.

**Comment by joshua-stewart** [comment]
Hi James,

I noticed today you've started making updates to ImageProcessor to support S3. I was just wondering how it was going.

Regards,

Joshua D. Stewart

**Comment by JimBobSquarePants** [comment]
Hi Joshua,

I'm working on it... I'm about 85% there I reckon I just need to do some testing and finishing off a couple of bits. I meant to say. I couldn't create any buckets using the login you gave me to test with. (insufficient permissions or something) so I'm working a little bit blind. 

I should get something figured out soon though.

Cheers

James

**Comment by phillip-haydon** [comment]
@JimBobSquarePants S3 on AWS comes with 5gb of free storage for a year. However I can setup a Key / Secret for you that can create/destory buckets (if prefixed with with certain criteria) and give full permissions to those buckets, to allow you to test with. Unless you start making 50k requests / month it wont cost me anything.

**Comment by JimBobSquarePants** [comment]
@phillip-haydon  That would be ace if you could! I reckon with something to test against I could probably get it finished pretty quickly.

**Comment by phillip-haydon** [comment]
Email sent with AWS Credentials and policy setup for bucket creation with full access.

**Comment by JimBobSquarePants** [comment]
See #313 for the workflow
