### ISSUE TITLE
Question/Feature Request: Focal Point

### ISSUE THREAD

**Issue by Myster** [JimBobSquarePants/ImageProcessor#136]
I would like to use resize mode=max and focal point (from Umbraco) but I cannot find elegant way to do this.

If the anchor parameter accepted x,y coordinates I think that would work perfectly.

**Comment by JimBobSquarePants** [comment]
I'm not sure what you're after; those two won't work in combination. 

`ResizeMode.Max` resizes an image to the maximum possible width/height to fit the given dimensions whilst maintaining the original aspect ratio. Nothing is cut off or added so there is no anchoring involved.

**Comment by Myster** [comment]
I figured it out, this does what I want.
`?mode=crop&center=0.2,0.3&width=100&height=10`
The http://imageprocessor.org/ documentation doesn't really cover this, I found it in the Umbraco source code. :-)

**Comment by JimBobSquarePants** [comment]
That's `mode = crop` not `mode = max`. 

Docs are open source and I am but one man....

**Comment by Myster** [comment]
Hi, I was going to add this to the docs but I can't find the `gh_pages` directory.

**Comment by JimBobSquarePants** [comment]
Aw cheers! :+1: It's actually a branch on the repo not a directory.

Brace yourself with Jekyll though, it's a nightmare. The docs are a bit of a mess just now as I started converting everything to markdown but failed miserably.

https://github.com/JimBobSquarePants/ImageProcessor/tree/gh-pages
