### ISSUE TITLE
Question - caching from a stream

### ISSUE THREAD

**Issue by amcgrego** [JimBobSquarePants/ImageProcessor#137]
Hey, just started using ImageProcessor, going well so far! I am using the ImageFactory to create resized images from image streams.

It is possible to create a local cached version inside the 'App_data/cache' folder and access that before going to get the stream? Similar way to how it works when using querystring values in urls.

Cheers

**Comment by JimBobSquarePants** [comment]
Hi there,

I take it you mean in a non web environment? 

You would have to implement your own caching system I'm afraid. The base libraries have no concept of caching. I guess you could base something off the web disk cache but you'd have to do some fancy footwork to create a key.
