### ISSUE TITLE
Anchoring padded image. Which version is this available in?

### ISSUE THREAD

**Issue by McGern** [JimBobSquarePants/ImageProcessor#141]
Hi,

Thanks for the great library, it is ridiculously good.

I am trying to position an image that is padded using the "anchor" parameter, but nothing seems to be happening. Am wondering whether I have the wrong version, there is an issue in the positioning or I just have to wrong expectations of what should happen.

This is the version from the packages.config in the solution
ImageProcessor  2.1.0.0
ImageProcessor.Web 4.1.0.0

Here is a demo where I was expecting the image to appear at the bottom with the black padding at the top.

http://www.hibristolfiltonhotel.co.uk/media/475879/holiday-inn-bristol-filton-exterior-fountain.jpg?width=500&height=500&anchor=bottom&quality=70

Was anchor added in later versions? Also do you have a demo of the latest library using live examples?

Thanks very much,
Jarrod

**Comment by JimBobSquarePants** [comment]
Hi Jarrod,

Thanks for your support, always nice to hear someone say my work is good.

Yeah, that code was added in 

 - ImageProcessor 2.2.0.0
 - ImageProcessor.Web 4.2.0.0

I should have added a snippet to the docs to say so.

You can upgrade them both via Nuget easily enough, just make sure you backup any config files first if you have them as there have been a few changes with Nuget might struggle to merge. 

https://www.nuget.org/packages/ImageProcessor.Web/

I don't have an live examples just now but I'm going to move the docs to a saner platform so I can make them more interactive. It'll take me a while though.

Cheers

James
