### ISSUE TITLE
Cropping by percentage and later resizing is not working

### ISSUE THREAD

**Issue by josecalderon** [JimBobSquarePants/ImageProcessor#144]
Hi all,

I need to resize a crop done with percentages (user can zoom and move the image on the umbraco backend). The cropped image should have the height and width defined by the crop (even if the image is zoomed) but it turns out that it is not working fine.

This is my url:

localhost:1340/remote.axd/ciras.blob.core.windows.net/media-test/1002/happy-young-businessman_big.jpg?crop=0.24671916010498687,0.029791962724296239,0,0.32968083870333464&cropmode=percentage&quality=90&width=480&heightratio=0.7491289198606271777003484321&slimmage=true

The final image should be 480px width, but it is 718px. (The original image is 1000px width)

Could you tell me what am I doing wrong?

I am using ImageProcessor.Web version="4.2.1.0" and the Azure Cache plugin.

Thanks.

**Comment by JimBobSquarePants** [comment]
Thanks for moving this here. 

That is indeed a bug. I've fixed it in the dev branch and will create a release soon one I have fixed a few outstanding issues I have spotted.

**Comment by josecalderon** [comment]
Hi James,

First of all congratulations for your amazing work on the image processor.

I already raised the issue, but I managed to the crop+resizing changing the coordinates to the x,y,width,height format, and changing the mode to stretch instead that the normal mode padding, although using this method, I need to access to the media node to get the width and height of the image.

Thanks

**Comment by JimBobSquarePants** [comment]
Fixed in [v4.3.0](https://www.nuget.org/packages/ImageProcessor.Web/)
