### ISSUE TITLE
RemoteImageService not rendering plain unprocessed images 

### ISSUE THREAD

**Issue by rmillo8** [JimBobSquarePants/ImageProcessor#145]
Hi,
 I've recently updated ImageProcessor.Web to 4.2.1 and I've noticed that urls such as this:
http://www.mysite.com/remote.axd?http://www.mycdn.com/myfile.jpg
are not working anymore.

If I use a "prefix", then I also need to use an "ImageProcessor parameter".
Is this bug, or is there any specific reason why we should enforce this?

Raf

p.s. 
Note that if I just add a "?any-string" the image will be rendered
http://www.mysite.com/remote.axd?http://www.mycdn.com/myfile.jpg?any-string

**Comment by JimBobSquarePants** [comment]
Docs, docs, docs..... :stuck_out_tongue_winking_eye: 

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#remote

Really there is no advantage in pulling a file from a CDN if it is not going to be processed. You're only making your server work harder. If you want to manipulate the file, use ImageProcessor, if not you're best just serving from the source.

Hope that helps...

**Comment by rmillo8** [comment]
Ah!
Didn't noticed that...

Quite a lot of changes in this last version!

Thanks!
Raf

**Comment by JimBobSquarePants** [comment]
No worries,

Yeah a lot has changed. Essentially, because I needed to allow for any image input or cache mechanism I could allow hacks like pulling images without querystring to work. All in all though it makes ImageProcessor.Web  much more powerful and flexible than it was.
