### ISSUE TITLE
v3 and Beyond....

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#148]
I want to start looking at a **v3** build and I'm going to need a lot of help doing it. 

Here's a basic list of things I would like to be able to do.

 - Cross platform and device functionality.
 - Much increased parallelization.
 - Asynchronicity where appropriate.
 - Better API's for work outside ImageFactory
 - Better tests and build processes. (MyGet etc)

I'm absolutely determined to keep ImageProcessor free of dependencies but this does seem unlikely given the current state of graphics in vNext. See  [here](https://github.com/aspnet/Home/issues/192) and [here](https://github.com/imazen/Graphics-vNext) Who knows what is going on? :8ball: 

So here's the thing...

ImageProcessor and It's Web extension have got a ton of downloads on Nuget (116,117) right now :metal: so it's proving extremely popular; demand is clearly there for its use. Unfortunately though,  there's only really two guys that do any work on it; myself and @cosmo0 so if we don't get help then the project will most likely peter out as I simply do not have the time nor the ability to deliver what we as developers, sorely need.

Can you help with this? Is there anyone at Microsoft who can give advice or pointers?

James :heart: 

Please comment below.

**Comment by yufeih** [comment]
@JimBobSquarePants 
I am also building a [portable image library](https://github.com/yufeih/Nine.Imaging) that mainly runs on the client and would like it to speak http. 
ImageProcessor looks promising and maybe we can help other.

Here is a list of things that I have:
- Runs on WindowsPhone, WindowsStore, Android, iOS and the Desktop with PCL profile 78.
- Load, save and manipulate images independent of System.Drawing, 
- Supports (jpg, png, bmp, gif)
- Comes with some pretty fast and paralleled filters.

Compare to ImageProcessor, it lacks:
- An HTTP module
- More filters
- Text rendering (for watermarks)
- WebP, post processors
- Documentation and popularity

Thoughts?

**Comment by JimBobSquarePants** [comment]
Hi Yufieh,

There looks like some really, really cool stuff going on in your library. I'm particularly impressed that you managed to keep dependencies to a minimal.

I would absolutely love to work with you to build something better than what we both have. We'll have to have a good head-to-head to discuss a roadmap to figure out exactly what we can get running out of the box. 

Now the question begs... Would you be happy to integrate your work into this library, sacrificing your own in the process? Since ImageProcessor is so popular now it makes sense (to me anyway) to continue with v3. I'm happy to give you full access to this repo so we can get started if this is the case?

Cheers

James :smile:

**Comment by cosmo0** [comment]
@yufeih so your library does not depend on System.Drawing ?

This sounds really great. Probably a lot of work to rewrite ImageProcessor to use something else, but also probably more future-proof (and also probably more performant).

**Comment by JimBobSquarePants** [comment]
Hi @cosmo0, good to see you. I think the work would most definitely be worth it. I've actually tried to think ahead for a lot of stuff so that we can switch out pretty easily when the time comes.

**Comment by yufeih** [comment]
@JimBobSquarePants  @cosmo0 

I am fine with using the *ImageProcessor* branding. But I also need to maintain my own library, mainly because I have a release schedule that is hard to catch if I wait for ImageProcessor v3.

The rewrite of ImageProcessor did require a lot of work, so I am thinking about a bottom up approach: Start simple with the current state of *Nine.Imaging* and gradually adding new stuff into it. 

We may need to consider add a [Gitter](https://gitter.im/) on the home page so we can chat!

**Comment by JimBobSquarePants** [comment]
@yufeih Waaay Ahead of you :wink: 

https://gitter.im/JimBobSquarePants/ImageProcessor

I've no problem with that at all, I just didn't want to lose the ImageProcessor branding. 

Yeah.. start with a stable platform and add/rework what we can. 

I'm going to give both you and @cosmo0 full access to the repo

**Comment by cosmo0** [comment]
Thanks! Not sure I'll be able to contribute much though, I'm changing job in a few weeks. I will keep an eye out for ways I can help.

**Comment by JimBobSquarePants** [comment]
No worries. Your contributions so far have been amazing.

**Comment by cosmo0** [comment]
Why not just using Nine.Imaging as a nuget package in ImageProcessor ?

Nine.Imaging could focus on "pure" fast and stable image processing (like other libraries are doing: see https://github.com/imazen/Graphics-vNext or rather https://github.com/nathanaeljones/imaging-wiki) and ImageProcessor could build over it to provide more higher-level things (filters and effects, HTTP module, etc).

**Comment by JimBobSquarePants** [comment]
Nah... It's tempting but I really want to keep going with all the core stuff in this library - It lets me keep up with bug fixing quickly.

The HttpModule is a separate library anyway.

**Comment by cosmo0** [comment]
I mean that there are several layers of image processing. Down at the bottom, you have things like "read the bytes of the file and translate it to pixels, meta infos, ICC profile, and many other things". Just above, you have "get the pixels values", which can be done in a thousand ways, some using more or less IO, CPU, or RAM.

Do you wish to write things like these in ImageProcessor, to replace System.Drawing ? Or would you rather rely on an existing library, which you don't touch, to load and read the images data ? Of course the processing itself (applying of effects, resizing...) would stay in IP.

It's a real question, either direction is interesting. Personnaly I would rely on a specialized library to do that.

Well, ideally, I would use dependency injection to allow anyone to use their preferred image library to load images. This way I can provide a not-great-but-stable System.Drawing usage, a faster-but-not-as-tested Nine.Imaging usage, users could write their own pick-your-own-favorite-library wrapper, etc. This would be awesome, but writing an interface common to all libraries would probably not use any library to their full potential. Or maybe it would, what do I know, I haven't checked any of them yet.

**Comment by cosmo0** [comment]
Well, this is assuming the baseline discussion is to get rid of System.Drawing, of course.

**Comment by JimBobSquarePants** [comment]
One thing that has always bothered me about imaging in .NET is the fracturing. To me, the target for ImageProcessor was to provide a single place to provide efficient, simple, and safe methods for developers to do the tasks they need to. ImageProcessor was never designed simply to be a wrapper for objects. I only chose System.Drawing as it was easy to use and had the largest distribution.

I still want ImageProcessor to be the go-to place. If someone wants so fix a bug in a gif encoder, they do it here, if they want to create a filter, do the same. I don't want to have to wait on another developer I'm relying on to find the time to fix things. I've felt that pain too much.

I strongly believe  .NET needs ImageProcessor and want to provide everything I possibly can through the library. System.Drawing is not getting updated any time soon and I want to be able to work without it. 

I do however, want people to be able to plug in certain aspects. an EXIF reader/writer for example, so allowing for dependency injection would be a definite target.

**Comment by JimBobSquarePants** [comment]
So you've both probably noticed I've made a healthy start on porting code across. I'm trying so cleanup as much of what you inherited as possible but it will take me a while.

I've made a start on a gif encoder also since it is missing. I'd like to have that working with the full possible range of colours and hopefully convert the old octree quantizer to reduce the palette.

I'd really appreciate a second or third opinion on what I have done so far so if either of you have a chance that would be great.

**Comment by yufeih** [comment]
I have been following your commits and it is doing great!. 

So far there are 2 main things that I wish to have before pushing code into it:

1. Visual Studio 2015 support. I really enjoy the new C# syntax :)
2. Lower the bar of code level XML Documentation. 

> Documentation. Nobody likes doing docs, I've written a lot but my prose is clumsy and verbose

Resource for documentation is always limited, so we should really focus more on the docs in imageprocessor.org.

**Comment by JimBobSquarePants** [comment]
Cheers!

I held off installing VS2015 as I wasn't sure how ready it was. What with the latest releases though I'm happy to upgrade and use C#6. There are some really cool features in the language.

As for the docs, yeah no worries. Getting things working is the most important thing just now. Just ensure that anything particularly complicated has got some inline comments and try to use semantic variable names to make it easier to follow each others code.

**Comment by JimBobSquarePants** [comment]
I've transitioned most of the code to C#6 now. Really struggling to get my head round the best approach to tackle the gif encoder just now so any input you have would be most welcome.

**Comment by JimBobSquarePants** [comment]
I'm gonna close this issue now that V3 is well on its way.
