### ISSUE TITLE
Input stream is not a supported format.

### ISSUE THREAD

**Issue by mrcode86** [JimBobSquarePants/ImageProcessor#149]
I have this:

        private void CreatePngThumb(Stream str)
        {
            ISupportedImageFormat Format = new PngFormat();
            var S = new Size(100, 100);
            using (var OutStream = new MemoryStream())
            {
                using (var Imf = new ImageFactory(true))
                {
                    Imf.Load(str)
                                .Resize(S)
                                .Format(Format)
                                .BackgroundColor(Color.White)
                                .Save(OutStream);
                }
            }
        }

str contains a png image, but when i load it (Imf.Load(str)) i get, Input stream is not a supported format.

Why?

**Comment by JimBobSquarePants** [comment]
Are you absolutely sure that the input stream is correct and hasn't been incorrectly encoded.?

If you look at the list of file signatures [here](http://en.wikipedia.org/wiki/List_of_file_signatures) the first four bytes of a png stream in hexadecimal are:  

    89, 50, 4E, 47

This translates to a decimal representation of: 

    137, 80, 78, 71

This is true for all png files. 

ImageProcessor uses the first four bytes of an image stream to identify the correct format. If the first four bytes are one of the recognised types then the correct `ISupportedImageFormat` is loaded to process the image. If not, then the error you are seeing is thrown.

Here is the identifier for the `PngFormatClass` https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor/Imaging/Formats/PngFormat.cs#L37

**Comment by JimBobSquarePants** [comment]
Closing as the png format is standard and recognised properly by ImageProcessor.

**Comment by darrenshrwd** [comment]
In case this helps someone else, if you are doing some kind of logic to work out if a file is an image that involves reading the file...BEFORE then reading the file into memorystream for imageprocesser, make sure you reset the file position:

file.InputStream.Position = 0;

**Comment by Athl33t** [comment]
Same error but with jpg. Here is the image http://www.uline.com/images/en-US/family2.jpg

**Comment by JimBobSquarePants** [comment]
Odd. I'm not able to replicate using the code. [Here](https://github.com/JimBobSquarePants/ImageProcessor/blob/dd89356a8aa43e93b884522c68f205a2ebf01fdd/tests/ImageProcessor.Playground/Program.cs)

**Comment by kgiszewski** [comment]
I just ran into this today myself with a `jpg`. Resaving the image in photoshop doesn't seem to help.

ImageProcessor version 2.3.3.0

Using a hex editor, the file is indeed a JPG `ffd8`.

<img width="597" alt="screen shot 2016-04-13 at 3 33 27 pm" src="https://cloud.githubusercontent.com/assets/4653907/14506704/1fa95a8e-018d-11e6-8afd-8116756cc1e6.png">

Continuing to figure it out. The same script is loading images correctly from the same shoot, but a handful are throwing this error.

**Comment by kgiszewski** [comment]
In case it helps, the exception appears to be thrown at the `.load()` method in my code:
```
 using (var imageFactory = new ImageFactory(preserveExifData: true))
{
    var factory = imageFactory.Load(stream);
    /* more code ommitted */
}
```
```
Input stream is not a supported format.
ImageProcessor.Common.Exceptions.ImageFormatException: Input stream is not a supported format.
   at ImageProcessor.ImageFactory.Load(Stream stream)

```

@JimBobSquarePants, I can send you a file privately that doesn't work if you'd like.

**Comment by JimBobSquarePants** [comment]
@kgiszewski Yeah, send me the image please so I can test and inspect it.

**Comment by kgiszewski** [comment]
I'll DM you a link on Twitter tomorrow when I'm in front of a computer.

**Comment by JimBobSquarePants** [comment]
Cheers! If you can share a private gist of the relevant bits your code also that would be great.

**Comment by kgiszewski** [comment]
@JimBobSquarePants, sorry for the delay but I've resolved the issue. You'll be happy (or annoyed) to know that it was fixed by updating my own code.

This code snippet produces intermittent results:

```
var azureStream = new MemoryStream();
blockBlob.DownloadToStream(azureStream);

using (var imageFactory = new ImageFactory(preserveExifData: true))
{
    var factory = imageFactory.Load(azureStream);

    Console.WriteLine(factory.CurrentImageFormat.MimeType);
}
```

Whilst adding a stream position reset makes it work for everything:

```
var azureStream = new MemoryStream();
blockBlob.DownloadToStream(azureStream);

//adding this fixed it for all
azureStream.Position = 0;

using (var imageFactory = new ImageFactory(preserveExifData: true))
{
    var factory = imageFactory.Load(azureStream);
    Console.WriteLine(factory.CurrentImageFormat.MimeType);
}
```

Thanks for all your hard work as usual :+1:

**Comment by JimBobSquarePants** [comment]
Ah good! No worries, I'll need to have a wee look at the load method to ensure we are resetting the position before checking. I thought it was.
