### ISSUE TITLE
Question: How make vertical watermark?

### ISSUE THREAD

**Issue by Radzhab** [JimBobSquarePants/ImageProcessor#151]
How make vertical watermark with this lib?

**Comment by JimBobSquarePants** [comment]
Hi Radzhab,

Have you had a look at the code or documentation?

At the moment it doesn't. I could maybe get it to do so though so shall investigate.

Cheers 

James.

**Comment by JimBobSquarePants** [comment]
Added in [v2.2.3](https://www.nuget.org/packages/ImageProcessor/)
