### ISSUE TITLE
Gamma 

### ISSUE THREAD

**Issue by dom0000** [JimBobSquarePants/ImageProcessor#159]
The reset method should reset the current gamma value.
If you re-use the same instance of ImageFactory to make thumbnail for example,
the first result is correct, but the next are every time more brighter.

```
using (var imageFactory = new ImageFactory())
{
	imageFactory.Load(stream);
	foreach (var size in Sizes)
	{
		using (var outStream = new MemoryStream())
		{
			imageFactory.Constrain(size).Save(outStream);
                        imageFactory.Reset();
		}
	}
}            
```

**Comment by JimBobSquarePants** [comment]
Good catch, Pull request?
