### ISSUE TITLE
Any way to pre-process an image?

### ISSUE THREAD

**Issue by leddt** [JimBobSquarePants/ImageProcessor#160]
Let's say I have a few presets defined. When a user uploads an image, I know there are a few of these presets that will be used in the near future. Is there a way, at upload time, that I can force ImageProcessor to generate some presets and cache them? It would make the first request to these images much faster.

**Comment by JimBobSquarePants** [comment]
And make them accessible via the Url API?  - No I'm afraid not. 

The location of the image cached by the API is determined by the full url, creation date of the image and it's size in bytes so it can only be calculated upon request.

If you have users uploading giant images you could reduce the base storage size by using the ImageFactory class in the base library.

**Comment by leddt** [comment]
Ah I see. I'll look into ImageFactory. If all else fails I could just send
dummy http requests to the final urls after saving the image.

Thanks

**Comment by JimBobSquarePants** [comment]
No worries. I'll close this for now. Good luck!
