### ISSUE TITLE
invalidoperationexception on autoprocess

### ISSUE THREAD

**Issue by Deidarius** [JimBobSquarePants/ImageProcessor#164]
/* This will run as a webjob. It will update all images on the storage, to ensure that they all have an image copy in of the presets. There will be a raw image, which the others are manipulated from. It all works fine, until it reaches the imagefactory.autoprocess. It throws the exception: InvalidOperationException method cannot be called during the application's pre-start initialization phase, and I don't know why */

[NoAutomaticTrigger]
        public static void UpdatePresetsBlob()
        {
            
                using (var presetStream = new MemoryStream())
                {
                    var rawBlob = container.GetBlockBlobReference(folder + "/Raw" + extension);
                    rawBlob.DownloadToStream(presetStream);
                    presetStream.Seek(0, SeekOrigin.Begin);

                foreach (var jtoken in jarray)
                {
                      var imageElement = (from e in presetDoc.Root.Elements("Preset")
                                        where e.Attribute("Name").Value == presetName
                                        select e).FirstOrDefault();
                        
                         using (var outStream = new MemoryStream())
                                {
                                    imageFactory.Load(presetStream)
                                                .AutoProcess("width=200&height=200&bgcolor=transparent")
                                                .Save(outStream);

                                    outStream.Seek(0, SeekOrigin.Begin);

                                    var presetPath = folder + presetName + format;
                                    var image = container.GetBlockBlobReference(presetName);
                                    image.UploadFromStream(outStream);
                                }
                                
                        }
                    
                    }
}

**Comment by JimBobSquarePants** [comment]
Can this get a bit of [Markdown](https://guides.github.com/features/mastering-markdown/) love please? It's very difficult to follow.

I need to see some further information; I simply cannot debug something with this.

1. The basics - Version numbers.
2. What string based commands are you passing to the `AutoProcess ()` method.
3. What are the messages contained in any inner exceptions.
4. What messages are received when you [attach to the process](http://blogs.msdn.com/b/webdev/archive/2014/11/12/new-developer-and-debugging-features-for-azure-webjobs-in-visual-studio.aspx) via Visual Studio against the library?

**Comment by Deidarius** [comment]
I have trimmed it down, so it only shows the most important.
The information you needed:
1:  ImageProcessor version="2.2.0.0" and ImageProcessor.Web version="4.2.1.0" 
2: I have changed the string command in the code, to show the first one, that is used in the autoprocess
3: It doesn't have any unfortunately
4: As said before, it's message says: This method cannot be called during the application's pre-start initialization stage.
Do you need more information from the View Detail of the exception?

**Comment by JimBobSquarePants** [comment]
Please... A little reading on the error message so far does not yield much info.

Does it work without the `bgcolor` instruction?

I have feeling we will not get this working The `AutoProcess` function is very tightly coupled in with a lot of configuration processes. I never should have allowed it to be publicly available.

**Comment by Deidarius** [comment]
It doesn't work without the bgcolor either. 
I would love to give you all information the exception, but it really doesn't have any, which is why I came to you for help.
The funny thing is, that the autoprocess work perfectly, when it is used for web, same code and all, but when I use it in a webjob, it won't run. Except this hickup, nothing but wonders can be said about it :)
I don't think it has anything do to the string from the precessing.config. 
If it can't be fixed in my code, then so be it.

**Comment by JimBobSquarePants** [comment]
Yeah.. The context will be completely different though. It'll have something to do with the WebJob life cycle. I don't know the answer but someone might so I'll keep this open.

**Comment by Deidarius** [comment]
Well, thank you for trying. If I find an answer, I will offcource post it

**Comment by JimBobSquarePants** [comment]
No worries. Thanks :+1:

**Comment by Deidarius** [comment]
I had forgot to move the imageprocessor config files to the webjob also. After I had done that, it now throws this exception: ImageProcessor.Web.Processors.DetectEdges.
I don't know if this help, or just tells us: Yep, still not able to solve the problem :)

**Comment by JimBobSquarePants** [comment]
Oh that's interesting.... Remove that processor. It's not wired up yet and shouldn't be there.

**Comment by Deidarius** [comment]
That did the trick. Thank you so much. Sorry if my bugreport wasn't descriptive enough
