### ISSUE TITLE
remote.axd and A potentially dangerous Request.Path value was detected from the client (:) error

### ISSUE THREAD

**Issue by wiske80** [JimBobSquarePants/ImageProcessor#167]
Hi,

i have a seperate IIS website installed just for images, and installed the latest nuget packages for imageprocessor. 

Cropping normal images work fine, but when trying to crop a remote image i have some issues. 

My url local url:
http://images.hr.local/remote.axd/http://img.youtube.com/vi/-s7UiQ3sOwI/hqdefault.jpg&width=100
return a **A potentially dangerous Request.Path value was detected from the client (:).** error

The legacy variant returns a 404:
http://images.hr.local/remote.axd?http://img.youtube.com/vi/-s7UiQ3sOwI/hqdefault.jpg&width=100

local images work fine: http://images.hr.local/blob/shoes.jpg?width=300&height=420&mode=crop (just works)

Below is my security.config which looks good in my opinion.  I also saw this issue: https://github.com/JimBobSquarePants/ImageProcessor/issues/10 but this was a long time ago and was resolved.

Am i missing something else?

```<security>
  <services>    
    <service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web">      
      <whitelist>        
      </whitelist>
    </service>
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="4194304" />
        <setting key="Timeout" value="3000" />
        <setting key="Protocol" value="http" />        
      </settings>
      <whitelist>
        <add url="http://img.youtube.com" />      
      </whitelist>
    </service>
  </services>
</security>

**Comment by JimBobSquarePants** [comment]
Hi there,

Yeah, should be an easy fix. Your url shouldn't have the `http://` protocol.

    http://images.hr.local/remote.axd/img.youtube.com/vi/-s7UiQ3sOwI/hqdefault.jpg&width=100

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#remote

**Comment by wiske80** [comment]
Hi Jim,

yeah sorry to mention that.. i tried that one as well... 

but still get the same error.
http://images.hr.local/remote.axd/img.youtube.com/vi/-s7UiQ3sOwI/hqdefault.jpg&width=100

if i try it with the legacy mode:
http://images.hr.local/remote.axd?http://img.youtube.com/vi/-s7UiQ3sOwI/hqdefault.jpg&width=100
i get the following error:  **Invalid URI: The hostname could not be parsed.**

**Comment by JimBobSquarePants** [comment]
Sorry.. My bad, didn't notice. You have an ampersand `&` instead of a question mark `?`.

http://images.hr.local/remote.axd/img.youtube.com/vi/-s7UiQ3sOwI/hqdefault.jpg?width=100

**Comment by wiske80** [comment]
awww man.. such a stupid one... thanks.. that was the problem... :facepalm: :+1:

**Comment by JimBobSquarePants** [comment]
No worries. Done it myself countless times!
