### ISSUE TITLE
Exception occurred while processing single pixel, single color GIF

### ISSUE THREAD

**Issue by CharlesShen** [JimBobSquarePants/ImageProcessor#169]
Hi there,

I have a single pixel GIF that is supposed to serve as a placeholder.  The image is requested with the following parameters, "blank.gif?width=270&height=150&bgcolor=fff".  An exception with the following stacktrace occurs

```
[NullReferenceException: Object reference not set to an instance of an object.]
   ImageProcessor.Imaging.Quantizers.Octree.Reduce() in c:\Users\Charles\Source\Repos\ImageProcessor\src\ImageProcessor\Imaging\Quantizers\OctreeQuantizer.cs:318
   ImageProcessor.Imaging.Quantizers.Octree.Palletize(Int32 colorCount) in c:\Users\Charles\Source\Repos\ImageProcessor\src\ImageProcessor\Imaging\Quantizers\OctreeQuantizer.cs:267
   ImageProcessor.Imaging.Quantizers.OctreeQuantizer.GetPalette(ColorPalette original) in c:\Users\Charles\Source\Repos\ImageProcessor\src\ImageProcessor\Imaging\Quantizers\OctreeQuantizer.cs:136
   ImageProcessor.Imaging.Quantizers.Quantizer.Quantize(Image source) in c:\Users\Charles\Source\Repos\ImageProcessor\src\ImageProcessor\Imaging\Quantizers\Quantizer.cs:100
```

It appears that the image dimensions is not the problem but the fact that it only has 1 color in its palette is.  Adding a conditional to the method Palletize(int colorCount) allows the image to process fine, but the bgcolor argument won't be applied.  A proper fix is something beyond my abilities given my brief investigation.

Attached is the image causing problems.  A direct url to it is https://cloud.githubusercontent.com/assets/2334303/7623843/0444f080-f99d-11e4-9655-1a8fec17a7ca.gif

Thanks!

![blank](https://cloud.githubusercontent.com/assets/2334303/7623843/0444f080-f99d-11e4-9655-1a8fec17a7ca.gif)

**Comment by JimBobSquarePants** [comment]
Hi there, 

Thanks for supplying the gif in question. I'll have a look at the earliest opportunity.

Cheers

James

**Comment by JimBobSquarePants** [comment]
Sorry for the delay, super busy and thought this would be a lot more difficult to fix than it was. 

I'll push out a release at lunch today that fixes the problem for you.
