### ISSUE TITLE
Progressive JPEG support

### ISSUE THREAD

**Issue by matthiasleitner** [JimBobSquarePants/ImageProcessor#170]
Hi,

is the generation of progressive, interlaced JPG supported somehow?

Thanks

**Comment by JimBobSquarePants** [comment]
Not at present as the jpeg encoder in `System.Drawing` does not support it. I am however attempting to use fully managed encoders in v3 which would support progressive jpegs. There's no release date for that defined though as it is a lot of work.

**Comment by matthiasleitner** [comment]
@JimBobSquarePants thanks for the quick response

**Comment by iansullivan88** [comment]
When I google 'Image Processor Progressive Jpeg' this issue appears. For other people looking for this feature, it has now been added - see [this post](https://our.umbraco.org/projects/collaboration/imageprocessor/feedback-for-imageprocessor/72484-progressive-image-rendering)

**Comment by JimBobSquarePants** [comment]
Thanks for updating here. That's only valid for the ImageProcessor.Web as of v4.4.0 The ImageFactory in the base library doesn't know about it so desktop applications will still be without..
