### ISSUE TITLE
RemoteImageService IsValidRequest gives errors

### ISSUE THREAD

**Issue by iwbo** [JimBobSquarePants/ImageProcessor#171]
Hei,

The two types of errors I get every day are:
   1. Invalid URI: The URI scheme is not valid. 
   2. Invalid URI: The hostname could not be parsed. 

Both happen when creating a Uri: `at System.Uri..ctor(String uriString)` in RemoteImageService IsValidRequest.

If I look at the code here: https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Services/RemoteImageService.cs

I see:
```CSharp
 public bool IsValidRequest(string path)
        {
            // Check the url is from a whitelisted location.
            Uri url = new Uri(path);
            string upper = url.Host.ToUpperInvariant();
```

##### Would creating new Uri be problematic if the path would not include a scheme/protocol  (http,https)?

I use the new recommended syntax for remote images:
```
<!-- Recommended syntax as of version 4.2 Note the lack of protocol -->
/remote.axd/your-external-image?width=300
```

**Comment by JimBobSquarePants** [comment]
Are you adding a url to the whitelist in the configuration files?

http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig

The path when passed to the checker has been augmented with the protocol prefix defined in the configuration file. The url is then roughly compared to the values in your config file to see whether it is a safe url to download from. It works out of the box without issue when set up correctly.

There's examples in the test MVC website in the repo if you are stuck.

**Comment by iwbo** [comment]
I have added a Url to the whitelist, but without protocol prefix. Can that be a problem?

To test what is the "path" value I, implimented my own IImageService (with the same code as RemoteImageService). And I saw that the path was not prefixed with a protocol.


But the strangest thing is that this problem doesn't happen all the time.

**Comment by JimBobSquarePants** [comment]
Can you share with me a raw url that was not prefixed with a protocol?

**Comment by iwbo** [comment]
MESSAGE - [Thread 27] IsValidRequest PATH: osomesites.blob.core.windows.net/media/21262/1628.jpg

**Comment by JimBobSquarePants** [comment]
Sorry, I meant the full request url that is rendered in the browser.

**Comment by iwbo** [comment]
http://www.siggi.ee/remote.axd/osomesites.blob.core.windows.net/media/21262/1628.jpg?center=0.42333333333333334,0.5140449438202247&mode=crop&width=360&height=360&rnd=130754501050000000

**Comment by JimBobSquarePants** [comment]
Hmm... And it's only happening sporadically? That url seems to be redirecting to the CDN for me.

**Comment by iwbo** [comment]
Yes, and currently I have now way of telling what urls are causing this.

Is there some possibility to log all the url going to remote.axd/  ?
So I can make better sense whats happening.

**Comment by JimBobSquarePants** [comment]
I'm afraid not. We'd need to do a custom build.

**Comment by iwbo** [comment]
Ok, thank you for your help.

I think I will let this one be, as it is not a mayor issue for me. Just keeps bugging me, that's all :D

**Comment by iwbo** [comment]
Hi,

### I am reopening this issue because it is my second time stumbling upon this problem.

First of all I think that it worked "sporadically" the first time is that I was transitioning form the old url syntax to the new:
From:
`/remote.axd/?http://your-external-image?width=300`
To:
`/remote.axd/your-external-image?width=300`
And most of the images where already cached

## In my new website I hit the problem again:
Versions:
* ImageProcessor ver:2.2.8.0
* ImageProcessor.Web ver:4.3.6.0
* ImageProcessor.Web.Plugins.AzureBlobCache ver: 1.0.4.0

#### The first problem is with RemoteImageService:
https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Services/RemoteImageService.cs

1. Problematic methods are:
`public bool IsValidRequest(string path)`
and
`public async Task<byte[]> GetImage(object id)`
2. Problematic lines are:
`Uri url = new Uri(path);`
and
`Uri uri = new Uri(id.ToString());`

3. The string that is used for creating a new Uri is:
`[accountName].blob.core.windows.net/media/1002/0.png`  
4. The resulting error is:
`Invalid URI: The format of the URI could not be determined.`
Because there is no scheme and the Uri.Kind is not provided

5. So I changed the lines to:
`Uri url = new UriBuilder(path).Uri;`
and
`Uri uri = new UriBuilder(id.ToString()).Uri;` 

And that fixed it form me.


#### Basically the same problem happens in AzureBlobCache:
https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

1. Problematic method is:
`public override async Task<string> CreateCachedFileNameAsync()`
2. Problematic line is:
`if ( new Uri(this.RequestPath).IsFile)`

3. The string that is used for creating a new Uri is:
`[accountName].blob.core.windows.net/media/1002/0.png`  
4. The resulting error is:
`Invalid URI: The format of the URI could not be determined.`
Because there is no scheme and the Uri.Kind is not provided

5. So I changed the line to:
`if (new UriBuilder(this.RequestPath).Uri.IsFile)`

There is a try-catch surrounding this, but the problem is the same. 
  
#### Should these problems be fixed this way? Or should a scheme/protocol be added to the URL somehow?

**Comment by JimBobSquarePants** [comment]
Hi @iwbo 

Are you adding the protocol value to the configuration as per the documentation?

http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig

Cheers

James

**Comment by iwbo** [comment]
Hi,

Yes, the protocol wasn't there.
