### ISSUE TITLE
Percentage cropping not functioning - ImageProcessor.Web

### ISSUE THREAD

**Issue by sprintstar** [JimBobSquarePants/ImageProcessor#176]
If I try percentage cropping (http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/crop/), the image is cropped as if the percentages are pixels.  For example:

http://mydomain/myimage.jpg?crop=0,0,100,60&cropmode=percent
http://mydomain/myimage.jpg?crop=0,0,100,60

Both return the same 100x60 pixel image.

I am using the following versions, within Umbraco 7.2.5.
ImageProcessor.dll v2.2.5.0
ImageProcessor.Web.dll v4.3.2.0

**Comment by JimBobSquarePants** [comment]
Thanks for this you've actually managed to expose 2 issues. 

1. The docs are wrong, it should be "percentage" not "percent".
2. The parser dies on it's ass when it tries to calculate 100%. 

I've just pushed a fix and will do a release tonight in time for CodeGarden.
