### ISSUE TITLE
Question- Force every image request through ImageProcessor

### ISSUE THREAD

**Issue by gnpretorius** [JimBobSquarePants/ImageProcessor#179]
Quick question - is it possible to force every request through your image processor pipeline? I'm using your ```CloudImageService``` and it works great (requesting the image in the cloud) However, if there are no querystring params (i.e. no image processing) then it looks like its serving the image from local. As we need to use this across multiple servers, we cannot store image locally. Is this possible?

```<img src="images/sample.jpg?width=50" /> ``` From cloud
```<img src="images/sample.jpg" /> ``` Locally

Thanks again for the help
Regards
G

**Comment by JimBobSquarePants** [comment]
You'll need to turn on RAMMFAR for this.

```
<system.webServer>
  <modules runAllManagedModulesForAllRequests="true" />
</system.webServer>
```

**Comment by JimBobSquarePants** [comment]
Note though, RAMMFAR is really, really not great for performance.

**Comment by gnpretorius** [comment]
I know it's not great. But in this case we will have the CDN to offload most of the traffic. 
Also, without it we would need to store our images locally which we cannot do. 

Regards
Gordon

**Comment by gnpretorius** [comment]
Hi James,

It's still not working for me

I have the following in my web.config

```
<system.webServer>
   <modules runAllManagedModulesForAllRequests="true">
      <remove name="FormsAuthentication" />
      <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
   </modules>
   <validation validateIntegratedModeConfiguration="false" />
</system.webServer>
```

And running the following code:

```
<img src="~/images/sample-smaller.jpg" />
<img src="~/images/sample-smaller.jpg?width=150" />
```

Only the second image shows. The first give me a 404 (the file is located in the cloud)

Any ideas? 
Thanks :)

G

**Comment by JimBobSquarePants** [comment]
You'll probably have to additionally tap into the [`ImageProcessingModule.OnProcessQuerystring`](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events) event to append a faux value something like `cloud=true` to the url. This could be done automatically in the constructor for the `CloudImageServce` though. (We could maybe update that)
