### ISSUE TITLE
UTC error when using overlay in ImageProcessor.Web

### ISSUE THREAD

**Issue by RufeyJ** [JimBobSquarePants/ImageProcessor#181]
I've just updated a web project to .net 4.5 and Imageprocessor.web 4.3.3.0 to take advantage of the Overlay function.  When I pass in the request for the overlaid images (http://xxx.com/pics/mainimage.jpg?overlay=overlay.gif&overlay.position=30,30&overlay.size=100,100&overlay.opacity=50) I get: 
----------------------------------------------------------------
The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset

StackTrace

[ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset]
   System.Runtime.CompilerServices.AsyncServices.<ThrowAsync>b__0(Object state) +18
   System.Web.LegacyAspNetSynchronizationContext.CallCallbackPossiblyUnderLock(SendOrPostCallback callback, Object state) +67

-----------------------------------------------------------------------

In that I am implementing only the default config etc, I'm not sure where dates are going to com into an image overlay.

**Comment by JimBobSquarePants** [comment]
Whoa! that is weird! I don't do anything with dates. 

Is it specific to that method and image? Could you try deleting the cache and running it again.

I'd also have a look to ensure that nothing else was updated also that could be causing an issue.

**Comment by JimBobSquarePants** [comment]
I just tested this locally and it's working perfectly. I think there must be something else corrupt in your solution. I simply don't do anything with dates.
