### ISSUE TITLE
Resizing PNG image with Pad option, stretches it.

### ISSUE THREAD

**Issue by gabrielius** [JimBobSquarePants/ImageProcessor#184]
I am resizing PNG image with Pad option, but the ImageFactory still stretches it. I am resizing to a bigger image. Resized Width/Height is the same. What is going on here?

Attaching the file below:

![0](https://cloud.githubusercontent.com/assets/7396135/8251644/f6ea92b2-1686-11e5-80ad-bfa27eca2909.png)

**Comment by JimBobSquarePants** [comment]
Resize is format independent, it's the same algorithm each time. Are you absolutely sure?

Can you show some code?

**Comment by JimBobSquarePants** [comment]
I was just able to resize that image using the following code:

    // ImageProcessor
    using (MemoryStream inStream = new MemoryStream(photoBytes))
    {
        using (ImageFactory imageFactory = new ImageFactory(true, true))
        {
            // Load, resize, and save an image.
            imageFactory.Load(inStream)
                .Resize(new Size(500, 200))
                .Save(Path.GetFullPath(Path.Combine(Path.GetDirectoryName(path), @"..\..\images\output", fileInfo.Name)));
        }
    }

I also tested it using the `ResizeLayer` overload. It definitely resizes correctly. Are you turning off the `UpScale` option?

Input
![f6ea92b2-1686-11e5-80ad-bfa27eca2909](https://cloud.githubusercontent.com/assets/385879/8254786/2c7507a8-1693-11e5-8ef5-95abebdc8a54.png)


Output
![f6ea92b2-1686-11e5-80ad-bfa27eca2909-resized](https://cloud.githubusercontent.com/assets/385879/8254776/189f0c24-1693-11e5-9032-986280819f54.png)

**Comment by gabrielius** [comment]
Sorry for late reply. Here is the code I use:
```
using (var inStream = new MemoryStream(imageData))
{
    using (var outStream = new MemoryStream())
    {
        using (var imageFactory = new ImageFactory(true, true))
        {
            imageFactory.Load(inStream)
                        .Resize(new ResizeLayer(new Size(200, 200), ResizeMode.Pad, AnchorPosition.Center, true))
                        .Save(outStream);
            return outStream.ToArray();
        }
    }
}
```
In one example I change "upscale" to false. Check the below images. *Desired output* is what I want to achieve. I don't want the image to be stretched and resampled (*Original padded with upscale = true* example), I just want to change the size of the canvas. Maybe I should use some other method?

*Original image:*
![original](https://cloud.githubusercontent.com/assets/7396135/8350878/e97bfcce-1b31-11e5-9153-e9f970fa3f75.png)

*Desired output:*
![desired](https://cloud.githubusercontent.com/assets/7396135/8350879/e97e2a3a-1b31-11e5-8377-796f678e1dc4.png)

*Original padded with upscale = false*
![original-padded-with-upscale-false](https://cloud.githubusercontent.com/assets/7396135/8350876/e97a00d6-1b31-11e5-9c2a-8ffcd4c9ed1b.png)

*Original padded with upscale = true*
![original-padded-with-upscale-true](https://cloud.githubusercontent.com/assets/7396135/8350877/e97a293a-1b31-11e5-9537-cc1ca43a8074.png)

**Comment by gabrielius** [comment]
Ok, I found a workaround. First I have to Pad width and then I Pad height. It would be nice to make it in one statement though :)

*Look here:*
```
using (var inStream = new MemoryStream(imageData))
{
    using (var outStream = new MemoryStream())
    {
        using (var imageFactory = new ImageFactory(true, true))
        {
            imageFactory.Load(inStream)
                        .Resize(new Size(200, 100))
                        .Resize(new Size(200, 200))
                        .Save(outStream);
            return outStream.ToArray();
        }
    }
}
```

**Comment by JimBobSquarePants** [comment]
Hi there,

Yeah, `Resize.Pad` doesn't quite do what you're after  I've tried to [document](http://imageprocessor.org/imageprocessor/imagefactory/resize/) the methods to demonstrate what you should expect from the output.

>Ok, I found a workaround. First I have to Pad width and then I Pad height. It would be nice to make it in one statement though :)

You could always submit code to build a Pad extension or `IGraphicsProcessor`? :stuck_out_tongue_winking_eye: 

>Also, it would be very cool to define a color (default is Color.Black) which will be used for padding.

One step ahead of you.... The default color you are describing is the result of jpegs not having an alpha channel; I don't actually set anything.  You can actually set a background colour though, there is a method for it demonstrated [here](http://imageprocessor.org/imageprocessor/imagefactory/backgroundcolor/). Call that method after resizing.

Cheers

James

p.s I'm gonna go ahead and close this now.

**Comment by gabrielius** [comment]
Ok, that explains everything. For me even in the samples of padding it seems that Resizing with Padding should work as I expect, since Resize method does nothing if Size is bigger than the image & upscale = false (as far as I remember). Nevertheless I have created an extension method for myself, maybe some time I will make a contribution :) 

By the way, you left a typo "contin" in the [document about Resizing] (http://imageprocessor.org/imageprocessor/imagefactory/resize). 

Nice lib, thanks.
