### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by markharrisonuk** [JimBobSquarePants/ImageProcessor#185]
I'm finding that the first time I access an image - the image is failing to be retrieved.  But it is generating it in the cache.   If I retry and access the image again - it works.

Is there some timeout that is configurable - and perhaps set to low ?

**Comment by JimBobSquarePants** [comment]
Version etc please....

- Is this a remote request?
- Local request? 
- Original Image size? 
- Original Image Format?
- Hosting setup?


What do you mean by failing to be retrieved?

**Comment by markharrisonuk** [comment]
It works fine in testing - but when I publish to a hoster I get the issue.  Local to the web site.
Original size is 3000 x 2000 ... trying to generate a 500 x 500 image 
Fails - as in the HTTP request fails.
Latest versions of software from Nuget
thanks

**Comment by markharrisonuk** [comment]
i just did a network trace using the built in browser tools.

the trace says 200OK contenttype image/jpeg and 36.55kb received

but the web browser says "This page can't be displayed' ... I'm just browsing to the image not a webpage

Weird is failing to display - yet the trace looks good.

try again / refresh ... and it works

**Comment by markharrisonuk** [comment]
I was using IE.  Tried with Firefox same issue - except it says "The connection was reset while the page was loading",    again the developer tools / network trace looks good ... says 200 status code 12.42kb transferred.  

Refresh and the image appears - this time the network shows 60.58kb transferred

**Comment by JimBobSquarePants** [comment]
I don't think this is an ImageProcessor issue.

Is it shared hosting by any chance? They're usually underpowered. My money is on your setting imposed by your hosting have a too low value for `executionTimeout`.

Checkout the following link for configuration info. http://stackoverflow.com/a/13947988/427899

**Comment by markharrisonuk** [comment]
Yes - Shared Hosting.  Thanks for the link. 
I changed the  maxRequestLength & maxAllowedContentLength lengths in the web.config ... seems to be working at the moment. :-)   thank you

**Comment by JimBobSquarePants** [comment]
Ace!... I'll close this then. Have fun!
