### ISSUE TITLE
PostProcessor not working correctly

### ISSUE THREAD

**Issue by Phyxion** [JimBobSquarePants/ImageProcessor#186]
This is in Umbraco at least. 

Perform the following steps:
* Delete all images from the cache folder.
* Load the website and check the filesize of an image that's processed by ImageProcessed (I use a preset for this). 
* Load the website again and check the filesize again, it's different (now the PostProcessor is executed).

I'm not sure if this is related to the caching as I sometimes don't see the cached images written to the cache folder until I refresh again. When this occurs I need to load the website another time before the image size is reduced.

**Comment by JimBobSquarePants** [comment]
This is by design.

The post processor can only work after the image has been written to the cache as applying the algorithms is an expensive process which can be slow. If I kept someone waiting 5-10 seconds for the process to finish it would be unacceptable. The first person to request the image gets the resized but unoptimized images but subsequent viewers get the optimized ones.

>I'm not sure if this is related to the caching as I sometimes don't see the cached images written to the cache folder until I refresh again. When this occurs I need to load the website another time before the image size is reduced.

I don't understand what you mean by this? Cached images are always displayed to the end user.

**Comment by Phyxion** [comment]
Thank you for the information, that makes sense (we only use resize on a few images so it's almost done immediately). 

I noticed that the image is not always written to the disk for the first visit (I checked this with multiple applications). I'm not entirely sure what's going on though as the images do load correctly for the first visit. It doesn't matter that much though.

**Comment by JimBobSquarePants** [comment]
Hmmmm They're definitely written to disk, I redirect to the cached file after saving. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/b207c6c463d368a19fda8afa4d865793761b8394/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L583

https://github.com/JimBobSquarePants/ImageProcessor/blob/b207c6c463d368a19fda8afa4d865793761b8394/src/ImageProcessor.Web/Caching/DiskCache.cs#L229

What you're seeing is most probably explorer not keeping up. I see that all the time when I'm testing.

**Comment by Phyxion** [comment]
I also checked it with cmd and Total Commander, they both didn't show the files. Maybe it's all part of the same problem, I don't know but as long as the images load I'm happy :+1:

**Comment by JimBobSquarePants** [comment]
I imagine they probably tap into the same underlying Windows API's.

I'll give this a close then, Thanks! :smile:
