### ISSUE TITLE
Crop Documentation Confusing

### ISSUE THREAD

**Issue by coderangerdan** [JimBobSquarePants/ImageProcessor#188]
I think the documentation for [Crop](http://imageprocessor.org/imageprocessor/imagefactory/crop/) is wrong; it appears its not Left, Top, Right, Bottom but Left, Top, Width, Height.

**Comment by JimBobSquarePants** [comment]
Looks correct to me.

>**Right**
The `System.Float` defining the **width** of the crop layer. When the crop mode is defined as `CropMode.Percentage` this becomes the percentage you want to remove from the right hand side of the image.

https://github.com/JimBobSquarePants/ImageProcessor/blob/b207c6c463d368a19fda8afa4d865793761b8394/src/ImageProcessor/Imaging/CropLayer.cs#L69

**Comment by Squiggle** [comment]
Surely this _is_ wrong.

For example, to crop a 100x100 square from the center of a 200x200 image, one would assume the values are: `Left: 50, Top: 50, Right: 50, Bottom: 50`

Instead we need to enter the the width and height, so the values are: Left: 50, Top: 50, Right: 100, Bottom: 100.

It's just a matter of naming the parameters more appropriately, but it took me a while to figure out what was going wrong when my code appeared to be fine.

**Comment by JimBobSquarePants** [comment]
The params mean two different things based on mode. Docs are really clear. http://imageprocessor.org/imageprocessor/imagefactory/crop/#usage

**Comment by JimBobSquarePants** [comment]
Couldn't change them if I wanted to either.
