### ISSUE TITLE
502 gateway issue when using Azure and CloudService

### ISSUE THREAD

**Issue by perosb** [JimBobSquarePants/ImageProcessor#189]
We are getting a 502 Gateway error sometimes which results in broken images.
Usaully the image works again after a couple of refreshes.

The below stacktrace might be related.

This is hosted on Azure, with the new UmbracoAzure FileSystemProvider.
Files are cached on disk and we are using WebP if supported.

`System.IO.IOException: The process cannot access the file 'D:\home\site\wwwroot\app_data\cache\0\6\5\f\2\7\065f27fc2c8e843443d210a1e84d1ea28bbab6c4.webp' because it is being used by another process. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) at System.IO.File.Create(String path, Int32 bufferSize) at System.IO.File.Create(String path) at ImageProcessor.Web.Caching.DiskCache.<AddImageToCacheAsync>d__10.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__10.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)`

**Comment by JimBobSquarePants** [comment]
Urgh.... Turns out I was checking if a file existed synchronously outside of my asynchronous lock and creating one inside. That causes the IO error on disk and most probably your gateway one on Azure. WIll deploy asap.

**Comment by perosb** [comment]
Awesome! Thanks.

I havent seen the issue since I switched to Azure Blob cache.

**Comment by JimBobSquarePants** [comment]
Fix released now. Enjoy! 

https://www.nuget.org/packages/ImageProcessor.Web/
