### ISSUE TITLE
Strong Name Sign

### ISSUE THREAD

**Issue by coderangerdan** [JimBobSquarePants/ImageProcessor#190]
Is it possible to strong name sign the DLL in your nuget package distro?

**Comment by JimBobSquarePants** [comment]
You'd have to wire it up yourself from the src I'm afraid. I don't get many requests for it. 

I need to change the build process actually so as to make it more flexible. 

What's the use case for strong naming anyway. I'm torn about it after reading these.
http://blog.marcgravell.com/2014/06/snk-we-need-to-talk.html
http://blog.marcgravell.com/2014/07/snk-and-me-work-out-compromise.html

**Comment by JimBobSquarePants** [comment]
Actually I think you might be able to use this to do it. 

https://www.nuget.org/packages/Nivot.StrongNaming/1.0.4.2

**Comment by coderangerdan** [comment]
I am using that already but it's not great, it doesn't present a gui, it doesn't work from build events and only from command line and therefore I can't set it up so it works automatically for every user of the project. I need it strong signed because it's necessary for my distribution. Understand if you don't want to do it, was just hoping it was something you would be able to do.

**Comment by JimBobSquarePants** [comment]
It's not something I have any experience with really. Wouldn't it have an affect on my version numbers? 

If I can improve my build process I might be able to automate a strong version. I can't promise just now though as I don't know how successful I will be.

**Comment by robv8r** [comment]
A Strong Name is only as trustworthy as the signer's ability to properly manage the private key of the Strong Name Key Pair.  If you are going to take on the responsibility of Strong Naming your assemblies, I strongly encourage you to read up on how to protect the private key of your Strong Name Key Pair.  For instance, the process of delay-signing your assemblies describes how to extract and distribute the public key of our your SNK while keeping your private key secured.

I've seen many open source projects openly publish their key pair along with the source code.  In my opinion, this completely invalidates the purpose of strong naming the assembly in the first place.

I've been working with Strong Named Assemblies for many years.  I'm very happy to further discuss the pros and cons of Strong Naming and my take on how to best manage the build process and protect your keys.
