### ISSUE TITLE
Constrain resizes small images to be bigger

### ISSUE THREAD

**Issue by darrenshrwd** [JimBobSquarePants/ImageProcessor#191]
Trying to use .Constrain in order to constrain images to not be any bigger than certain dimensions, however if the image is already smaller than the dimensions given it actually scales the image up.

                        // Save constrained for sharing
                        imageFactory.Load(ms)
                            .AutoRotate()
                            .Constrain(new Size(800, 600))
                            .Format(format)
                            .Save(fullPath);

I can get around this by testing the dimensions beforehand, but this doesn't seem right.

**Comment by darrenshrwd** [comment]
Whoops, I read the resize doco and now use that instead with upscale: false.

                        // Save constrained for sharing
                        imageFactory.Load(ms)
                            .AutoRotate()
                            .Resize(new ResizeLayer(new Size(800, 600), ResizeMode.Max, upscale: false))
                            .Format(format)
                            .Save(fullPath);

**Comment by JimBobSquarePants** [comment]
Glad you found the solution. Yeah, using the `Resize` method allows you a lot more flexibility.
