### ISSUE TITLE
NullReferenceException in ImageProcessor.Web.Helpers.ExtendedColorTypeConverter

### ISSUE THREAD

**Issue by AndyA13** [JimBobSquarePants/ImageProcessor#192]
I can't reproduce this locally :rage:  but keeps happening on an azure website instance.

Not 100% sure the issue is at your end, but you probably know more about the type converters and can shine some light on it.

`ImageProcessor.Web.Helpers.ExtendedColorTypeConverter in ConvertFrom at line 66:0`

The line number doesn't seem to be accurate.

When creating a spreadsheet using [ClosedXml][0], the [`InitializeTheme` method][1] makes some calls to [`XLColor.FromHtml`][2]

It is using 8 character hex codes :anguished: Examples:
```
    Text1 = XLColor.FromHtml("#FF000000"),
    Background1 = XLColor.FromHtml("#FFFFFFFF"),
    Text2 = XLColor.FromHtml("#FF1F497D"),
    Background2 = XLColor.FromHtml("#FFEEECE1")
```
It looks like `XLColor.FromHtml(string htmlColor)` is calling `ColorTranslator.FromHtml(htmlColor)` which is finding your type converter and calling that.

Stacktrace:
```
    Module "Usercontrols.FormDataViewerPages.List", line 6, in DataTableToExcelByteArray
        Byte[] DataTableToExcelByteArray(System.Data.DataTable, System.String)
    Module "ClosedXML.Excel.XLWorkbook", line 245, in .ctor
        Void .ctor(ClosedXML.Excel.XLEventTracking)
    Module "ClosedXML.Excel.XLWorkbook", line 0, in InitializeTheme
        Void InitializeTheme()
    Module "System.Drawing.ColorTranslator", line 297, in FromHtml
        System.Drawing.Color FromHtml(System.String)
    Module "ImageProcessor.Web.Helpers.ExtendedColorTypeConverter", line 66, in ConvertFrom
        System.Object ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
```

A quick local test with `ColorConverter` seems to return a valid color from the 8 character codes.

Packages | Versions
-------------|-------------
DocumentFormat.OpenXml | 2.5.5631.0
ClosedXml | 0.76.0.0
ImageProcessor | 2.2.6.0
ImageProcessor.Web | 4.3.4.0

[0]: https://closedxml.codeplex.com/
[1]: https://closedxml.codeplex.com/SourceControl/latest#ClosedXML/ClosedXML/ClosedXML/Excel/XLWorkbook.cs
[2]: https://closedxml.codeplex.com/SourceControl/latest#ClosedXML/ClosedXML/ClosedXML/Excel/Style/Colors/XLColor_Static.cs

**Comment by JimBobSquarePants** [comment]
Hmmm... This is interesting. They must be using the TypeDescriptor to look for converters.

Ignoring the line number as I think you're right and it is probably wrong, I wonder whether the issue is caused by a lack of culture getting passed through? That's the only place I could imagine a null reference exception occurring.

https://github.com/JimBobSquarePants/ImageProcessor/blob/d4171429ce470e890f76b0f2000120bf779791f2/src/ImageProcessor.Web/Helpers/QuerystringParser/ExtendedColorTypeConverter.cs#L77

I'll see if I can knock up some time to put a test for this. If you can in the interim it would be very much appreciated.

**Comment by AndyA13** [comment]
I've added a test to call the ExtendedColorTypeConverter directly, these are all failing with the null reference exception at the moment.

https://github.com/AndyA13/ImageProcessor/blob/fix/8-digit-hex-color-codes/src/ImageProcessor.Web.UnitTests/ExtendedColorTypeConverterTests.cs

Should the setting of culture to a default maybe be handled by the converter itself? As it might not always be called from QueryParamParser.

https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Helpers/QuerystringParser/QueryParamParser.cs#L101

It'll probably be tomorrow before I can take another look at this.

**Comment by JimBobSquarePants** [comment]
Yeah, you're correct, they should be able to be used independently. I overlooked someone else calling them directly. If you can have a look tomorrow that would be great. I'm swamped.

**Comment by AndyA13** [comment]
[This regex][1] matches 8 character hex codes, but [the following code][2] assumes that if it's not a 6 character code then it must be 3 characters.

So at the moment [this test case][3] is failing as it is returning yellow. `#ff0000ff` is just taking the first 3 chars so it gets `#ff0`

So do you want to handle that case or should it just be passed to the base ColorConverter. Not sure if ColorTranslator comes into it, but this works fine in Linqpad.

```
System.Drawing.Color c = System.Drawing.ColorTranslator.FromHtml("#ff0000ff");
c.Dump();
```

[1]: https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Helpers/QuerystringParser/ExtendedColorTypeConverter.cs#L29
[2]: https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Helpers/QuerystringParser/ExtendedColorTypeConverter.cs#L118-L129
[3]: https://github.com/AndyA13/ImageProcessor/blob/3a094995e470d05c27b3844b4eef00c8cd30ae2d/src/ImageProcessor.Web.UnitTests/ExtendedColorTypeConverterTests.cs#L14

**Comment by JimBobSquarePants** [comment]
Looking at the source for [ColorTranslator](http://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Advanced/ColorTranslator.cs) it looks like it passes off the translation of 8 digit hex codes to another converter. I guess that must be happening in Linqpad somehow.


What I shall most likely do is steal a bit of code from [ColorConverter.ConvertFromString()](http://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ColorConverter.cs) to deal with 8 digit codes.
