### ISSUE TITLE
Improve the build process.

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#195]
I'd like to integrate the build progress more closely with AppVeyor and start hosting nightly builds on MyGet much like dotnet are doing. I'd also like to get the automated coverage tests working with a badge.

I have example configuration from simple projects that do this. @cosmo0 Is this something you could help with? You know much more about this stuff than I.

- https://github.com/leekelleher/umbraco-ditto
- https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure

Anyone else like to take this on?

**Comment by robertjf** [comment]
Hey @JimBobSquarePants I'll take it on if you like - about time I took a good look at AppVeyor... doesn't look too hard :)

**Comment by JimBobSquarePants** [comment]
:100: Cheers @robertjf that would be ace!

**Comment by cosmo0** [comment]
Hi! I'm back from vacations.
@robertjf have you already taken a look?

**Comment by robertjf** [comment]
@cosmo0 not of any substance - work has me going almost 20 hours a day at the moment it feels like
