### ISSUE TITLE
Change image DPI

### ISSUE THREAD

**Issue by sebascomeau** [JimBobSquarePants/ImageProcessor#196]
Hi,

How to change easily an image from 230 DPI to 96 DPI with ImageProcessor?

Thanks

**Comment by JimBobSquarePants** [comment]
Hi,

There is no way at present to do so but I think you or I could add something easily enough. It would require us to ensure that any EXIF data is set in addition to bitmap data.

I'll look into it when I get a chance.

**Comment by sebascomeau** [comment]
Thanks!

**Comment by JimBobSquarePants** [comment]
No worries... The latest build does it now via a method on the `ImageFactory` called `Resolution()`. I need to check some other stuff but I should be able to get a release out soon enough.

**Comment by sebascomeau** [comment]
Hey Jim,

Do you know when you will published the method Resolution() on Nuget?

Thanks

**Comment by JimBobSquarePants** [comment]
Soon hopefully. I've recently moved to Australia so progress has been slow. (Sharing internet from my phone to my laptop atm)

Probably the beginning of next week though.

**Comment by sebascomeau** [comment]
Cool! 

Thanks for your good work btw.

**Comment by JimBobSquarePants** [comment]
Cheers!:smile:

**Comment by JimBobSquarePants** [comment]
Fixed in [v2.3.0](https://www.nuget.org/packages/ImageProcessor/2.3.0)

**Comment by zpbd** [comment]
Hi James, is there any way to choose the DPI via querystring parameter?

We have a client that loves to upload 400 PPI images that are massive even when cropped.

**Comment by JimBobSquarePants** [comment]
Hi @zpbd 

No but you could pretty easily create your own WebGraphicsProcessor to to that for you. Check out the examples in the repo.
