### ISSUE TITLE
Watermark to horizontal for portraits photos

### ISSUE THREAD

**Issue by chuki2** [JimBobSquarePants/ImageProcessor#198]
Dear Mr Jim,

How can I make my watermark as horizontal for potraits photo in C# language? It is possible?

Here the sample of image 

![03da4e02-f419-421a-bde7-7e92245db357](https://cloud.githubusercontent.com/assets/13462282/8843483/5ac03174-313b-11e5-9295-968f92bdca18.jpg)

**Comment by JimBobSquarePants** [comment]
Hi there, are you using ImageProcessor or ImageProcessor.Web?

**Comment by chuki2** [comment]
Sorry forgot to mentions, I using ImageProcessor

**Comment by JimBobSquarePants** [comment]
Interesting... By default for me, the text watermark would be horizontal. I wonder whether this is a culture setting?  What would your default be?

**Comment by chuki2** [comment]
Do you means culture settings in my computer?

Currently I was stay in Malaysia, so my culture settings is English (Malaysia) "en-MY"

Here is my code in C#

 // Initialize the ImageFactory using the overload to preserve EXIF metadata.
                                        using (var imageFactory = new ImageFactory(preserveExifData: true))
                                        {
                                            // Do your magic here
                                            imageFactory.Load(inStream)
                                                .AutoRotate()                                        
                                                .Resize(size)
                                                .Format(format)
                                                .Watermark(new TextLayer()
                                                {
                                                    DropShadow = true,
                                                    Text = "TESTING",
                                                    Style = FontStyle.Bold,
                                                    FontColor = Color.White,
                                                    Opacity = 70,
                                                    FontSize = 45,
                                                })
                                                .BackgroundColor(Color.White)
                                                .Save(outStream) ;

**Comment by chuki2** [comment]
Any suggestion?

**Comment by JimBobSquarePants** [comment]
Sorry, not had a chance to look yet. I think it might be something to do with `AutoRotate()` try moving it to before `Save()`

**Comment by JimBobSquarePants** [comment]
Ok.. I've just realised that you are combining retaining EXIF metadata with the AutoRotate method. 

AutoRotate is used to ensure that the orientation of the image is correct when the metadata is to be removed; otherwise it will do nothing.

http://imageprocessor.org/imageprocessor/imagefactory/autorotate/

If you turn off metadata preservation in the ImageFactory constructor and use the watermark method it will work correctly. If you need the EXIF metadata to be preserved I need to fix ImageProcessor so that the watermark is calculated correctly. I'm moving to Australia from the UK this week so if I can't get it done in the next 24 hours it'll be a few weeks most probably before I can submit a fix.

**Comment by chuki2** [comment]
Ok thanks jim, let me check...

**Comment by chuki2** [comment]
Dear Jim, Went I turn off  the EXIF to false is working. Thanks a lot. Good and keep it up!

**Comment by JimBobSquarePants** [comment]
Ace! The next version will work with EXIF on also. :smile:
