### ISSUE TITLE
ImageService prefix with site in a virtual directory

### ISSUE THREAD

**Issue by richsoft** [JimBobSquarePants/ImageProcessor#199]
I am trying to deploy my webapp to IIS, where the site is run within a virtual directory, rather then in the root of site and use the remote image service and a custom ImageService that I have written

However, it appears that the HttpModule is either not run, or more likely the prefix does not match as I expected when the site is not in the root (which caused me some confusion as to why it worked in VS but not when in IIS!):

*http://domain.com/myapp/remote.axd/url-to-image?width=200*

rather than:

*http://domain.com/remote.axd/url-to-image?wdth=200*

To make this work, it appears that the prefix in the service config must also include the virtual directory eg:  *'myapp/remote.axd'*, as I think it does a StartsWith on the URL.

Am I missing a configuration item that will make this work without hardcoding the virtual directory path into the prefix config?

Thanks,

Richard

**Comment by JimBobSquarePants** [comment]
Hi Richard,

There's no additional config values so yeah, you would.

Have you been able to replicate the issue using IIS rather than IISExpress on your development machine? I'd like to see exactly what would be causing the url to be parsed incorrectly if that is the case so adding a debugger would be really useful.

Cheers

James

**Comment by richsoft** [comment]
Hi James,

Thanks for you quick reply!

I don't think there is a problem parsing the URL; I had VS setup to use IIS Express, but the site was not set to run in a virtual directory (the url was something like *http://localhost:16000/remote.axd*), so the normal prefix worked as expected.

The problem is that I misunderstood how the prefix works, and the fact that the HttpModule just looks at the start of the path and, if it matches, it handles the request.   

As the site is in a sub-directory, the path will never start with the prefix but have the folder name first (*/myapp/remote.axd/...*).  You can't use the normal root-relative url */remote.axd/...*, as it will never be handled as IIS will look in the root for a file called remote.axd instead as the module isn't registered there (if you see what I mean!).

I may look to see if its possible to edit the HttpModule so when it looks at matching the prefix it takes into account the path of the site, however this isn't a show-stopper for me at the moment.

Expect a couple of beers from me, as you have made my latest project **much** easier :)   It's a rewrite of an app I developed a few years ago, and the image manipulation was always a bit dodgy, and the caching ability of the library is a huge bonus!

Cheers

Richard

**Comment by JimBobSquarePants** [comment]
Hi Richard,

I'm really happy to hear that it's made working on your project much easier. It exactly why I've continued to work on the solution over the last few years :smile: 

I think it should be possible to augment the way the `IImageService` is identified using the prefix to allow for virtual paths. I originally used `StartsWith` as that reduced the chance of collision with site urls. I'm wondering whether we could turn it into a regular expression? That would allow much greater flexibility and backwards compatibility. I'll need to experiment by copying your setup to see what the best plan is.

Cheers

James 

Oh and thanks for the beer money! :beers:

**Comment by richsoft** [comment]
Hi,

I realised yesterday, that I could implement this in my custom `IImageService` by adding the virtual path to the prefix from the config file in the `Prefix` property setter (I'm using VB)..

    Public Property Prefix As String Implements IImageService.Prefix
        Get
            Return _prefix
        End Get
        Set(value As String)
            Dim request = HttpContext.Current.Request
            Dim path = request.ApplicationPath

            _prefix = (path.TrimEnd("/") & "/" & value).TrimStart("/")
        End Set
    End Property

This seems to work for me in both IIS Express (in the root of the site) and when deployed to a virtual directory in full IIS.   I no longer have to edit the security.config to update the prefix attribute when I deploy.

Thanks,

Richard
