### ISSUE TITLE
Setting format to PNG causes color shift

### ISSUE THREAD

**Issue by dsargent3220** [JimBobSquarePants/ImageProcessor#204]
Not sure if I'm doing something wrong here.
If I set the format of an image to Ping colors shift,  blues become more purple.
If I set the Ping settings, nothing seems to change.
Example:

```
ISupportedImageFormat imageFormat = null;   
PngFormat pf = new PngFormat();
pf.IsIndexed = false;  // Also tried true
pf.ColorCount = 1;  // Also tried 8, 16, 24, 32 with no difference
pf.Quality = 20; // Tried 100 etc.
imageFormat = pf;
imageFactory.Format(imageFormat);
```

Note: I tried setting the above PngFormat settings to extream to see what the change is, but it doesn't seem to do anything. 
I've tried this with source files that are JPEG's and source files that are already Ping's
Also note that changing the setting to Gif does what is expected.

Is this broken or am I missing something obvious.

**Comment by JimBobSquarePants** [comment]
Hi,

So.. PNG is a lossless format and setting the quality will have no effect on it. Setting the colour count will only effect 8bit pngs.

I recommend you read this. https://en.wikipedia.org/wiki/Portable_Network_Graphics

Could you please post an example of exactly what you are doing to the images? Resizing, cropping etc? An example image too so I can replicate. I can't see what you have done. 

Could you also let me know if there is any difference if you turn off gamma correction in the ImageFactory constructor?

Cheers

James

P.s I added code formatting to your sample to make it easier to read. There's a guide for how to do that here. https://guides.github.com/features/mastering-markdown/

**Comment by dsargent3220** [comment]
Jim.  Thanks for the reply.  I've tried turning off Gamma correction using 	imageFactory.FixGamma = false;  The end result was just a darker, but still color shifted image.
I'm attaching the original image.
As far as processing.  Right now I'm just setting the format to PNG.
That might not make sense.  But here's our scenario.  We are uploading PNG's as our losless source and setting them to convert to JPG at 85% by default.  They are also being resized to certain breakpoints based on the size of the source device.  We can then pass some params to have them be returned as GIF or PNG (if we want the original).  It's when we tell it to return the PNG that it does something strange and color shifts the image.  The really weird part is if you view the original image with Windows Photo Viewer you also see that purpalish shift.  But if you view the original with any other photo viewer including all three browsers you do not see the shift.
We've double and triple checked the images and can find no color profile information.

I'am attaching the original image and screenshots of the out put in JPEG and PNG.
Original:
![industry-placeholder2](https://cloud.githubusercontent.com/assets/3372486/9308146/3d2bc5e4-44b7-11e5-8418-f4f576199312.png)
Screenshot of the image converted to a JPEG
![imageasjpg](https://cloud.githubusercontent.com/assets/3372486/9308234/c3e8b0ec-44b7-11e5-921f-576ed5febe31.jpg)
Screenshot of the image converted to a PNG (Purple!)
![imageaspng](https://cloud.githubusercontent.com/assets/3372486/9308246/d14d6016-44b7-11e5-9891-a8c274294a36.jpg)

**Comment by dsargent3220** [comment]
I should also mention that this color shift has happened in every image I've tried so far, regardless of original format (JPEG or PNG)

**Comment by JimBobSquarePants** [comment]
Unfortunately I've not been able to replicate this at all on multiple local machines. 

Do you have any custom color profiles attached to the machine itself? I'm wondering whether the browsers are ignoring that and using their own but the Windows Photo Viewer and .NET framework are reading those profiles when loading/manipulating the image. 

This is the first case I've ever had where something like this is happening.

**Comment by dsargent3220** [comment]
I checked the Color Profiles and my machine and there is one installed as I have a Dell U2410 display but according to the settings its using the system default sRGB.  I've tried changing them but nothing seem to alter how the image is displayed.
On Monday a security update fried my Visual Studio.  I'd been waiting to upgrade to Windows 10 and a larger SSD so I did that instead of troubleshooting this further.  So now I'm running a new install of Windows 10 and it still does it.
However, when we deploy the code to one of our servers and I view the same image from there in PNG and JPEG, it does not.
So . . .  Yeah.
I guess I'm good here, as long as it's not doing it on the server, I'm happy.

**Comment by dsargent3220** [comment]
Update!  I was pointing to the wrong server, that one didn't have the new code on it so it wasn't doing the format conversion.
Against the correct server I DO see the color shift on my workstation but my coworker does not.  Which says to me it's somehow client based, which makes no sense.
This is a little bit troubling as we won't know what our customers are seeing when we display PNG files.
Thoughts?

**Comment by JimBobSquarePants** [comment]
I really don't think this is an ImageProcessor specific thing. If it's specific to individual monitor setups that's going to be due to incorrect color profiles or some other such corruption. I use the standard .NET encoders/decoders when processing images.
