### ISSUE TITLE
How to properly cache images when changing width internally

### ISSUE THREAD

**Issue by dsargent3220** [JimBobSquarePants/ImageProcessor#205]
I'm sure the above title is a bit confusing, so let me explain what I mean.
First off, we may be trying to do this wrong.  If you can think of a better way we are all for it.

Our goal is to set certain "image breakpoints".  What I mean is this.
If the Query String has a width of 1080, we'd check a list of breakpoints and pic the next highest one up and actually reside the image to a width of 1200.

Right now we are doing this by creating our own Resize based on the one in ImageProcessor.Web and putting some custom code in the ParseSize method.
This code does a couple things, but the most important for us in this case is that we reset width to one of the breakpoints as mentioned above.

This works from a processing standpont but fails from a caching standpoint.
If I call an image with a width of 300 and then again with a width of 301, IP.Web caches two versions of the image (I've looked through the code quickly and it looks like it's due to the QS) but both images are exactly the same (i.e. both are set to the width of the next breakpoint up)

Any thoughts on how I can do this better or different?  It's almost like we need to alter the QS before IP.Web gets it, but I don't know how to do that.

**Comment by JimBobSquarePants** [comment]
Hi,

Hacking a new Processor would be the incorrect approach. You're far too late in the pipeline

You need to be determining the request url on a client side basis. There are HTML elements that have partial browser support for doing this but I would recommend using [Picturefill](https://scottjehl.github.io/picturefill/) to do this as then you have full support. You can supply a source url for different media widths and get the correct image for each breakpoint.

Hope that helps.

**Comment by HughJeffner** [comment]
I saw this and thought it might help: `ImageProcessingModule.OnProcessQuerystring`

You can inspect and manipulate the QS

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events
