### ISSUE TITLE
Problem with ImageFactory.Load

### ISSUE THREAD

**Issue by ghua78** [JimBobSquarePants/ImageProcessor#207]
Hello!
I am tryin gto load 24 bit PNG into windows Forms.PictureBox.

```
photoBytes = File.ReadAllBytes(open.FileName);
using( MemoryStream inStream = new MemoryStream(photoBytes))
{
  using (MemoryStream outStream = new MemoryStream(outBytes))
  {
    using (ImageFactory imageFactory = new ImageFactory())
    {
      imageFactory.Load(inStream);
      ...
     }
  }
}
```
and then attach image by `pictureBox1.Image = imageFactory.image`

Problem is image displayed in pictureBox is dithered. It doesnt happen when I do pictureBox1.Load(open.FileName);

Any ideas? I really like the library but we need more samples :)

**Comment by JimBobSquarePants** [comment]
Hey chum,

Sorry to hear you've had problems. Can you give me a few basics to work with to I can diagnose the issue please.

- ImageProcessor version number
- A link to the original image or a sample program so I can test (both would be best).

Cheers

James

p.s Github supports [code formatting](https://guides.github.com/features/mastering-markdown/). I've edited your post to use that.

**Comment by JimBobSquarePants** [comment]
Closed as no response.
