### ISSUE TITLE
Image is changed and made larger when no processing is requested.

### ISSUE THREAD

**Issue by dsargent3220** [JimBobSquarePants/ImageProcessor#208]
Good morning.  I was just testing the case where we want ImageProcessor.Web to output and cache the image but not change it in any way and found the cached image file ended up bigger (in terms of file size) than the source.

I'm attaching both images below.
The only "custom" code we have is Remote Image Service that specializes how to load the image from our back end server.  It's pretty much a copy of the built in remote image service with some minor modifications we needed, none of which should affect the image AFAIK.

The source is 526K and the cached version is 572.  I don't know how to see what is different in them. Their resolution is the same.  The only thing I can think of is that I've seen this kind of thing when using PNG Crush (sometimes images get bigger when crushed).  Is it a difference in the compression algorithm used?

Is there a way to tell ImageProcessor.web to do nothing to the image except cache it?

Here they are.
![849_callouts](https://cloud.githubusercontent.com/assets/3372486/9471747/afaa4d34-4b06-11e5-8ace-7929f1f5fa1e.png)
![9eb4b3c7d467a9f974ba00b0121ab20cec577d5c](https://cloud.githubusercontent.com/assets/3372486/9471748/afbae4f0-4b06-11e5-906b-0df218106e87.png)

**Comment by kenyus** [comment]
+1 for me too
I have similar problem with trying to output image without modifying it, in my case the image is also PNG but file size is shrink from 1MB to nearly 200KB which obviously means lost in quality as the image looks much horrible. 
Again how can we output the image without changing quality? As we want to utilise the same method of caching and validating our protected images.

**Comment by JimBobSquarePants** [comment]
@dsargent3220  What you're seeing is down to the built in .NET encoder - It's not great so I'm trying to work on a way to improve the output. The current development code uses post processing to ensure that the output is as optimized as possible. Could you build from source (sorry, no nightlies yet) and test against that?

@kenyus Something doesn't seem right about your description. For an image to shrink 800kb simply by resaving it seems infeasible to me. Do you have postprocessing installed? Are you changing format? Is it actually a png or a bitmap with the incorrect extension.

Could you post the original image online?

**Comment by JimBobSquarePants** [comment]
Fixed in [v4.4.0](https://www.nuget.org/packages/ImageProcessor.Web/4.4.0)
