### ISSUE TITLE
Cross platform version of System.Drawing

### ISSUE THREAD

**Issue by Emasoft** [JimBobSquarePants/ImageProcessor#210]
I'm working on a cross-platform version of System.Drawing. Are you interested in helping me? It would be useful for making your library usable on PC, Mac, Linux, OSX and Android at the same time. I'm currently using Mono and Xamarin for achieving this.

**Comment by JimBobSquarePants** [comment]
That sounds like quite an enormous undertaking. What are your plans? To wrap around an existing image library or do something from scratch?

Microsoft have started something themselves [here](https://github.com/dotnet/corefxlab/tree/857d1b53f4820200569273901b96694726716e3c/src/System.Drawing.Graphics) though I'm not convinced they will get it working as progress has been almost non existent and they only have interns working on it. 

I'm aiming a little lower and attempting to create a cross-platform library in C# to do basic operations like resizing/cropping etc. You can see my current progress in the v3 branch.
