### ISSUE TITLE
the term "media" is globally replaced in path

### ISSUE THREAD

**Issue by perosb** [JimBobSquarePants/ImageProcessor#211]
It seem thata the "prefix", ie "media" is globally replace in the path which means that you cannot have an image named ```my_media_image.png```

**Comment by perosb** [comment]
my git is strange and not sure what up.

fix here https://github.com/perosb/ImageProcessor/commit/b1d1e6523f8593448ac56dfc7824b9cc96e77ed8

**Comment by JimBobSquarePants** [comment]
Fixed in [v4.4.0](https://www.nuget.org/packages/ImageProcessor.Web/4.4.0)
