### ISSUE TITLE
Lanzcos Kernal A=3 Seems Off?

### ISSUE THREAD

**Issue by christopherbauer** [JimBobSquarePants/ImageProcessor#215]
I was trying to write tests for Interpolation.LanzcozKernal3 method. I'm not great with math, so I just wanted to bring this up, just in case my understanding how these are being used. According to the wikipedia, https://en.wikipedia.org/wiki/Lanczos_resampling it appears that A=3 should be 0 for -2, -1, 1, and 0. I wrote my tests with that expectation and they all fail except for x=0 (expected: 1d):

        [TestFixture]
        public class WhenInterpolatingLanczosKernel3
        {

            [Test]
            [TestCase(-2, 0d)]
            [TestCase(-1, 0d)]
            [TestCase(0, 1d)]
            [TestCase(1, 0d)]
            [TestCase(2, 0d)]
            public void ThenShouldReturnExpectedGivenX(double x, double expected)
            {
                // Arrange
                var lanczosKernel3 = Interpolation.LanczosKernel3(x);

                // Act // Assert
                Assert.That(lanczosKernel3, Is.EqualTo(expected));
            }

        }
Am I misunderstanding this?

**Comment by JimBobSquarePants** [comment]
Thanks... I'll have another look. I wouldn't bother with that class nor FastResizer just now since I'm not actually using them as I couldn't make them performant just now. I will however use some of the algorithms in V3.

**Comment by christopherbauer** [comment]
Ok I'll take a walk on these.

**Comment by JimBobSquarePants** [comment]
Cheers :+1:

**Comment by JimBobSquarePants** [comment]
Looking at the equation again

![92347cbe4a147f80bdb246dc963a9f87](https://cloud.githubusercontent.com/assets/385879/9851681/567f236e-5b3d-11e5-9c3d-5b37e729af6e.png)

It would look like I am doing the correct thing within my code, however below is written:

>The Lanczos kernel is zero at every integer argument x, except at x = 0, where it has value 1. Therefore, the reconstructed signal exactly interpolates the given samples: we will have S(x) = si for every integer argument x = i.

Which causes me to believe that three might be either some sort of rounding error on my part or I am missing something where  am supposed to round. This is simple enough to fix comparing against an epsilon though.
