### ISSUE TITLE
Universal App

### ISSUE THREAD

**Issue by bbougot** [JimBobSquarePants/ImageProcessor#225]
Great project! Is this lib compatible with WinRT / Windows Universal App ? I plan using it into Windows Phone 10

**Comment by JimBobSquarePants** [comment]
Thanks! I'm afraid most likely not just now..  I hope to get a v3 going which would be though. I've started a branch but will need help.

**Comment by bbougot** [comment]
Right, I'll try giving you a hand

**Comment by JimBobSquarePants** [comment]
Thanks! Much appreciated :+1:
