### ISSUE TITLE
CloudImageService - support for default container

### ISSUE THREAD

**Issue by tmoxon** [JimBobSquarePants/ImageProcessor#234]
The cloud service is passed an "id" of a file that doesn't include the root container (e.g. /media) and the uri object buildup means that you can't include the /media - or whatever the root container part is - in the host. Need to be able to configure in a container to find the image in.

**Comment by JimBobSquarePants** [comment]
If you setup  the service in your config like this.

    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="Host" value="http://[myAccountName].blob.core.windows.net/media/"/>
      </settings>
    </service>

You wouldn't need the additional container property. However I do quite like the idea of a container property and syntactically the host property would become a misnomer in this instance so I will have a look at the implications breaking the current behaviour would be.

**Comment by tmoxon** [comment]
Ah yes, I see, I missed the trailing slash so the build-up trimmed it. Thanks for the input. I hope the 'fix' / idea is of some use.

**Comment by olaj** [comment]
I'm not 100% sure i understand this questions but i have my files hosted like /dist/icons, dist/screens and so on.

It seems like it's impossible to get rid of the "dist" part of the url.

No matter if i have 

<setting key="Host" value="http://alt2cdn.blob.core.windows.net/dist/"/>

or

        <setting key="Host" value="http://alt2cdn.blob.core.windows.net/"/>

My urls need to be

http://myurl/dist/icons/icon.png?width=100

Would be cleaner to get rid of the /dist/ ...

Thanks for a great library!

**Comment by JimBobSquarePants** [comment]
@olaj 

You should be able to define multiple copies of the cloud image service in the config each with a different name and host url.

``` xml
<service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
         ...
        <setting key="Host" value="http://myurl/dist/icons/"/>
      </settings>
</service>

<service name="CloudImageService2" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
         ...
        <setting key="Host" value="http://myurl/dist/screens/"/>
      </settings>
</service>
```

**Comment by JimBobSquarePants** [comment]
Added in the new release available on Nuget.

**Comment by olaj** [comment]
Still doesn't really behave as i want.

I get a 404 now when i have this settings and try to access http://domain.com/dist/icons/zyzzyva_60317.png?width=90 and http://domain.com/icons/zyzzyva_60317.png?width=90

    <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304" />
        <setting key="Timeout" value="30000" />
        <setting key="Host" value="http://xxxx.blob.core.windows.net/dist/" />
      </settings>
    </service>

If i add the "dist/" prefix it works with http://domain.com/dist/icons/zyzzyva_60317.png?width=90 but still doesn't work with http://domain.com/icons/zyzzyva_60317.png?width=90

    <service prefix="dist/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304" />
        <setting key="Timeout" value="30000" />
        <setting key="Host" value="http://xxxx.blob.core.windows.net/dist/" />
      </settings>
    </service>

Not really sure what is going on here. Is it possible to get rid of the /dist path in my url in some way?

**Comment by JimBobSquarePants** [comment]
Apologies.. I forgot the prefix values. That _should_ fix it.

To be honest... I wouldn't. It's a sensible root path to images. Why not rename it to "images"?

**Comment by olaj** [comment]
Ahh, it's not that important its just acting a bit weird imho, i could live with the /dist path (or maybe rename it) but it would be nice to get rid of it if that was possible.

It feels like the configurations "suggests" that "Host" take that path part of the URL in account but it feels like it just ignoring it?

**Comment by JimBobSquarePants** [comment]
No worries...

Host should do that... Or at least I thought it did... Maybe I only wrote it to handle the first part of the relative url. I'd have to trawl through the source to be sure. 

You could actually write your own `IImageService` implementation based on the `CloudImageService` if it really starts to niggle at you. It's pretty simple and you'd be copying 99% of the code from the current implementation.
