### ISSUE TITLE
ReplaceColor doesn't use the chosen color

### ISSUE THREAD

**Issue by dentalsoftware** [JimBobSquarePants/ImageProcessor#240]
ReplaceColor doesn't use the chosen color. E.g. instead of drawing things yellow as set, the color shows purple. This behavior has changed in the latest release 2.3.0.

regards
Fabian

**Comment by christopherbauer** [comment]
Can you post the code you're using so I can take a look?

**Comment by dentalsoftware** [comment]
Hello Christoph

Here is what I do:

        With myProcessor
            Try
                .Load(myInStream)
            Catch ex As Exception
                MsgBox(ex.Message)
                Return False
            End Try
                .ReplaceColor(Color.LightGray, Color.Yellow, 10)
            End Select
            .Save(myOutStream)
            myOutStream.Flush()
	End With
I attach 2 sample images before and after Color changement...

Thanks and regards
Fabian
![before](https://cloud.githubusercontent.com/assets/15136812/10513271/c0677fa8-7346-11e5-8439-647861f1067c.png)![after](https://cloud.githubusercontent.com/assets/15136812/10513270/c065223a-7346-11e5-89b9-5f5455b41318.png)

**Comment by christopherbauer** [comment]
OK - 2.3.0 was released a while ago (august 2013). Did you update to that version or did you update the most recent version of the main repo?

**Comment by dentalsoftware** [comment]
Hello Christopher,

 

This is the latest release:

 



 

Kind regards

Fabian 

 

 

Von: Christopher Bauer [mailto:notifications@github.com] 
Gesendet: Donnerstag, 15. Oktober 2015 19:32
An: JimBobSquarePants/ImageProcessor
Cc: dentalsoftware
Betreff: Re: [ImageProcessor] ReplaceColor doesn't use the chosen color (#240)

 

OK - 2.3.0 was released a while ago (august 2013). Did you update to that version or did you update the most recent version of the main repo?

**Comment by christopherbauer** [comment]
Sorry Fabian, there doesn't seem to be any content after your ':'. What version were you on and what version did you update to?

**Comment by dentalsoftware** [comment]
I posted a screen shot from the ImageProcessor site (https://www.nuget.org/packages/ImageProcessor/). Here the same in textual form:

 

ImageProcessor               2.3.0      Sunday, September 20 2015

 

In the previous version (2.2.8) replacing a color worked perfect.

 

Kind regards

Fabian

 

Von: Christopher Bauer [mailto:notifications@github.com] 
Gesendet: Freitag, 16. Oktober 2015 14:34
An: JimBobSquarePants/ImageProcessor
Cc: dentalsoftware
Betreff: Re: [ImageProcessor] ReplaceColor doesn't use the chosen color (#240)

 

Sorry Fabian, there doesn't seem to be any content after your ':'. What version were you on and what version did you update to?

**Comment by JimBobSquarePants** [comment]
I'll have a wee look today if i can and figure out what has gone wrong.

**Comment by christopherbauer** [comment]
This bug is confirmed using ImageFactory.

Heyo @JimBobSquarePants take a look at https://github.com/christopherbauer/ImageProcessor/tree/ReplaceColorIssue. Contains a fix but was highly destructive to some logic I found there and I'm not sure why it was set up that way originally.

**Comment by JimBobSquarePants** [comment]
I'd somehow messed up the operators when removing some unneeded code. Will get a fix released asap.

**Comment by JimBobSquarePants** [comment]
Fix added to V2 branch @christopherbauer can you double check it for me please.

**Comment by JimBobSquarePants** [comment]
Fixed in the new release available on Nuget.
