### ISSUE TITLE
Purge single cached crop

### ISSUE THREAD

**Issue by dampee** [JimBobSquarePants/ImageProcessor#241]
Hi
How can i purge a single cached file?  For some reason there was one file where the cache got corrupt.  Instead of removing all cache (gigabytes), it would be helpful to know which file I need to remove from the cache.  Or to be able to tell to imageprocessor to remove the cache of this particular crop.
How and where do I start?
Kind regards

**Comment by JimBobSquarePants** [comment]
I'm afraid not. If I offered a way via the url to purge an individual image that would open me up to DDOS attacks. You could however write something based off the code here to determine the location of the cached file.

https://github.com/JimBobSquarePants/ImageProcessor/blob/49bb8b14dd15ecfac6672b7307af9d71a0e2f769/src/ImageProcessor.Web/Caching/ImageCacheBase.cs#L119

p.s. Gigabytes! Crikey, that must be a lot of cached images!

**Comment by dampee** [comment]
Thanks!  I was thinking about attacks too.  I was afraid that would be the answer.

I'll look into the generated filename.

Lots of images in different crops makes even more gigabytes in the cache folder :-)
