### ISSUE TITLE
Quality setting ignored when format=jpg set

### ISSUE THREAD

**Issue by PhilDye** [JimBobSquarePants/ImageProcessor#242]
I noticed larger-than-expected image payloads when we explicitly set `format=jpg` (which we do to stop clients uploading photographic PNGs).  After some testing, I can deduce that when `format=jpg` is set, the quality setting is ignored and images are generated with the default as `quality=90`

To reproduce;

1. Create a new empty web project
2. Install-Package ImageProcessor.Web  (currently v4.4.0.0)
3. Place a large jpg image in the root (in my case, 3805527 bytes)
4. Requests return as follows 

    /image.jpg?width=1000    136020 bytes
    /image.jpg?width=1000&quality=90    136020 bytes
    /image.jpg?width=1000&quality=10    14690 bytes  (and visibly poorer quality)
    /image.jpg?width=1000&format=jpg    136020 bytes  (ie default quality, 90)
    /image.jpg?width=1000&quality=10&format=jpg    136020 bytes  (INCORRECT, and visibly high quality)

**Comment by PhilDye** [comment]
Ah, as I started reviewing the code (in the hope I might be able to fix it), I see that the order of params is significant... Indeed;

/image.jpg?width=1000&quality=10&format=jpg 136020 bytes   is not the same as 
/image.jpg?width=1000&format=jpg&quality=10  14690 bytes

Now that I RTFM, I see "The API for ImageProcessor.Web is imperative. This means that the order in which you supply the querystring parameters is the order in which the individual processors are implemented."

**Comment by JimBobSquarePants** [comment]
You have me a wee fright there! Glad you figured it out.
