### ISSUE TITLE
GIF used as background image gets resized

### ISSUE THREAD

**Issue by PSinke** [JimBobSquarePants/ImageProcessor#247]
We're using imageprocessor that is now default with the Umbraco CMS. 
We noticed one of the animated GIFs that is used as a background image on a div gets resized by imageprocessor, while we do not want this to happen. It's a fairly large transparent GIF (1917x1580) but when the imageprocessor is enabled in the web.config, the image gets scaled to something smaller. 

Is there any way to prevent image processing on certain files or directories?

**Comment by JimBobSquarePants** [comment]
Could you please supply some more details and perhaps the image.

No scaling should occur unless there are querystring parameters passed. The post processor might be doing something though and I'd like to test it.

In the interim add `?ipignore=true` to the image request. That should tel ImageProcessor.Web to ignore it.

**Comment by PSinke** [comment]
![flag2](https://cloud.githubusercontent.com/assets/2011552/11116672/6b6ab4a8-8934-11e5-83ac-cd5be83f69f5.gif)

Here's the image. 
Meanwhile one of our devs found a solution(and with that the probable cause for this). Placing a pixel in the right-hand bottom corner fixed it, and the GIF is no longer resized. 
The problem here was that the GIF is mostly transparent, with a small animation in it, but around the naimation everything is transparent. For some reason imageprocessor removed the excess transparency on the right and bottom of the image.

**Comment by JimBobSquarePants** [comment]
It's most probably [gifsicle](http://www.lcdf.org/gifsicle/man.html) then that is doing it. I'm using gifsicle to shrink the output images for the web.

There might be a setting that will prevent this. If you have the opportunity before I can to compare the available settings with what I have [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/PostProcessor/PostProcessor.cs#L156) please let me know.

**Comment by PSinke** [comment]
I will have a look at the settings, but shouldn't imageprocessor skip the GIF when no parameters are passed in the first place?

**Comment by JimBobSquarePants** [comment]
It used to but there was an issue with remote files getting returned at a larger size than when they were first downloaded. I couldn't find a way to cleanly identify each potential IImageService source without introducing breaking changes so decided to intercept all requests. I might have another go at cracking it but I'm really concentrating on v3 now. 

Sadly I don't get the contribution I always hoped to get so I can only devote so much time to the project.

**Comment by PSinke** [comment]
I really appreciate the time and effort you're putting into this. Unfortunately I don't have the time to offer much assistance myself.

I did just look at your sourcecode for imageprocessor. I could be worng ofcourse, but wouldn't it be as simple as adding the following code to the ProcessImageAsync method in the ImageProcessingModule.cs file:

    if (request.QueryString == null || request.QueryString.AllKeys.Count() == 0)
	{
	    return;
	}

just below your line that excludes everything that has the ipignore parameter?

**Comment by JimBobSquarePants** [comment]
It'll require a wee bit more than that *I think* as I still want to store remote files locally.... I'll see what I can come up with.
