### ISSUE TITLE
Accept-Ranges support

### ISSUE THREAD

**Issue by perosb** [JimBobSquarePants/ImageProcessor#256]
Current setup is using:
  UmbracoFileSystemProviders.Azure
  CloudImageService
  AzureBlobCache
  StreamCachedImage=true

So not quite sure where this goes but if you have video, .mp4, uploaded.
I assume this doesn't go through ImageProcessor, but still through the above.

The videos are not seekable and doesn't support "Accept-Ranges".

What are your thoughts on this?

The only solution I have found so far is to setup an additional sub domain pointing directly to the Storage container on azure.

**Comment by JimBobSquarePants** [comment]
Imageprocessor won't be doing anything with those items and will jump out as soon as it can identify the stream. It's might be something we have to set up in the FileSystemProvider. 

Could you raise the issue there?

**Comment by perosb** [comment]
https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/20
