### ISSUE TITLE
Implement new Vector methods correctly to take advantage of performance improments

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#259]
The new `System.Numerics.Vectors` contains several new types that take advantage of SIMD processors and are specifically designed graphics programming. I have little-to-no knowledge of those types and will need assistance integration the various methods they offer in order to utilize them properly.

**Comment by voidstar69** [comment]
@JimBobSquarePants is this the sort of change that you are looking for?

Changing Color.Lerp from this:

        public static Color Lerp(Color from, Color to, float amount)
        {
            amount = amount.Clamp(0f, 1f);

            if (Math.Abs(from.A - 1) < Epsilon && Math.Abs(to.A - 1) < Epsilon)
            {
                return from + (to - from) * amount;
            }

            // Premultiplied.
            return from * (1 - amount) + to;
        }

to this:

        public static Color Lerp(Color from, Color to, float amount)
        {
            amount = amount.Clamp(0f, 1f);

            if (Math.Abs(from.A - 1) < Epsilon && Math.Abs(to.A - 1) < Epsilon)
            {
                return Vector4.Lerp(from, to, amount);
            }

            // Premultiplied.
            // TODO: not sure how to use Vector4.Lerp here
            return from * (1 - amount) + to;
        }

*might* improve performance by making use of the Vector4.Lerp method (need to measure performance to be certain).

**Comment by JimBobSquarePants** [comment]
You're absolutely correct. I can use the built in `Vector4.Lerp` in that situation. The `Color` minus operator utilizes the backing vector but we might as well cut out the middle man.

The code, I believe, would be: 

    return Vector4.Lerp(from.backingVector, to.backingVector, amount);

For premultiplied alpha we'd probably have to fall back to the non SIMD approach. 

I'd imagine it would be a very tiny performance improvement but every little most certainly helps.

**Comment by JimBobSquarePants** [comment]
This issue was moved to JimBobSquarePants/ImageSharp#3
