### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#265]
![ImageProcessor Logo](http://imageprocessor.org/assets/ico/imageprocessor.svg)

Look at it... Just look at it! 

I may know my way around a pixel array but I know nothing about design. It's hideous! 

I need a designer to create me something that doesn't make me feel a little bit mouth-vomity when I look at it. Something instantly recognisable that inspires people to get involved. Something that doesn't look anything like this monstrosity.

I feel dizzy now just thinking about it.

**Comment by phillip-haydon** [comment]
If you want to start a project on 99 designers, I'll contribute $25 to the cause. :)

**Comment by ctolkien** [comment]
Looks to be solved?

![image](https://cloud.githubusercontent.com/assets/515955/15280681/8b8d4c12-1b76-11e6-90b3-557f513c75d5.png)

**Comment by phillip-haydon** [comment]
I like it.

**Comment by robertjf** [comment]
major improvement :)

**Comment by ctolkien** [comment]
Uh, just for clarity.. this isn't me :)

Spotted initially here:
https://twitter.com/James_M_South/status/730616556674113537

And is now featured in the readme.

**Comment by JimBobSquarePants** [comment]
Thanks @ctolkien totally forgot I had an open issue on that!

Yup definitely solved. I'm very happy with it. 

If anyone from Instagram is reading I can help you with yours if you like. :stuck_out_tongue_winking_eye:
