### ISSUE TITLE
Bitmap Lockbits and Unlockbits

### ISSUE THREAD

**Issue by SirusDoma** [JimBobSquarePants/ImageProcessor#266]
I just found out this project after few searches on google.
Readme on V3 Branch of this repo really suit on my needs.

I need an Image library for my game that compatible with NETCore (in other words: without System.Drawing.dll)

My game require to load general image formats (at least png and bmp) into OpenGL texture.
following code used to upload image data to OpenGL texture:

```
	// Lock Bits Bitmap Data
	BitmapData bmpdata = bmp.LockBits(
		new Rectangle(0, 0, bmp.Width, bmp.Height),
		ImageLockMode.ReadOnly,
		System.Drawing.Imaging.PixelFormat.Format32bppArgb);

        // Upload Texture Image
        GL.TexImage2D(TextureTarget.Texture2D, 0,
				PixelInternalFormat.Rgba,
				bmp.Width, bmp.Height, 0,
				OpenGL.PixelFormat.Bgra,
				PixelType.UnsignedByte,
				bmpdata.Scan0);

	// Pixels copied, Unlock it
	bmp.UnlockBits(bmpdata);
```
So my questions
1. Is this library implemented `LockBits/UnlockBits` like the code shown above?
2. Can library handling decode process from PNG to Bitmap? When I load a png image (using `new Bitmap(Image.FromFile("....");`) and uses code above to upload the image data to OpenGL texture, the transparency is still there, is ImageProcessor have same behavior?

Thanks in advance!

**Comment by JimBobSquarePants** [comment]
Hi Sirus,

No this version does not use `LockBits/UnlockBits`.

ImageProcessor images once loaded are format independent, storing a float array of pixels in the order rgba. Transparency is only lost when re-encoding the image.  You should be able to pass it around easily enough.

Here's an example of what you would like to do coded by @mellinoe at Microsoft.

https://github.com/mellinoe/BoxGame/blob/4b5ac397655aa16979fb2087c7fc5562e9ea08c4/src/EngineCore/Graphics/OpenGL/TextureBuffer.cs#L39

**Comment by SirusDoma** [comment]
Thanks for clarification!
I don't know there is `Pixels` property there!

Keep up your good work!

**Comment by JimBobSquarePants** [comment]
No worries. Will try my best! :smile:

**Comment by SirusDoma** [comment]
I'm sorry for reopening the issue, but it seems i cant compile the project
I'm using DNX 5.0 and got an error (the error seems occur when restoring dnx package)

`Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.DNX.PackageManager'`

I'm not really familiar with CoreCLR actually but any ideas?

**Comment by JimBobSquarePants** [comment]
Looking at this similar issue  and solution on StackOverflow you are probably not using the latest tooling. 

https://github.com/aspnet/dnx/issues/2426

http://stackoverflow.com/a/32357737

In answer to your next question you would have to do extra work to support old frameworks. System.Numerics.Vectors for example require DotNet5 to run.

https://www.nuget.org/packages/System.Numerics.Vectors

Personally I'm finding the support matrix increasingly difficult to understand. There's a lot of discussion here but I wasn't much wiser after reading it all. https://github.com/dotnet/corefx/issues/973

**Comment by SirusDoma** [comment]
Thanks for your help!
I able to compile it now

hmm I see, easiest way to do this is clone the corefx and took their System.Numerics sources.
Or just use .NET Core haha

Thanks again!
