### ISSUE TITLE
Upgrading using Nugets keeps changing/reseting config files.

### ISSUE THREAD

**Issue by perosb** [JimBobSquarePants/ImageProcessor#269]
When upgrading, the packages is reconfiguring everything in cache and security config files.

Changing config files should be done more carefully.

**Comment by JimBobSquarePants** [comment]
Nothing I can do about that. It's managed by standard use of Nuget transforms.

**Comment by Jeavon** [comment]
If you switched to xsd transforms you can ship only .install.xsd which stops this behaviour but it means package uninstall leaves behind what has been changed. I think NuGet is flawed in this regard, a package upgrade is really a uninstall/install where it should only be a install or even introduce .upgrade.xsd

**Comment by JimBobSquarePants** [comment]
Yeah Nuget is a bit of a mess with this regard and with them stripping out powershell it won't get any easier. I won't be making any changes as it's not an issue I can easily control nor get great to do so.
