### ISSUE TITLE
Allow kernel caching on unmodified images

### ISSUE THREAD

**Issue by voordes** [JimBobSquarePants/ImageProcessor#270]
Kernel caching is extremely powerful for frequently requested resources like css, js and supporting images. However, whenever a request is rewritten during the pipeline it is ignored by the kernel cache, Since the imageprocessor acts uppon all images, including already-optimized supporting images a rewrite is not needed. The original images would be just fine

Is there a way to exclude images from being processed by the imageProcessor? Either by a querystring or by adding exluded paths to the configuration?

**Comment by JimBobSquarePants** [comment]
ImageProcessor.Web will only act upon images without a querystring when you have RAMMFAR enabled, which means, of, course that all modules will be intercepting all requests. This would be much more of a performance concern than not having kernel caching enabled for certain images though for the overwhelming majority of applications this overhead is dwarfed by the actual application logic.

If any of the scenarios described in this [document](https://support.microsoft.com/en-us/kb/817445) are present then kernel caching will not occur also. 

Any image processed by ImageProcessor.Web are cached in-browser, in-memory, and on the server be it via the disk cache (which internally uses the native static file handler which as I understand should be utilizing kernel caching) or another cache mechanism. 

ImageProcessor.Web will not be a bottleneck for scalability, I've recently had a discussion with a developer about a site they have running with over 746k images and 2.5 million cached files. He was amazed by the performance.

In answer to your question though. Yeah, you can tell ImageProcessor.Web to ignore a file by adding `?ipignore=true` to the request url.

**Comment by voordes** [comment]
Hi James,
Thanks for the elaborate answer. We mostly use Umbraco which still has
RAMMFAR enabled by default. However, testing showed that a simple image
request without query string was actually put in the kernel cache
regardless RAMMFAR. Only when I enabled ImageProcessor it did not. My
belief is that this is caused by the rewrite.

Nonetheless I agree that it is not essential to the speed of IP and with
svg as statics we are just fine. Still, i am curious why images without
querystring are being processed, unless its the default quality compression
that kicks in. Setting the ipignore on all css images is not my prefered
approach.

Kind regards,
Sandor

Op di 8 dec. 2015 00:43 schreef James Jackson-South
notifications@github.com>:

**Comment by JimBobSquarePants** [comment]
Hi Sandor,

No worries, The inclusion was as a result of two issues: #145 #208 

People are using ImageProcessor to request and cache remote files without querystring instructions (A shout out identified quite a few people doing it) and I was getting questions on various forums.

Ensuring that remote images were at least optimized was an issue. I could identify that the image was remote using the IImageService properties but I couldn't be confident that the image was optimized. 
As such, I included blanket processing to ensure that the output was always both minimal and cached in the browser. (You'd be surprised how many people don't cache static files).

It's never really sat comfortably with me but I thought, as long as someone doesn't have RAMMFAR (I don't know why Umbraco needs it) enabled then it wouldn't be an issue plus you always end up with an optimized file.

I'd love to think of something better for when I write the Web version for Vnext and I'd welcome any input you have. 

Cheers 

James

P.S I'd love to know how you tested the kernel caching. That would be a cool tool to have when testing.

**Comment by HughJeffner** [comment]
Just to confirm, images without a querystring are supposed to be cached to disk by ImageProcessor?  I don't really have any concerns with it but I was surprised to see the cache populated with such images.

Here is my setup:

* IIS8
* RAMMFAR not enabled
* All image requests are being to passed to any modules without `preCondition="managedHandler"`

**Comment by JimBobSquarePants** [comment]
It was there so that all images were optimized. (Most developers dont optimize properly). I've made the functionality optional for the next release defaulting to false.

**Comment by HughJeffner** [comment]
Sounds good, thanks!
