### ISSUE TITLE
Resizing image

### ISSUE THREAD

**Issue by SirusDoma** [JimBobSquarePants/ImageProcessor#271]
Hello

I use V3 branch and I don't have any idea to resize the image
How can I do this?

**Comment by JimBobSquarePants** [comment]
There's a `Resize` method in the `ImageProcessor.Samplers` namespace. (I may yet flatten that down to `ImageProcessor`). It has a few overloads.

Here's an example in the test solution.

https://github.com/JimBobSquarePants/ImageProcessor/blob/V3/tests/ImageProcessor.Tests/Processors/Samplers/SamplerTests.cs#L59
