### ISSUE TITLE
Azure Blob Cache Doesn't Respect Content Type

### ISSUE THREAD

**Issue by iansullivan88** [JimBobSquarePants/ImageProcessor#276]
Hello
I know this is a plugin so this may not be the correct place to raise this issue but here goes:

I'm serving images using Azure Blob Cache and StreamCachedImage=true. The problem is that the cached images are either being served with no content type or a content type of text/html. The source images are served with the correct content type.

I'm working around this just now by manually rewriting responses that go through remote.axd - is there a less hacky way to fix it?

Cheers
Ian

**Comment by JimBobSquarePants** [comment]
Hi there,

I'm not sure why this would happen. I'm definitely instructing the HttpModule to set the correct headers.

https://github.com/JimBobSquarePants/ImageProcessor/blob/ab01a422b2c8463ee7bbaa57fe158fe5bb89f321/src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L384

https://github.com/JimBobSquarePants/ImageProcessor/blob/ab01a422b2c8463ee7bbaa57fe158fe5bb89f321/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L156

**Comment by iansullivan88** [comment]
Ah, that's where the source is. On [this line](https://github.com/JimBobSquarePants/ImageProcessor/blob/ab01a422b2c8463ee7bbaa57fe158fe5bb89f321/src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L384) `this.mimeType == null`.

This field is only set when uploading an image so is `null` for subsequent requests. I used `response.ContentType` instead and removed the `mimeType` field and that seemed to fix the issue.

Does that sound reasonable?
Cheers

**Comment by JimBobSquarePants** [comment]
Oh good spot! :+1: 

So just to clarify. Instead of passing `this.mimetype` to the `ImageProcessingModule.SetHeaders` you are passing `response.ContentType` each time?

I think if we check whether it is null and pass `response.ContentType` if it turns out to be so we will cover both new and subsequent requests. 

Would you be able to submit a pull request?

**Comment by iansullivan88** [comment]
My thought was to just get rid of the mimeType field and always use the
content type returned from the Azure response - it should always be correct
as you are setting the correct content type when you add the cached image
to Azure.

I may have to be a jerk and not submit a pull request - sorry! I'm using
the plugin on a client's machine and I don't know what their rules are for
open source. I'm lacking free time in the evenings too. Sorry!

Thanks for the library, it's great.
Ian

**Comment by JimBobSquarePants** [comment]
No worries.... I'll have a look at  adding it when I can then. Cheers!

**Comment by JimBobSquarePants** [comment]
Fixed
