### ISSUE TITLE
Please provide watermark position

### ISSUE THREAD

**Issue by Radzhab** [JimBobSquarePants/ImageProcessor#278]
top, bottom,center,left,right

**Comment by JimBobSquarePants** [comment]
Hi there,

I'm not currently adding new features to the V2 platform as I am now working on a cross-platform version of ImageProcessor for corefx. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/1bae9d492217e4e619e411a4cec66ea0304d4b23/README.md

If you wish to add the functionality please submit a pull request and I will review it.

Cheers

James

**Comment by bartvanderwal** [comment]
:+1: +1
