### ISSUE TITLE
Deployment on Shared Hosting

### ISSUE THREAD

**Issue by avrandrei** [JimBobSquarePants/ImageProcessor#279]
Hello, 

I have a question about deploying applications that use ImageProcessor.Web in a shared hosting environment. 
It seems that ImageProcessor tries to start cmd.exe which is not allowed in most of shared hosting environments. Since the access is denied, ImageProcessor crashes and no image is returned.

Is there something that can be done to have ImageProcessor work properly in a shared hosting environment?

Many thanks

**Comment by JimBobSquarePants** [comment]
Hi there,

This issue has already been raised here #268 

Turn off post processing using the [configuration](http://imageprocessor.org/imageprocessor-web/configuration/#processingconfig)

You can install the configuration Nuget package [here](https://www.nuget.org/packages/ImageProcessor.Web.Config/)

Cheers!

**Comment by avrandrei** [comment]
Many thanks for the quick reply. Much appreciated! This is a very cool project. Keep up the good work!

**Comment by JimBobSquarePants** [comment]
No problem, happy to help! :smile:
