### ISSUE TITLE
Specify pixel in certain coordinate

### ISSUE THREAD

**Issue by SirusDoma** [JimBobSquarePants/ImageProcessor#280]
Hi
I don't see an option to set specify a pixel in a certain coordinate under V3

I think it will be useful

**Comment by JimBobSquarePants** [comment]
Hi there,

I'm not sure I follow what you mean? Do you mean the ability to get or set the color at a given pixel coordinate?

The `Image` class has an indexer inherited from the class `ImageBase`. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/1bae9d492217e4e619e411a4cec66ea0304d4b23/src/ImageProcessor/ImageBase.cs#L121

You can get or set the pixel color in the following manner.

``` csharp
Color color = sourceImage[x, y];

targetImage[x, y] = color;
```

There's plenty of examples of that in the source.

https://github.com/JimBobSquarePants/ImageProcessor/blob/1bae9d492217e4e619e411a4cec66ea0304d4b23/src/ImageProcessor/Filters/Alpha.cs#L52

Adding an extra set of methods to do this like the old `GetPixel(x, y)` `SetPixel(x, y)` from System.Drawing would only slow things down and we want these methods to be as fast as possible.

I hope that clears thing up.

**Comment by SirusDoma** [comment]
Thanks for clarify!
That's what i meant
