### ISSUE TITLE
Pixel Format is changed after re-saved

### ISSUE THREAD

**Issue by SirusDoma** [JimBobSquarePants/ImageProcessor#282]
I'm creating an opengl game based on this library to avoid System.Drawing dependency.
So, I try to load the Texture with RGBA pixel format and it's works!

However, my game has ability to save (serialize) the sprite instance, it save Vertices and Texture.
Everything works fine except the pixel format, it change to BGRA instead RGBA

Here the codes that I use to load the serialized data:
```
// Read some data here
Image image = new Image(new MemoryStream(imageData));
```

and here the codes that I use to serialize the data
```
// Save some data here
image.Save(imageStream, image.CurrentImageFormat);
byte[] serializedImage = imageStream.ToArray();
```

So when I load the Image directly from file, it's still RGBA
But when I load the image file, serialize it and reload with the serialized data, it turns to BGRA

any ideas?

**Comment by JimBobSquarePants** [comment]
Interesting... Could you provide what format `image.CurrentImageFormat` is?

**Comment by JimBobSquarePants** [comment]
Cant seem to replicate this. Please reopen if it still occurs with the latest builds.
