### ISSUE TITLE
Gifs Are Losing Transparent Background

### ISSUE THREAD

**Issue by iansullivan88** [JimBobSquarePants/ImageProcessor#283]
Hello

When urls have a query string, GIFs lose their transparent backgrounds. For example, the second url returns an image with a dark background.

    /remote.axd/info.eps.surrey.ac.uk/logos/transbugs.gif
    /remote.axd/info.eps.surrey.ac.uk/logos/transbugs.gif?randomstring

The query strings I'm using are meaningless but important as I use them for cache busting.

I'm using ImageProcessor.Web 4.4.1.0. Do you know if there is a way to fix this?

Thanks again
Ian

**Comment by JimBobSquarePants** [comment]
I think It's gifsicle doing something wrong. Could you  turn off post processing via the config and let me know what happens?

**Comment by iansullivan88** [comment]
I'm on holiday at the moment, I'll get round to it soon.
Cheers
Ian

**Comment by iansullivan88** [comment]
I had a look at the source, it seems I can use 'IPIGNORE=TRUE' for gifs which will fix my particular use case but I had a quick look at the issue anyway:

If there's no query string, image processor does nothing because of [this line](https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L488). That makes sense.

When I do have a query string, the GIF retains its transparent background until [this line](https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor/Imaging/FastBitmap.cs#L676). That gets called somewhere inside `FormatUtilities.GetColorCount(this.Image)`. It goes beyond my knowledge to do anything about that I'm afraid!

**Comment by JimBobSquarePants** [comment]
Ah! Good digging. I'll have a look at that then.

**Comment by JimBobSquarePants** [comment]
Fixed it. System.Drawing is weird!

**Comment by iansullivan88** [comment]
Nice one, thanks!
