### ISSUE TITLE
ImageProcessor.Web prevents List<string> and List<int> bindings after request to resize image

### ISSUE THREAD

**Issue by coultonluke** [JimBobSquarePants/ImageProcessor#284]
I wanted to start by saying that I love Image Processor, you've done such a great job - it's fantastic!

I noticed this issue when my website was failing to bind `List<string>` values in ASP.NET MVC for some reason, after some digging I realised that it was happening after making a call to resize an image through the query string.

I previously posted a question [on StackOverflow](http://stackoverflow.com/questions/34464671/imageprocessor-request-makes-future-list-bindings-fail).  It contains an application that I created to demonstrate the issue, this is located in an S3 bucket [here](https://s3.amazonaws.com/bindingissue/BindingIssue.zip).

As far as my testing goes, it affects `List<string>` and `List<int>` but I guess it could affect other (or all) value types.  `List<object>` properties appear to bind correctly still.

As mentioned on the StackOverflow question, it seems that one way to get around it is to bind to the interface `IList<string>` and `IList<int>`.

If there is any way that I can be of assistance then I'd be more than happy to help.

**Comment by JimBobSquarePants** [comment]
Thanks for raising this. My initial suspicion is that it is something to do with the custom TypeConverters, I'll have a look at your project and see what I can come up with.

**Comment by JimBobSquarePants** [comment]
Oops, linked wrong issue. Still working on this one. Sorry!

**Comment by JimBobSquarePants** [comment]
It's definitely the type converter causing the issue. Unfortunately it looks like the only way I can fix it is by replacing the current system with something more customised as there's not enough info passed to the converter to set up logic to ensure my methods don't interfere.

**Comment by coultonluke** [comment]
Thanks for taking a look.  I guess my only question is, is the `IList<>` a suitable workaround and is it just `List<>` that is likely to be affected?

**Comment by Shazwazza** [comment]
Can you point me to where you are setting these type converters? I assume the problem is that Image Processor is setting a Global property - which affects the default model binders.

**Comment by Shazwazza** [comment]
Think this is the one: https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Helpers/QuerystringParser/GenericListTypeConverter.cs

The main issue being that any time you replace anything on a global level from a library, there is a high degree of potential to affect a site that uses this library. I would assume that the logic in this global type converter could just be moved to an extension method (or helper method) for wherever it is you are using this logic to convert Lists. If it is used for model binding query strings, then it should be relatively easy to write a custom ModelBinder for where you require it which doesn't need to register anything at a global level.

I'd be more than happy to help if you can let me know where this converter logic is required/being used.

**Comment by JimBobSquarePants** [comment]
Thanks @Shazwazza yeah, I was planning on replacing the TypeConverter with something less invasive. 

All the TypeConverters in that folder are used only by the [QueryParamParser](https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Helpers/QuerystringParser/QueryParamParser.cs) class so if you have the chance to have a look at it today that would be amazing. If not, I shall have a go tomorrow. This is the last blocking issue for a new release.

**Comment by nul800sebastiaan** [comment]
Shan asked me to tell you: he didn't have time today but if you can't get to it by tomorrow morning our time he'll give it another go!

**Comment by JimBobSquarePants** [comment]
Cheers @nul800sebastiaan Looks like I've got it sorted. Replace type converters with my own system. All unit tests are passing.

**Comment by JimBobSquarePants** [comment]
Fixed

**Comment by coultonluke** [comment]
I'm really excited for the fix to be released, thanks James for addressing this!

**Comment by Shazwazza** [comment]
:+1: Nice one !:)

**Comment by JimBobSquarePants** [comment]
Cheers! :beers:

**Comment by nul800sebastiaan** [comment]
Whoop!

**Comment by JimBobSquarePants** [comment]
Oh @coultonluke it's released. I did it when I commented. https://www.nuget.org/packages/ImageProcessor.Web/

**Comment by coultonluke** [comment]
I've just tested it and it seems to be working great now, no more binding issues.  Thanks again.
