### ISSUE TITLE
Filters not using SIMD instructions

### ISSUE THREAD

**Issue by yufeih** [JimBobSquarePants/ImageProcessor#286]
`Color` is now backed by `Vector4`, but the filters are not using SIMD operations exposed by Vector4, it still operates on the floating point *R*, *G*, *B*, *A* components, so the benefit of using Vector4 is completely gone.

**Comment by JimBobSquarePants** [comment]
Some things are, some things aren't. I need help with the SIMD stuff as it's all brand new to me and there is no adequate documentation out there. If you could help out in that department I would be most grateful.

**Comment by JimBobSquarePants** [comment]
ColorMatrix operations now use SIMD methods.
