### ISSUE TITLE
Black and white still have grey pixel

### ISSUE THREAD

**Issue by cdie** [JimBobSquarePants/ImageProcessor#289]
It seems that black & white filter still produces some grey pixel (zoom in to find them). In some cases, we really need just black or white.
I know a method, but it uses BitmapData to process pixel by pixel.
I didn't found any method using matrix to do it...

**Comment by JimBobSquarePants** [comment]
Yeah.... It's not exact but quick. You could probably do it using the binary threshold filter but that would leave it fairly ugly. Really an implementation of Otsu thresholding would be best.

https://en.wikipedia.org/wiki/Otsu%27s_method

**Comment by JimBobSquarePants** [comment]
Closing for now as thresholding is out of scope for this release.
