### ISSUE TITLE
Dependency Issues and Possible Resolutions

### ISSUE THREAD

**Issue by PromontoryProtean** [JimBobSquarePants/ImageProcessor#295]
I started doing some testing this morning and brought ImageProcessor into my project using MyGet. I immediately ran into dependency errors. I was able to resolve the dependency errors and get the project to build in not only .net core, but also 4.6.1. Changes I made were in 2 files and the new versions are as follows.

global.json
```
{
    "projects": [ "src" ],
    "sdk": {
      "version": "1.0.0-rc1-update1"
    }
}
```
project.json
```
{
  "version": "3.0.0-*",
  "description": "ImageProcessor",
  "authors": [
    "James Jackson-South and contributors"
  ],
  "tags": [
    "Image Resize Crop Quality Gif Jpg Jpeg Bitmap Png Fluent Animated"
  ],
  "projectUrl": "",
  "licenseUrl": "",
  "dependencies": {
    "Microsoft.CSharp": "4.0.1-beta-23516",
    "System.Collections": "4.0.11-beta-23516",
    "System.IO": "4.0.11-beta-23516",
    "System.Linq": "4.0.1-beta-23516",
    "System.Numerics.Vectors": "4.1.1-beta-23516",
    "System.Reflection": "4.1.0-beta-23516",
    "System.Runtime": "4.0.21-beta-23516",
    "System.Runtime.Extensions": "4.0.11-beta-23516",
    "System.Threading": "4.0.11-beta-23516",
    "System.Threading.Tasks.Parallel": "4.0.1-beta-23516"
  },
  "frameworks": {
    "dnx461": {
      "dependencies": {
      }
    },
    "dnxcore50": {
      "dependencies": {
      }
    }
  }
}
```

Not sure if you had left support for .net framework 4.5.x out for any specific reason, but if you had tried to add it and couldn't get it to compile for any specific reason, it appears that the reason is 4.5.x does not work with System.Numerics.Vectors. 4.6.x does however, for reasons that are above my head at the time being. Check this out:
https://github.com/MikePopoloski/SharpBgfx/issues/2

Anyway, I think it makes sense to have support for the full .net framework in V3. Would definitely open V3 up to a wider audience and help get more feedback. Cool stuff.

I didn't do this as a pull request because I want to get your feedback first. Also I haven't check the tests project yet, but hopefully that will work the same way. Thoughts?

**Comment by JimBobSquarePants** [comment]
Hi there,

Net 4.5 is a definite no-go. The new vector types are integral to providing decent performance plus ASP is using .NET 4.6 for RC2 onwards.

Quick question? Isn't `1.0.0-rc1-update1` an older version than my currently installed 1.0.0-rc1-final?

**Comment by PromontoryProtean** [comment]
I'm pretty sure rc1-update1 is newer than rc1-final. There were installer bugs that Microsoft fixed shortly after releasing rc1-final. Microsoft naming conventions at their finest. Anyway, this kind of explains it: http://blogs.msdn.com/b/webdev/archive/2015/11/18/announcing-asp-net-5-release-candidate-1.aspx.

I'm definitely on board for only supporting 4.6 and up, especially given that this is a complete rewrite. There is a danger of going down a long, convoluted road here though. If you do support full framework, do you support full framework on just dnx, or do you also support System.Web type projects? I'm thinking only dnx for a variety of reasons, but in theory we could bring support for V3 to Web Forms. It's mainly a question of if somebody wants to spend the time to do the work. This should probably be way down at the bottom of the wish list, but I can't think of a reason that it wouldn't be possible. My philosophy right now is that if it currently compiles on 4.6, let it compile...it won't hurt. Maybe stick with it until it creates a road block, because it will be more complicated to bring it back later. But I'm not personally opposed to only supporting .net core, since the ultimate goal is to create a solid cross-platform solution that supporting full framework might contradict. I don't want to step on your toes here, so if you have something else in mind definitely let me know.

**Comment by JimBobSquarePants** [comment]
Ok coke, so I've been doing some more reading...

As you said, [update-1](https://www.nuget.org/packages/dnx-clr-win-x64/) is newer so I've upgraded to that. I'm still sitting with the x64 architecture version for now since that allows me to benefit from the SIMD instructions used by the new vector types. I've also altered the json file to use `dotnet5.5` instead of `dnxcore50` as indicated at https://github.com/aspnet/Announcements/issues/98.

As far as the library goes. Like you said the the ultimate goal is to create a solid cross-platform solution. By limiting myself to corefx I am able to do that. Anything that is built utilizing the library would then reference the extra required packages like MVC are doing [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc/project.json). There should be no extra complexity in working this way, as far as I understand it this is the recommended methodology.

**Comment by Jeavon** [comment]
FYI, rc1-update1 is a minor bug fix release of rc1-final, I think only impacting the installer so nothing new really

**Comment by JimBobSquarePants** [comment]
Cheers @Jeavon!

**Comment by PromontoryProtean** [comment]
Jim, I think I follow. I'll update my project to be .net core only and go from there.

Question on the MyGet feed - how often is that built? Is it done automatically somehow? I'll try to pull in whatever is available later today and see if I run into the same dependency errors. I have a feeling it will still throw up errors though. There was a weird issue with referencing one of the following that caused the dependency errors:
"Microsoft.NETCore.Portable.Compatibility": "1.0.1-beta-23516"
"Microsoft.NETCore": "5.0.1-beta-23516"
"Microsoft.NETCore.Platforms": "1.0.1-beta-23516"

I was able to get around the error by changing the dependencies around as I listed in my post above. I think one of the 3 libraries above still references an older beta library that caused things to break. But I'll test more later today or tomorrow and confirm.

Also, just a heads up to anybody reading this. I hit a major roadblock yesterday because I had set "dnx461" in my project.json. Turns out 4.6.1 does not work yet. I had to change it to "dnx46". When I had it set to 461 the project refused to launch in IIS Express. I thought it had something to do with the ImageProcessor build I was working with so I spun my wheels for a couple of hours. Instead of erroring out the app just spins up and does nothing forever. Never errors out, never loads a page.

Good news is that after I figured that out I was able to get some basic resizing to work in my dnx app using my build of ImageProcessor V3. I'm fooling around with possible approaches for building the middleware. I don't have anything fit for consumption yet, but I did get it to function in an MVC6 website on a very basic level. Progress!

**Comment by PromontoryProtean** [comment]
Ok, I went with dnxcore50 in my file manager project and removed 4.6 support. I brought ImageProcessor in via the MyGet feed and it works, though I do get the following warning:
`NU1007 Dependency specified was ImageProcessor >= 3.0.0-alpha-596 but ended up with ImageProcessor 1.0.0.`

I'm not really sure what that means, but I am not getting any build errors, so maybe it has something to do with how the MyGet package is built.

I'm going to do some more experimenting with my basic middleware setup, but I guess the dependency issues are resolved for now.

**Comment by JimBobSquarePants** [comment]
That's odd. I'll double check the build process, the version number mustn't be getting set. @Jeavon any ideas? You're the wizard when it comes to this stuff.

**Comment by Jeavon** [comment]
Very odd that it says 1.0.0! I have had a thought that we probably need the AppVeyor build process to update the values in AssemblyInfo.cs as well as project.json so I'll take a look at getting that sorted. But that wouldn't explain where v1.0.0 is coming from as it would still be v3.0.0.0....

**Comment by JimBobSquarePants** [comment]
Thanks @Jeavon appreciate it!

**Comment by Jeavon** [comment]
I have absolutely no idea why but it seems that MSBuild is creating an additional folder depth in the NuGet package (maybe it doesn't understand dotnet5.5 yet) so we were getting lib -> dotnet5.5 -> dotnet5.5 -> dlls So I have switched to using dnu for both build and pack instead of MSBuild and now it's creating folders correctly. I have also added AppVyor AssemblyInfo patching.
See #299 for the change

**Comment by JimBobSquarePants** [comment]
Cripes! How did you work that out? It didn't occur to me to use dnu to build, makes sense though. Still working my way through the docs.

**Comment by Jeavon** [comment]
A journey of discovery and at times despair but at least I found a way out. Just experimentation on the command line really until the right thing happened.

**Comment by Jeavon** [comment]
Interestingly, the series of commands in the before_build, build_script & test_script sections of appveyor.yml are now largely universal. You can run the same commands on OSX for example.

**Comment by Jeavon** [comment]
p.s. At least there are some docs now, remember when we began this, there was more or less nowt!

**Comment by PromontoryProtean** [comment]
Thanks for checking into this. I just took a look in Visual Studio, but I am still seeing build 596 from yesterday. I'll try again later tonight and see if the MyGet feed updated itself. I'm not really sure how the integration with MyGet works, so I'll need to educate myself a bit more. Will report back when I have some updated info.

**Comment by Jeavon** [comment]
@PromontoryProtean I don't think James has merged in the change yet so their won't be a new build until he has

**Comment by PromontoryProtean** [comment]
@Jeavon ok, makes sense, don't know why I didn't think of that. I'll keep an eye out for commits and go from there.

**Comment by PromontoryProtean** [comment]
I'm happy to report that I was able to install a newer build via the MyGet feed today, and all the dependency errors are gone. Thanks for clearing this up.

**Comment by Jeavon** [comment]
:relieved: :triumph::boom:

**Comment by christopherbauer** [comment]
:+1: Haven't been commenting here but been watching, great job guys!

**Comment by JimBobSquarePants** [comment]
:100: Loving the little community we have got going here. I'll close this off now.
