### ISSUE TITLE
Using ImageProcessor with images stored in SQL

### ISSUE THREAD

**Issue by tombille** [JimBobSquarePants/ImageProcessor#296]
Hi

Can I use this plugin to scale images served from a SQL database? I have an .aspx page which gets the bytearray from the SQL and serves it like this:

Response.Clear()
Response.ContentType = i.ContentType
Response.BinaryWrite(i.Image)
Response.[End]()

Then I try to process the image by setting the src to /ShowImage.aspx?id=202&filter=blackwhite. The filter is not applied. 

When I process another image, which is located on the server and is directly referenced, it works.

How can I get the database-images to work?

**Comment by JimBobSquarePants** [comment]
Hi there,

You won't be able to do it like that. You'll need to implement your own `IImageService`. 

http://imageprocessor.org/imageprocessor-web/extending/#iimageservice

I strongly recommend against implementing pages in the manner you have for any images. Only the HttpModule will capture the request at the correct part of the page life-cycle.
