### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#297]
I would like to create documentation like the following: 

http://dotnet.github.io/

MS are using the library below but I can't seem to follow the instructions.

http://dotnet.github.io/docfx/

**Comment by robertjf** [comment]
@JimBobSquarePants I have a little spare time at the moment and can take a look at it - have had a look through the walkthroughs etc.

Have you started a project for this in Visual Studio yet?  If so do you want to check it in and I'll start with that, or do you want me to start from scratch?  And is your preference to use Visual Studio IDE or configure it under **dnx** instead?

**Comment by JimBobSquarePants** [comment]
Awesome! Thanks mate :+1: 

I haven't started a project yet, I planned to set a docs folder and stick a web project in there to do it all so I could preview.

**Comment by priyanshu92** [comment]
@JimBobSquarePants  I looked at it and created a sample documentation following their tutorials and I was able to create it but it doesn't seem to work on .NET Core projects with project extension as **.xproj. I think currently it only supports .csproj files.

Let me know if I can help.

**Comment by JimBobSquarePants** [comment]
@priyanshu92 Thanks for giving it a go, I had issues myself when I tried. Maybe I should look elsewhere for something to use. 

Ideally I want something people can make pull requests against. I just wish Jekyll wasn't such a chore on Windows machines.

**Comment by JimBobSquarePants** [comment]
This issue was moved to JimBobSquarePants/ImageSharp#6
