### ISSUE TITLE
Lossless WebP support

### ISSUE THREAD

**Issue by optlink** [JimBobSquarePants/ImageProcessor#300]
Is it possible to add lossless WebP support to the WebP plugin in V2? For my application, the VP8 codec seems to be incompatible with nearly everything out there. I have been poking around in the V2 code and libwebp documentation, and it seems to me that it only requires the import of a few more C methods and some way of determining when to use lossless encoding, perhaps when quality = 100?

**Comment by JimBobSquarePants** [comment]
I had a lot of trouble working out the bindings when adding support for WebP when I did it. (I don't read C) If you want to have a crack at adding lossless support then please give it a try. I'd add a Boolean to the encoder/decoder that is automatically triggered at 100 quality.

**Comment by JimBobSquarePants** [comment]
I've just released the update supporting your changes. V1.0.4 Thanks again for your help :+1:
