### ISSUE TITLE
ImageProcessor.Web.AzureBlobCache.1.0.6 sets incorrect Content Type

### ISSUE THREAD

**Issue by perosb** [JimBobSquarePants/ImageProcessor#303]
In the latest 4.5.0 version it looks like Content-Type is default set to "text/html".

This seem to be for the second request when coming from cache. (in my case Azure Blob cache)

The first request set proper image/* header.

Prior to 4.5.0, the second request doesn't set any header at all, hence it still seem to work.

**Comment by perosb** [comment]
This commit looks suspecious: https://github.com/JimBobSquarePants/ImageProcessor/commit/2f6e9f8c04c0f843b2e00f748e66f6d8550d0b24

**Comment by perosb** [comment]
https://github.com/JimBobSquarePants/ImageProcessor/issues/276

**Comment by JimBobSquarePants** [comment]
Hmmm... `this.mimetype` is not null then that means the content type of the blob should have been set. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/2f6e9f8c04c0f843b2e00f748e66f6d8550d0b24/src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L223

If it is this causing the problem then it's not ImageProcessor.Web but the AzureBlobCache setting the wrong type.

**Comment by perosb** [comment]
It might be better to default to an unknown content type, image/xyz and have the browser decide.
Right not, text/html is not correct.

**Comment by perosb** [comment]
From what I can see, the Content-Type header is set correctly on the Blob.
Also looks ok, when setting the metadata.

**Comment by perosb** [comment]
@JimBobSquarePants think I fixed it.
issue was that using this.mimetype which is only set when adding to cache instead of using the GET requests headers.

**Comment by perosb** [comment]
Also properly fixes https://github.com/JimBobSquarePants/ImageProcessor/issues/276 I believe

**Comment by perosb** [comment]
Let me know if there is anything more i can do here.
I believe the PR https://github.com/JimBobSquarePants/ImageProcessor/pull/304 fixes the issue currently breaking all AzureBlobCache images.

**Comment by JimBobSquarePants** [comment]
Sorry, I'll get this merged in. I'm juggling a few too many things just now.

**Comment by perosb** [comment]
No worries @JimBobSquarePants 
Just saw 4.5.1 and thought there still were issues with the PR.

Thanks!

**Comment by JimBobSquarePants** [comment]
The PR is actually against the Azure plugin not ImageProcessor.Web

**Comment by perosb** [comment]
Sorry to bug you about this one @JimBobSquarePants, when do you think the Azure plugin will be released?

**Comment by JimBobSquarePants** [comment]
There you go :smile: 

https://www.nuget.org/packages/ImageProcessor.Web.Plugins.AzureBlobCache/1.0.7
