### ISSUE TITLE
Version 4.5.0 breaks percentage cropping

### ISSUE THREAD

**Issue by arknu** [JimBobSquarePants/ImageProcessor#305]
When using a predefined crop in Umbraco, it generates a URL like this: http://localhost:1823/media/1019/loebere-paa-strand.jpg?crop=0.020427188497102129,0,0.72831839298854173,0.6610013498588786&cropmode=percentage&width=246&height=221&rnd=130975950450000000

This works fine with ImageCropper.Web 4.4, but breaks with 4.5. It throws an ArgumentException in the Crop processor. And debugging, it is quite understandable why: 

0.020427188497102129 in the URL somehow becomes 2.04271887E+16. The bug seems to lie in the class GenericConvertableConverter, on this line: 

    return (T)Convert.ChangeType(value, t);

In short, it seems there has been some change regarding the parsing of float values, as that is where the issue comes from. In particular, commit 189908982cd1ddcec7bccd76d99d0266403779ca seems to be the problematic one.

**Steps to reproduce (using Umbraco)**

1. Update your Umbraco site to ImageProcessor.Web 4.5
2. Set your Umbraco site language to da-DK (or any culture that uses comma as decimal separator) in Settings, Languages (just changed default en-US to da-DK).
3. Add a preset crop to Image Cropper datatype
4. Upload an image. 
5. Go to the image and customize the crop by clicking it and dragging it around and zooming in.
6. Then try to render the named crop using GetCropUrl. You will get an HTTP 500 error instead of the image.

**Comment by arknu** [comment]
I have a hypothesis that this is happening because I'm running on a system with da-DK culture. As no culture is passed into the ChangeType method, it uses the system culture. Hence it works on en-US system, but breaks in locales where we use comma as decimal separator. I'm testing this now - will produce a PR if this fixes it.

**Comment by arknu** [comment]
Yep, ammending the line by passing in the culture fixes the issue: 
    return (T)Convert.ChangeType(value, t, culture);

**Comment by arknu** [comment]
PR is here: https://github.com/JimBobSquarePants/ImageProcessor/pull/306

**Comment by JimBobSquarePants** [comment]
Thanks. Fixed
