### ISSUE TITLE
Evaluating resize performance in Core

### ISSUE THREAD

**Issue by PromontoryProtean** [JimBobSquarePants/ImageProcessor#307]
Hey Jim,
During my experiments with creating middleware for V3, I ran into some performance question marks when resizing images to generate thumbnails in my file manager web app. I've been trying to think of a good way to present these to you and finally settled on building a sample app in a fork.

My fork is here:
https://github.com/PromontoryProtean/ImageProcessor/tree/WebProjects
I added a new project called ImageEditingWebTools. It is basically a stub right now with a single tool to resize an image. But I'm thinking maybe we can build in additional tools over time to compliment the documentation.

I've attached a sample image to this post. If you fire up the app that I created and try to resize the attached image, you'll see a processing time of between 6 and 10 seconds. I am using a stop watch timer to output the processing time. I figured this might be a convenient way to test sample images while tweaking or working on optimizing the resizing algorithms.

BTW, I was psyched to see your latest pull request regarding maintaining aspect ratio. I was actually debating how to handle that myself but you solved it for me :+1: 

I have no idea if you would be interested in including sample apps or sites like this in your repository, but if you are interested and/or want to restructure my setup I am open to suggestions. Project organization is always tricky.

I am also working on a couple of things to do with middleware, but my main snag right now is the resize time. I'll try and post some of my work to my fork in a couple of days. Hopefully some of it will be useful when you start building ImageProcessor.Web.

![img_0077](https://cloud.githubusercontent.com/assets/10098842/12434577/9bd24b20-bed5-11e5-84fd-15e2a83e3eb3.JPG)

**Comment by JimBobSquarePants** [comment]
Hi there,

That's a big image! I'm fairly certain that would have caused issues with memory in V2 on some 32bit machines.

I'm getting around 5-6 seconds to decode/downscale/encode that using bicubic interpolation, I'm not convinced now that the resampler itself is the issue having boosted its performance somewhat. Other methods that do much less work (Hue) are still taking around 5 seconds. It looks more likely that simply iterating pixels is too slow. The encoder/decoder could probably do with some work also.

I'm really gonna need some help here getting performance up to something acceptable.

Let's keep this issue based purely around performance. I don't want to add any demo apps to the project just now as I want to keep it as lean as possible.

**Comment by JimBobSquarePants** [comment]
To update.

It seems that simply encoding/decoding the jpeg takes around the same time as processing the image. I will need to have a look at improving the performance of the code there. The code is based on [libjpeg.net](https://github.com/BitMiracle/libjpeg.net), there are performance concerns noted [here](http://bitmiracle.com/blog/libjpeg-net-is-ready-for-download) but no commits that I can find designed to improve performance.

**Comment by PromontoryProtean** [comment]
It's definitely a big image, so I will describe our usage scenario so that you have some context. We have a proprietary CMS that has an image uploader. Our clients build a lot of image galleries, so we train them to take their images right off their phone or digital camera and upload them through the file manager in the CMS. The file manager takes care of reducing the source image to something usable on the web. The user can set the resize dimensions up to a max of something like 1200px by 1200px.

I just did some quick tests using V2 on the image that I posted in this thread, and the processing time is less than half a second. 00:00:00.3910282 on my last pass for example. I have run into virtual memory problems in extreme cases when users use the library in combination with the querystring api for auto-generated galleries, but I've never had memory problems when resizing images one at a time as I did in my example above.

The V2 tests I ran were with a quick webforms app that I threw together to mimic the V3 app in my repository. Not sure what you are looking for to create benchmarks, but I'm happy to share this with you if you will find it useful.

Your mention of benchmarks reminds me of an old article I read quite a while back. It was written by Bertrand Le Roy. You've probably seen it but here is the link:
http://weblogs.asp.net/bleroy/state-of-net-image-resizing-how-does-imageresizer-do

Maybe we can do something similar? Only problem is I don't think we can combine the V3 library into a test solution that incorporates all the .net framework stuff, since V3 won't work in a .net framework app. I guess one other way we could do it is just have a single GitGub repository with a bunch of web apps built on whatever platforms we want to benchmark, that do the same exact thing and spit out timers in the same way. Each platform test would have to be run separately, so it won't be very convenient. Can anybody think of a better way to do this?

**Comment by PromontoryProtean** [comment]
Jim, you must have posted that seconds before I posted my post. Thanks for the quick feedback. I am on the road tomorrow for work, but will definitely give the libjpeg.net link a read through. Lots for me to absorb here as I learn the nuts and bolts of how the library is built.

**Comment by JimBobSquarePants** [comment]
I'm having a look around just now for alternatives to work from but it could take a while to get something right.

**Comment by JimBobSquarePants** [comment]
I've managed to clean up the png encoder/decoder quite considerably and provide a small performance boost there. If I could make a bit more of the code there either parallel or use SIMD we'd be on to a winner. 

https://github.com/JimBobSquarePants/ImageProcessor/commit/06d2d11922aa844dab91c857e540a6517eb88d45

**Comment by PromontoryProtean** [comment]
Thanks for the update. I was on the road all day yesterday for work and playing catch up today, but should have time later today or tomorrow to check out the changes. I did read through the libjpeg stuff you referenced. So there are basically 3 steps to resizing a jpeg? Decompress, resize (process) and recompress? And you are hitting bottlenecks in all 3? When you say you are looking for alternatives, do you mean as a replacement for libjpeg?

**Comment by JimBobSquarePants** [comment]
I'm hitting bottlenecks in stages 1 & 3 more than 2. If I convert the image to bmp then decoding/resizing/encoding takes slightly less than 2 seconds on my machine. 

The biggest bottleneck with resizing now is the need to expand/compress each color when iterating through them in order to more accurately resize the image as per http://www.4p8.com/eric.brasseur/gamma.html 

There's no vector version of `Math.Pow` so I have to transform each pixel individually. This essentially double the processing time.

By alternatives, yeah I mean an alternative to Libjpeg.Net, I struggle reading the source code and it appears far too slow for me at the moment.

**Comment by PromontoryProtean** [comment]
Jim, I'd say you made more than a small improvement in performance. I just tested with the newest build and resize time on the image in this post went from an average of 11.2 seconds to around 6.3. That's a huge jump, so nice job. It's unfortunate that the bottleneck is now in the libjpeg code. Optimizing and improving complex code that is not your own is always much more difficult. I also wonder what the limits of managed code will prove to be in this space. It will be interesting to see how close you can get to native performance without taking dependencies on external libraries in some way.

I'll explore the code base more this weekend. Not sure how/where I can help you, but I'll try.

**Comment by JimBobSquarePants** [comment]
That's great to hear! So happy to be making progress. :smile: 

I've created a branch to test out the encoder/decoder in [FluxJpeg.Core](https://github.com/briandonahue/FluxJpeg.Core) The code there needs some work but for the most part is easily clean enough to follow and improve upon. The jpeg specification is a bugger to read though!

Managed code can be fast, really fast. You should see the work Ben Adam has done with the new Kestrel server, something like 1.25 million requests a second now that thing can do. I wish I had his chops! I think we can make it blazing eventually. 

Looking forward to seeing what you can bring to the project.

**Comment by PromontoryProtean** [comment]
I checked out FluxJpeg and it actually has a built in resizer. I built a quick web forms app to test it out. I uploaded it here:
https://github.com/PromontoryProtean/FluxJpegImageResizer/tree/master/FluxJpegImageResizer

I was able to get resize times of less than 1.5 seconds using the test image in this post. So I absolutely  think it is worth while to explore and probably replace libjpeg with FluxJpeg. Even with no improvements you'll be within a second of the processing time I got with V2.

I'm giving more thought now to how the new ImageProcessor.Web might look, but I have some questions on API changes between V2 and V3. I have to take off now but I will try to post more on that later.

**Comment by voidstar69** [comment]
@JimBobSquarePants, you wrote:
"The biggest bottleneck with resizing now is the need to expand/compress each color when iterating through them in order to more accurately resize the image..."

If each color component were an 8-bit unsigned integer rather than a float, you could use a 256-entry lookup table to map a linear component to an sRGB component, and another lookup table to perform the reverse operation.

Perhaps a 'FastResize' class should be written, mapping each color component to (e.g.) a 16-bit integer (could be configurable), then looking up the integer in a 64K lookup table to perform the above mapping? This would be slightly imprecise, but might be much faster than the current Resize class.

**Comment by JimBobSquarePants** [comment]
@voidstar69 it would certainly be faster than the Bicubic or the rest of the more complicated algorithms. You would definitely introduce banding into the image though. I'd wager passing Box or NearestNeighbor would be nearly as quick though.

**Comment by zpbd** [comment]
Just an observation here. But a few years ago (okay, 10, so a different world) I was working on an AI vision project in C# and I needed to do a lot of image manipulation very very fast (mainly resize, rotate and crop). At the time nothing seemed to exist that was remotely fast enough and I had to build all of my image processing manually in unsafe code. It took me absurdly long but the performance was orders of magnitude faster than everything else I could find at the time.

Apologies if I'm stating the blindingly obvious here. I had sort of assumed that image processing packages these days would be advanced enough or using some dependencies that made all this irrelevant, but I noticed you did talk about managed vs unmanaged.

Anyway I just happened across this thread after trying to solve an ImageProcessor issue. Love this package btw :+1:

**Comment by JimBobSquarePants** [comment]
Hi there, your input is most welcome!

My algorithms are pretty quick so far (Im using SIMD where I have figured out where) but yeah, there's certainly some improvement to be had using unsafe code. I'm sure the pixel access indexer could be done better to utilize it for example. My experience with unsafe code blocks is severely limited though having only coded in managed code for the most part over the years so if you have any advice I'd love to hear it.

The Jpeg encoder/decoder is my primary bottleneck definitely so far. I'm working on it but it's pretty tricky stuff.

Hope you got your issue sorted!

**Comment by JimBobSquarePants** [comment]
Hey @PromontoryProtean I'm now getting 2 seconds to decode/downscale/encode that using bicubic interpolation. That's on a 12 core Intel(R) Xeon @ 3.20 Ghz.

That's a 3-4 second drop so we've made good progress. I'm sure there is a lot more we can do though.

**Comment by JimBobSquarePants** [comment]
Closing this now in favour of #347
