### ISSUE TITLE
OutOfMemory exception processing animated GIF

### ISSUE THREAD

**Issue by nul800sebastiaan** [JimBobSquarePants/ImageProcessor#308]
Spent an hour to try to find some workarounds to fix an OutOfMemory exception when processing the GIF below. There error occurs after processing about 280 out of th 675 frames on this line of code: 
https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor/Imaging/Formats/GifDecoder.cs#L59

The error was reported here: http://issues.umbraco.org/issue/U4-7720 as "The parameter is Invalid" but when I run it, it's consistently crashing on an OutOfMemory.

Instead of keep trying to Google this and finding workarounds that make things worse I thought I'd ask the expert first to see if he knows a better tactic of the top of his head! ;-) Any ideas? Happy to work on this some more once I have a direction to try.

![ogb-insider-blogs-googlelogox2-animated](https://cloud.githubusercontent.com/assets/304656/12455610/ac271448-bf9c-11e5-8e90-8215cdc178ed.gif)

**Comment by JimBobSquarePants** [comment]
Hey chum,

There's no way I can think of that you'll get this to work with the present codebase - there's just too many frames.

Here's essentially what is happening. For `System.Drawing` to be able to edit an individual image frame it needs to be able to load it expanded into memory. With the way it's written just now that means we are attempting to load 675 images, each at 1280x720. We're successfully loading 280 concurrent images at the same time which I think is pretty good!

There's a big part of me that simply says "Use Photoshop"  :tongue: for images like this as I never thought someone would attempt to edit a gif with so many frames but there might be a way with some refactoring to vastly reduce the amount of memory used.

In the `GifDecoder` we create all the frames at once then add them to the encoder in a loop.

What we could do instead is create each frame on demand, process it, add it to the `GifEncoder` then dispose of it.  By adding a method to the `GifDecoder` that allows you to access each frame by index it should be possible... All the information is there to add to the `GifEncoder` without having to create hundreds of images.

I *might* have a chance to look at it today but if you want to have a crack, go for it and see how you get on. 

I might just work!

**Comment by JimBobSquarePants** [comment]
Thinking about v3 I extract all the frames on load. Time to rethink that process!

**Comment by nul800sebastiaan** [comment]
Thanks for the feedback! I may have some time to look into it today but I'm teaching courses, so I'm fully occupied until the end of the day. If they don't wear me out too much today I can have a look in the evening.

**Comment by coolmikkel** [comment]
We have in our Umbraco websites choose not to put any width or height on GIF images. So the gif is not handled by the ImageProcessor.

It looks like that ImageProcessor is doing a lot of work on GIFs. Resizing every single image in the animation and then finalizing it bye combining all the images to one GIF.

**Comment by JimBobSquarePants** [comment]
@nul800sebastiaan I've rewritten the code to work how I described above. The image can now be fully processed without the memory climbing too high. I'll do a release soon but it's after midnight and there's still something funny going on with transparent gifs. (Which I can't seem to solve)

However, I really wouldn't recommend someone attempting this kind of process on the fly, and I would recommend you try to dissuade them also.  Resizing 675 images in one go will be far too slow for a web application. It'll lock up the server and cause time-outs.

**Comment by nul800sebastiaan** [comment]
Ah awesome, thanks @JimBobSquarePants Been too busy to look at this until now. Yes, this just clicked for me too, you should not want this for all gifs! 

How about a parameter that does the following: if there's more than `x` frames in a GIF, don't process and resize all of them, instead pick one (I don't know.. the 10th? the middle one? to be determined) and show that as a thumbnail. Or maybe pick at max 10 and process those and make it an abbreviated animated gif (so you can still see it's animated? Thoughts? I can work on this tomorrow.

**Comment by dampee** [comment]
If its for thumbnailing , the idea of an "abreviated" gif is superb.  Certainly if you take the frames spread across the image.  Eg, every 25th frame.  If the delay between the frames is slower and the total length is equal to the original image, the users will get a good idea of the original image.

If you can use estimated final size or "percentage" of quality to keep, it might work for different types of animated gifs.

Just a few thoughts...

**Comment by JimBobSquarePants** [comment]
@nul800sebastiaan, @dampee  Maybe... You'd have to add a parameter to the gif encoder telling it whether to and how many frames to skip, then do some maths. You'd then have to write something in Imageprocessor.Web to parse that instruction...

Makes me wonder how developers prepared gifs for the web before I wrote all this?

**Comment by nul800sebastiaan** [comment]
@JimBobSquarePants That I can do, struggling a little as to how to pass the querystring value to the `GifDecoder`& `ImageExtensions.Copy`. Any hints on how you would handle that?

**Comment by voidstar69** [comment]
The principle of separation of concerns suggests that the gif decoder and encoder should not know anything about this frame-skip logic. Instead the client code using the gif decoder/encoder (maybe Imageprocessor.Web?) should handle the frame-skip logic. The gif decoder should simply supply all images from the file (all in one data structure, or maybe as a 'stream' of images), and the gif encoder should simply encode all images that it is supplied with.

Creating an 'abbreviated' gif thumbnail may still be too slow for a web application, as presumably every image in the source gif needs to be decoded? A simpler solution might be to simply make a thumbnail out of the first image in the gif, although here you would want the gif decoder to only decode the first image, rather than all images in the source gif file. Perhaps a streaming gif decoder would be appropriate, where each image is returned to the client code in sequence, and the client code can stop the decoder after any image?

**Comment by nul800sebastiaan** [comment]
Yeah, I was going to start with doing just the first frame. I don't think you'd need to do much CPU intensive work though, you can pick frames to do processing on and ask for them by index.

**Comment by nul800sebastiaan** [comment]
Started to dive into this and created PR #322

**Comment by JimBobSquarePants** [comment]
Good conversation guys. First frame is definitely the way to go. Otherwise the logic would get mental.

**Comment by JimBobSquarePants** [comment]
Just released now. V2.3.3 and V4.5.2

**Comment by nul800sebastiaan** [comment]
Dude, are you still living on Scottish time!?

AWESOME!! Shannon promised he'll take you out for a beer when he's on holiday there next week! :beers:

**Comment by JimBobSquarePants** [comment]
:smile: It needed doing! Looking forward to seeing him when he comes over. I'll try not to steal him back.

**Comment by nul800sebastiaan** [comment]
@JimBobSquarePants Haha! Well, he hates the Danish winters so he'll return anyway at some point! ;-)

Thanks again!!
