### ISSUE TITLE
ImageProcessor V3 on "Framework"

### ISSUE THREAD

**Issue by SamuelEnglard** [JimBobSquarePants/ImageProcessor#309]
Been looking for a .NET image manipulation library not dependent on `System.Drawing` and ImageProcessor seems perfect. Only issue is that I'm developing on .NET Framework, not .NET Core/DNX.

On my local machine I have created a new Framework DLL that uses linked files so it has the same code and it does compile.

Before I continue (and start running tests) I wanted to know if this would be something acceptable?

**Comment by JimBobSquarePants** [comment]
Hi Samuel,

Would you be able to show me what changes you have made? I'm not quite following what you mean. (Truth be told I'm still struggling to get to terms with dnx etc.)

Cheers

James

**Comment by SamuelEnglard** [comment]
See https://github.com/MapText/ImageProcessor/tree/Framework/src/ImageProcessor.Framework

**Comment by JimBobSquarePants** [comment]
Ah right... I would wait it out. The ability to reference a dnx project in a csproj is supposed to be coming with RC2

https://github.com/aspnet/Home/issues/621

**Comment by SamuelEnglard** [comment]
In that case yeah, I'll just wait. Thanks!
