### ISSUE TITLE
InvalidOperationException: An asynchronous module or handler completed while an asynchronous operation was still pending.

### ISSUE THREAD

**Issue by kipusoep** [JimBobSquarePants/ImageProcessor#311]
Hi James,

I updated ImageProcessor in one of our Umbraco projects last week.
I went from:

```XML
  <package id="ImageProcessor" version="2.3.1.0" targetFramework="net46" />
  <package id="ImageProcessor.Web" version="4.4.1.0" targetFramework="net46" />
  <package id="ImageProcessor.Web.Config" version="2.2.4.0" targetFramework="net46" />
  <package id="ImageProcessor.Web.PostProcessor" version="1.0.3.0" targetFramework="net45" />
```

To:

```XML
  <package id="ImageProcessor" version="2.3.2.0" targetFramework="net46" />
  <package id="ImageProcessor.Web" version="4.5.1.0" targetFramework="net46" />
  <package id="ImageProcessor.Web.Config" version="2.2.5.0" targetFramework="net46" />
  <package id="ImageProcessor.Web.PostProcessor" version="1.1.0.0" targetFramework="net46" />
```

Now we got an Exception caught by our Exception logger:
```InvalidOperationException: An asynchronous module or handler completed while an asynchronous operation was still pending.```

This was triggered by the URL: /media/1002/file.jpg?width=500&rnd=20151207104041
So I guess this might be an issue triggered inside ImageProcessor. Never seen it before.

**Comment by JimBobSquarePants** [comment]
Oh dear... 

Did the exception logger provide any more detail? What was the output of the image request, did it resize?

**Comment by kipusoep** [comment]
No more details unfortunately, I guess that's because there are no pdb files.
Got more instances of the error since I reported it yesterday and found out the picture isn't loading. I have an example URL for you, but can't post it here. It's just loading indefinitely.
I'll send you the URL via DM on Twitter.

**Comment by JimBobSquarePants** [comment]
Looking at that image I think an out of memory exception is being thrown somewhere since it's 5760x3840 pixels. Unfortunately the error itself is not getting logged. I'm not sure why that would be the case.

**Comment by kipusoep** [comment]
Just tested this with the previous version and everything is working fine, so it's an issue with the latest version.

**Comment by JimBobSquarePants** [comment]
I'm not sure what is happening. Here's a screenshot of the image getting resized with the test website within the solution. The code there is identical to the latest release.


![resized](https://cloud.githubusercontent.com/assets/385879/12581629/1269adb2-c48c-11e5-9b51-ae4a6764cfdc.png)

**Comment by kipusoep** [comment]
So I just upgraded IP again, due to an umbraco to 7.3.6 and now everything works fine... :confused: 
Thanks for you time @JimBobSquarePants and I'm sorry it was nothing after all.

**Comment by JimBobSquarePants** [comment]
No worries chum,

Asynchronous threading is an odd affair in Asp.Net, more hack than true support as far as I can gather. Very glad you got it sorted!

**Comment by kipusoep** [comment]
For future readers:

> I found out the older version of ImageProcessor.Web.Plugins.PostProcessor.dll was in the bin folder. Don't remember the name though. I deleted it and now it's working.

**Comment by Leftyx** [comment]
Bloody hell. Same problem here. Didn't read the whole tread and wasted more than 2 hours to find the problem. **ImageProcessor.Web.Plugins.PostProcessor.dll** needs to be removed.

**Comment by JimBobSquarePants** [comment]
Always be a readin' :wink:
