### ISSUE TITLE
amazon s3 integration

### ISSUE THREAD

**Issue by EnterpriseWide** [JimBobSquarePants/ImageProcessor#313]
is the idea for the plugin for s3 to do the following:
image to be requested by the client from webserver
checks the s3 cache
which then in turn requests the full image from s3, 
processes changes, 
caches the result, 
uploads the result to s3
then returns a redirect to the client pointing at s3?

**Comment by JimBobSquarePants** [comment]
Yeah, that's how it should work. Have you had a look at the Azure plugin? That's a complete workflow.

**Comment by JimBobSquarePants** [comment]
Closing to continue in #135
