### ISSUE TITLE
Disposing source stream

### ISSUE THREAD

**Issue by akusmin** [JimBobSquarePants/ImageProcessor#316]
Load(Stream stream, IList<IImageFormat> formats) method is disposing source stream. From my point of view it is not task for a processor to dispose source stream.
Will it stay as a feature of ImageProcessorCore or can it be fixed. ImageProcessor don't have such behavior...

**Comment by JimBobSquarePants** [comment]
You're absolutely correct. The responsibility of managing the stream should be the responsibility of the client user. I'll make sure that's updated.
