### ISSUE TITLE
Resizing in a Pad mode

### ISSUE THREAD

**Issue by akusmin** [JimBobSquarePants/ImageProcessor#317]
Is there is any option to resize in a Pad mode like it was in a previous version in ImageProcessor? I've tried to find solution but no result...

**Comment by JimBobSquarePants** [comment]
There are no resize modes as yet. This is still an alpha so we are concentrating on getting the raw basics of an API solid.

Please also bear in mind that the Core version is an entirely different library to ImageProcessor for the Net Framework. They perform different roles and will have different functionality available.

**Comment by akusmin** [comment]
Sorry for bothering you... It's clear that ImageProcessorCore is completely new and different library but I need to know is it in you plans to implement resizing with a result similar to ImageProcessor resize Pad mode?

**Comment by JimBobSquarePants** [comment]
No worries at all... Eventually it probably will yeah.
