### ISSUE TITLE
image.Process problems when resizing in Core

### ISSUE THREAD

**Issue by PromontoryProtean** [JimBobSquarePants/ImageProcessor#321]
I'm running into resizing problems when using the image.Process extension method in V3 (Core). The following works as expected, I'll call this scenario 1.
`image.Resize(width, height).Save(outputStream);`

The following incorrectly returns the original image, unaltered, but takes some time as if processing is being performed. I'll call this scenario 2.
`image.Process(width, height)`

The following throws up errors every time. This is scenario 3.
`image.Process(width, height, processors.ToArray()).Save(outputStream);`

The following works as expected. Scenario 4.
`image.Process(processors.ToArray()).Save(outputStream);`

The errors in scenario 3 usually read something like:
`ArgumentOutOfRangeException: Value cannot be less than zero or greater than the bitmap width.`

I've been trying to figure out where the problem lies, but I think this one is a little over my head to fix. But I think there is a problem in the following overload:
```
public static Image Process(this Image source, int width, int height, Rectangle sourceRectangle, Rectangle targetRectangle, params IImageProcessor[] processors)
{
    // ReSharper disable once LoopCanBeConvertedToQuery
    foreach (IImageProcessor filter in processors)
    {
        source = PerformAction(source, false, (sourceImage, targetImage) => filter.Apply(targetImage, sourceImage, width, height, targetRectangle, sourceRectangle));
    }
    return source;
}
```

If I understand this correctly, if there are no filters/processors passed as parameters, the image will never get resized. That explains scenario 2. But I can't figure out how/why width and height are getting set to 0 in scenario 3 and causing it to error out.

**Comment by JimBobSquarePants** [comment]
Hey chum, Can you list the Processors and the order you call them in scenario 3?

**Comment by PromontoryProtean** [comment]
I don't think I tested any scenarios with multiple processors. I ran into it when working on my pull request and building the test pages that showed examples with individual effects applied. But I got the errors with alpha and hue. For example the following trips:

```
var processors = new List<IImageProcessor>();
processors.Add(new Hue(50));
image.Process(300, 300, processors.ToArray()).Save(outputStream);
```

But this works:
```
var processors = new List<IImageProcessor>();
processors.Add(new Hue(50));
image.Process(processors.ToArray()).Save(outputStream);
```

Hope that explains it a little better.

**Comment by JimBobSquarePants** [comment]
Hue will try and operate on the full image. It uses the second overload internally if you check the source. We'll have to make it more robust though.

**Comment by PromontoryProtean** [comment]
Ok, but am I wondering - was I correct in assuming that there is a problem causing scenario 2? Should the following return a resized image?
`image.Process(300, 300)`

I'm just getting back what appears to be the original, unaltered image when I use this overload. Though it does take some time as if there is some processing going on.

**Comment by JimBobSquarePants** [comment]
No because we don't pass a the resizer. I'll put some thought to it.

**Comment by PromontoryProtean** [comment]
Ok, I guess if you already have `image.Resize` that particular overload becomes redundant. I just looked at the source again and realized that there is no actual `Process(this Image source, int width, int height)` overload. I did some reading and realized that a params parameter is an optional parameter. Because it is optional the `Process(this Image source, int width, int height)` becomes implied, even if it was never intended to be viable.

I guess you could change the functions to take an `IEnumerable<IImageProcessor>` instead of `params IImageProcessor[]`, but I'm assuming you had specific reasons for using params. Anyway, just thinking out load on this. Another simple solution might be to just toss up an explanatory exception if dimensions are passed in without any processors.

**Comment by IanYates** [comment]
In my own app I have a repository locking API where I had a params parameter but it was a stupid error on my part if I left the params part empty.  Similar to what @PromontoryProtean is describing, I wanted to guard against this at compile time just to save myself some boneheaded mistakes and as a great early hint to others using the API.

I achieved it by changing the signature from something like
`Process(this Image source, int width, int height, params IImageProcessor[] procesors)`
to
`Process(this Image source, int width, int height, IImageProcessor firstProcessor, params IImageProcessor[] otherProcesors)`

It's a nice compile-time enforced hint.  An overload can still be made available that doesn't use params and accepts an IEnumerable<IImageProcessor> for those times where the procesors aren't coming from hand-typed code that takes advantage of the syntax sugar provided by params.

Note also that you can use `IEnuemerable<T>` with params as of C# 6.

**Comment by JimBobSquarePants** [comment]
@PromontoryProtean @IanYates Thanks both for your input. I think I might actually make the Process method internal (I haven't fully decided yet) since I have external chainable methods for all the processors anyway. I've already made restrictions on what processors can be mixed.

**Comment by JimBobSquarePants** [comment]
@PromontoryProtean @IanYates I'm changing the code now to only accept a single processor. That reduced the number of allocations per request and doesn't reduce flexibility since you can still loop.
