### ISSUE TITLE
Unrecognized attribute 'postProcess'. Note that attribute names are case-sensitive.

### ISSUE THREAD

**Issue by jonrandahl** [JimBobSquarePants/ImageProcessor#327]
After initiating an update from Umbraco 7.3.x up to both 7.3.7 and 7.4 I've experienced this issue:

	Server Error in '/' Application.

	Configuration Error

	Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

	Parser Error Message: Unrecognized attribute 'postProcess'. Note that attribute names are case-sensitive.

	Source Error: 

	Line 1:  <?xml version="1.0" encoding="utf-8"?>
	Line 2:  <processing preserveExifMetaData="false" postProcess="true">
	Line 3:    
	Line 4:    

	Source File: E:\Users\jon\Documents\Visual Studio 2015\Projects\Nation Grid Control Projects\NGControls.LatestNews\src\NGControls.LatestNews\config\imageprocessor\processing.config    Line: 2 

	Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1038.0
	
and I have to copy over the example processing.cofig from the website in order for the site to run.

As I said above this has happend twice tonight on both install updates of Umbraco to the latest versions of ImageProcessor.Web via Nuget.

What Can I do to help?

J

**Comment by JimBobSquarePants** [comment]
Ah right.. I didn't set the config to remove the attribute. It's all xdt transforms. If you have a mo could you experiment? You can find the config transform for configuration package in the build folder. 

https://docs.nuget.org/create/configuration-file-and-source-code-transformations

**Comment by JimBobSquarePants** [comment]
Just remembered that I use the same config files as built-in resources so I can't add transforms. 

I'm gonna have to close this as can't fix.

**Comment by jonrandahl** [comment]
Thanks James, is it then a case of ensuring the ImageProcessor.web is the latest or the one shipped with 7.4.n?

**Comment by JimBobSquarePants** [comment]
I always upgrade, then again I know what comes with each upgrade. The one in 7.4.1 is pretty good though.
