### ISSUE TITLE
The package does not contain any assembly references or content files that are compatible with that framework. 

### ISSUE THREAD

**Issue by Yorkst** [JimBobSquarePants/ImageProcessor#331]
I'm trying to add alpha 692 to my project in visual studio 2015 and get an error:

> 
Could not install package 'ImageProcessorCore 1.0.0-alpha-692'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

What profile should I target?

**Comment by JimBobSquarePants** [comment]
ImageProcessorCore doesn't support NET 4.5, It's CoreFX only. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/src/ImageProcessorCore/project.json#L30

We'll probably add NET 4.6 support before final release though. It can never support Net 4.5 due to the use of `System.Numerics.Vectors`

**Comment by MasoudRahmani** [comment]
you could get system.numeric from nuget that way it would work on dot net 4.5.

**Comment by Yorkst** [comment]
I've never worked with CoreFx. There is no option to change target framework in Visual studio as with .Net projects. Can you describe this a little more in detail?

**Comment by JimBobSquarePants** [comment]
@MasoudRahmani What were your requirements that meant you needed .NET4.5? I ask because ASPNET Core will be .NET4.6+ only.

**Comment by MasoudRahmani** [comment]
Building a WPF project for Windows seven, his question where too broad and that's why i said it could be used with Vector package from nuget.
