### ISSUE TITLE
s3 support for CloudImageService

### ISSUE THREAD

**Issue by bjammin** [JimBobSquarePants/ImageProcessor#333]
I'm looking at using ImageProcessor.Web for processing images stored in s3.  Of course I can use it right now with the CloudImageService (have tested and it works fine) but I would have to make my buckets public and reference via http.

I was wondering if anyone has built a CloudImageService specifically for s3 that would enable you to specify the access key & secret and use the s3 api to retrieve the image?

If not, I might write one and contribute, would there be any interest?

**Comment by JimBobSquarePants** [comment]
Hi there,

Thanks for that.

ImageProcessor.Web uses the CloudImageService with http to ensure that there are not too many overheads fetching an image. I've a feeling adding service calls to S3 would incur many additional processing costs to the running server in comparison.

So unfortunately that would mean the additional functionality would not be something we are looking to add just now.

Incidentally, we're actually very close to releasing an [S3 cache plugin](https://github.com/JimBobSquarePants/ImageProcessor/pull/172#issuecomment-190658727) and I'd love to have your input on that.

Cheers

James

**Comment by bjammin** [comment]
Thanks for the quick response James.

Surprisingly I have done some benchmarking with another product which has native S3 support and it was still very fast, actually faster than ImageProcessor!  So I think the overhead is negligible if anything.

Anyway it would be pretty trivial to prototype it up, so if we settle on ImageResizer I will certainly look into it.
