### ISSUE TITLE
ImageProcessor.Web - overlay.size doesn't do anything

### ISSUE THREAD

**Issue by bjammin** [JimBobSquarePants/ImageProcessor#335]
I may be misunderstanding it in some way, but trying to use the [overlay method](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/overlay/) and the overlay.size parameter does not appear to do anything.

`&overlay.size=100,100`

I'm not sure what the numbers refer to (pixels? percent?) but either way they don't seem to do anything whatever I change them to.

**Comment by JimBobSquarePants** [comment]
Hi there,

Great catch Thanks! :+1: 

Unfortunately I managed to miss parsing size when I rewrote the querystring parameter parser - It used to work. Here's an old working example using ImageProcessor.Web v4.3.6
http://jamessouth.me/media/1011/bear.jpg?overlay=monster.png&overlay.position=30,30&overlay.size=100,100&overlay.opacity=80

The values are equal to pixels. I'll update the code now and get a release out asap.

**Comment by mzajkowski** [comment]
Hi Jim, are you planning to release new version soon? I updated all packages from nuget and it seems to broke my overlays :) Just want to know if I need to revert to some old version or just wait for new release. Thanks in advance for your answer!

**Comment by JimBobSquarePants** [comment]
@mzajkowski I'm hoping to get a new release very soon now that I've got an established plan for some security concerns. Hopefully before the end of the week. 

Fingers crossed that's not too much of an issue.

**Comment by mzajkowski** [comment]
Awesome @JimBobSquarePants. Looking forward for this. Could you meanwhile describe from which version problem occurs? Want to roll back to this version before the next release.

**Comment by JimBobSquarePants** [comment]
New version now released :boom:
