### ISSUE TITLE
Error 400 (Bad Request) with ImageProcessor.Web and Azure Cache

### ISSUE THREAD

**Issue by bussemac** [JimBobSquarePants/ImageProcessor#337]
I think I have this setup correctly:
I have a classic storage account with two blobs: media and cache, both are set for public container (I wasn't sure if public blob was enough).
I have a CDN classic setup pointing to media.
All my config files have the azure accounts and keys, these nuget versions:
* UmbracoFileSystemProviders.Azure    {0.5.1-beta}
* ImageProcessor                      {2.3.3.0}                  
* ImageProcessor.Web                  {4.5.3.0}                            
* ImageProcessor.Web.Config           {2.2.5.0}                        
* ImageProcessor.Web.Plugins.Azure... {1.0.8.0}

If I request /media/1010/image.png the image loads. I also see some things being populated into the cache blob.
If I request /media/1010/image.png?width=40 I get an Error 400

> [WebException: The remote server returned an error: (400) Bad Request.]
>    System.Net.HttpWebRequest.GetResponse() +1390
>    ImageProcessor.Web.Plugins.AzureBlobCache.<>c__DisplayClass36.<RewritePath>b__33() +36
>    ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.TryFiveTimes(Action delegateAction) +51
>    ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.RewritePath(HttpContext context) +192
>    ImageProcessor.Web.HttpModules.<ProcessImageAsync>d__b.MoveNext() +5080
> 
> 

Any ideas why the ImageProcessor query string is breaking?

**Comment by bussemac** [comment]
To further test this, I changed only cache.config to switch back to the DiskCache, and it worked fine, the image loaded with and without the query string. Here's the cache.config that's not working:

```xml
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
  <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=XXXXX;AccountKey=XXXXX" />
        <setting key="CachedBlobContainer" value="cache" />
        <!--<setting key="UseCachedContainerInUrl" value="false" />-->
        <setting key="CachedCDNRoot" value="http://azXXXXXX.vo.msecnd.net/" />
        <setting key="SourceStorageAccount" value="[same-as-above]" />
        <setting key="SourceBlobContainer" value="media" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache></caches>
</caching>
```

That CDN root is set with the origin as http://[account].blob.core.windows.net/ and has "Enable Query String" set on as well as HTTPS enabled.

**Comment by JimBobSquarePants** [comment]
Hi there,

The disk cache will work fine as there is no rewrite to an Azure url, everything happens locally.

There must be either an inconsistency in the way you have set up your containers and the rewrite url. FYI Public blob should be enough.

>If I request /media/1010/image.png the image loads. I also see some things being populated into the cache blob.
If I request /media/1010/image.png?width=40 I get an Error 400

ImageProcessor.Web will only create a cached image if a querystring parameter is present unless you have specifically asked it to intercept all requests. So this cannot (should most definitely not) happen.

Could you uncomment out this setting and change the value to `true`.

``` xml
<!--<setting key="UseCachedContainerInUrl" value="false" />-->
```

I'm not sure why you would choose to comment it out. It's not disabled in the [documentation](http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/#config)

Cheers

James

**Comment by bussemac** [comment]
I had it commented out because it was unclear what "newer Azure formats" was, and none of the examples I could find from the Umbraco community had the setting present at all.

So I uncommented it, changed it to true, and it worked, at least as far as not throwing a 400, but I still see it just requesting /media/... ; is the URL supposed to be rewritten to the CDN http://XXXX.vo.msecnd.net/ or not? 

BLOB1 = blob root without container
CDN1 = the full url of the CDN root (which is set to source from BLOB1)

FileSystemProviders.config:
* containerName is media
* rootUrl is the BLOB1 URL
* connectionstring is BLOB1 CS

Security.config
* Service prefix media/
** host is BLOB1 URL/media

Cache.config (AzureBlobCache)
* Cached strorage account = BLOB1 CS
* Cached blob container = cache
* UseCachedContainerInUrl = true
* CachedCDNRoot = CDN1
* SourceStorageAccount = BLOB1 CS [identical to the above connection string]
* SourceBlobContainer = media
* StreamCachedImage = false

**Comment by JimBobSquarePants** [comment]
Ah right...

The Umbraco forums can go out of date pretty quickly. I would recommend the readme and docs here as the source of truth. 

The new format urls all end with _azureedge.net_ and it's only with a certain (non standard I believe) setup you need to change the value to false. 

The request will appear relative on the surface but there is some rewriting going on. If you r-click and open the image in a new tab you will see the redirect taking place. You should also be able to see the redirect in your browser developer tools.

I hope I've managed to help clear things up a little.

**Comment by bussemac** [comment]
That helps, yes. So I busted out Fiddler and checked what I was seeing:

/media/1234/home.jpg -> HTTP 200, comes with a caching header: max-age [1 year], must-revalidate, and a probably redundant Expires date (also set for 1 year)
/media/2345/pic.jpg?width=40 -> HTTP 302 to the *.msecdn.net/cache/... path

Fiddler then shows the request for the cache item in the CDN (since I had cleared cache first), which is HTTP 200 (exactly what you'd expect) with a cache header also for max-age 1 year (no must-revalidate or Expires).

If I hit F5 to reload the page, the static images are redownloaded, while the ImageProcessor ones again show the 302 (makes sense) and then the CDN returns a 304 because they haven't changed.

So clearly the ImageProccesor requests are being cached and served through the CDN, and I guess  figuring out why the static images aren't is a question for elsewhere.

**Comment by JimBobSquarePants** [comment]
Yeah, that all looks correct. ImageProcessor is setting various header when uploading the images to blob storage. As for static images without querystring params (which IP will ignore), are you manually uploading them to blob storage or are they served from the file system?

**Comment by bussemac** [comment]
The azure file system plugin uploads them to the media storage container.
Existing images were copied there, and once that virtual path provider was
tested and working, the ones in the web app were removed.

**Comment by JimBobSquarePants** [comment]
The filesystem provider _should _be caching when files are added through the back office.

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/develop/src/UmbracoFileSystemProviders.Azure/AzureFileSystem.cs#L210

They are then passed in the response when serving the virtual file.

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/develop/src/UmbracoFileSystemProviders.Azure/FileSystemVirtualFile.cs#L70

**Comment by bussemac** [comment]
So there's no URL rewriting for things not passed through IP, and that's by design? I see the HTTP Headers being set, yet if I reload (not force-reload, just a regular click the reload button), the result is that the images that ARE done via IP are available instantly while everything else has to redownload.

![screenshot044](https://cloud.githubusercontent.com/assets/842344/13746850/c08396a6-e9cb-11e5-800d-24457fa1dab1.gif)

![screenshot043](https://cloud.githubusercontent.com/assets/842344/13746821/92be2470-e9cb-11e5-9482-ade7e2757312.gif)

Fiddler does warn for the items coming directly from media (included the 302 responses generated for the IP images): "This response contains neither an ETAG nor a Last-Modified time. This will prevent a Conditional Revalidation of this response." 

Whereas on the ones served from the CDN:
HTTP/1.1 ETAG Header is present: 0x8D346A87CB7AC38

	!! WARNING: The ETAG header value MUST be a quoted-string.
HTTP Last-Modified Header is present: Mon, 07 Mar 2016 16:49:45 GMT

So if I'm reading this right, and I'm not an expert on HTTP caching, it looks like the FileSystemProvider needs to set that ETAG or Last-Modified time header if the cache directives will have any benefits at all, else the browser is forced to revalidate.

**Comment by JimBobSquarePants** [comment]
>So there's no URL rewriting for things not passed through IP, and that's by design?

Not exactly. With a VirtualPathProvider your relative request to anything in the media folder is redirected internally to the blob storage url which is requested using the Azure SDK. There's no 302 taking place at all since what you are requesting is a virtual path.

You cannot update the last modified header when saving items to Azure blob storage as it is readonly. This gets updated automatically when the blob is updated. 

http://stackoverflow.com/a/23415589/427899

I'd need to check the rules on HTTP caching but I should be able to set the values if need be with a bit of trickery in the FileSystemVirtualFile constructor by casting and returning extra properties.

**Comment by bussemac** [comment]
Yeah, you probably just need to set the Last-Modified header in the HTTP response when you return the file from the virtual path, and just retrieving the value from the Azure blob should work, no need to change it. I think if that's set properly, then the caching will work better. It might even work to just modify the cache-control property of the CloudBlockBlob to include Last-Modifed when you upload the file in the first place, since that cache-control property does get read later by the browser.

**Comment by critot** [comment]
Hi James and Bussemac, I've some problem, and I'm not able to make the plugin working...

My environment:
Azure, basic plane, .net framework 4.6, pipeline integrated, host: http://xyz.azurewebsites.net;
A Blob service, https://xyz.blob.core.windows.net, width a container /photos (access type = blob);
A Cdn, http://xyz.azureedge.net, linked to the above blob.

I've installed the latest ImageProcessor, ImageProcessor.Web,  ImageProcessor.Web.Config, ImageProcessor.WebPlugins.AzureBlobCache, and the configs files are:

web.config

 <sectionGroup name="imageProcessor">
      <section name="security" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageSecuritySection, ImageProcessor.Web" />
      <section name="processing" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageProcessingSection, ImageProcessor.Web" />
      <section name="caching" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageCacheSection, ImageProcessor.Web" />
    </sectionGroup>

    <httpModules>
    <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </httpModules>

    <modules>
    <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </modules>

<imageProcessor>
    <security configSource="config\imageprocessor\security.config" />
    <caching configSource="config\imageprocessor\cache.config" />
    <processing configSource="config\imageprocessor\processing.config" />
  </imageProcessor>

---
cache.config

  <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=myaccountname;AccountKey=myaccountkey" />
        <setting key="CachedBlobContainer" value="cache" />
        <setting key="UseCachedContainerInUrl" value="false" />
        <setting key="CachedCDNRoot" value="http://xyz.azureedge.net" />        
        <setting key="SourceStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=myaccountname;AccountKey=myaccountkey" />
        <setting key="SourceBlobContainer" value="photos" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache>
----
security.config

   <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
   <settings>
        <setting key="Container" value="photos"/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://xyz.azurewebsites.net"/>
      </settings>
    </service>
---

processing.config: not modified

----

My webapp upload some files via an handler in chunks, commit them with a PutBlockList, create a container inside '/photos' and put the blobs; 
the only thing that happens is the creation of the cache container..I do not receive any type of error; when I call the images with a querystring the original images are returned.
I've tried different settings, for example:

in cache.config:

<setting key="UseCachedContainerInUrl" value="true" />
CachedStorageAccount and SourceStorageAccount with the complete conn string of the blob

in security.config

prefix set to the /photos blob

but nothing... any idea?

thank you
