### ISSUE TITLE
Alpha Mask

### ISSUE THREAD

**Issue by LemonTVnz** [JimBobSquarePants/ImageProcessor#338]
Heres an implmintation of alpha mask (code has not been cleaned up and contains some umbraco stuff that should be refactored out etc)
It applies the alpha channel from a png to the current image

Not sure if you will find it uesful and I dont have time to do a proper git commit but I've attached the files anyway

[alphamask.zip](https://github.com/JimBobSquarePants/ImageProcessor/files/162152/alphamask.zip)

**Comment by JimBobSquarePants** [comment]
Hi there,

Thanks for adding this. I'm wondering though, what functionality difference is there in this to the existing [Mask](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/mask/) functionality.

Cheers

James
