### ISSUE TITLE
Tilt functionality

### ISSUE THREAD

**Issue by GarethFZA** [JimBobSquarePants/ImageProcessor#341]
Hi James.  Is image tilt functionality on the roadmap?
Thank you
Gareth

**Comment by JimBobSquarePants** [comment]
Hi Gareth,

Do you mean tilt by rotation to skew? We have rotation built in but I'll need help working out skew. 

James

**Comment by GarethFZA** [comment]
Hi James.  Thanks for the reply.
Our requirement is to take an image and tilt it (3 dimensionally) so that the top of the image appears to be closer to the view than the bottom.

**Comment by JimBobSquarePants** [comment]
Ah yeah... That I'm going to need help doing then. I have rotate and flip working fine but not that.

I'm fairly certain it's all easily possible with the System.Numerics.Vectors classes, I just don't know the API well enough to know how yet.

**Comment by JimBobSquarePants** [comment]
Hey @GarethFZA I've added a new Skew method in recent builds. Would this cover your requirements?
