### ISSUE TITLE
Version 1.0.8 returns Bad Request for crops using Remote.axd

### ISSUE THREAD

**Issue by kgiszewski** [JimBobSquarePants/ImageProcessor#344]
Not sure if this is the right repo for this issue.

Version `1.0.8` returns `Bad Request` for crops using `remote.axd`

https://www.nuget.org/packages/ImageProcessor.Web.Plugins.AzureBlobCache/1.0.8

Works fine for `1.0.7` and prior.

**Comment by JimBobSquarePants** [comment]
Is your config up to date? 

I.E do you have the

`<setting key="UseCachedContainerInUrl" value="true"/>` property set? Nuget should have updated your config though it may have skipped it.

http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/#config

**Comment by kgiszewski** [comment]
Ace, that was it. :+1: 

Wondering if it should default to `true` for that setting if the key is missing.

**Comment by JimBobSquarePants** [comment]
I had a reason. I can't remember what that was now though...
