### ISSUE TITLE
why not supporting  dnx451?

### ISSUE THREAD

**Issue by ahmedanis03** [JimBobSquarePants/ImageProcessor#350]
i dun know it is a bug or intended and if it is then why?
Thanks a lot

**Comment by JimBobSquarePants** [comment]
Hey there,

Mostly cos it's old, It doesn't support System.Numerics.Vectors, and AspNet Core minimum support is .NET 4.6 

There's plenty of libraries including the classic ImageProcessor library that support NET 4.5. Personally I wouldn't bother though If you are going to use DNX (Or whatever the new build system is called now)

Hope that clears things up.

Cheers

James
