### ISSUE TITLE
ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Resize

### ISSUE THREAD

**Issue by eNTi** [JimBobSquarePants/ImageProcessor#354]
i'm having trouble with the resize method on a REMOTE SERVER. this doesn't occur on my local machine (in debug mode). i basically get an exception which tells the file upload (fineuploader) that something went south. this doesn't happen with every picture though. i've yet to find a pattern as to when that occurs. it seem to occur more frequently with .png files but it will also happen (less often) with .jpg files. it doesn't seem to be overly related to the file size. sometimes smaller pictures fail while larger one's work.

```
ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Resize 
---> ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Resizer 
---> System.ArgumentException: Ungültiger Parameter. bei
 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format) bei ImageProcessor.Imaging.Resizer.ResizeLinear(Image source, Int32 width, Int32 height, Rectangle destination) bei 
ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Int32 width, Int32 height, Int32 maxWidth, Int32 maxHeight, List`1 restrictedSizes, ResizeMode resizeMode, AnchorPosition anchorPosition, Boolean upscale, Single[] centerCoordinates, Boolean linear) 
--- Ende der internen Ausnahmestapelüberwachung 
--- bei ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Int32 width, Int32 height, Int32 maxWidth, Int32 maxHeight, List`1 restrictedSizes, ResizeMode resizeMode, AnchorPosition anchorPosition, Boolean upscale, Single[] centerCoordinates, Boolean linear) bei
 ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Boolean linear) bei
 ImageProcessor.Processors.Resize.ProcessImage(ImageFactory factory) 
--- Ende der internen Ausnahmestapelüberwachung
--- bei ImageProcessor.Processors.Resize.ProcessImage(ImageFactory factory) bei
 ImageProcessor.Imaging.Formats.FormatBase.ApplyProcessor(Func`2 processor, ImageFactory factory) bei ImageProcessor.ImageFactory.Resize(ResizeLayer resizeLayer) bei ImageProcessor.ImageFactory.Resize(Size size) bei Nop.Services.Media.PictureService.Reformat(Byte[] fileBinary, Int32 dpi, Double height, Double width) in C:\Projects\nopCommerce\src\Libraries\Nop.Services\Media\PictureService.cs:Zeile 881.
```

the code where the issue occurs is:
```
public byte[] Reformat(byte[] fileBinary, int dpi, double height, double width)
{
	var memoryStream = new MemoryStream();
	var iFactory = new ImageFactory();
	var size = new Size();
	var i = iFactory.Load(fileBinary);

	if (i.Image.Width > i.Image.Height)
	{
		size.Width = (int)Math.Ceiling(dpi * width);
	}
	else
	{
		size.Height = (int)Math.Ceiling(dpi * height);
	}

	i.Resize(size).Resolution(dpi, dpi).Save(memoryStream); // Zeile 881

	var newBinary = new byte[memoryStream.Length];
	memoryStream.Read(newBinary, 0, newBinary.Length);

	return newBinary;
}
```

**Comment by JimBobSquarePants** [comment]
Hi there,

Without looking into any details you are most likely having problems since you are not disposing of any of the `IDiposable `objects within your method. Did you look at the example code?

http://imageprocessor.org/imageprocessor/imagefactory/#methods

**Comment by eNTi** [comment]
oh... hmm. well if i did, i wasn't paying attention. i'm not used to memory management in c#. i'll try that out. thanks for the quick reply.

**Comment by JimBobSquarePants** [comment]
No worries, happy to help. :smile: There's some stuff in C# that you need to keep an eye out for memory wise. Imaging is one of them with System.Drawing. 

Update your code and I'll keep this issue open so we can see if that makes a difference. Fingers crossed that was the problem. If not we'll work it out together.

**Comment by eNTi** [comment]
it seems your suggestion fixed my problem. weird behavior but i guess that's always the case with memory corruption/leaks thanks.

**Comment by JimBobSquarePants** [comment]
Excellent! Glad you got it solved. :+1:
