### ISSUE TITLE
Update the website 

### ISSUE THREAD

**Issue by karl-sjogren** [JimBobSquarePants/ImageProcessor#355]
I've noticed an error in the documentation at the website. I spent over 8 hours pinning this down so it would be a shame if others ends up doing it as well.

On the page for the [WebP-plugin](http://imageprocessor.org/imageprocessor/plugins/webp/) it says you need msvcr110.dll from the Visual C++ Redistributable Package with a link to the VS2012 redist package. But in 1d92a36cecacae8e694ec0376154d6542f0bebc3 libwebp was updated to a newer version that requires msvcr120.dll from the VS2013 redist package instead  The new required package is available from https://www.microsoft.com/en-us/download/details.aspx?id=40784 and it would be great if the website was updated with this.

**Comment by JimBobSquarePants** [comment]
Sorry about that. I documented it on the Nuget package page but forgot to update the docs page. The docs are actually open source, stored in the gh_pages branch so if you are feeling adventurous they are there to update.

**Comment by karl-sjogren** [comment]
Sorry I missed the gh-pages branch, never thought you were using that since the pages are so customized. I've created a pull request #356 that clarifies the situation a bit more even for users of older versions.
