### ISSUE TITLE
Moving Image to IDisposable. 

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#360]
This relates to #347 

I've been doing some benchmarking with various approaches to accessing pixel data within my `Image` class. If we can make that as fast as possible then we have a quick performance win which benefits the library as a whole. 

So these are the three approaches I'm using (I'm only including the important bits):

**Image (The current default.)**

``` c#
// Constructor
public Image(int width, int height)
{
    pixels = new float[width * height * 4];
}

// Indexer
public Color this[int x, int y]
{
    get
    {

        int start = ((y * this.Width) + x) * 4;
        return new Color(this.pixels[start],
                            this.pixels[start + 1],
                            this.pixels[start + 2],
                            this.pixels[start + 3]);
    }

    set
    {
        int start = ((y * this.Width) + x) * 4;

        this.pixels[start] = value.R;
        this.pixels[start + 1] = value.G;
        this.pixels[start + 2] = value.B;
        this.pixels[start + 3] = value.A;
    }
}
```

**Fixed Image (Pixels fixed upon access)**

``` c#
// Constructor
public Image(int width, int height)
{
    pixels = new float[width * height * 4];
}

// Indexer
public Color this[int x, int y]
{
    get
    {
        fixed (float* p = &this.pixels[0])
        {
            return *((Color*)(p + ((y * this.Width) + x) * 4));
        }
    }

    set
    {
        fixed (float* p = &this.pixels[0])
        {
            Color* c = (Color*)(p + (((y * this.Width) + x) * 4));
            c->R = value.R;
            c->G = value.G;
            c->B = value.B;
            c->A = value.A;
        }
    }
}
```

**Unsafe Image (Pixels fixed at initialisation, implements IDisposable)**

``` c#
// Constructor
public Image(int width, int height)
{
    this.pixelsHandle = GCHandle.Alloc(new float[width * height * 4], GCHandleType.Pinned);
    this.pixels = (float*)this.pixelsHandle.AddrOfPinnedObject().ToPointer();
}

// Indexer
public Color this[int x, int y]
{
    get
    {
        return *((Color*)(this.pixels + ((y * this.Width) + x) * 4));
    }

    set
    {
        Color* c = (Color*)(this.pixels + (((y * this.Width) + x) * 4));
        c->R = value.R;
        c->G = value.G;
        c->B = value.B;
        c->A = value.A;
    }
}
```

This yields the following results:

```
BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz, ProcessorCount=12
Frequency=3117490 ticks, Resolution=320.7709 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
JitModules=clrjit-v4.6.1063.1

Type=ImagePerformance  Mode=Throughput
```

                   Method |     Median |    StdDev | Scaled |
------------------------- |----------- |---------- |------- |
                 1. Image | 14.6007 ms | 0.7283 ms |   1.00 |
        2. Image Parallel | 12.2520 ms | 0.4032 ms |   0.84 |
           3. Fixed Image | 11.5585 ms | 0.8774 ms |   0.79 |
  4. Fixed Image Parallel | 12.0792 ms | 0.5968 ms |   0.83 |
          5. Unsafe Image |  9.4637 ms | 0.2921 ms |   0.65 |
 6. Unsafe Image Parallel |  8.2399 ms | 0.1148 ms |   0.56 |

We can safely ignore fixing each time but Implementing `IDisposable` and pinning the pixels at initialisation yields a **~35%** increase in speed in linear and a **~34%** increase in parallel compared to the original parallel approach. 

These numbers are too much of an improvement to ignore but it will make the API a lot more complicated and prone to developers not cleaning up after themselves.

So... Your input is important here.

Do we implement `IDisposable` or is there another way? Additionally, if you can see anything in the code that can be improved upon please chip in. :smile: 

Please comment below.

Benchmark Code: 
[BenchmarkTest.zip](https://github.com/JimBobSquarePants/ImageProcessor/files/205769/BenchmarkTest.zip)

**Comment by JimBobSquarePants** [comment]
Ok so I've been playing around a bit more. 

If I change the setters a bit more to what would appear on the surface to be more efficient . 

**Fixed Image (Pixels fixed upon access)**
``` c#
public Color this[int x, int y]
{
    get
    {
        fixed (float* p = &this.pixels[0])
        {
            return *((Color*)(p + ((y * this.Width) + x) * 4));
        }
    }

    set
    {
        fixed (float* p = &this.pixels[0])
        {
            *(Color*)(p + (((y * this.Width) + x) * 4)) = value;
        }
    }
}
```

**Unsafe Image (Pixels fixed at initialisation, implements IDisposable)**
```c#
public Color this[int x, int y]
{
    get
    {
        return *((Color*)(this.pixels + ((y * this.Width) + x) * 4));
    }

    set
    {
        *(Color*)(this.pixels + (((y * this.Width) + x) * 4)) = value;
    }
}
```

I get the following results (Note the ratio is more important than time)

Both fixed and unsafe get a performance boost in linear. Parallel bizarrely seems to slow things down. 

Does anyone know why?

```
BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz, ProcessorCount=12
Frequency=3117490 ticks, Resolution=320.7709 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
JitModules=clrjit-v4.6.1063.1

Type=ImagePerformance  Mode=Throughput
```
                   Method |     Median |    StdDev | Scaled |
------------------------- |----------- |---------- |------- |
                 1. Image | 13.6190 ms | 0.2642 ms |   1.00 |
        2. Image Parallel | 12.3815 ms | 0.6229 ms |   0.91 |
           3. Fixed Image |  9.6160 ms | 0.6788 ms |   0.71 |
  4. Fixed Image Parallel | 12.3755 ms | 0.4107 ms |   0.91 |
          5. Unsafe Image |  7.2887 ms | 0.1586 ms |   0.54 |
 6. Unsafe Image Parallel |  8.1792 ms | 0.1470 ms |   0.60 |

**Comment by rytmis** [comment]
My results:

Benchmark code as-is

```ini

BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz, ProcessorCount=8
Frequency=2728068 ticks, Resolution=366.5598 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
JitModules=clrjit-v4.6.1531.0

Type=ImagePerformance  Mode=Throughput  

```
                   Method |     Median |    StdDev | Scaled |
------------------------- |----------- |---------- |------- |
                 1. Image | 15.9796 ms | 1.0788 ms |   1.00 |
        2. Image Parallel | 12.0840 ms | 0.4778 ms |   0.76 |
           3. Fixed Image | 12.2143 ms | 1.4041 ms |   0.76 |
  4. Fixed Image Parallel | 11.4232 ms | 0.8076 ms |   0.71 |
          5. Unsafe Image | 10.6769 ms | 0.5672 ms |   0.67 |
 6. Unsafe Image Parallel |  7.6689 ms | 0.3947 ms |   0.48 |

Direct memory assignment in fixed and unsafe

```ini

BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz, ProcessorCount=8
Frequency=2728068 ticks, Resolution=366.5598 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
JitModules=clrjit-v4.6.1531.0

Type=ImagePerformance  Mode=Throughput  

```
                   Method |     Median |    StdDev | Scaled |
------------------------- |----------- |---------- |------- |
                 1. Image | 17.7992 ms | 1.1530 ms |   1.00 |
        2. Image Parallel | 11.9554 ms | 0.3178 ms |   0.67 |
           3. Fixed Image | 12.2498 ms | 0.9363 ms |   0.69 |
  4. Fixed Image Parallel | 10.9880 ms | 0.2686 ms |   0.62 |
          5. Unsafe Image |  9.3535 ms | 0.3994 ms |   0.53 |
 6. Unsafe Image Parallel |  7.8387 ms | 0.2934 ms |   0.44 |

**Comment by JimBobSquarePants** [comment]
Interesting. Thanks for that, useful to see. I'm assuming your direct assignment adjusted code is as I described in my sample.

This is an interesting learning process. It does seem clear to me in both our results that switching to `IDisposable` would yield an excellent improvement. Let's hope someone from the .NET team happens to stumble upon this.

**Comment by JimBobSquarePants** [comment]
I went ahead and merged this just now. Don't think there's any leaks but if anyone reads this please check.
