### ISSUE TITLE
Nuget install issues

### ISSUE THREAD

**Issue by alastair-todd** [JimBobSquarePants/ImageProcessor#362]
In VS 2015 I get this reported trying to `install-package imageprocessor`

Given its core to Umbraco, I'm guessing its local issue, so I reinstalled VS 2015, but still no luck. Any ideas? I have tried all types of .net framework targets...

Interestingly I can install anything up to and including version 2.3.2

> install-package : Could not install package 'ImageProcessor 2.3.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are 
> compatible with that framework. For more information, contact the package author.

**Comment by JimBobSquarePants** [comment]
Very odd... I have heard of this issue once before though. 

I'll have to double check what version I am running. I might have switched to 4.5.2 as 4.5.1 has now reached end of life.

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

Have you tried switching your project to that?

**Comment by alastair-todd** [comment]
Yeah tried all the variants. Ended up going the manual route for Umbraco. DIsappointing but had to get on. Certainly something amiss in my local env. just no idea what. I did a full reinstall of VS but still the same. Will try fixing frameworks

**Comment by JimBobSquarePants** [comment]
I wonder if it is caused by different Nuget versions? I always keep my version up to date.

I have set no constraints but you never know with Nuget.

**Comment by JimBobSquarePants** [comment]
Fingers crossed this issue does not affect the new release.

**Comment by alastair-todd** [comment]
Yes that works. The lurgy has now jumped to Markdown 1.14.4.

Anything in particular was changed to fix that?

**Comment by JimBobSquarePants** [comment]
Excellent! 

I updated all the individual projects to use the latest Visual Studio build version. Other than that I've no idea what could have caused it unless there was a bug in the version of Nuget I was using to pack it. 

I'm working from a fresh Windows install now.

**Comment by alastair-todd** [comment]
well a forced install of Markdown + Automapper specific versions before Umbraco-cms has worked.

i had been installing umbraco first via VS 2013, then switching...actually less painful. i really dont like getting involved with nuget. its just supposed to work right?

**Comment by JimBobSquarePants** [comment]
That's the idea yeah... Never had any positively identifiable issues.
