### ISSUE TITLE
ImageProcessorCore .NET Framework 4.5.2 build

### ISSUE THREAD

**Issue by zabulus** [JimBobSquarePants/ImageProcessor#363]
I've needed ImageProcessorCore library for using in our .NET Framework 4.5.2. And I've successfully built it. Will you accept PR for net452 target for the library?

**Comment by JimBobSquarePants** [comment]
Cool! :sunglasses:  How did you get past the need for the vectors library? I didn't know it was installable on 4.5.2.

I'm assuming the need for this is so that you can use the same codebase in your application for both .NET Core and .NET 4.5.2?

If so, then yeah. I'd like to setup the configuration to support the full framework also.

**Comment by zabulus** [comment]
>Cool! :sunglasses: How did you get past the need for the vectors library? I didn't know it was installable on 4.5.2.

According to this article: https://mariantines.com/2015/08/24/simd-support-in-net-framework/
>  For .NET Framework 4.5 both fixed and variable length type are in the same NuGet package of version 4.0.0.

So I simply added dependency for 4.0.0 version. With some little magic around System.Runtime it begun build. Though, I needed additional tweak in my dependant project.

> I'm assuming the need for this is so that you can use the same codebase in your application for both .NET Core and .NET 4.5.2?

Not exactly. We are using System.Drawing for saving PNG files in memory and profiler shows that it takes big amount of time. I'm looking 3-rd party libraries for performant PNG encoder or at least with tweaks of compression to decrease it.

**Comment by zabulus** [comment]
Just pushed:
https://github.com/JimBobSquarePants/ImageProcessor/pull/364

**Comment by razblack** [comment]
Hi, I want to say there is a problem with moving down to 4.5.2  atleast with regards to DNX.

I tried to move down to 4.5.1 for the current project I'm working on and it was failing quite badly with..

> "Could not load file or assembly 'System.IO.Compression, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

In particular, my input file is PNG and I wanted to convert down for thumbnails to JPG... eventually to Base64String for blobs...:

```
using (FileStream stream = File.OpenRead(filePath))
using (Image image = new Image(stream))
using (FileStream output = File.OpenWrite(storagePath  + blobName + "_blob"))
{
	image.Resize(320, 180).SaveAsJpeg(output);
}
```
at using (Image image = new Image(stream))

`StackTrace = "   at ImageProcessorCore.Formats.ZlibInflateStream..ctor(Stream stream)\r\n   at ImageProcessorCore.Formats.PngDecoderCore.ReadScanlines(MemoryStream dataStream, Single[] pixels, IColorReader colorReader, PngColorTypeInformation colorTypeInformation)\r\n  ...`

I tried compiling ImageProcessor for 451 and 452, both times same results..   I then moved my project up to DNX46...  and now things are working great.

I looked through the assemblies of System.IO.Compression in 4.0.0 and 4.1.0-beta-23516, each is missing the actual file and contain empty holders  (ie:  _._ )

The only versions that have the assembly for System.IO.Compression are net46 and dotnet (the next CLI)...  so, i'm thinking for anyone else that is targeting ASP.NET 5 at DNX451, just update the project to DNX46

**Comment by JimBobSquarePants** [comment]
This should all work now I have released the RC2 update targeting netstandard1.1 (works on my machine) please let me know when you have tested it
