### ISSUE TITLE
Gif images have black background

### ISSUE THREAD

**Issue by Vitalii-Efremov** [JimBobSquarePants/ImageProcessor#366]
Hello, I have some problems with the plugin.

I tried to use the plugin to optimize the gif image and have gotten black background after it.

`var format = new GifFormat();

            format.Quality = 80;

            byte[] result = null;

            using (MemoryStream inStream = new MemoryStream(image))
            {
                using (MemoryStream outStream = new MemoryStream())
                {
                    // Initialize the ImageFactory using the overload to preserve EXIF metadata.
                    using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
                    {
                        // Load, resize, set the format and quality and save an image.
                        imageFactory.Load(inStream)
                                    .Format(format)
                                    .Save(outStream);
                    }
                    result = outStream.ToArray();
                    // Do something with the stream.
                }
            }
            return result;`
Original image:
![loading](https://cloud.githubusercontent.com/assets/16013311/14688936/47b027ca-0745-11e6-9145-6dd98c39527c.gif)
Optimized image:
![5b10fb41-e516-46ab-91cd-cda6a10239af](https://cloud.githubusercontent.com/assets/16013311/14688947/55d5a438-0745-11e6-9a77-ff501214a961.gif)

How could I fix this problem? 

Thanks in advance.

**Comment by JimBobSquarePants** [comment]
Yeah.... I'm struggling to fix this one. :disappointed: 

Somehow the `System.Drawing` encoder is kicking in and re-quantizing the gifs reducing the quality to the built-in level and removing transparency on animated ones. I've tried every trick I know to fix it but the inner workings of the encoder are a mystery.

[An animated gif encoder is not that hard to write](https://github.com/JimBobSquarePants/ImageProcessor/blob/dfc11ff2e5491cd114583461ac43fab91615f4d9/src/ImageProcessorCore/Formats/Gif/GifEncoderCore.cs) so I don't understand how they manage to mess it up that much!

**Comment by Vitalii-Efremov** [comment]
Thank you for the attempt to fix this issue. I am sorry but I can't help you to fix this problem because It is very specific field and I am not an expert in it. Is it possible to fix this problem at the nearest future?

**Comment by JimBobSquarePants** [comment]
No worries. I'll have a further look. It might be a case of me replacing the whole infrastructure with a custom encoder...It's a lot of work though.

**Comment by JimBobSquarePants** [comment]
Had a flash of inspiration and managed to fix this. Will have a new release out asap.

**Comment by Vitalii-Efremov** [comment]
Awesome, thank you very much for this work!

**Comment by JimBobSquarePants** [comment]
Closing for now as will be in the next release and I'm tracking it.
