### ISSUE TITLE
[core] Cropping does not work as expected

### ISSUE THREAD

**Issue by pinki** [JimBobSquarePants/ImageProcessor#367]
Hi,
I tried to crop an image, but it doesn't work as expected.
No matter what source rectangle is defined, the x and y values are ignored and I get a cropped image with the origin (0, 0).

**Comment by pinki** [comment]
I've got the solution.

In Crop.cs, change line 32 to
`target[x, y] = source[x + sourceRectangle.X, y + sourceRectangle.Y];`

**Comment by JimBobSquarePants** [comment]
Thanks for this, very much appreciated! Having to flatten my computer just now but will have a proper look asap

**Comment by JimBobSquarePants** [comment]
I've merged your code in now. Thanks again for this.
