### ISSUE TITLE
rotating an image should change width/height as well

### ISSUE THREAD

**Issue by jemala** [JimBobSquarePants/ImageProcessor#370]
If an image is being rotated, the width and height stay the same and the image gets cropped. This should be fixed, as it is a really important feature for an image processor.

**Comment by JimBobSquarePants** [comment]
Hi Jemala,

Could you please provide some context here. Which library, the new one?

When raising an issue on an open source project it is usually good practise to provide as much information as possible. 

Thanks

James

**Comment by jemala** [comment]
Hi James,

yes, I am talking about the new library ImageProcessorCore. I was using the latest source code of ImageProcessorCore and ASP VNext dnxcore50 release candidate.

Rotating the following image by 90 degrees:

![quick_banners32](https://cloud.githubusercontent.com/assets/18643746/14780165/f24226b8-0adb-11e6-8861-12dfaeb89f33.jpg)

Leads to this result:

![23866c27-ee30-4bef-a443-8e9544295b8d](https://cloud.githubusercontent.com/assets/18643746/14780189/0f88fe22-0adc-11e6-935b-b8984f926e23.jpeg)

Thanks,
Marco

**Comment by JimBobSquarePants** [comment]
Hey @jemala, assuming you were using the `Image.Rotate(float angle)` method that's now fixed.
