### ISSUE TITLE
Setting Default Quality

### ISSUE THREAD

**Issue by Myster** [JimBobSquarePants/ImageProcessor#371]
I'd like to tweak the default quality down a bit to save bandwidth / load time.
I'd like to do this globally in the setting file? (I tried editing the processing.config to add a settings/setting within the quality plugin element but that didn't work)

Is it possible to set the default quality?

_It's not a big deal if not, I can encapsulate calls to the querystring generation to include it on the querystring._

**Comment by JimBobSquarePants** [comment]
Nah not through the config I'm afraid but you could do it via the `ImageProcessingModule.OnProcessQuerystring`event.

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events
