### ISSUE TITLE
First load on WPF project takes 5 a 10 seconds

### ISSUE THREAD

**Issue by mrfatmen** [JimBobSquarePants/ImageProcessor#372]
In my WPF application i need to make thumbs from photo the user add to the program. To do this i use the ImageProcessor package which works perfect for me. Bu i have one small problem the first use in an application session always takes 5 a 10 seconds to complete every next thumb making in the same session only takes milliseconds.

It looks like the DLL is only loaded on first use. Is there a way to make this faster?

**Comment by JimBobSquarePants** [comment]
The Framework code yeah, not the new Core stuff?

When ImageProcessor first loads up it does a search through your referenced assemblies to look for pluggable file formats, it shouldn't be anywhere near as slow as that to initialize though. Does your application have a lot of references?

The relevant loading code code that does this code can be found [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/a1926cf01d77d09dc751c4d2cfd5871da7bf2da1/src/ImageProcessor/Common/Helpers/TypeFinder.cs#L58). Maybe we need to add a few more known assemblies to the exclusion list?

**Comment by mrfatmen** [comment]
Indeed the Framework code.
That could be it my application has a few dozen assemblies referenced.
Most of them are DevExpress.*, Google.*

I think if those get excluded too, it must go beter.

**Comment by JimBobSquarePants** [comment]
Yeah definitely. If you could list a couple I could add them, or PR?

**Comment by mrfatmen** [comment]
I you could just exclude all assemblies starting with DevExpress and Google it would be reduced very much.
![image](https://cloud.githubusercontent.com/assets/4401786/14887931/26ad62c2-0d58-11e6-9157-82db8a281098.png)

**Comment by JimBobSquarePants** [comment]
Cripes yeah! Will do.

**Comment by mrfatmen** [comment]
Can you tell when it will be availible as nuget package?

**Comment by JimBobSquarePants** [comment]
I've got a bit of work to do on the library before I can get a release out I'm afraid. You can see a list of open issues I need to clear out here.

https://github.com/JimBobSquarePants/ImageProcessor/milestones/Framework%20Consolidation

I'm hoping the community will step up and help.

**Comment by mrfatmen** [comment]
Hi Jim, Can you give a estimated release date?

**Comment by JimBobSquarePants** [comment]
The code is finished but I cannot release without updating the docs. I'm gonna do my best to get them done tonight.

**Comment by JimBobSquarePants** [comment]
New version now released :boom:
