### ISSUE TITLE
Watermark in Core

### ISSUE THREAD

**Issue by GVX111** [JimBobSquarePants/ImageProcessor#373]
When will be available watermark method in .NetCore?

**Comment by JimBobSquarePants** [comment]
As I explain in the readme under "Things that might never happen" Font support requires new code from Microsoft to be written before I can proceed. 

Reading and writing text to images is well outside my fields of expertise so I will need help from the developer community in order to make it happen. 

So to answer your question... Dunno.

**Comment by GVX111** [comment]
I want Image watermark no text watermark. at this stage in Core exists like this method?

**Comment by JimBobSquarePants** [comment]
My mum always used to say to me "I want never gets".

I'm hoping that this is just a language issue but you come across as quite demanding.

[Watermark](http://imageprocessor.org/imageprocessor/imagefactory/watermark/) in the original Framework code is specifically for text overlays there is a separate method called [Overlay](http://imageprocessor.org/imageprocessor/imagefactory/overlay/) which covers what you are describing.

We have a method in the Core code just now called [Blend](https://github.com/JimBobSquarePants/ImageProcessor/blob/719525a97c5dbb394ab78e39a37a855af28efd2e/src/ImageProcessorCore/Filters/ImageFilterExtensions.cs#L83) which could be used as the basis for a new method doing what you need. This won't come quickly though as there is still a lot of work required getting the basic operation functionality up to speed.

I'm building something brand new here and it's very complicated and difficult stuff to get right so I want to concentrate on the basics first. Then I shall try to copy over some of the original functionality from the Framework code.

This is all still very early days...
