### ISSUE TITLE
ImageCacheBase.IsExpired is incorrect?

### ISSUE THREAD

**Issue by kendallb** [JimBobSquarePants/ImageProcessor#374]
The function is currently written like so:

```
        protected virtual bool IsExpired(DateTime creationDate)
        {
            return creationDate.AddDays(this.MaxDays) < DateTime.UtcNow.AddDays(-this.MaxDays);
        }
```

however this is going to make the expiration date be 2x the value of MaxDays? So the default of 365 days means that cache items will not expire for exactly two years, not one. It should be written like this:

```
        protected virtual bool IsExpired(DateTime creationDate)
        {
            return creationDate < DateTime.UtcNow.AddDays(-this.MaxDays);
        }
```

**Comment by JimBobSquarePants** [comment]
I am absolutely blown away that no one has noticed this before; the code is so obviously wrong that I feel a little ashamed to have published it. Many, many thanks for picking up on it! 👍

**Comment by JimBobSquarePants** [comment]
Thanks for your help. New version now released :boom:
