### ISSUE TITLE
Limit available image sizes?

### ISSUE THREAD

**Issue by kendallb** [JimBobSquarePants/ImageProcessor#377]
For security purposes and to avoid someone running a nasty script against a site to generate all images in a zillion different sizes (with the intent to fill the disk and crash the server), I am wondering if it would make sense to have some kind of white list for allowed image sizes that can be generated? If the passed in width (and/or height) does not match the allowed values, the URL is rejected as a 404?

**Comment by JimBobSquarePants** [comment]
There's a property on the resize plugin called restrictTo that we can restrict sizes. There's actually a discussion about that scenario in a raised longstanding issue. You can see it here #49 (The important stuff is at the bottom)

**Comment by kendallb** [comment]
Interesting discussion and it touches on the same issues. I took a completely different approach for the way I did it and it might possibly make sense to move it upstream if you are interested. My approach is to filter the allowed widths (we don't allow heights) in the file image handler. I wrote my own code for this and hooked it into the IsValidRequest() function so that if it does not pass my test it simply throws a 404 so it is very cheap. The elements to control it live in the security configuration section which kinda makes sense, and it should be low impact.

Let me know if you like the idea of moving support for it into the official code.

**Comment by JimBobSquarePants** [comment]
In IImageService yeah? That's interesting, I'd like to see that. 

I'd much, much rather go the code over configuration route if possible but the API is quite creaky really, I designed the greater part of it over a weekend and I wish I could change most of it.

**Comment by kendallb** [comment]
This is the base class I use for my custom local and remote file image services. It is a bit hacky in that it has to look specifically at the query string, but really that is no different to looking at it through the query string hook anyway, since it all does the same thing. 

```
    public class BaseImageService
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public BaseImageService()
        {
            Settings = new Dictionary<string, string> {
                { "AllowedWidths", string.Empty },
            };
            Prefix = string.Empty;
            WhiteList = new Uri[] { };
        }

        /// <summary>
        /// Gets or sets the prefix for the given implementation.
        /// </summary>
        public string Prefix { get; set; }

        /// <summary>
        /// Gets or sets any additional settings required by the service.
        /// </summary>
        public Dictionary<string, string> Settings { get; set; }

        /// <summary>
        /// Gets or sets the white list of Uri's. Unused by this code.
        /// </summary>
        public Uri[] WhiteList { get; set; }

        /// <summary>
        /// Gets or sets any additional settings required by the service.
        /// </summary>
        protected int[] AllowedWidths
        {
            get
            {
                if (_allowedWidths == null) {
                    var allowed = new List<int>();
                    var widths = Settings["AllowedWidths"].Split(',');
                    foreach (var width in widths) {
                        int v;
                        if (int.TryParse(width, out v)) {
                            allowed.Add(v);
                        }
                    }
                    _allowedWidths = allowed.ToArray();
                }
                return _allowedWidths;
            }
        }
        private int[] _allowedWidths;

        /// <summary>
        /// Gets a value indicating whether the current request passes sanitizing rules.
        /// </summary>
        /// <param name="path">The image path.</param>
        /// <returns>True if the request is valid; otherwise false</returns>
        public bool IsValidRequest(
            string path)
        {
            // Make sure the path is a valid image extension
            if (!ImageHelpers.IsValidImageExtension(path)) {
                return false;
            }

            // Make sure we only have width in the query string
            var queryString = HttpContext.Current.Request.QueryString;
            var qWidth = queryString["width"];
            if (queryString.Count != 1 || qWidth == null) {
                return false;
            }
            int width;
            if (!int.TryParse(qWidth, out width)) {
                return false;
            }

            // Make sure the width is a valid value
            return AllowedWidths.Contains(width);
        }
    }
```

The config file looks like this:

```
        <service name="LocalImageService" type="Website.Images.LocalImageService, Website.Images">
          <settings>
            <setting key="AllowedWidths" value="100,200,400,475,1200"/>
          </settings>
        </service>
```

**Comment by JimBobSquarePants** [comment]
I ended up adding a new event `ValidatingRequest` which allowed all services to intercept requests plus restricted all processor. Available in the new release now.

**Comment by kendallb** [comment]
Awesome, I will give it a look see!
