### ISSUE TITLE
IImageService.IsValidRequest is called twice for each image URL

### ISSUE THREAD

**Issue by kendallb** [JimBobSquarePants/ImageProcessor#378]
This is first called inside the GetImageServiceForRequest() function (except for the case where it matches a service by request path prefix). Then it is called again later for the resource path, but this seems redundant to me? Is there some reason the second call is required?

**Comment by JimBobSquarePants** [comment]
I can't think of a scenario where we would need to call it twice. It's probably a hangover from refactoring. Will trace through and see why.

**Comment by kendallb** [comment]
Check it for the remote file service also as if will get called twice there as well on a different code path.

**Comment by JimBobSquarePants** [comment]
Does it... Bugger, Can you give me some line numbers.

**Comment by kendallb** [comment]
It all happens in GetImageServiceForRequest(). The first block of the code matches an image service on a prefix, but never calls IsValidRequest() at all. So I suspect the code in ProcessImageAsync() that you changed was originally added to make sure it got called for remote processing that matches a specific prefix. However for the local file service it calls it specifically and then for the last line:

`services.FirstOrDefault(s => string.IsNullOrWhiteSpace(s.Prefix) && s.IsValidRequest(path) && s.GetType() != typeof(LocalFileImageService));
`

it also calls it. So in the case where a custom IImageService is used, it will still get called twice again. 

I think the correct solution is to completely remove the call in ProcessImageAsync() that you modified, and instead put all the code to call IsValidRequest() entirely in GetImageServiceForRequest(). I originally was going to do that but I was not sure of the implications of changing that. But I have a better grasp on that now so I will attempt a fix in my tree and you can take a look at it.

**Comment by JimBobSquarePants** [comment]
Ah I see now. If it is a custom, unprefixed service we are still calling it twice.

The fix is trivial then:

``` csharp
    // Check whether the path is valid for other requests.
    // We've already checked the unprefixed requests in GetImageServiceForRequest().
    if (!string.IsNullOrWhiteSpace(currentService.Prefix) && !currentService.IsValidRequest(resourcePath.ToString()))
    {
        return;
    }
```

We need to call `IImageService.IsValidRequest` later on in the pipeline for requests with a prefix because we need to manipulate the url first to separate out the composite parts before sanitising.
