### ISSUE TITLE
Interlacing is not supported

### ISSUE THREAD

**Issue by Bartmax** [JimBobSquarePants/ImageProcessor#379]
When using a Png file I get this error:
```
ImageProcessorCore.ImageFormatException: Interlacing is not supported
```
some png works but some doesn't.

The code is here:
https://github.com/JimBobSquarePants/ImageProcessor/blob/abbf63f863635d4df1a04d322eccd425db7e82db/src/ImageProcessorCore/Formats/Png/PngDecoderCore.cs#L385

What does this mean? is this a limitation of the library or am I doing something wrong or a bug?

**Comment by JimBobSquarePants** [comment]
Hi @Bartmax 

It means exactly that. Png files can be interlaced but it is strongly recommended not to do that as it hurts compression, increasing filesize. 

See 

- http://stackoverflow.com/a/14124340/427899
- http://blog.codinghorror.com/getting-the-most-out-of-png/ 

Interlaced png files are generally uncommon so I haven't gone out of my way to support them cos it's complex. I could maybe add support in the future though as there is [good reference material](https://github.com/leonbloy/pngcs/blob/master/Hjg.Pngcs/PngDeinterlacer.cs) to base my code on so if you could share a failing image that would be really useful.

**Comment by Bartmax** [comment]
Thanks for the fast reply.

Here is a sample file that is failing. I have 3 out of 10 that seems to be interlaced :(

![546ce378-2bcf-4604-8338-91d9065727c4](https://cloud.githubusercontent.com/assets/3386797/15064484/31fc702c-132b-11e6-8bf9-1500c51e43f1.png)

**Comment by JimBobSquarePants** [comment]
No worries. I'll branch off and try to tinker with it. Fingers crossed it's not too difficult.

**Comment by JimBobSquarePants** [comment]
This is tricky stuff...

Reading up it looks like I need to decode each scanline 8 times. Which will require some significant refactoring here. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/7d28a87716e4b7c2dea73bc0fb804873d30372f6/src/ImageProcessorCore/Formats/Png/PngDecoderCore.cs#L242

I could really do with someone who has done this before stepping up and adding the code.

**Comment by MarcosMeli** [comment]
@JimBobSquarePants 
Just a little question here. There is an option to use the .Net native image load implementation and convert the resulting Bitmap to the format you need ?

ie. try to use custom decode for the pngs but, if interlaced, so use Bitmap constructor: https://msdn.microsoft.com/en-us/library/z7ha67kw(v=vs.110).aspx

Thanks

**Comment by dlemstra** [comment]
The library should build on .NET Core where we don't have the Image class of System.Drawing. Adding it to the encoder should be the way to go.

**Comment by MarcosMeli** [comment]
@dlemstra Thanks for clarification, I understand now.

**Comment by JimBobSquarePants** [comment]
This issue was moved to JimBobSquarePants/ImageSharp#9
