### ISSUE TITLE
Exif data isn't stripped unless a resize operation is taken

### ISSUE THREAD

**Issue by ctolkien** [JimBobSquarePants/ImageProcessor#383]
I'd hoped to put together a decent repro, until I can that done...

* Create a image factory with `preserveExifData` set to `false`
* Load an image source (I tested with a `stream`)
* Change the image quality
* Save the image out
* Newly saved image still has exif data.

If I throw a resize operation into the chain, then the exif data _is_ stripped.

**Comment by JimBobSquarePants** [comment]
Bit of an oversight on my part there. Didn't realise the data was getting copied. Fixed on dev for now anyway.

**Comment by JimBobSquarePants** [comment]
New version now released :boom:
