### ISSUE TITLE
No ability to set encoders (CCIT G4 gets changed to LZW)

### ISSUE THREAD

**Issue by neilw1** [JimBobSquarePants/ImageProcessor#389]
Hello,
1 bit CCITT T.6 (group 4) TIFF files are being auto converted to 32 bit LZW without any available option in the library to set compression or formats.

However, I've found the exact code that works on Stackoverflow and I guess could easily be added to the library to support saving of any available compression or format supported by .NET imaging library:
http://goo.gl/2MBvOo

thanks.

**Comment by JimBobSquarePants** [comment]
Hi there, 

I've just updated the code to allow the preservation of existing bit depth and also to change them. 

In order to not make too many breaking changes I'm defaulting the Tiff Compression to CCITT T.6 (group 4) for 1 bit images and LZW for anything else.

I'll be getting a release out soon.

**Comment by neilw1** [comment]
Cheers.

That was quick :)

I've actually just spotted an issue. Well with my code anyway. It came in
as lzw and I exported as ccitt g4. Then realised it converted all the greys
to black :)

Essentially color manipulation makes no sense to 1 bit

**Comment by JimBobSquarePants** [comment]
Yup, Yeah, you're not gonna get very far doing that. Thanks for raising the issue here anyway, it was a nice quick win. :beers:

**Comment by neilw1** [comment]
I did a workaround by showing the 32 but image and the to-be 1 bit image.

But I don't know if there's a bug in your old code but I cannot save 1 bit
images to a memory stream (using the code I pointed you at anyway), I get
an unsupported format error. As a workaround i've had to write the stream
to a file then load it back in in order to pick up the converted 1 but
image, if that makes any sense :)

**Comment by JimBobSquarePants** [comment]
There's probably a bug in the old stuff. I was doing something funky when copying images. I'll double check the stuff I just committed to ensure the image can still be loaded from a stream afterwards.

**Comment by JimBobSquarePants** [comment]
New version now released :boom:
