### ISSUE TITLE
bmp images with negative height produce Exception when decoding

### ISSUE THREAD

**Issue by pammann-work** [JimBobSquarePants/ImageProcessor#392]
Exception: array dimensions exceeded supported range
at: BmpDecoderCore.cs
float[] imageData = new float[this.infoHeader.Width * this.infoHeader.Height * 4];

due to negative this.infoHeader.Height

**Comment by pammann-work** [comment]
for negative height in bmp see here:
see http://www.drdobbs.com/architecture-and-design/the-bmp-file-format-part-1/184409517

**Comment by JimBobSquarePants** [comment]
Thanks for submitting a fix. I'll close this off now :smile:
