### ISSUE TITLE
bmp/gif save to stream will close the stream

### ISSUE THREAD

**Issue by pammann-work** [JimBobSquarePants/ImageProcessor#395]
MemoryStream ms = new MemoryStream();
image.SaveAsBmp(ms);

will lead to a closed memory stream

and this will then not work:

using (var dest = new FileStream(destFileName, FileMode.Create, FileAccess.Write, FileShare.None, bufferSize: 16384))
{
  ms.CopyTo(dest);
}
-> Exception: "Cannot access a closed Stream"

**Comment by JimBobSquarePants** [comment]
These are the kinds of thing unit tests miss and only real usage will catch. That' one of the reasons I'm running such a long alpha. Thank for this!
