### ISSUE TITLE
Image types

### ISSUE THREAD

**Issue by Mtahtaci** [JimBobSquarePants/ImageProcessor#397]
hi james , 

have you got an example code for figuring out the image type (jpg,png,svg,gif,bmp,....)  ?
i dont want to look at the file extension , bcs some files has wrong extensions (eg. File's codec is jpeg but extension is png)

**Update** : Image data coming from MemoryStream and i convert it to System.Drawing.Bitmap class.

**Update 2** : I will use this image for Resizing in ImageProcessor , (dont want to png files losing transparency and jpeg files losing quality)

Thanks in advice.

**Comment by JimBobSquarePants** [comment]
Hi @Mtahtaci,

I see you opened and closed this issue. Did you find what you are looking for?

Both libraries, ImageProcessor and ImageProcessorCore use the various file headers to identify what format the image is and use the correct encoders and decoders. If it's not a supported image format e.g. svg then they will throw an exception.

You will be able to query the loaded format by looking at the `CurrentImageFormat` property.

Cheers 

James
