### ISSUE TITLE
Crop the black part of the image

### ISSUE THREAD

**Issue by sreevishnu** [JimBobSquarePants/ImageProcessor#399]
I am using ImageFactory for resizing images. But for some images, black color padding appears. I saw suggestions mentioned in Git for this issue. But I see, I need a different behavior. I need to crop out the black padding if it's there. So how do we know there is a black padding ? And any method to crop it out ?

**Comment by JimBobSquarePants** [comment]
Hi @sreevishnu 

You should apply a different resize mode as per the documentation.

http://imageprocessor.org/imageprocessor/imagefactory/resize/

If you are changing the aspect ration it is most likely you want `ResizeMode.Crop`

Hope that makes sense.

James

**Comment by sreevishnu** [comment]
ResizeMode.Crop only crops the black part of the image ?+

**Comment by JimBobSquarePants** [comment]
Ah sorry, I thought you meant you want to prevent the black areas appearing on resize.

You mean detect the black areas and remove them? You might be able to do it using EntropyCrop 

http://imageprocessor.org/imageprocessor/imagefactory/entropycrop/

That might end up cropping more than you want though. Other than that there is nothing in the library.
