### ISSUE TITLE
Filesize bigger after resize

### ISSUE THREAD

**Issue by fabianScout** [JimBobSquarePants/ImageProcessor#400]
Related to #197 
I upload a jpg file with original file size 60kb(width of the img 1920px).
I resize the file to 1920px and 1200px. The resized 1920px file is 130kb and the 1200px file is 180kb?!

Set Gamma adjustment and upscale to false. I expect that the file size should be the same, 60kb or smaller.
Is there an explaination?

**Comment by JimBobSquarePants** [comment]
Hi @fabianScout 

It could be a multiple of factors really. Most likely though was that image was been encoded originally at a lower quality setting using a better encoder than the one offered in `System.Drawing`.

It's very odd that the 1200px wide one is larger than the 1920px wide one though. 

I would play about with the quality setting to see if that makes a difference but I doubt you will match 60kb as the Jpeg encoder offered with System.Drawing doesn't do chroma subsampling.

This is one of the many, many reason why I have been writing my own encoders.
