### ISSUE TITLE
Image zoom issue

### ISSUE THREAD

**Issue by sreevishnu** [JimBobSquarePants/ImageProcessor#401]
#If I try to resize a thumbnail image( for eg : 70x70) to a larger one, the image is getting zoomed. Instead I have to set the same image as is, to the larger canvas and make rest part as transparent. I don't see such an option in the documentation.

**Comment by JimBobSquarePants** [comment]
Hi @sreevishnu 

I really cannot determine from your issue what you are trying to do. 

Please.

- Tell me which library and which version you are using.
- Share a code sample of what you are doing.
- Show me an example of your image and your expected output.

**Comment by sreevishnu** [comment]
=> Tell me which library and which version you are using
        id="ImageProcessor" version="2.3.3.0"
=>  Share a code sample of what you are doing.

      ` `using (MemoryStream inStream = new MemoryStream(fileContent))
            {

                using (MemoryStream outStream = new MemoryStream())
                {
                    using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
                    {
                        imageFactory.Load(inStream);
                        if (imageFactory.Image.Height < size.Height || imageFactory.Image.Width < size.Width)
                        {
                            imageFactory.Resize(new ResizeLayer(size, ResizeMode.Pad))
                                      .BackgroundColor(Color.Transparent)
                                      .Quality(70)
                                      .Save(outStream);
                        }
                        else
                        {
                            imageFactory.Resize(new ResizeLayer(size, ResizeMode.Crop))
                                        .Quality(70)
                                        .Save(outStream);
                        }
                    }`



 => Show me an example of your image and your expected output.
**My Image**
![img-7](https://cloud.githubusercontent.com/assets/3965656/15711202/c0162088-282a-11e6-8601-0d662d5197b0.jpg)

**Expected Output**

![expected](https://cloud.githubusercontent.com/assets/3965656/15711310/15cb9cec-282b-11e6-8cff-8852ed9712b0.png)


Please note that the expected image is having a higher ratio(or say bigger canvas), but background color is white. The Source Image should be croped on a Size we provide and keep it in the Target at center (because the target is bigger, we should be able to keep the source image in center).

**Comment by JimBobSquarePants** [comment]
That's much better thanks. So you want this image as your output yes?
![](https://cloud.githubusercontent.com/assets/3965656/15711310/15cb9cec-282b-11e6-8cff-8852ed9712b0.png)

You probably want something like the following.

    imageFactory.Load(inStream);
    int height = imageFactory.Image.Height;
    int width = imageFactory.Image.Width;

    if (height < size.Height || width < size.Width)
    {
        imageFactory.Resize(new ResizeLayer(size, ResizeMode.Pad))
                    .BackgroundColor(Color.Transparent)
                    .Quality(70);
    }
    else
    {
        int dX = (width - size.Width) / 2;
        int dY = (height - size.Height) / 2;

        // ->                         left,top, width,      height
        CropLayer crop = new CropLayer(dX, dY, size.Width, size.Height, CropMode.Pixels);

        imageFactory.Crop(crop)

                    // If you wanted to then pad the image to a minimum size
                    // you would then use ResizeMode.BoxPad to increase the canvas area.
                    .Quality(70);
    }

**Comment by sreevishnu** [comment]
Now I wrote something like this
` imageFactory.Load(ImageToResize.ToStream(ImageFormat.Jpeg));
                        if (imageFactory.Image.Height < size.Height || imageFactory.Image.Width < size.Width)
                        {
                            imageFactory.Resize(new ResizeLayer(new Size(imageFactory.Image.Height, imageFactory.Image.Height), ResizeMode.Crop))
                                      .Resize(new ResizeLayer(size, ResizeMode.BoxPad))
                                      .BackgroundColor(Color.Transparent)
                                      .Quality(70)
                                      .Save(outStream);
                        }
                        else
                        {
                            imageFactory.Resize(new ResizeLayer(size, ResizeMode.Crop))
                                        .Quality(70)
                                        .Save(outStream);
                        }`

Got the output like

![img-7-resized-70](https://cloud.githubusercontent.com/assets/3965656/15712715/057c64ba-2831-11e6-8a17-d26454235ef8.jpg)


the background color is not transparent :(

**Comment by JimBobSquarePants** [comment]
Jpeg's don't support transparency. They don't have an alpha channel.

**Comment by sreevishnu** [comment]
ah...I really forget that! :D

**Comment by JimBobSquarePants** [comment]
I forget myself sometimes :smile: Change the format to png for transparency

**Comment by sreevishnu** [comment]
I done like
`Image ResizedImage = Image.FromStream(outStream);
                    ResizedImage.Save($@"MyPath/imageResized.png", ImageFormat.Png);`

but still transperency is not working.

Is there any way to do it via ImageFactory ?

**Comment by JimBobSquarePants** [comment]
Yeah

    .Format(new PngFormat())

http://imageprocessor.org/imageprocessor/imagefactory/format/

**Comment by sreevishnu** [comment]
Yup, that makes my life easier :)

**Comment by JimBobSquarePants** [comment]
Excellent! If you have everything please close the issue. I'm very glad I could be of help.

**Comment by sreevishnu** [comment]
Sure, I'll close the issue. Great help Jim! Thank you very much :)
