### ISSUE TITLE
Pre release of ImageProcessorCore on NuGet.org?

### ISSUE THREAD

**Issue by michielpost** [JimBobSquarePants/ImageProcessor#402]
With RC2 now available and ASP.net Core RTM in just a few weeks, are there any plans to publish a ImageProcessorCore package to the official nuget.org feed?

I know there's already a MyGet feed and using that currently. But it would help if the (pre release) package is also available on NuGet. Using it in more projects would be easier.

The readme says "when ready", but a pre release on NuGet, even if it's not fully ready yet, would also be useful.

**Comment by JimBobSquarePants** [comment]
Hi there, 

I'm loath to do so just now as I really haven't had enough feedback from the community as to the shape of the API and some of the core work. If I put it on Nuget, even in pre, people are going to use it in production environment despite me telling them not to. 

I keep asking for code reviews in various forums but I simply am not getting any constructive feedback. Once I finally have some and know that I am doing the right thing then I can move to beta which I would be much happier deploying to Nuget. 

I must ask though, why would adding it to Nuget make it easier? Surely you simply add the url to your Nuget.config file?

**Comment by michielpost** [comment]
Yes, if you really don't want people to use it in production yet, then not putting it on NuGet is probably the best idea.

We're currently only using it for getting the size of an Image and will start using resizing soon.

Adding it to the NuGet.config is pretty simple yes. But using a CI feed for a stable project feels wrong, but maybe that's exactly what you want :)

**Comment by JimBobSquarePants** [comment]
Ooh er! I wouldn't go so far as saying it's stable yet ☺. I keep changing and adding API calls, it's only 2 months ago I switched to IDisposable also. 

I do really need devs to start digging around in the code and double checking my approach. For all I know it could be idiotic as there's nothing out there to compare against.

**Comment by piehouserat** [comment]
Hi James,

Have you seen this project? https://github.com/imazen/imageflow

They seem to imply that the vast majority of other on-the-fly image manipulation frameworks are full of security holes and have performance issues. Might be worth having a look to see if they've actually got something there or have a laugh at their claims...

**Comment by JimBobSquarePants** [comment]
Yeah, I know the guy who writes it, we share code and ideas all the time. 

He's actually correct, many of the libraries out there suffer from either or both issues. I work very hard to ensure I suffer from neither.

**Comment by piyushchauhan2011** [comment]
Hey @JimBobSquarePants , I actually used this package which is same `imageprocessorcore` but don't know why it's published using different namespace [https://www.nuget.org/packages/Ngonzalez.ImageProcessorCore/](https://www.nuget.org/packages/Ngonzalez.ImageProcessorCore/).

Also, it works really good, and on nuget it's not listed `1.0.0` but that guy released it as `1.0` because when I installed in `project.json` and ran the simple grayscale example you listed in the README.

It would be good to release it even an alpha because we can try and run, much needed functionality like JPEG, GIF, BMP or other format decoding and encoding is working perfectly and can be utilised to build upon that for image processing operations. I may even suggest to break it into separate module or namespace and release it as stable on nuget so that other people can build upon that.

Thanks 💯  for good continuous effort in core community 😄

**Comment by JimBobSquarePants** [comment]
Hi @piyushchauhan2011 thanks for your support. 

Please don't use the package you linked to. I'm actually pretty angry that they did that and will be contacting them to ask them to ask them to unlist the library. If you want to use ImageProcessorCore use it with the MyGet feed as described above. 

Whilst it works in your scenario, the library is not production ready yet. We are still working on fundamental core components. 

Cheers 

James

**Comment by vdachev** [comment]
@JimBobSquarePants I guess that's also true for this package:
https://www.nuget.org/packages/ChyImageProcessorCore/1.0.0-alpha1031 ?

**Comment by JimBobSquarePants** [comment]
Thanks @vdachev I'll be in touch with them also.

**Comment by michielpost** [comment]
There's probably no stopping to this. People want the package on NuGet.org, and it's open source, you can fork it, make your own release and put it on NuGet.
If you put the package on NuGet yourself, at least you have control.

**Comment by JimBobSquarePants** [comment]
@michielpost The thing is though they have no valid reason to do so and are only creating work for themselves. I'm creating builds for every push just now so anything they post will become horribly out of date. 

They're also linking directly to my repo which means people will come to me looking for support which I cannot possibly give.  That adds work for me as I have to then tell these developers not to use those packages. It's incredibly poor form.

I'm not going to put the package on Nuget until I am out of alpha. There is a MyGet feed, that is easily addable to Nuget.Config files, 85k+ downloads have been done so far so most people seem to have figured it out.
