### ISSUE TITLE
Center an Image for Blend

### ISSUE THREAD

**Issue by Feasoron** [JimBobSquarePants/ImageProcessor#403]
If I am blending two images, say to add a logo to the middle of an image, it should be possible to  move the second image before blending. For example, if I am doing something like:

```
private Image ApplyWatermark(ImageBase image, int percent)
{
    var logo = LoadImageFromFile(_imagePath + "wm_logo.png");
    return watermark..Blend(logo, percent);
}
```

I would like to center it, rather than upper left hand corner. It is possible that that is what the version with Rectangle does, but reading the code and documentation I can't determine how it should be used.

**Comment by JimBobSquarePants** [comment]
Took me a moment to realise you meant the new Core stuff there...

The overload with the rectangle means to only blend the certain part of the given image constrained by the given rectangle.

If you wanted to centre your watermark image you could use the Pad(width, height) method to pad the image out to the same size as its target. 

```
private Image ApplyWatermark(ImageBase image, int percent)
{
    var logo = LoadImageFromFile(_imagePath + "wm_logo.png").Pad(image.Width, image.Height);
    return image.Blend(logo, percent);
}
```

Hope that helps

James

**Comment by Feasoron** [comment]
That does! Sorry for not being more clear in my question, but that's doing exactly what I need now. I love the work you've done with this project - I know from experience porting to core is no small task.

**Comment by JimBobSquarePants** [comment]
That's great to hear! 😄 Yeah, this is certainly a massive learning experience.
