### ISSUE TITLE
System.AccessViolationException doing a Resize

### ISSUE THREAD

**Issue by corneliutusnea** [JimBobSquarePants/ImageProcessor#404]
Hi guys,

I'm getting an 'System.AccessViolationException' doing a resize of a JPG about 400k in size.

Crash is at ImageBase:153.
```
return *((Color*)(this.pixelsBase + ((y * this.Width) + x) * 4));
```

Original image size: 1306x979. New Image size: 200x200 with Pad.

Resize code is:
```
   image.BackgroundColor(Color.RebeccaPurple); // << it works if I comment this line out!
    var result = image.Resize(new ResizeOptions()
    {
        Size = new Size(200, 200),
        Mode = ResizeMode.Pad,
        Compand = true
    });
```

**Comment by JimBobSquarePants** [comment]
Hi there, what version number are you running from myget? Would it be possible to share the image?

**Comment by corneliutusnea** [comment]
I tried with 1.0.0-alpha-860 from nuget and with latest source code straight from GH.
Any larger image will do. The issue I think is the dispose in ImageExtensions:169.
Code is disposing the incoming source object that is now owned by your method but it's the one I own so you should not be disposing it.
That happens at the end of the image.BackgroundColor() call. Then the second call to image.Resize is basically working on a disposed image.

The general rule of Disposing is that you never dispose what you don't specifically created yourself and you don't need. Never dispose incoming objects. It's the callers responsibility to dispose both the source and the result of the BackgroundColor.

I think the confusion is that the BackgroundColor method returns a new Image. I expected it to modify the existing one.

**Comment by JimBobSquarePants** [comment]
Bugger... This is tricky... Every method returns a new image.

I'm making a copy so that if something goes wrong the original pixels can be returned. This is done throughout. If I don't dispose of the source then I get a memory leak as I create more and more copies.

I'll have to rethink this. Good thing it's alpha :smile:

**Comment by JimBobSquarePants** [comment]
@corneliutusnea That should be it fixed now. I need to do some research into how long the unmanaged pixels are held onto within the original source image before the GC collector kicks in though so if you have any advice on that please let me know.

**Comment by corneliutusnea** [comment]
@JimBobSquarePants How long they stay in memory depends mostly on GC pressure and the type of GC. If you want to do a quick test use nbench to whip a memory pressure test https://github.com/petabridge/NBench

I've been thinking a lot about this if you should always return a new image or you should always edit the current image and there are some pros&cons.

Let's see if I get them right, and maybe that should drive the decision of how to fix the api:
### Never return a new image

1. Pro: Potentially less memory pressure as lots of operations could be done "in place" on the current image
1. Pro: You can have a nice fluid API without worry of memory leaks .ApplyBackgroundColor().Resize().Crop()....
1. Some algorithms might have to apply a pattern of copy/edit/replace but that's all hidden from external users
1. Cons: Might confuse some users as why you change their existing image. Can be easily fixed through documentation.
1. Cons: You'd need to clone/duplicate the image if you want to use it in separate operations. E.g. Resize one image to 4 different other sizes. You'd need to duplicate 4 times. Is this a worry?

### Always return a new image:

1. Pro: Every image is readonly. Can be good in some scenarios.
1. Cons: Increased memory usage. Every operation is a new image.
1. Cons: You can't have a fluid API without serious memory pressure and risk of forgetting to cleanup.

I'm not sure what else to add to this list but I think the best would be to _never return new image_ unless specifically asked by a Clone method or through copy constructors.
Always return "this" and always process on the current image.
If you need to allocate a new underlying image internally, that's fine, but by the time the call is finished clean-up and still return this.

**Comment by JimBobSquarePants** [comment]
Thanks for that, all good stuff. 

The approach I'm trying to take is to return what becomes to the user, the same image but altered, internally switching out the image for a new one. There's a few places I could return the same image without switching but I will have to do some work to redefine filters and samplers within the framework. (I'm defining filters as anything that can operate on an image without requiring a new one to be created.) 

I'll have a look at NBench asap.
