### ISSUE TITLE
Issue with animationprocessmode

### ISSUE THREAD

**Issue by azzlack** [JimBobSquarePants/ImageProcessor#405]
Every time animationprocessmode is added to the url, the query fails with a `The request could not be understood by the server due to malformed syntax` message. This happens whether the value is set to `first` or `all`.

It works perfectly with other queries like `width` or `height`, but `animationprocessmode` seems to crash the request.

Here is the full error:
```
[HttpException (0x80004005): The request /media/1070/spans_aften.jpg?animationprocessmode=all could not be understood by the server due to malformed syntax.]
   ImageProcessor.Web.HttpModules.<ProcessImageAsync>d__32.MoveNext() +5399
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +184
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +70
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +166
```

and here is my config

```xml
<cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
  <settings>
	<setting key="CachedStorageAccount" value="***" />
	<setting key="CachedBlobContainer" value="cache" />
	<setting key="UseCachedContainerInUrl" value="true" />
	<setting key="CachedCDNRoot" value="http://az790501.vo.msecnd.net/" />
	<setting key="SourceStorageAccount" value="***" />
	<setting key="SourceBlobContainer" value="media" />
	<setting key="StreamCachedImage" value="true" />
  </settings>
</cache>
```
```xml
<service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
  <settings>
	<setting key="MaxBytes" value="8194304" />
	<setting key="Timeout" value="30000" />
	<setting key="Host" value="http://panoramahotel.blob.core.windows.net/media/" />
  </settings>
</service>
```

**Comment by JimBobSquarePants** [comment]
> `/media/1070/spans_aften.jpg?animationprocessmode=all`

Why would you ever want to use that method with a jpg? `animationprocessmode` was never designed to be used on it's own and is specifically designed to be used when manipulating animated gifs to extract only the first frame for rendering.

**Comment by JimBobSquarePants** [comment]
Requesting `animationprocessmode=all` is essentially a noop since that is the default behaviour for animated gifs. However, I'm going to allow it on its own in the release along with `animationprocessmode=first`.

**Comment by JimBobSquarePants** [comment]
I've just popped out a release that fixes your issue. https://www.nuget.org/packages/ImageProcessor.Web/4.6.1

**Comment by azzlack** [comment]
@JimBobSquarePants Thanks! I agree that it is unecessary for a jpg(png, but in this particular case I don't know the file type beforehand.

**Comment by JimBobSquarePants** [comment]
No worries. Thanks for raising the issue :smile:

**Comment by perosb** [comment]
I'm getting the same error on gifs with the below
`/media/3549/giphy.gif?anyparamhere`
I'm I missing some new configuration? I have the latest 4.6.1 and the default "enabled".
This works on a 4.5.3 version.

**Comment by JimBobSquarePants** [comment]
@perosb  Please don't hijack issues unless you have the exact same symptoms.

    /media/3549/giphy.gif?anyparamhere

Is this your url? How am I supposed to diagnose anything from that?
