### ISSUE TITLE
Quality for png files is not working

### ISSUE THREAD

**Issue by Vitalii-Efremov** [JimBobSquarePants/ImageProcessor#406]
Hello!

I used quality attribute for png files and It increased the file size.

For example, I have the original png image and this image has 1.7 Mb size. I set a quality attribute to 85 and ImageProcessor produced the file which has 2.0 Mb.

Original file (1.7 Mb)
![orginal](https://cloud.githubusercontent.com/assets/16013311/16073873/3e2f727c-32e8-11e6-85fc-7980a079b0bc.png)

Compressed file (2.0 Mb)
![compressed](https://cloud.githubusercontent.com/assets/16013311/16073892/501187e6-32e8-11e6-9369-74e3dad5710c.png)

`public class ImageOptimizationService : IImageOptimizationService
    {
        public byte[] Optimize(byte[] image, string contentType, int quality)
        {
            var format = GetImageFormat(contentType);       
            format.Quality = quality;

            byte[] result = null;

            using (MemoryStream inStream = new MemoryStream(image))
            {
                using (MemoryStream outStream = new MemoryStream())
                {
                    // Initialize the ImageFactory using the overload to preserve EXIF metadata.
                    using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
                    {
                        // Load, resize, set the format and quality and save an image.
                        imageFactory.Load(inStream)
                                    .Format(format)
                                    .Save(outStream);
                    }
                    result = outStream.ToArray();
                    // Do something with the stream.
                }
            }
            return result;
        }

        private ISupportedImageFormat GetImageFormat(string contentType)
        {
            switch (contentType)
            {
                case "image/gif": return new GifFormat();
                case "image/jpeg": return new JpegFormat();
                case "image/png": return new PngFormat();
                default: return new PngFormat();
            }
        }`

**Comment by JimBobSquarePants** [comment]
Png files in System.Drawing have no concept of quality so this has no effect. I actually specify in the documentation that this method is for jpeg files only.

http://imageprocessor.org/imageprocessor/imagefactory/quality/

**Comment by JimBobSquarePants** [comment]
The png encoder in System.Drawing also doesn't allow you to set the compression which is why images can sometimes be bigger.

**Comment by Vitalii-Efremov** [comment]
Thank you, James!

Please, give me advice how I can compress png images. You are the pro in this questions, maybe you know some other libraries which can help me to compress png images.

**Comment by JimBobSquarePants** [comment]
Hey @Vitalii-Efremov  Apologies for the slow reply, I was travelling out of the country. 

Yeah, there's [pngquant](https://pngquant.org) which you could use. I actually have source code showing how to call it from the command line in my postprocessor plugin.

https://github.com/JimBobSquarePants/ImageProcessor/blob/4c030bfa70ef58e212335269ea1311b5191efe5a/src/ImageProcessor.Web.Plugins.PostProcessor/Resources/Unmanaged/x86/png.cmd
