### ISSUE TITLE
ImageProcessor Unit Tests Fail on 'Framework' branch

### ISSUE THREAD

**Issue by DermotAtPimss** [JimBobSquarePants/ImageProcessor#407]
Hello,

I believe that the current version of ImageProcessor available via NuGet is from the 'Framework' branch. 

Forgive me if I am wrong. 

I have cloned the repository and switched to the Framework branch and tried running the unit tests in the 'ImageProcessorUnitTests' project. Three Unit Tests fail. 

When I try to run the test 'ResizeIsApplied' on its own, this test also fails.

`System.ArgumentException : Parameter is not valid.
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at ImageProcessor.Imaging.Formats.FormatBase.Load(Stream stream) in E:\ImageProcessor\src\ImageProcessor\Imaging\Formats\FormatBase.cs:line 87
   at ImageProcessor.ImageFactory.Reset() in E:\ImageProcessor\src\ImageProcessor\ImageFactory.cs:line 421
   at ImageProcessor.UnitTests.ImageFactoryUnitTests.ResizeIsApplied() in E:\ImageProcessor\tests\ImageProcessor.UnitTests\ImageFactoryUnitTests.cs:line 1034
`

This is the failure I am really interested in because it seems to be the same error I am experiencing in a section of code in a web site we are developing
![imageprocessorbug1](https://cloud.githubusercontent.com/assets/18266008/16111623/43a4a74a-33ab-11e6-89cf-3e09319583bc.png)
![imageprocessorbug2](https://cloud.githubusercontent.com/assets/18266008/16111622/43a34210-33ab-11e6-860a-1823877ac2f4.png)

**Comment by JimBobSquarePants** [comment]
Hi there,

It's an odd one... I recently updated Nunit and since then I get intermittent failing tests when I run them all the same time. If I rerun any of those tests they always pass.

![tests](https://cloud.githubusercontent.com/assets/385879/16112322/38f154fc-33fa-11e6-9817-3d10edc5e111.png)

I'd like to see that section of failing code you have written if I can. System.Drawing doesn't return the most helpful of error messages when something goes wrong so it's difficult to debug.

**Comment by DermotAtPimss** [comment]
Hi James,

Attached is the skeleton of a console application prototyping a requirement that an uploaded image should be no greater than 1Mb.

It is using the ImageFactory to perform a number of resizes and only fails with Gifs.


[Program.cs.txt](https://github.com/JimBobSquarePants/ImageProcessor/files/318186/Program.cs.txt)

**Comment by JimBobSquarePants** [comment]
Thanks. I'll have a look as soon as possible :smile:

**Comment by JimBobSquarePants** [comment]
Hi @DermotAtPimss I had a dig around and discovered two issues, one with the unit tests themselves and one with the the `Reset()` method on `ImageFactory` I just ran your code with the current  codebase on the Framework branch and all is good. I'll have a new release out soon.

**Comment by JimBobSquarePants** [comment]
Fixed and released. Thanks for raising the issue.
