### ISSUE TITLE
ImageBase API design and unmanaged memory.

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#408]
This issue stems from #404 

In the current codebase the `ImageBase` class implements the `IDisposable` interface combined with  `GCHandle` to pin the pixels array in memory for the lifetime of the image. You can see that code [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/16779a3ac82e4d9ca67d4b9dd318b443c12e0949/src/ImageProcessorCore/IImageBase.cs).

This has been done in order to allow accessing the individual colors using pointers to vastly increase performance (~44%) over a managed equivalent of the class. 

Now this approach causes me a little worry about the unmanaged resources for a few reasons.

1. I Keep the pixels pinned for the lifetime of the image. I don't know how that will affect performance on a server.
2. I don't know how long unmanaged references are kept in memory when you assign a new image to an existing reference. See the [example code](https://github.com/JimBobSquarePants/ImageProcessor/blob/16779a3ac82e4d9ca67d4b9dd318b443c12e0949/src/ImageProcessorCore/ImageExtensions.cs#L169) where I reassign an image without disposing.
3. I don't even know for sure whether I can get away without disposing. AFAIK there's no guarantee that a finalizer will get called.

So what are my options?

1. Go back to using a managed pixel array (Too slow - Infeasible)
2. Explicitly add a Lock/Unlock method (Developers recognise `IDisposable` and might forget to Unlock)
3. Continue as is if it is ok
4. Something else...

Any input is most welcome. This is a fundamental part of the API.

**Comment by SamuelEnglard** [comment]
First let me answer your 3 questions:

1. I hate to use the line but... "It depends"
2. The unmanaged references are around till you get rid of them aka till `Dispose` is called. If you don't call it something else either has to or it will be around till the process dies.
3. There are really only two reasons a finalizer will not be called: The process exited before it could, in which case the memory is released anyways; Or another finalizer get's stuck in an infinite loop, in which case the process is in real trouble anyways.

**Comment by JimBobSquarePants** [comment]
Thanks for the input. I look forward to seeing what else you can add :+1:

**Comment by xoofx** [comment]
In an old project [SharpDX.Toolkit](https://github.com/sharpdx/Toolkit), I used an [Image](https://github.com/sharpdx/Toolkit/blob/master/Source/Toolkit/SharpDX.Toolkit.Graphics/Image.cs) class and It was basically manipulating only a pointer to a buffer (managed or unmanaged).

Typically, if it was initialized with a managed byte[] buffer bigger than 85Ko, the buffer was pinned, otherwise it was copied to an unmanaged memory (see for example [here](https://github.com/sharpdx/Toolkit/blob/master/Source/Toolkit/SharpDX.Toolkit.Graphics/Image.cs#L487)). It is usually bad to pin managed buffers smaller than 85Ko, as you could start to fragment the gen0 memory or annoy the GC as it could not move the buffer from/to gen1/gen2.

On `Image.Dispose()` the unmanaged memory was released or the pinned buffer released.

The buffer was then accessed through a [PixelBuffer](https://github.com/sharpdx/Toolkit/blob/master/Source/Toolkit/SharpDX.Toolkit.Graphics/PixelBuffer.cs)

The main difference maybe with ImageProcessor (though, don't know in details) is that the `Image` from SharpDX was supposed also to interop easily with GPU hardware buffer which can have a different buffer width/stride not equal to the pixel width, so the denominator of unmanaged memory was better. Also it was necessary to handle mipmaps.

Also, just looking at `IImageBase` (but sorry, again, I haven't looked at the rest of the code! So that might be not relevant), be careful that interface calls are costly, so usually you want to avoid them. Moreover, you usually want the get/set pixels to be inlined to the client.

**Comment by SamuelEnglard** [comment]
It's 12:33 AM here so take my advice with a grain of salt.

I would move all manipulation into it's own class that implements `IDisposable` and remove both `IDisposable` and the pinning from `ImageBase`. Then to manipulate an image you call `GetManipulator()` which returns this manipulation class. When it's created it pins the memory and needs to be disposed and has a finalizer.

Advantage to this is even if the developer forgets to dispose, the finalizer will be called sooner allowing the memory to be unpinned and moved around again if needed.

**Comment by JimBobSquarePants** [comment]
Hi @xoofx,

Thanks for the info, that's very interesting to note. I didn't know about the size constraints. 

I've not designed the API to interop with any GPU hardware (That's well outside my field of expertise) so I'm only expecting a single pixel format once I have decoded an image. It's a bit of a closed system really. 

As far as the `IImageBase` interface is concerned, I only put that in there for potentially improved testing but since I don't actually use it anywhere it really has no need to exist. 

>Moreover, you usually want the get/set pixels to be inlined to the client.

By that do you mean that should be set within the `Image` class? If so, I actually have two classes `Image` and `ImageFrame` that inherit from `ImageBase` so using the indexer in the base fits well there.

**Comment by JimBobSquarePants** [comment]
@SamuelEnglard I see what you're thinking there. A bit like my Lock/Unlock idea but using an `IDisposable` instance. That could work but kinda disassociates pixel manipulation from the image itself. I want to keep the API really simple.

**Comment by SamuelEnglard** [comment]
@JimBobSquarePants I get that want but I think the cost is worth it, IMHO 😄

**Comment by JimBobSquarePants** [comment]
@xoofx @SamuelEnglard I'd like to thank you both very much for your input. I think I have this cracked now. 

I'm introducing a new class called [`PixelAccessor`](https://github.com/JimBobSquarePants/ImageProcessor/blob/9b7174022ac6745534acff3ed69718d143e91e6f/src/ImageProcessorCore/PixelAccessor.cs) which pins the image array allowing access to the pixels like the `ImageBase` class did before.

Using it is as follows:

``` c#
protected override void Apply(
    ImageBase target,
    ImageBase source,
    Rectangle targetRectangle,
    Rectangle sourceRectangle,
    int startY,
    int endY)
{
    int targetY = targetRectangle.Y;
    int targetBottom = targetRectangle.Bottom;
    int startX = targetRectangle.X;
    int endX = targetRectangle.Right;
    int sourceX = sourceRectangle.X;
    int sourceY = sourceRectangle.Y;

    using (PixelAccessor sourcePixels = source.Lock())
    using (PixelAccessor targetPixels = target.Lock())
    {
        Parallel.For(
            startY,
            endY,
            y =>
                {
                    if (y >= targetY && y < targetBottom)
                    {
                        for (int x = startX; x < endX; x++)
                        {
                            targetPixels[x, y] = sourcePixels[x + sourceX, y + sourceY];
                        }

                        this.OnRowProcessed();
                    }
                });
    }
}
```

This allows me to keep the pixels pinned only when I need them to be which should make memory management much easier. If there are any improvements you can offer please let me know.

**Comment by JimBobSquarePants** [comment]
Gonna close this for now.

**Comment by JimBobSquarePants** [comment]
@xoofx I have a question if I may about memory alignment. 

I've just realized in my code that I am not actually copying the array if the buffer size is less than 85 within my PixelAccessor.

I've had a dig through SharpDX to see how best to do this but I can't wrap my head around the memory alignment stuff.

https://github.com/sharpdx/SharpDX/blob/e4e820ea5d1fcd98fe4199be299b5de4831d6758/Source/SharpDX/Utilities.cs#L447

I'm currently working with floats rather than bytes so does that mean the alignment should be 4X the size? I'm no CS guy so it's a steep learning curve.

**Comment by xoofx** [comment]
Memory alignment is not really a requirement, so you don't have to worry much about it. It helps mostly to ensure that pixels will fit into the same L1 cache line and don't cross over. It can help also for SIMD access that can be faster if data is aligned on a 16 bytes boundary. But recent processors will often hide the problem, so you could not notice an impact of it (but it can happen in some  memory access patterns)
Also, as you are working with managed buffers, you cannot really control it, so...

**Comment by JimBobSquarePants** [comment]
@xoofx Thanks for that.... I've been trying for a wee while now to get the allocation and copying working but it doesn't seem to be working could you give me some pointers (pun intended :smile:).

```
/// <summary>
/// Provides per-pixel access to an images pixels.
/// </summary>
public sealed unsafe class PixelAccessor : IDisposable
{
    /// <summary>
    /// Whether the pixels are copied.
    /// </summary>
    private readonly bool copied;

    /// <summary>
    /// The position of the first pixel in the bitmap.
    /// </summary>
    private float* pixelsBase;

    /// <summary>
    /// Provides a way to access the pixels from unmanaged memory.
    /// </summary>
    private GCHandle pixelsHandle;

    /// <summary>
    /// A value indicating whether this instance of the given entity has been disposed.
    /// </summary>
    /// <value><see langword="true"/> if this instance has been disposed; otherwise, <see langword="false"/>.</value>
    /// <remarks>
    /// If the entity is disposed, it must not be disposed a second
    /// time. The isDisposed field is set the first time the entity
    /// is disposed. If the isDisposed field is true, then the Dispose()
    /// method will not dispose again. This help not to prolong the entity's
    /// life in the Garbage Collector.
    /// </remarks>
    private bool isDisposed;

    /// <summary>
    /// Initializes a new instance of the <see cref="PixelAccessor"/> class.
    /// </summary>
    /// <param name="image">
    /// The image to provide pixel access for.
    /// </param>
    public PixelAccessor(ImageBase image)
    {
        Guard.NotNull(image, nameof(image));
        Guard.MustBeGreaterThan(image.Width, 0, "image width");
        Guard.MustBeGreaterThan(image.Height, 0, "image height");

        int length = image.Pixels.Length;
        int size = length * 4;
        this.Width = image.Width;
        this.Height = image.Height;

        // Disabled for testing.
        // Assign the pointer.
        // If buffer is allocated on Large Object Heap i.e > 85Kb, then we are going to pin it instead of making a copy.
        //if (size > 87040)
        //{
        //    this.pixelsHandle = GCHandle.Alloc(image.Pixels, GCHandleType.Pinned);
        //    this.pixelsBase = (float*)this.pixelsHandle.AddrOfPinnedObject().ToPointer();
        //}
        //else
        //{
        fixed (float* pbuffer = image.Pixels)
        {
            // TODO: This isn't actually copying. 
            // We need to allocate and copy the pixels into unmanaged memory.
            // Will need to research how to do this.
            this.pixelsBase = (float*)AllocateMemory(size);
            float* ps = pbuffer;
            float* pt = this.pixelsBase;
            for (int i = 0; i < length; i++)
            {
                *pt = *ps;
                pt++;
                ps++;
            }
        }

        this.copied = true;
        //}
    }

    /// <summary>
    /// Finalizes an instance of the <see cref="PixelAccessor"/> class. 
    /// </summary>
    ~PixelAccessor()
    {
        this.Dispose();
    }

    /// <summary>
    /// Gets the width of the image.
    /// </summary>
    public int Width { get; }

    /// <summary>
    /// Gets the height of the image.
    /// </summary>
    public int Height { get; }

    /// <summary>
    /// Gets or sets the color of a pixel at the specified position.
    /// </summary>
    /// <param name="x">
    /// The x-coordinate of the pixel. Must be greater
    /// than zero and smaller than the width of the pixel.
    /// </param>
    /// <param name="y">
    /// The y-coordinate of the pixel. Must be greater
    /// than zero and smaller than the width of the pixel.
    /// </param>
    /// <returns>The <see cref="Color"/> at the specified position.</returns>
    public Color this[int x, int y]
    {
        get
        {
#if DEBUG
            if ((x < 0) || (x >= this.Width))
            {
                throw new ArgumentOutOfRangeException(nameof(x), "Value cannot be less than zero or greater than the bitmap width.");
            }

            if ((y < 0) || (y >= this.Height))
            {
                throw new ArgumentOutOfRangeException(nameof(y), "Value cannot be less than zero or greater than the bitmap height.");
            }
#endif
            return *((Color*)(this.pixelsBase + (((y * this.Width) + x) * 4)));
        }

        set
        {
#if DEBUG
            if ((x < 0) || (x >= this.Width))
            {
                throw new ArgumentOutOfRangeException(nameof(x), "Value cannot be less than zero or greater than the bitmap width.");
            }

            if ((y < 0) || (y >= this.Height))
            {
                throw new ArgumentOutOfRangeException(nameof(y), "Value cannot be less than zero or greater than the bitmap height.");
            }
#endif
            *(Color*)(this.pixelsBase + (((y * this.Width) + x) * 4)) = value;
        }
    }

    /// <summary>
    /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
    /// </summary>
    public void Dispose()
    {
        if (this.isDisposed)
        {
            return;
        }

        if (this.pixelsHandle.IsAllocated)
        {
            this.pixelsHandle.Free();
        }

        if (this.copied)
        {
            FreeMemory((IntPtr)this.pixelsBase);
        }

        this.pixelsBase = null;

        // Note disposing is done.
        this.isDisposed = true;

        // This object will be cleaned up by the Dispose method.
        // Therefore, you should call GC.SuppressFinalize to
        // take this object off the finalization queue 
        // and prevent finalization code for this object
        // from executing a second time.
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Allocate an aligned memory buffer.
    /// </summary>
    /// <param name="size">Size of the buffer to allocate.</param>
    /// <param name="align">Alignment, 16 bytes by default.</param>
    /// <returns>A pointer to a buffer aligned.</returns>
    /// <remarks>
    /// To free this buffer, call <see cref="FreeMemory"/>.
    /// </remarks>
    private static IntPtr AllocateMemory(int size, int align = 16)
    {
        int mask = align - 1;
        IntPtr memPtr = Marshal.AllocHGlobal(size + mask + IntPtr.Size);
        long ptr = (long)((float*)memPtr + sizeof(void*) + mask) & ~mask;
        ((IntPtr*)ptr)[-1] = memPtr;
        return new IntPtr((void*)ptr);
    }

    /// <summary>
    /// Frees an allocated an aligned memory buffer.
    /// </summary>
    /// <param name="alignedBuffer">The aligned Buffer to free.</param>
    /// <remarks>
    /// The buffer must have been allocated with <see cref="AllocateMemory"/>.
    /// </remarks>
    private static void FreeMemory(IntPtr alignedBuffer)
    {
        if (alignedBuffer == IntPtr.Zero)
        {
            return;
        }

        Marshal.FreeHGlobal(((IntPtr*)alignedBuffer)[-1]);
    }
}
```

**Comment by xoofx** [comment]
Not sure if you are working in 64bits, but the AllocateMemory in SharpDX Toolkit had a bug and it should be actually `var ptr = (ulong)((float*)memPtr + sizeof(void*) + mask) & ~(ulong)mask;` 

Also, if you use a Lock/Unlock pattern, GCHandle/pin the array should be ok, as long as the PixelAccessor is mostly used for a relative short period of time (for buffers < 85kb) and because you are using 4 floats per pixel, an image with a size under 85kb would be max 74x74px which is rather small and unlikely a main usecase...

Also, not sure about the idea of using float buffers, but why not using directly a Color[] buffer? (instead of handling the logic x 4 bytes)

**Comment by JimBobSquarePants** [comment]
Thanks for that. I've ditched the copy now then as pinning only lasts for the time it takes to loop through the pixels. 

Switching to a `Color[]` buffer was an excellent idea. It looks like I've bumped performance up as a result of switching that out..
