### ISSUE TITLE
Alpha method causes system exception and no means of trapping error

### ISSUE THREAD

**Issue by neilw1** [JimBobSquarePants/ImageProcessor#413]
Hello,
I'm using the latest 2.4.1.0. Not quite sure how you can recreate this as it's sometimes random but it always happens...

I have a factory:
            private ImageFactory ifac;

It is populated by an image and I update it a few times:

``` c#
    ifac.Reset();
    ifac.Contrast(Photo.Contrast);
    ifac.Brightness(Photo.Brightness);
    ifac.Hue(Photo.Hue);
    ifac.Saturation(Photo.Saturation);
    ifac.Alpha(100 - Convert.ToInt16(Photo.Opacity));
```

The Alpha (it doesn't matter if I call it first in the list or last) method generates a System exception that cannot be caught: 
An unhandled exception of type 'System.ArgumentException' occurred in System.Drawing.dll

I do call this in quick succession, that's the only thing I can think of.

btw, those values are all valid. when it fails I haven't touched any of the variables so Photo.Opacity is 0 so Alpha is set to 100.

so I know the image is perfectly fine, and sometimes it works for quite a few cycles, but it does always crash and always here.

**Comment by neilw1** [comment]
Definitely seems to be time bases (so a threading issue?). If I go slowly in my calls to this method, it works fine. If I go slightly fast, it always fails with an untrappable fault, but only ever on Alpha.

**Comment by JimBobSquarePants** [comment]
Hi there,

I cleaned up your code sample a little to make it more readable. Could you post a completeb sample so I can test it properly?

Cheers

James

**Comment by neilw1** [comment]
I've got a workaround, but that workaround shows the fault. The part of my
application that requires constant updates in quick succession does not
need alpha so when it is 100 in code I don't call it, as it's straight
after a reset.

So essentially the fault is calling alpha straight after a reset.

You can probably just copy my lines of code and stick then on a button?

Dunno if it makes a difference but the image then gets immediately assigned
to a picture box?

**Comment by JimBobSquarePants** [comment]
That workaround is very useful thanks. I'll start digging.

**Comment by JimBobSquarePants** [comment]
Fixed and released

**Comment by neilw1** [comment]
Thanks. Looks like a lot of changes 😧

When will it be up on nuget as a binary?

**Comment by JimBobSquarePants** [comment]
It already is. 

http://www.nuget.org/packages/ImageProcessor/

**Comment by neilw1** [comment]
That is magnificent. Thanks.

**Comment by neilw1** [comment]
Hello,
I'm afraid it doesn't work. Well, it's either this release or a version after 2.3.3.0 which was my last one.

As soon as you call the hue method (e.g. ifac.Hue(0)) it is adding a positive hue to the image and turning everything reddish. It looks like you've got an index offset issue as it's the equivalent of calling 1 not 0. In my case it is pictures of people and they all get a red face :)
