### ISSUE TITLE
Replace all instances of request.Path with new code

### ISSUE THREAD

**Issue by aerionTech** [JimBobSquarePants/ImageProcessor#415]
Hi, 
I pulled the newest update of the newget package and got it running that code fix worked however there is more spots in code where the same problem is occuring e.g
ImageProcessingModule
```
if (hasMultiParams)
                        {
                            string[] paths = url.Split('?');
                            requestPath = protocol
                                          + request.Path.TrimStart('/').Remove(0, currentService.Prefix.Length).TrimStart('/')
                                          + "?" + paths[1];
                            queryString = paths[2];
                        }
                        else
                            {
                         
                            requestPath = protocol + request.Path.TrimStart('/').Remove(0, currentService.Prefix.Length).TrimStart('/');
                            queryString = request.QueryString.ToString();
                        }


```

These and other instances will also need to be replaced. When i do a test build and replace it using similar code The iamges load correctly however the above code generates the following error 
```
Invalid file name for file monitoring: 'ssor.TestWebsite/custom.axd/logo.png'. Common reasons for failure include:
- The filename is not a valid Win32 file name.
- The filename is not an absolute path.
- The filename contains wildcard characters.
- The file specified is a directory.
- Access denied.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Web.HttpException: Invalid file name for file monitoring: 'ssor.TestWebsite/custom.axd/logo.png'. Common reasons for failure include:
- The filename is not a valid Win32 file name.
- The filename is not an absolute path.
- The filename contains wildcard characters.
- The file specified is a directory.
- Access denied.

Stack Trace: 


[HttpException (0x80004005): Invalid file name for file monitoring: 'ssor.TestWebsite/custom.axd/logo.png'. Common reasons for failure include:
- The filename is not a valid Win32 file name.
- The filename is not an absolute path.
- The filename contains wildcard characters.
- The file specified is a directory.
- Access denied.]
   System.Web.FileChangesMonitor.StartMonitoringPath(String alias, FileChangeEventHandler callback, FileAttributesData& fad) +830
   System.Web.Caching.CacheDependency.Init(Boolean isPublic, String[] filenamesArg, String[] cachekeysArg, CacheDependency dependency, DateTime utcStart) +3215
   System.Web.Caching.CacheDependency..ctor(Int32 dummy, String[] filenames, String[] cachekeys, CacheDependency dependency, DateTime utcStart) +106
   System.Web.ResponseDependencyList.CreateCacheDependency(CacheDependencyType dependencyType, CacheDependency dependency) +340
   System.Web.HttpResponse.CreateCacheDependencyForResponse() +143
   System.Web.HttpCachePolicy.UpdateFromDependencies(HttpResponse response) +483
   System.Web.HttpCachePolicy.UpdateCachedHeaders(HttpResponse response) +339
   System.Web.HttpCachePolicy.GetHeaders(ArrayList headers, HttpResponse response) +43
   System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders) +991
   System.Web.HttpRuntime.FinishRequestNotification(IIS7WorkerRequest wr, HttpContext context, RequestNotificationStatus& status) +185
```

With the URL being http://localhost/ImageProcessor.TestWebsite/custom.axd/logo.png?width=201
it removes the length of "custom.axd" from the request.path and leaves 

````
ssor.TestWebsite/custom.axd/logo.png
````
which then causes the above exception. 

When i remove the application path from the request.path again 
all that remains is
```
logo.png
```

I'm not too sure of the rest of your logic in the solution or the number of places similar logic is performed, which is limiting me to correct al linstances of the issue, otherwise it could be a case of fix, test, merge, update, repeat

**Comment by aerionTech** [comment]
Forgot to mention this is for the first request to every url. after the first one the image loads correctly. 
Hopefully it wont take too long to update all isntances or locations where the url is being processed

**Comment by JimBobSquarePants** [comment]
Can you test and submit a PR with all the required changes then please. 

I was under the impression that you had already tested your PR that you had submitted given the urgency in which it appeared you wanted the code changes deployed.

**Comment by aerionTech** [comment]
I Had tested that code and that exception hadn't been raised in the tests only know that i got it working on the project i'm currently on. I'll do a change and test on all request.path tomorrow

**Comment by JimBobSquarePants** [comment]
That would be brilliant if you could. I appreciate that catching all  issues can be tricky (I have missed too many countless times). I look forward to seeing your PR :+1:

**Comment by JimBobSquarePants** [comment]
Hey @aerionTech it looks like the two extra places you spotted the issue were the only issue. Just successfully pulled remote images using the following url. Will have a fix out soon.

localhost.imageprocessor.test.com

**Comment by aerionTech** [comment]
ok cool. Sorry I have been held up on project and hadn't been able to get onto the pull request yet. I had it scheduled for this sprint.

**Comment by JimBobSquarePants** [comment]
That's no problem at all. I had a free moment to look at this and a few other issues.

**Comment by aerionTech** [comment]
Thanks and Great work on the library.

**Comment by JimBobSquarePants** [comment]
New release available on Nuget now.

**Comment by aerionTech** [comment]
Thank you. That's awesome.

**Comment by aerionTech** [comment]
HI Just updated the nuget package seems to still be a problem when running under localhost/testWebsite 

Invalid file name for file monitoring: '.axd/3-.jpg'. Common reasons for failure include:
- The filename is not a valid Win32 file name.
- The filename is not an absolute path.
- The filename contains wildcard characters.
- The file specified is a directory.
- Access denied.

where 3-.jpg is our image id in a filename that we parse to retrieve the correct image.

**Comment by JimBobSquarePants** [comment]
No idea I'm afraid, cannot replicate. 

I've never had anyone using this url structure before with ImageProcessor and I don't even know how to mimic it with IIS.

Can pull the source, test it and submit a PR please as that is the only way this is going to get fixed.
