### ISSUE TITLE
It lacks WEBP support

### ISSUE THREAD

**Issue by ststeiger** [JimBobSquarePants/ImageProcessor#416]
You should add support for the WEBP image format (according to readme.md). 
That's basically 24-bit color animated gifs with transparency. 
A successor to the .gif format. 
https://developers.google.com/speed/webp/
https://en.wikipedia.org/wiki/WebP

There is some C# handling-code here:
https://webp.codeplex.com/
something to build on, perhaps, not that you start from scratch when you don't have to.

**Comment by JimBobSquarePants** [comment]
Hi @ststeiger What lacks WebP support, the new core library? 

Could you please be more specific, remember, tickets have to be accessible to all users independent of their knowledge of the repo.

WebP support is available in the Framework release by installation of the plugin [ImageProcessor.Plugins.WebP](http://www.nuget.org/packages/ImageProcessor.Plugins.WebP/) This obviously only enables WebP on Windows devices thus far and is not supported on .NET Core.

I don't plan to support WebP out-of-the-box as it would dramatically increase the install size and complexity of the library, rather I'd like to focus on developing core encoders and decoders in C#, taking advantage of some of the new namespaces available to us.

That said, if someone can figure out a way to allow easy, x-plat loading and p-invoking of the various encoders then I would certainly look into using them.
