### ISSUE TITLE
2.4.2.0 apply a positive hue to all images when Hue is called

### ISSUE THREAD

**Issue by neilw1** [JimBobSquarePants/ImageProcessor#418]
Hello,
In the latest version 2.4.2.0 it seems to have created a bug with Hue by applying an increment of 1 to Hue when you call the Hue method.

All was well in 2.4.1.0. I raised a fault relating to an Alpha bug and subsequently a release was made. I downloaded and tried. Whether the two are related I have no idea but simply it was working in 2.4.1.0 and not in the release made the following day that made a few changes to exif data and other related items.

When you apply Hue(0) you get the effect of Hue(1). When you apply Hue(-1) you effectively get Hue(0), i.e. the original image, etc.

You can see by simply applying Hue(0) to an image and it is altered from the original. In my case white faces get a red tinge.

Hope this helps.

**Comment by JimBobSquarePants** [comment]
I think this is actually a rounding error in some internal custom color translation.

**Comment by JimBobSquarePants** [comment]
New release available on Nuget now.
