### ISSUE TITLE
IndexOutOfRangeException when trying to crop an image to dimensions bigger than it's

### ISSUE THREAD

**Issue by gdoron** [JimBobSquarePants/ImageProcessor#425]
The issue can be caught a lot sooner and give a clearer error and save some CPU time.

System.IndexOutOfRangeException: Index was outside the bounds of the array.
 at ImageProcessorCore.Formats.JpegEncoderCore.emitHuffRLE(huffIndex h, Int32 runLength, Int32 v)
 at ImageProcessorCore.Formats.JpegEncoderCore.writeBlock(Block b, quantIndex q, Int32 prevDC)
 at ImageProcessorCore.Formats.JpegEncoderCore.encode420(PixelAccessor pixels)
 at ImageProcessorCore.Formats.JpegEncoderCore.writeSOS(PixelAccessor pixels)
 at ImageProcessorCore.Formats.JpegEncoderCore.Encode(Stream stream, ImageBase image, Int32 quality, JpegSubsample subsample)
 at ImageProcessorCore.Formats.JpegEncoder.Encode(ImageBase image, Stream stream)

Great library by the way!

**Comment by JimBobSquarePants** [comment]
Thanks! Yeah, still lots of sanitation work to happen yet. Should be easy enough to trap. 

Just checking... You used the Crop() method not the CropProcessor yeah?

**Comment by gdoron** [comment]
Correct, it was `Crop`.

To be honest, it seems like an **awesome!** library, but really lacking of documentation.
 I tried for hours to figure out how I can take an image and convert it to a thumbnail.
 Meaning, crop it from the sides so it will be square and and resize it to be 150px*150px.
 
 I literally tried that for most of the day.
 It's a shame, because it really looks like the best tool we have in .NET today (not to say .NET Core..).

**Comment by JimBobSquarePants** [comment]
The new stuff isn't documented yet as it is still a very early alpha. That's why it's only available on Myget for now. Please don't use it for production yet as there is still a lot to do and there's a very strong  possibility I will be changing the API a wee bit very soon.

Also... That's really nice of you to say! I'm really hoping that once it's ready for release it will be second-to-none for ease of use and flexibility.

**Comment by gdoron** [comment]
@JimBobSquarePants Ohhh, O.K.
BTW, I still didn't figure out how to do that, so I'll be really grateful if you can give me a hand here :smile: 

**Thank you for the contribution!**

**Comment by JimBobSquarePants** [comment]
My pleasure. :smile: 

You want to resize to those dimensions cropping the excess if they overlap yeah?

This would do that.

``` c#
ResizeOptions options = new ResizeOptions()
{
    Size = new Size(150, 150),
    Mode = ResizeMode.Crop
};

 image.Resize(options)
           .Save(output);
```

**Comment by gdoron** [comment]
Thanks a ton! 👍👍👍

**Comment by JimBobSquarePants** [comment]
Just pushed a fix.
