### ISSUE TITLE
Exif images. Read image orientation

### ISSUE THREAD

**Issue by Bartmax** [JimBobSquarePants/ImageProcessor#426]
I'm using this library on production, i know... i know.. but it works great! and AFAIK is the only working library for NET Core :)

I was wondering, uploading images from a phone/device that has exif information about the orientation. It is possible to read that data now and adjust/rotate accordingly? I don't think this is supported now, but since I'm not sure I prefer to ask.

Thanks,

**Comment by JimBobSquarePants** [comment]
Eeeeeeeeeeeeeeeeeeeeeeeeeeep!

![scurrd](https://cloud.githubusercontent.com/assets/385879/16674902/dcaeb8ee-44ff-11e6-9c43-02daed6eb18a.gif)

There's an open PR that would add EXIF support https://github.com/JimBobSquarePants/ImageProcessor/pull/357

Unfortunately it seems that @stbraley has been caught up with other work which is understandable. He's made excellent progress so far so hopefully it can be completed sometime soon.

Once we have that performing an EXIF based rotation should be a cinch.

**Comment by gdoron** [comment]
@Bartmax seems like we meet again, I guess .Net core on GitHub doesn't give too much options :smile: 

I'm curious to know how you overcome this, we are using it too (on production...) and iPhone images are being rotated when resized.

**Comment by dlemstra** [comment]
I am working on adding support for EXIF information (see #357 for more info). That would mean the information would be preserved when you read/write an image. I also wonder if a feature to AutoOrient (thats how we call it in ImageMagick) the image would be a nice addition to the library. I will try and see if I can add that once the EXIF code is included.

**Comment by Bartmax** [comment]
@gdoron i didn't. I told people to upload photos and fix the orientation if it's wrong for the time being. :cry:

**Comment by gdoron** [comment]
@Bartmax So your site gives rotating API for the user, correct?
Or do they need to edit it somewhere else?

**Comment by Bartmax** [comment]
@gdoron fortunatelly my upload thing is internal and not public faced. Since they do work on the images in a photo editor before upload they just do it there.

**Comment by dlemstra** [comment]
The pull request for adding exif support has been pushed and merged (#450). Will work on adding support for auto orientation.

**Comment by dlemstra** [comment]
AutoOrient has been added: ae4de1ad

**Comment by Bartmax** [comment]
Wow that was fast! Amazing

**Comment by gdoron** [comment]
👏👏👏
Thank you all!
I wish I could contribute to this super important library, but unfortunately I didn't attend to any of the image processing classes at college...
Great stuff!👍

**Comment by dlemstra** [comment]
I also haven't had any image processing classes at college. You just need to do a lot of reading on image formats and algorithms. And if you can read `C` you can also take a look at the ImageMagick library (I work on that project) and see how stuff is done there and learn from it. There are a couple of issues where help is requested (needed): https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+needed%22

**Comment by dlemstra** [comment]
And I just got a request for my Magick.NET project that is related to this: https://magick.codeplex.com/discussions/657123. You could help creating the huge `ExifDescriptions` class so we can use it here and in Magick.NET.

**Comment by JimBobSquarePants** [comment]
I'm learning by doing. Wikipedia and looking through older open source libraries has been how I've learned. You'd be amazed how much you can pick up in a short time.

**Comment by dlemstra** [comment]
Decided to use a different approach: 3bca9a911. We could still use some help.

**Comment by omric-axonize** [comment]
Hi,
We are looking for this awesome feature too!
Any ETA on this?

Thanks!

**Comment by dlemstra** [comment]
This feature has been added we are still fine tuning it but the latest build from appveyor should have this feature.

**Comment by gdoron** [comment]
It's not on myget yet, right?
I checked the latest version, 1.0.0-alpha-999, and it doesn't seem to exists there.

**Comment by JimBobSquarePants** [comment]
We're a few build on from that now. 

v1.0.0.1021 as of just now. 

https://ci.appveyor.com/project/JamesSouth/imageprocessor/branch/Core

**Comment by gdoron** [comment]
@JimBobSquarePants Can you please push it to myget?
I still get `1.0.0-alpha-999` as the latest version there.

**Comment by JimBobSquarePants** [comment]
![myget](https://cloud.githubusercontent.com/assets/385879/17887640/b4831be6-696a-11e6-9219-49d0cd5a4690.png)

Can you double check this. Publishing is automatic.

**Comment by JimBobSquarePants** [comment]
Actually hold on, main page says different!

**Comment by JimBobSquarePants** [comment]
It's MyGet, it's not understanding version numbers!  https://www.myget.org/feed/imageprocessor/package/nuget/ImageProcessorCore/1.0.0-alpha-1021

**Comment by gdoron** [comment]
You're right, I found it somewhere way way down the list, for some reason VS/myget decided 1000 < 999.
Sounds legit... :dizzy_face:

**Comment by JimBobSquarePants** [comment]
Frantically investigating semver rules now. Not sure how I can fix this. :worried:

**Comment by JimBobSquarePants** [comment]
Fixed. https://www.myget.org/feed/imageprocessor/package/nuget/ImageProcessorCore
