### ISSUE TITLE
AzureBlobCache.streamCachedImage disables browser caching

### ISSUE THREAD

**Issue by JasonElkin** [JimBobSquarePants/ImageProcessor#428]
Creating a new response and streaming the blob directly ([here](https://github.com/JimBobSquarePants/ImageProcessor/blob/Framework/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L387)) breaks the cache/ETag headers and ability to send a 304 response.

Happy to have a stab at fixing this - should just be a case of mapping the headers between the requests.

**Comment by JimBobSquarePants** [comment]
Hi Jason,

Thanks for this.

Yeah please do. The functionality is something that was requested but that I have personally never used so I wont be able to test properly.

**Comment by JimBobSquarePants** [comment]
This is now merged but I'll keep it open until I ship again. Thanks for your efforts!

**Comment by JimBobSquarePants** [comment]
@JasonElkin That's the code released now. Thanks again for your efforts. Much appreciated! :+1:
