### ISSUE TITLE
Watermark is always vertical

### ISSUE THREAD

**Issue by zokiad** [JimBobSquarePants/ImageProcessor#430]
Hi,

Since 2.4.x, watermark is alway vertical.

`imageFactory.Load(streamPhoto)
                                                 .Watermark(new TextLayer { Text = "Watermark", Vertical = false }) `

Render of watermak is alway vertical.

**Comment by JimBobSquarePants** [comment]
Hi there,

Thanks for you issue.

Could you please add a full code sample etc as per the [contribution guidelines](https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/contributing.md). So we can appropriately assess and debug.

Thanks!

James

**Comment by zokiad** [comment]
Hi,

Follow, you can found an example to reporduce the issue in VS 2015:
[ErrorVertical.zip](https://github.com/JimBobSquarePants/ImageProcessor/files/366242/ErrorVertical.zip)

Regards

**Comment by JimBobSquarePants** [comment]
Brilliant. Thanks for the sample it will make things a lot easier. :+1:

**Comment by JimBobSquarePants** [comment]
Hi @zokiad sorry for the delay. I've managed to find and fix the issue and will release a new version soon. Thanks again for providing the code sample. It was instrumental in me finding and fixing the bug. :+1:

**Comment by JimBobSquarePants** [comment]
@zokiad That's the code released now.

**Comment by zokiad** [comment]
Thanks
