### ISSUE TITLE
[Proposal] A non-destructive way to support AzureBlobCache settings customisation

### ISSUE THREAD

**Issue by Philo** [JimBobSquarePants/ImageProcessor#432]
We've previously discussed (#369) the ability to support customisation of the settings values for the ```ImageCacheBase``` and specifically the ```AzureBlobCache```.  

At present all configuration logic happens within the constructor, whether the Settings dictionary to read and applied to internal properties, this method prevents any derived implementations from altering those base settings before they are applied.  

From our previous discussion you were not inclined to make any significant changes the ImageProcessor as you were starting on Core support, I can totally understand and accept that, I do however have a proposal for a minor change that will allow for the ```AzureBlobCache``` and ```ImageCacheBase``` to support a customisation path for the scenario where you want to store configuration details elsewhere.

My proposal is to introduce a means to augment the ```ImageCacheBase``` with two new methods:

```c#
private void AugmentSettingsCore(Dictionary<string, string> settings)
{
  AugmentSettings(settings);
}

protected virtual void AugmentSettings(Dictionary<string, string> settings)
{
}
```
Then call ```AugmentSettingsCore(Settings)``` from the ```ImageCacheBase``` constructor:

```c#
protected ImageCacheBase(string requestPath, string fullPath, string querystring)
{
  this.RequestPath = requestPath;
  this.FullPath = fullPath;
  this.Querystring = querystring;
  this.Settings = ImageProcessorConfiguration.Instance.ImageCacheSettings;
  this.MaxDays = ImageProcessorConfiguration.Instance.ImageCacheMaxDays;
  this.BrowserMaxDays = ImageProcessorConfiguration.Instance.BrowserCacheMaxDays;
  AugmentSettingsCore(Settings);
}
```

This will allow a derived instance to act on the settings before the immediate classes (like ```AzureBlobCache```) and then allow the Settings values to be updated via custom logic.

Here is my working example (that has required me to re-implement the ```AzureBlobCache``` locally):

```xml
<appSettings>
  <add key="AzureBlobCache.CachedStorageAccount" value="<storage connection string>" />
  <add key="AzureBlobCache.CachedCDNRoot" value="https://somewhere.com" />
  <add key="AzureBlobCache.SourceStorageAccount" value="<storage connection string>" />
</appSettings>

<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="AzureBlobCache" type="Test.AzureBlobCacheFromAppSettings, Test" maxDays="365" />
  </caches>
</caching>
```

Which is read by:

```c#
public class AzureBlobCacheFromAppSettings : AzureBlobCache
{
    public AzureBlobCacheFromAppSettings(string requestPath, string fullPath, string querystring) : base(requestPath, fullPath, querystring)
    {
    }

    protected override void Configure(Dictionary<string, string> settings)
    {
        var prefix = $"{nameof(AzureBlobCache)}.";
        var removePrefix = new Func<string, string>(key => key.Replace(prefix, string.Empty));

        var matchingKeys = ConfigurationManager.AppSettings.AllKeys.Where(
            key => key.StartsWith(prefix, StringComparison.InvariantCultureIgnoreCase));
        matchingKeys.ForEach(key =>
        {
            settings.AddOrUpdate(removePrefix(key), key.FromAppSettings());
        });
    }
}
```

Which derives from (updated from [AzureCacheBlob.cs](https://github.com/JimBobSquarePants/ImageProcessor/blob/master/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L86))

```c#
public AzureBlobCache(string requestPath, string fullPath, string querystring)
    : base(requestPath, fullPath, querystring)
{
    ConfigureCore(Settings);
    // Retrieve storage accounts from connection string.
    CloudStorageAccount cloudCachedStorageAccount = CloudStorageAccount.Parse(this.Settings["CachedStorageAccount"]);

    // Create the blob clients.
    CloudBlobClient cloudCachedBlobClient = cloudCachedStorageAccount.CreateCloudBlobClient();

    // Removed for brevity...
}

private void ConfigureCore(Dictionary<string, string> settings)
{
    Configure(settings);
}

protected virtual void Configure(Dictionary<string, string> settings)
{
}
```
This change would allow the sensitive configuration values such as storage account connection strings and other environment specific settings to be managed based on the requirements of the application/developer.

Apologies for the wall of text :)

**Comment by JimBobSquarePants** [comment]
@Philo Well done!! :100: 

I really like this, especially how you avoided having to touch the interface. If you want to open a PR with the code changes I would be more than happy to accept them. 

I really appreciate the effort you have made.

Cheers

James

**Comment by JimBobSquarePants** [comment]
@Philo  That's the code released now. Thanks again for your PR, a really excellent way to work around the limitations of my API. :+1:

**Comment by erzki** [comment]
Are there any documentation of how to use this which as I understand is in the latest release?

**Comment by CasperTDK** [comment]
Really nice, but do we not have the same issue for CloudImageService?

**Comment by aerionTech** [comment]
Thanks for the great solution and getting this implemented. 
I have written up a blog post on our company blog about how this was implemented and we use it with multiple AppService Slots
