### ISSUE TITLE
Error: "Property cannot be found"

### ISSUE THREAD

**Issue by hoanghai123** [JimBobSquarePants/ImageProcessor#434]
Hi,

I have used ImageProcessor to manipulate with uploaded images.

One of my developer has this error "Property cannot be found" while trying to resize the attached image to a new size of 150x24.

If resize to other size such as 224x150, there's no error.

Here is  my code to resize the image:

using (ImageFactory imageFactory = new ImageFactory())
{
      // load from Stream
      imageFactory.Load(merchantImageStream);
      // create thumnail 1
      var size1 = ImageSize.Merchant150x42;
      imageFactory.Resize(new Size(size1.Width, size1.Height)).Save(filePath);                    
}

and here is the stack trace:

Stack Trace: 

[ArgumentException: Property cannot be found.]
   System.Drawing.Image.GetPropertyItem(Int32 propid) +475913
   ImageProcessor.Imaging.Formats.GifDecoder.GetFrame(Image image, Int32 index) +128
   ImageProcessor.Imaging.Formats.GifFormat.ApplyProcessor(Func`2 processor, ImageFactory factory) +198
   ImageProcessor.ImageFactory.Resize(ResizeLayer resizeLayer) +248
   ImageProcessor.ImageFactory.Resize(Size size) +169
   MyProject.Business.MerchantService.Update(Merchant merchant, Stream merchantImage, Stream promotionDefaultImage, Stream bannerDetailImage, List`1 categoryList) in [hidden folder]\MerchantService.cs:136
   MerchantController.Create(Merchant data) in [hidden folder]\MerchantController.cs:119
   lambda_method(Closure , ControllerBase , Object[] ) +103
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +30
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +197
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +46
   System.Web.Mvc.Async.ActionInvocation.InvokeSynchronousActionMethod() +37
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +24
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +43
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +68
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +69
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +230
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +230
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +68
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +42
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +124
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +32
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +26
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +40
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +24
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +29
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +23
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9644037
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

![hotdeals-transcosmos-thau-tom-co-phan](https://cloud.githubusercontent.com/assets/20239021/16894209/e2a4c8b2-4b79-11e6-9102-09a954ce087b.gif)

What should I do to fix this error ?

Thanks,

Hai

**Comment by JimBobSquarePants** [comment]
Hello Hai,

Thanks for supplying so much detail. One last thing please. What version number are you running?

I think I've already identified an issue and have deployed a fix to development.

Cheers

James

**Comment by hoanghai123** [comment]
Hello James,

FYI, I'm runing on version 2.4.3.0

May I know your plan to release the fix for this issue?

Thanks,

Hai

**Comment by JimBobSquarePants** [comment]
Hi @hoanghai123 I have changed the way EXIF data is handled slightly which will fix the issue, you can see some of it in the referenced commit. I'm just checking some other tickets now before building a release.

**Comment by JimBobSquarePants** [comment]
@hoanghai123 That's the code released now.
