### ISSUE TITLE
Quality only applies if placed after format in querystring

### ISSUE THREAD

**Issue by arknu** [JimBobSquarePants/ImageProcessor#436]
If I have a querystring that says image.jpg?quality=50&format=jpg, the quality never is applied, since it is overwritten by the format being applied afterwards. Putting it the other way round makes it work, i.e. image.jpg?format=jpg&quality=50 works just fine.

This is rather unintuitive (especially given that Umbraco's GetCropUrl method generates URL's with the quality specified first by default). 

Could it be ensured that the quality is applied, even if it is before the format specifier in the querystring?

**Comment by JimBobSquarePants** [comment]
Hi there,

I would raise a bug then on the Umbraco issue tracker as they haven't implemented the API properly.

>The API for ImageProcessor.Web is imperative. This means that the order in which you supply the querystring parameters is the order in which the individual processors are implemented. This allows the API to be very flexible, allowing you to combine processes in any order.

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#about

**Comment by arknu** [comment]
Thanks for the feedback. That does make sense. What tripped me up was that I didn't think of the quality and format as two separate things but two parameters of the same thing (the final image quality). 

I have raised the issue with Umbraco here: http://issues.umbraco.org/issue/U4-8751

**Comment by Jeavon** [comment]
Umbraco doesn't have a format parameter which is the actual problem you have, but adding parameters to existing methods is a breaking change :(

**Comment by JimBobSquarePants** [comment]
@arknu Thanks for raising that. 

@Jeavon the GetCropUrl method accepts additional properties though doesn't it?

``` html
<img src="@Url.GetCropUrl(Model.Content, propertyAlias: "image", cropAlias: "banner", useCropDimensions:true, furtherOptions: "&blur=11&sigma=1.5&threshold=10")" />
```

Could the method not internally ensure quality is last or at least after any format requests without changing the signature?
