### ISSUE TITLE
Overlay not working on all images

### ISSUE THREAD

**Issue by simoazzo** [JimBobSquarePants/ImageProcessor#438]
Hi Guys,

I have this strange problem where the overlay is not being created on all the images and I don't know why:

example 1:auctions.remax-malta.com/media/1128/a001l05-2.jpg?width=1000&overlay=wm.png&overlay.opacity=80 (is working)

example 2: auctions.remax-malta.com/media/1143/a001l05-17.jpg?width=1000&overlay=wm.png&overlay.opacity=80 (is not working)

I cannot get any pattern why this is happening.

Can  someone can help me with this issue?

Thanks

**Comment by JimBobSquarePants** [comment]
Closed. Same as #445
