### ISSUE TITLE
Denial of Service attack vulnerability

### ISSUE THREAD

**Issue by base33** [JimBobSquarePants/ImageProcessor#442]
We recently performed a security audit on a web site that uses Image Processor and have found that it is possible to perform a DOS attack on a website that utilises Image Processor.  The attacker can craft image urls with various parameter changes to increase CPU activity and increase disk usage.

To get round this, is it possible to add a new parameter called "Sig", which is a hash of the querystring parameters hashed with the machine key?  Also a config value to enable this security feature?  This way, the Image Processor module can deny the attackers requests.

**Comment by base33** [comment]
Ignore this.  I think this is the wrong repo.  I will find the correct one

**Comment by base33** [comment]
I am unable to find another repo for the ImageProcessor.Web project.

Hopefully you can point me to where I can report this?

**Comment by JimBobSquarePants** [comment]
Hi there,

It's all one repository, so you're in the correct place.

I think you may have missed #49 which deals with this scenario in detail. The result of which provides the means to quite effectively lock down an install. You're probably looking to use this method.

``` c#
ImageProcessingModule.ValidatingRequest += (sender, args) =>
{
    if (!string.IsNullOrWhiteSpace(args.QueryString))
    {
        var queryCollection = HttpUtility.ParseQueryString(args.QueryString);
        if (!queryCollection.AllKeys.Contains("sig"))
        {
            args.Cancel = true;
            return;
        }
        // Perform validation on "sig" and reject if invalid.
    }
};
```

Hope that helps.
