### ISSUE TITLE
JpegEncoder ignores 'HorizontalResolution' and 'VerticalResolution' attributes

### ISSUE THREAD

**Issue by eat-sleep-code** [JimBobSquarePants/ImageProcessor#443]
The JpegEncoder sets the DPI to 72 regardless of what the HorizontalResolution and VerticalResolution are set to.

The PngEncoder works as expected.

The following is the code example that shows both code snippets.

```
public byte[] ResampleImage(Stream sourceStream, string contentType, double targetDPI)
{
	MemoryStream outputStream = new MemoryStream();
	try
	{
		using (sourceStream)
		{
			Image image = new Image(sourceStream);
			image.HorizontalResolution = targetDPI;
			image.VerticalResolution = targetDPI;

			switch (contentType)
			{
				case "image/gif":
					GifEncoder gifEncoder = new GifEncoder();
					gifEncoder.Quality = 256;
					image.Save(outputStream, gifEncoder);
					break;
				case "image/jpeg": // BAD: DPI is always set to 72
					JpegEncoder jpegEncoder = new JpegEncoder();
					jpegEncoder.Quality = 100;
					image.Save(outputStream, jpegEncoder);
					break;
				default: // GOOD: DPI is set to whatever we set the HorizontalResolution and VerticalResolution to.
					PngEncoder pngEncoder = new PngEncoder();
					image.Save(outputStream, pngEncoder);
					break;
			}
		}
	}
	catch (Exception ex)
	{
		return null;
	}
	return outputStream.ToArray();
}
```

**Comment by JimBobSquarePants** [comment]
Hi there,

Thanks for that. I've actually just fixed it in my Core-Flava branch which will be the main branch once I've finished porting everything over. (I'm vastly reducing the memory usage in that branch.)

You can see the reading and writing here.

https://github.com/JimBobSquarePants/ImageProcessor/commit/fcf404c9fede3784fd312aaba739185e12aba2d8#diff-ca7976f0fe9cdbd42d4b6de4677f1616R724

https://github.com/JimBobSquarePants/ImageProcessor/commit/fcf404c9fede3784fd312aaba739185e12aba2d8#diff-a6cd03ac430480180219270554a48aafR566

Just to note. Your method name in your example code is a bit of a misnomer as you're not doing any resampling.

I'll keep this issue open until I merge the two branches.

**Comment by JimBobSquarePants** [comment]
I merged the flags branch today fixing the issue. Please give it a whirl and let me know if you have any trouble.
