### ISSUE TITLE
Add watermark image 

### ISSUE THREAD

**Issue by iranidesign** [JimBobSquarePants/ImageProcessor#451]
Hello ,can i add watermark image to httppostedfilebase and how do this?

**Comment by JimBobSquarePants** [comment]
Hi there,

Please read the documentation for [ImageFactory](http://imageprocessor.org/imageprocessor/imagefactory/#example) and also the dopcumentation for [Watermark](http://imageprocessor.org/imageprocessor/imagefactory/watermark/) and also the [contribution guide](https://github.com/JimBobSquarePants/ImageProcessor/blob/4a6cad5cac25407cab5f7ab09ff042c4ae03b1b9/contributing.md) everything you need should be there.

The issue tracker is not the place for questions, we have a dedicated [Gitter Chatroom](https://gitter.im/JimBobSquarePants/ImageProcessor) for that.

Thanks

James
