### ISSUE TITLE
Core Web API:  `Cannot resolve symbol 'ImageProcessorCore'

### ISSUE THREAD

**Issue by gerryLowry** [JimBobSquarePants/ImageProcessor#453]
Architecture:

vs2015 Update 3:
 
Solution:   Core Web API application   ~~ structure on disk  
```
 ...........ImageProcessorCore 
 ...........MyWebAPIProject
......................References
..............................ImageProcessorCore(1.0.0)  
```
``` c#
public ImageProcessorCore.Image CameraImage { get; set; }
```

Rebuilding the solution has zero errors.

HOWEVER, "ImageProcessorCore" is shown in Red by vs2015.

Mouseover on "ImageProcessorCore displays:

``` c#
{} namespace ImageProcessorCore`
Cannot resolve symbol 'ImageProcessorCore'
```

N.B.:  under References, the icons for all of the parts except ImageProcessorCore(1.0.0) are similar to what one sees with Microsoft.NETCoreApp(1.0.0) and Microsoft.AspNetCore.Mvc(1.0.0).

The icon for ImageProcessorCore(1.0.0) is a rectangle in landscape orientation with a dark bar at the top.

Part of my project.json for MyWebAPIProject:
``` json
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "MailKit": "1.4.2",
    "ImageProcessorCore": "1.0.0-*"
  },
```

**Comment by JimBobSquarePants** [comment]
Hi Gerry,

Just to confirm that you have no errors in the reference list and the package installer works ok?

There's no icon because I keep forgetting to add it to my package.json file. 

Are you able to run the code and manipulate the image?

Also do you have Resharper installed?

Cheers

James

**Comment by JimBobSquarePants** [comment]
Hello?

**Comment by JimBobSquarePants** [comment]
Closed due to lack of response
