### ISSUE TITLE
PNG -> jpeg transparency 

### ISSUE THREAD

**Issue by dwdickens** [JimBobSquarePants/ImageProcessor#456]
Opening a png, resizing and saving as a jpeg is causing issues with loss of the transparency colour (I think that's the write description, I'm not very familiar with how transparency works). First attachment is formFile, second is output. Note the output has a black background.

Asp.net core RTM, "ImageProcessorCore": "1.0.0-alpha-996"

     using (MemoryStream stream = new MemoryStream())
      using (MemoryStream tempStream = new MemoryStream())
      using (FileStream output = File.OpenWrite(filePath))                
            {
                 ImageProcessorCore.Image image = new ImageProcessorCore.Image(formFile.OpenReadStream());

                  image.Resize(500,0).SaveAsJpeg(tempStream, 85);
                  //check processed file is readable
                 ImageProcessorCore.Image testImage = new ImageProcessorCore.Image(tempStream);
                 tempStream.WriteTo(output);
             }

![bgbcam3-9_39l](https://cloud.githubusercontent.com/assets/13432550/17775021/d09060c0-6599-11e6-9a2a-26dd2004801d.png)
![65109](https://cloud.githubusercontent.com/assets/13432550/17775031/d92ed766-6599-11e6-9184-052dd69d6a8e.jpeg)

**Comment by JimBobSquarePants** [comment]
That's absolutely expected behaviour. Jpegs don't have an alpha component.

http://stackoverflow.com/questions/16906144/transparent-background-in-jpeg-image
