### ISSUE TITLE
Azure Blob Returned Directly Unprocessed

### ISSUE THREAD

**Issue by geoffbeaumont** [JimBobSquarePants/ImageProcessor#459]
Following an upgrade to:
ImageProcessor v2.4.4.0.
ImageProcessor.Web v4.6.4.0
ImageProcessor.Web.Config v2.3.0.0
ImageProcessor.Web.Plugins.AzureBlobCache v1.1.1.0 
the images are now being returned directly from the site, unprocessed.

When this is requested:
https://sitedomainname/media/1357/my-image.jpg?anchor=center&mode=crop&width=297&height=152

Instead of being redirected to the cached processed image on the storage account the original image is returned.

It's worth noting that the files are only present on the blob storage, not the local file system, so the image is being picked up from the blob storage but then returned directly not processed. On dev and another copy of the system on Azure where the images are within the site root at the requested URL (so not using ImageProcessor.Web.Plugins.AzureBlobCache) the images are processed correctly.

Cache config is as follows (sorry, can't get it to format this nicely):
``` xml
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" browserMaxDays="365">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
  <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=accname;AccountKey=acckey" />
        <setting key="CachedBlobContainer" value="cache" />
        <setting key="UseCachedContainerInUrl" value="true" />
        <setting key="CachedCDNTimeout" value="1000" />
        <setting key="CachedCDNRoot" value="https://accname.blob.core.windows.net/" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache></caches>
</caching>
```

I'm assuming I've got something configured incorrectly, but I can't for the life of me see what!

**Comment by JimBobSquarePants** [comment]
On first glance your CDN root is wrong, You're calling the blob storage location not the CDN URL, If you are not using a CDN comment out the setting.

**Comment by geoffbeaumont** [comment]
That didn't make any difference. What does CDN root do then? I assumed it specified the base URL to serve the files from (I can't see any other reason ImageProcessor would need to know about the CDN? Surely it would just push files to the BLOB storage and they'd be available via the CDN?).

I've rolled the ImageProcessor DLLs and config back on one instance and still have the same problem, so I think this was a pre-existing problem and nothing to do with the upgrade. I just picked it up when testing afterwards.

**Comment by geoffbeaumont** [comment]
Okay, after a bit of playing around I've got it working - the problem was in security.config where I had:

`<service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="https://accname.blob.core.windows.net/media"/>
      </settings>
    </service>`

instead of

`<service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="Container" value="media"/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="https://accname.blob.core.windows.net"/>
      </settings>
    </service>`

This was per the documentation for your UmbracoFileSystemProviders.Azure, and I think was probably an older version that's been broken by upgrading at some point?

**Comment by JimBobSquarePants** [comment]
Yeah, need to update the docs. Working on the latest release of that so will do so once we've finalised.
