### ISSUE TITLE
Overflow when decoding a particular png

### ISSUE THREAD

**Issue by dwdickens** [JimBobSquarePants/ImageProcessor#460]
![37](https://cloud.githubusercontent.com/assets/13432550/17812068/e06cc9f0-6668-11e6-8ab8-dd0e17bee60c.png)

Opening the attached file throws the following error. I've been using many other png files and these work fine.

{System.OverflowException: Array dimensions exceeded supported range.
   at ImageProcessorCore.Formats.PngDecoderCore.ReadChunkData(PngChunk chunk)
   at ImageProcessorCore.Formats.PngDecoderCore.ReadChunk()
   at ImageProcessorCore.Formats.PngDecoderCore.Decode[T,TP](Image`2 image, Stream stream)
   at ImageProcessorCore.Image`2.Load(Stream stream)

Build:  "ImageProcessorCore": "1.0.0-alpha-1012"
ASP.Net core RTM

Code:

        public abcd (IFormFile formFile)
        {
            try
            {               
             using (MemoryStream stream = new MemoryStream())                          
              {
                //throws error for attached file                  
               ImageProcessorCore.Image image = new ImageProcessorCore.Image(formFile.OpenReadStream());
              //...
              }

*******
Here's some info on the PNG file. Not sure if this is relevant:

ExifTool

Warning [minor] Trailer data after PNG IEND chunk 

File — basic information derived from the file. 

File Size 82 kB 
File Type PNG 
File Type Extension png 
MIME Type image/png 

PNG

Animation no 
Bit Depth 8 
Color Type RGB with Alpha 
Compression Deflate/Inflate 
Filter Adaptive 
Image Size 429 × 429 
Interlace Noninterlaced 
SRGB Rendering Perceptual 
Gamma 2.2 
Pixels Per Unit X 3,779 
Pixels Per Unit Y 3,779 
Pixel Units meters

**Comment by JimBobSquarePants** [comment]
Thanks for that. One of the fun things when writing a decoder is coping with poor encoding via other tools.

Should be good now.
