### ISSUE TITLE
Adding querystring params causes an error

### ISSUE THREAD

**Issue by dbajric** [JimBobSquarePants/ImageProcessor#461]
I am running version 2.4.3.0 of ImageProcessor and 4.6.3.0 of ImageProcessor.Web.
When I add a custom query string parameter that I use for tracking purposes, I get following error:

> The request /content/images/order_confirmation_logo.png?on=123456 could not be understood by the server due to malformed syntax

Ideally, any parameters not used by the ImageProcessor would be ignored.
Is there currently a way to avoid this issue, and if not could you guys add some capability that would allow me to pass any arbitrary params with the image?

**Comment by JimBobSquarePants** [comment]
Hi @dbajric 

>Ideally, any parameters not used by the ImageProcessor would be ignored.

Actually that's not true. the full url is used for generating the cache key so we can't ignore parameters as parsing the string and stripping any unknown ones out is too labor intensive to be useful.

If you follow the [docs](http://imageprocessor.org/imageprocessor-web/) you'll see the linked issue that led to the restricted API design. #49 It's a lot of reading but we really wanted to make the system as safe as possible.

In that issue and in the docs you will see reference to an event `ImageProcessingModule.ValidatingRequest`. You can use this to cancel the event and ensure ImageProcessor.Web doesn't try to process the image.

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

Hopefully that should be enough for you to carry on

Cheers

James

**Comment by dbajric** [comment]
This will work for me.

Thanks!
