### ISSUE TITLE
Multidimensional vs jagged arrays

### ISSUE THREAD

**Issue by omariom** [JimBobSquarePants/ImageProcessor#462]
Access to jagged array elements is currently faster:

Output:
```
jagged (sec)
0.000683631317134085 

multidimensional (sec)
0.00203599641664631 
```

Microbecnhmark:
```C#
float _f;

void Main()
{
    float[][] jagged = new float[1000][];
    
    for (int i = 0; i < jagged.Length; i++)
    {
        jagged[i] = new float[1000];
    }
  	
	Measure.Time(()=>
	{
        float f = 0;

        for (int y = 0; y < 1000; y++)
        {
            var ys = jagged[y];
            for (int x = 0; x < 1000; x++)
            {
                //f = jagged[y][x]; 
                f = ys[x];
            }
        }
		_f = f;
	}).Dump("jagged (sec)");
    
    float[,] multiDim = new float[1000, 1000];

    Measure.Time(() =>
    {
        float f = 0;

        for (int y = 0; y < 1000; y++)
        for (int x = 0; x < 1000; x++)
        {
            f = multiDim[y, x];
        }

        _f = f;
    }).Dump("multidimensional (sec)");
}
```

**Comment by JimBobSquarePants** [comment]
I'm trying to think where I use a multidimensional array? I've been using a 1D array throughout and mathing my way to the correct part. As far as I'm aware that should be faster than both.

**Comment by omariom** [comment]
@JimBobSquarePants 

I see `float[,]` in many places. 
For example, [Convolution2PassFilter](https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/src/ImageProcessorCore/Filters/Processors/Convolution/Convolution2PassFilter.cs#L23).

**Comment by JimBobSquarePants** [comment]
Ah yeah, of course!

Managed to break all my edge detection code in the last few commits so I'll look into switching out as I figure out whats wrong.

**Comment by JimBobSquarePants** [comment]
@omariom I've finally gotten round to switching all the code round. Thanks for the suggestion! 😄
