### ISSUE TITLE
The remote server returned an error: (500) Internal Server Error.

### ISSUE THREAD

**Issue by simoazzo** [JimBobSquarePants/ImageProcessor#463]
Hi,

I have a site online and was working fine, using the Image Processor. 

All of a sudden, remote images were not working and nothing has been changed from the file system on the server. For images being served remotely, an internal error is being thrown: https://www.remaxcollection-malta.com/remote.axd?http://www.remax-malta.com/UserImages/24/large/L_878263c333524b61bb336ed6eba363a2_iList.jpg?anchor=center&mode=crop&width=1358&height=800&rnd=131081472090000000?entropycrop=250&width=1358&height=800&mode=crop

![image](https://cloud.githubusercontent.com/assets/19478530/17988822/15bdacd6-6b29-11e6-8b6d-469a1d0618de.png)

Any help would be much appreciated.

Thank you in advance.

Kind Regards

**Comment by JimBobSquarePants** [comment]
Hi @simoazzo 

What steps have you done to debug this so far. The error message looks to me like a malformed url is somehow being sent to your remote server. Attach a debugger to a local build of the requesting server. If you are using **ImageProcessor v2.4.0** or later (**ImageProcessor.Web v4.6.0** or later) you will receive debug logs to your output pane in visual studio which will help you gather details.

There must have been an environmental change for things to break. Has your Cloudflare setup changed? Have there been any server updates? Have you recently updated any part of the software or configuration?

I have to ask... Why are you using the wrong, legacy API calls for remote images?

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#remote

The url is a bit mess. you've duplicated the following parameters **width**, **height**, **mode**.

**center** is the default anchor point. You don't need to add this. 

```
https://www.remaxcollection-malta.com/remote.axd?http://www.remax-malta.com/UserImages/24/large/L_878263c333524b61bb336ed6eba363a2_iList.jpg?anchor=center&mode=crop&width=1358&height=800&rnd=131081472090000000?entropycrop=250&width=1358&height=800&mode=crop
```

Should be 
```
https://www.remaxcollection-malta.com/remote.axd/www.remax-malta.com/UserImages/24/large/L_878263c333524b61bb336ed6eba363a2_iList.jpg?&mode=crop&width=1358&height=800&rnd=131081472090000000?entropycrop=250
```

If I navigate to the remote server directly the server is serving the image correctly so we know that ImageProcessor.Web is working well there. 

Hopefully we can get to the bottom of this quickly.

Thanks

James

P.S. Please list version numbers when creating issues as described in the [contributing guidlines](https://github.com/JimBobSquarePants/ImageProcessor/blob/401fa40681eb231eabcfe11f5115c05404c84498/contributing.md), it saves us a few steps.

**Comment by JimBobSquarePants** [comment]
Closing due to lack of response.
