### ISSUE TITLE
resizing and ProPhoto RGB

### ISSUE THREAD

**Issue by joshball** [JimBobSquarePants/ImageProcessor#465]
First, I know very little about image theory... ;-)
We have been using imageprocessor to resize for a while now. No issues.
However, we just had an image come through that, when resized, its "color" would change (naive term, I know, but it basically got brighter):

Original Image:
Processed with: /remote.axd/path/18_raw.jpg
![18_raw](https://cloud.githubusercontent.com/assets/127526/18183030/5899a186-7047-11e6-8f58-80fd4eb258db.jpg)

Resized Image:
Processed with: /remote.axd/path/18_raw.jpg**?height=700**
![18_raw t](https://cloud.githubusercontent.com/assets/127526/18183036/5d9b7e48-7047-11e6-9bf2-e9b0e8ef3d43.jpg)

I started googling around and looking into exif. I found that the original image was created as a "ProPhoto RGB". I found a few articles, notably [this one](https://www.apnphotographyschool.com/concepts/working-spaces-srgb-vs-adobe-rgb-vs-prophoto-rgb/). After reading the general gist of "color mgmt", and this particularly:

> But there are no printers and monitors which can output ProPhoto RGB. Thus, before using the image in the target medium it’s recommended to convert to the target color-space and let go off the bloat.

I thought it might have to do with what I am seeing.

Can anyone suggest if this "lightening" is expected. And suggest what should be done (ask photographer to not use ProPhoto?)

Thanks!

**Comment by JimBobSquarePants** [comment]
Hi @joshball really sorry bout the slow reply. I actually posted one a few days but it must not have actually registered on the server.

Having a look at the colourspace I would definitely expect some difference in colours. However an increased brightness is a surprise. I would have expected a decrease in tonality. Unfortunately I have no way to know what System.Drawing does when decoding an image with varying spaces. 

My advice would be not use something like photoshop to convert ProPhoto to sRGB for furture web processing.

I hope that helps.   

James
