### ISSUE TITLE
Property cannot be found - when processing animated gif

### ISSUE THREAD

**Issue by czerwiakowskim** [JimBobSquarePants/ImageProcessor#473]
When trying to process animated gif (scale down) I have below error:

[ArgumentException: Property cannot be found.]
   System.Drawing.Image.RemovePropertyItem(Int32 propid) +476289
   ImageProcessor.ImageFactory.ClearExif(Image image) +141
   ImageProcessor.ImageFactory.Save(Stream stream) +93
   ImageProcessor.Web.HttpModules.<ProcessImageAsync>d__32.MoveNext() +3722
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +71
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +9770477

Reference image is available here: http://vandorsenartistsmedia.blob.core.windows.net/media/7645/zmniejszony.gif

Packages versions are:

ImageProcessor" version="2.4.4.0" targetFramework="net45"
ImageProcessor.Web" version="4.6.4.0" targetFramework="net45"
ImageProcessor.Web.Config" version="2.3.0.0" targetFramework="net45"

Wha I'm missing?

**Comment by JimBobSquarePants** [comment]
I don't think you're missing anything if you are using those versions. 

I was absolutely sure I'd got rid of this bug a while back. I'll double check against the latest build.

**Comment by czerwiakowskim** [comment]
Super! Thanks a lot, I'm first to test it ;)

**Comment by JimBobSquarePants** [comment]
Fixed in latest release 2.4.5
