### ISSUE TITLE
Encoding Errors on incoming image URLs

### ISSUE THREAD

**Issue by CVertex** [JimBobSquarePants/ImageProcessor#478]
Hey,

I'm using ImageProcessor to process some images for our customers. Recently, people started sharing these URLs on facebook and IP is not decoding parameters correctly.

Instead of the URL https://muru.info/remote.axd?https://i.scdn.co/image/8851b36688b767d01a00c7d1f0981997db0062d2?width=512&startcolor=aad774&endcolor=ac2833

Facebook is asking for 

https://muru.info/remote.axd?https%3A%2F%2Fi.scdn.co%2Fimage%2F8851b36688b767d01a00c7d1f0981997db0062d2%3Fwidth=512&startcolor=aad774&endcolor=ac2833

and as a results, we're getting errors like so:

![image](https://cloud.githubusercontent.com/assets/120773/18739312/f73c508c-80e5-11e6-87ac-42fedfa8e436.png)

How can I fix this? Shouldn't IP automatically detect these encoded URLs?

Any help is greatly appreciated.

Thanks

**Comment by JimBobSquarePants** [comment]
Hi Vijay,

This will be the line in question. Should be easy enough to test and fix.

https://github.com/JimBobSquarePants/ImageProcessor/blob/1daf15cb83cd7b715192260acfdf76aca8dc3b9f/src/ImageProcessor.Web/Services/RemoteImageService.cs#L78

I'll have a look asap, though feel free to have a peek yourself.

Cheers

James

**Comment by JimBobSquarePants** [comment]
Looks like I've fixed it in source. I tested it in the test website with your encoded url.

 Could you have a look to be sure though.

**Comment by JimBobSquarePants** [comment]
Fixed in latest release 4.6.5

**Comment by CVertex** [comment]
@JimBobSquarePants 
I only just came back to look at this properly!
Thanks for fixing this! You're a legend

**Comment by JimBobSquarePants** [comment]
No problemo 😎
