### ISSUE TITLE
Image Crop Background Color Problem?

### ISSUE THREAD

**Issue by oguzhansari** [JimBobSquarePants/ImageProcessor#479]
I Image resize.
Sizing Type: "BoxPad".
I can not change the background color. :(
Image position: center.

imgfac.Load(InputStream.ToArray());
imgfac.BackgroundColor(Color.White);
ResizeLayer RL= new ResizeLayer(new Size(200, 400, ResizeMode.BoxPad, anchorPosition: AnchorPosition.Center);

I can not change black color. :(

<a href="http://hizliresim.com/VEBlMV"><img src="http://i.hizliresim.com/VEBlMV.jpg" width="200"></a>
<br><br>
<a href="http://hizliresim.com/nEyAWg"><img src="http://i.hizliresim.com/nEyAWg.jpg" width="200"></a>
<br><br>
<a href="http://hizliresim.com/vZygpR"><img src="http://i.hizliresim.com/vZygpR.jpg" width="200"></a>
<br><br>
<a href="http://hizliresim.com/1N7YgD"><img src="http://i.hizliresim.com/1N7YgD.jpg" width="200"></a>

**Comment by oguzhansari** [comment]
I added the background color after resizing.
Successful conclusion :)

**Comment by JimBobSquarePants** [comment]
Glad your figured this out. The lack of alpha channel in jpegs throws a lot of people off.
