### ISSUE TITLE
ImageProcessorCore throws "Invalid bmp colormap size '1024'"

### ISSUE THREAD

**Issue by vdachev** [JimBobSquarePants/ImageProcessor#482]
Hello,

First of all, I want to thank you for the awesome job you have done on porting `ImageProcessor` to the .NET Core!

I've been playing around with it... and tried to load a 24-bit Bitmap file (I converted a JPEG image w/ Paint) and it failed with the following exception:

> Invalid bmp colormap size '1024'

which is obviously thrown on line 109 of _[BmpDecoderCore.cs](https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/src/ImageProcessorCore/Formats/Bmp/BmpDecoderCore.cs)_:

```csharp
// 255 * 4
if (colorMapSize > 1020)
{
  throw new ImageFormatException($"Invalid bmp colormap size '{colorMapSize}'");
}
```

I admit I am not aware of any BMP specifications but the fact that an error is thrown on a seemingly valid file (note `ImageProcessor` loads the file correctly) is bothering me.

**Comment by JimBobSquarePants** [comment]
Yup... That's a bug. Should be 1024. 

`Math.Pow(2, 8) * 4 = 1024`
