### ISSUE TITLE
Any sample somewhere?

### ISSUE THREAD

**Issue by JeanCollas** [JimBobSquarePants/ImageProcessor#485]
Can we find a sample of upload+use of imageprocessor somewhere? :)

**Comment by JimBobSquarePants** [comment]
Hi Jean, 

I'm not sure what you mean. Do you mean the new ImageProcessor Core library or the ImageProcessor Framerwork library that is a wrapper around `System.Drawing`?

Both libraries contain constructors that accept a stream.

ImageProcessor Core

```
Image image = new Image(stream)
```

ImageProcessor 
```
using (ImageFactory factory = new ImageFactory(stream)) {
}
```

File uploads us a [HttpPostedFileBase](https://msdn.microsoft.com/en-us/library/system.web.httppostedfilebase(v=vs.110).aspx) class to represent the binary information. This class has a property, `InputStream` which you could pass to either library for manipulation.

Does that help?

Cheers

James

**Comment by JeanCollas** [comment]
It for  core version. I guess it helps, I will try to check that tomorrow! [😊]


________________________________
De : James Jackson-South <notifications@github.com>
Envoyé : jeudi 6 octobre 2016 02:07
À : JimBobSquarePants/ImageProcessor
Cc : Jean Collas; Author
Objet : Re: [JimBobSquarePants/ImageProcessor] Any sample somewhere? (#485)


Hi Jean,

I'm not sure what you mean. Do you mean the new ImageProcessor Core library or the ImageProcessor Framerwork library that is a wrapper around System.Drawing?

Both libraries contain constructors that accept a stream.

ImageProcessor Core

Image image = new Image(stream)


ImageProcessor

using (ImageFactory factory = new ImageFactory(stream)) {
}


File uploads us a HttpPostedFileBase<https://msdn.microsoft.com/en-us/library/system.web.httppostedfilebase(v=vs.110).aspx> class to represent the binary information. This class has a property, InputStream which you could pass to either library for manipulation.

Does that help?

Cheers

James
