### ISSUE TITLE
How crop image polygonic?

### ISSUE THREAD

**Issue by Radzhab** [JimBobSquarePants/ImageProcessor#488]
Does this lib support crop image by shape?

**Comment by JimBobSquarePants** [comment]
Which lib? 

Could you please read the contribution guidelines.

**Comment by Radzhab** [comment]
imageprocessor lib.

**Comment by JimBobSquarePants** [comment]
I believe you are referring to masking. This is possible as identified in the documentation.

http://imageprocessor.org/imageprocessor/imagefactory/mask/
