### ISSUE TITLE
ColorTranslator and HTML colors?

### ISSUE THREAD

**Issue by Gillardo** [JimBobSquarePants/ImageProcessor#491]
Trying to get rid of System.Drawing and use this code (excellent btw), but i need to be able to convert colors from HTML (which i believe you can do using the constructor to color?) and then back from Color to HTML string...

Is this inbuilt into this code??  if so, where?

**Comment by dlemstra** [comment]
I am guessing that you are using the .Core version because of your comment about the constructor. You are right that it already works with the constructor of Color. But I send a pull request (#500) that will add support for going to and from a hexadecimal color with a `ToHex` and `FromHex` method.

**Comment by JimBobSquarePants** [comment]
@Gillardo As of version 1.0.0-alpha1078 you can now do this. 😄

**Comment by Gillardo** [comment]
Thank you @jimbobsquarepants will try this as soon as I can!
