### ISSUE TITLE
Trimming

### ISSUE THREAD

**Issue by AntonPetrov83** [JimBobSquarePants/ImageProcessor#493]
Hi!

Is it possible to do a trimming of an image? I mean to find the rectangle containing all non-transparent pixels of an image and then crop the image with this rectangle?

How should API be implemented in an idiomatic way?

**Comment by robertjf** [comment]
@antonpetrov83 you probably want to take a look at EntropyCrop:

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/entropycrop/

**Comment by JimBobSquarePants** [comment]
Thanks @robertjf. @AntonPetrov83 is that what you are after?
