### ISSUE TITLE
Bit depth is not supported or not valid

### ISSUE THREAD

**Issue by judypol** [JimBobSquarePants/ImageProcessor#494]
when I resize a png,then got the error Bit depth is not supported or not valid.and debug I can get the this.header.BitDepth=16.

**Comment by JimBobSquarePants** [comment]
Hi there,

Can you please reread the contributions guidelines that were highlighted to you when raising this issue and provide me with the relevant information to debug. You've left me with very little to go on. 

Cheers

James
