### ISSUE TITLE
What about 16bpp4444 and other formats?

### ISSUE THREAD

**Issue by AntonPetrov83** [JimBobSquarePants/ImageProcessor#496]
Do you plan to support 16bpp4444  and other non-standard formats found in video-games and mobile-games industry? Looks like sticking to System.Drawing.Imaging.PixelFormat is a limiting choice.
Maybe it is possible to indroduce custom formats with any bit depth per channel up to 32-bits?

**Comment by JimBobSquarePants** [comment]
Do you mean in Core? If so, yeah. The library is designed with that in mind and doesn't use PixelFormat nor System.Drawing. `Image` actually implements the `Image<TColor, TPacked>` class allowing developers to implement their own color models in the same manner as Microsoft XNA Game Studio and MonoGame. I'll probably add the relevant color models myself though when I get time. 

If you mean the Framework version then no. It's a wrapper around GDI+ so suffers from the same limitations.
