### ISSUE TITLE
Github homepage

### ISSUE THREAD

**Issue by oliverjanik** [JimBobSquarePants/ImageProcessor#498]
When I go to https://github.com/JimBobSquarePants/ImageProcessor it takes me to "Core" branch which has readme which talks about this lib being in alpha/pre-release. This confused me for a while because I came from nuget.org where the package is already at 2.x.y

I'm assuming master is the main branch here: https://github.com/JimBobSquarePants/ImageProcessor/tree/master

Which has a much more up to date README.

Any way to fix the main repo page?

**Comment by dlemstra** [comment]
The Core branch is for the rewrite that makes it possible to use this library in .NET Core. That part is still in alpha/pre-release. The master branch is indeed the code for the current NuGet package but as you can read under the roadmap (https://github.com/JimBobSquarePants/ImageProcessor/tree/master#roadmap) the focus will be on ImageProcessorCore and that is why this is not the primary branch.
