### ISSUE TITLE
Only one instance per service type possible

### ISSUE THREAD

**Issue by mortenbock** [JimBobSquarePants/ImageProcessor#502]
If I want to set up the CloudImageService to be used with two different prefixes, it seems that ImageProcessor is not able to fetch the configuration for it.

When fetching the settings in ImageProcessorConfiguration.cs, it uses the name of the type:

![2016-10-24_1354](https://cloud.githubusercontent.com/assets/1760256/19644797/0a3622c4-99f2-11e6-8d94-4d75a826b3d9.png)

But you can supply any name you want in the config:
![2016-10-24_1357](https://cloud.githubusercontent.com/assets/1760256/19644796/0a32fedc-99f2-11e6-964a-000a35d32841.png)

Is this intentional, or is this a bug in the ImageProcessorConfiguration?

**Comment by JimBobSquarePants** [comment]
Good spot! I would say that's a bug. Services should be reusable.

**Comment by leddt** [comment]
I encountered the same issue.

As a workaround, you can define a new class inheriting from the service that you want to duplicate:
```csharp
public class CloudImageService2 : CloudImageService {}
```
and reference it in your config:
```xml
<service name="CloudImageService2" type="Your.Namespace.CloudImageService2, YourAssembly">
```

**Comment by JimBobSquarePants** [comment]
Bad news I'm afraid...

The only way I can fix this is to change the `IImageService` interface which I cannot do without a major version and I doubt there will ever be a V5. (What with the excellent progress of [ImageSharp](https://github.com/JimBobSquarePants/ImageSharp) and the move to netcore) so I'm going to close this as wontfix but document the workaround in the ImageProcessor docs.
