### ISSUE TITLE
Alpha ignored when applying greyscale filter

### ISSUE THREAD

**Issue by neilw1** [JimBobSquarePants/ImageProcessor#504]
Hello,
Apologies if this is not a bug. Using ImageProcesser version 2.4.1.0. I have a colour image (below stored in iFac, which is an ImageFactory). I then push it into another ImageFactory (iGreyscaleFac). I then convert it to grey scale (the code below was the best way I could think of!)

I also have a set of controls that adjust brightness, contrast, etc. of the iFac object. All adjustments are reflected in the greyscale version except Alpha. If I adjust alpha on my colour image so it is complete white, the greyscale image is unchanged, and any other percentage has no effect either. This was from a jpeg image.

```
iFac.Alpha(value);  //just a line to show alpha was adjusted, the code applies all changed
Stream s = new MemoryStream();
ifac.Save(s);
iGreyscaleFac.Load(s);
iGreyscaleFac.Filter(ImageProcessor.Imaging.Filters.Photo.MatrixFilters.GreyScale);
```

thanks.

**Comment by JimBobSquarePants** [comment]
Hi @neilw1 

Sorry for the slow reply. Jpeg images do not store an alpha channel so no alpha changes will be persisted. If you used a png you should see the expected changes.

Hope that all makes sense.

Cheers

James
