### ISSUE TITLE
Url encoding in remote image service

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#506]
Hello again,

This issue is related to #487 There are issues with URL decoding in the remote image service. Here's an example of passing a valid url to remote.axd **without** encoding it first.
`/remote.axd?https://external.xx.fbcdn.net/safe_image.php?d=AQBKGZEQAA7QoMzM&url=http%3A%2F%2Fwww.gotakanal.se%2Fmedia%2F1566%2Fbildspel_1440x780.jpg%3Fanchor%3Dcenter%26mode%3Dcrop%26width%3D1024%26rnd%3D130921477360000000`

This results in the following URL being parsed by the service:
`https://external.xx.fbcdn.net/safe_image.php?d=AQBKGZEQAA7QoMzM&url=http://www.gotakanal.se/media/1566/bildspel_1440x780.jpg?anchor=center&mode=crop&width=1024&rnd=130921477360000000`
Which is **incorrect**. The encoded querystring of the valid url has now been decoded.

Now you'd think the solution to this would be to first encode the url before passing it to remote.axd
`https%3A%2%2Fexternal.xx.fbcdn.net%2Fsafe_image.php%3Fd%3DAQBKGZEQAA7QoMzM%26url%3Dhttp%253A%252F%252Fwww.gotakanal.se%252Fmedia%252F1566%252Fbildspel_1440x780.jpg%253Fanchor%253Dcenter%2526mode%253Dcrop%2526width%253D1024%2526rnd%253D130921477360000000`
However, this gives the exact same incorrect result as above.

I'm not sure how to solve this. I think the best solution would be to require that the passed url is encoded. Even though this might be a breaking change, it wouldn't really make a difference since the URL is already decoded (incorrectly) today.

**Comment by JimBobSquarePants** [comment]
>This results in the following URL being parsed by the service:
https://external.xx.fbcdn.net/safe_image.php?d=AQBKGZEQAA7QoMzM&url=http://www.gotakanal.se/media/1566/bildspel_1440x780.jpg?anchor=center&mode=crop&width=1024&rnd=130921477360000000
Which is incorrect. The encoded querystring of the valid url has now been decoded.

I don't follow.. Which parts of the url are incorrectly decoded?

I'm not even sure there is a solution to this. There's no way to determine which parts should and should not be decoded. I use only the built in Microsoft tools to [decode the url](https://github.com/JimBobSquarePants/ImageProcessor/blob/2a747188b14cdac88272e1a7b97bf1df5fc91093/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L839) and I can only do an all-or-nothing approach. 

Perhaps you would need to write your own `IImageService` implementation?

**Comment by ZNS** [comment]
In the first example the url passed to remote.axd is already correct
`https://external.xx.fbcdn.net/safe_image.php?d=AQBKGZEQAA7QoMzM&url=http%3A%2F%2Fwww.gotakanal.se%2Fmedia%2F1566%2Fbildspel_1440x780.jpg%3Fanchor%3Dcenter%26mode%3Dcrop%26width%3D1024%26rnd%3D130921477360000000`
The url contains a query "url" which needs to be kept encoded for the url to be valid.

We need to treat the whole passed url as a query parameter. So simply decoding it once (instead of the decode loop) should be enough? Doing that would still break the example above, but as I mentioned if we'd first encode the url above and then pass it to remote.axd it would work.

Writing my own service will only work if the url passed to it is untouched, as it is now I think it runs DecodeUrlString before passing it to the service?

**Comment by JimBobSquarePants** [comment]
Ok coke, 

Could you perhaps provide a PR for this? You have the urls to test against and know what to look out for.

**Comment by ZNS** [comment]
I'm looking into it adding a helper for decoding and writing some tests. However when I check the code it seems you decode the whole raw url "http://domain.com/remote.axd?http://someurl/?width=640&height=640" Is there a reason for this instead of just decoding the passed url "http://someurl/" in the example?

**Comment by JimBobSquarePants** [comment]
Thanks 👍 

Yeah, if the passed url is encoded then `Response.Url` is incorrect only containing a partial url.

**Comment by ZNS** [comment]
Yeah, I see this is about fixing #478 I don't really see a good way of supporting that kind of URL without (as now) breaking other valid urls. Also the fix that's in place now will not work for all urls, like the one in the example above. I'm adding a workaround for it, but it's not very pretty.

**Comment by JimBobSquarePants** [comment]
@ZNS I'm assuming I can go ahead and close this now?

**Comment by ZNS** [comment]
Yep
