### ISSUE TITLE
Ignore unrecognized querystring params

### ISSUE THREAD

**Issue by robbaman** [JimBobSquarePants/ImageProcessor#508]
Is there a way to make ImageProcessor just ignore the unrecognized querystring parameters? We use additional querystring parameters for varying purposes but after upgrading ImageProcessor from 2.3.3.0 to 2.4.5.0 and ImageProcessor.Web from 4.5.3.0 to 4.6.6.0 we get the error `The request {request.Unvalidated.RawUrl} could not be understood by the server due to malformed syntax.`

This wasn't the case in the past and now our application is littered with places where the images suddenly no longer work. I'd hate to have to stay stuck on an older version of ImageProcessor because of this...

**Comment by JimBobSquarePants** [comment]
Yes there is.

Use the [`ImageProcessingModule.ValidatingRequest`](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events) event to reject calls or augment the querystring for requests. 

Theses changes were an important security addition designed to present DDOS attack. You can see the conversation that led to the change of behaviour [here](https://github.com/JimBobSquarePants/ImageProcessor/issues/49).

Hope that helps

James

**Comment by robbaman** [comment]
Considering the security implications I suppose we should just not do what we did. It's a bit of a shame that I have to find out what querystring params are added to an image url anywhere in the application and why, but the security concerns are obviously valid. 

Thanks for taking the time to answer the question.

**Comment by JimBobSquarePants** [comment]
No problem at all. 

We really tried hard to do something that would affect the bare minimum of users negatively but also protect you in the best way possible. Unfortunately it's not possible to cater for all scenarios.
