### ISSUE TITLE
DiskCache files are never deleted

### ISSUE THREAD

**Issue by devnutmike** [JimBobSquarePants/ImageProcessor#511]
Using ImageProcessor.Web 4.5.3  

Looking at the code, it seems cached files should be deleted after maxDays, however, in my application they are never deleted and the cache just keeps growing. I have max days set to 90 and there are files in the cache created over 6 months ago. 

The DiskCache implementation logs exceptions that occur during a file deletion, but I'm unsure how to implement logging or turn on logging:
ImageProcessorBootstrapper.Instance.Logger.Log<DiskCache>("Unable to clean cached file: " + fileInfo.FullName...

Here is my cache.config:

<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="DiskCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="90">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
  </caches>
</caching>

**Comment by dlemstra** [comment]
Would you mind sharing how you solved this for future readers?

**Comment by JimBobSquarePants** [comment]
By default, the logger logs to the console window which you can see by attaching a debugger. Implementing your own logger is actually quite simple. If you create an implementation of `ImageProcessor.Common.Exceptions.ILogger` the library will automatically pick it up and replace the default implementation.

Here's an example one I wrote for the [Umbraco CMS](https://github.com/umbraco/Umbraco-CMS/blob/fcca95787b30d88d6733f22faa7e848e055df331/src/Umbraco.Core/Logging/ImageProcessorLogger.cs)
