### ISSUE TITLE
Saving image with alpha padding

### ISSUE THREAD

**Issue by AtomicSpider** [JimBobSquarePants/ImageProcessor#514]
Hi Jim,
I'm trying to resize a 1000x1000px png image to 500x500px image and trying to save it as 1000x1000 image with 250px padding on all sides. 

This is what I'm using.

```
imageFactory.Load(inStream)
.Resize(new size(500,500))
.Resolution(1000,1000);
.Save(outStream);
```

But it's saving the file as 500x500png and not as 1000x1000 png

**Comment by JimBobSquarePants** [comment]
Hi @AtomicSpider 

Sorry for the slow reply! You'll need to use the `Resize` method twice. First time to scale the image down and the second time to pad the image. You would use the `Resize(ResizeLayer resizeLayer)` overload to do so with `ResizeMode.BoxPad`. 

http://imageprocessor.org/imageprocessor/imagefactory/resize/#example

`Resolution` only changes EXIF values for print
http://imageprocessor.org/imageprocessor/imagefactory/resolution/

Hope that helps!

Cheers

James

**Comment by AtomicSpider** [comment]
@JimBobSquarePants Thanks for the help. I'll give it a try.

PS: Kudos for your amazing work creating this library. You have seriously made life easier for a lot of us :)

**Comment by JimBobSquarePants** [comment]
@AtomicSpider That's really great to hear! 😄
