### ISSUE TITLE
DiskCache is not cleaned

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#517]
Hello again!

I'm using the default diskcache implementation and so I thought cached files should be deleted after 365 days? It seems this isn't the case. Wrote some code to enumerate through the files in the cache and in our dev environment about half of the files should have expired.

Would it cause any conflict deleting these files and empty directories with a batch job or similar?

**Comment by JimBobSquarePants** [comment]
Errrrmmmm.... It should delete them. What version are you running?

I know, in the past there was a bug but that was fixed in the following commit.

https://github.com/JimBobSquarePants/ImageProcessor/pull/376/commits/9aa7dc2ddb448615d237d502f8eaed0f3938e0f8

Maybe what you are seeing is the remnants of the prior bug. Or maybe the spread of file distribution is not as even as I hoped.

Deleting the files shouldn't cause a problem.

**Comment by ZNS** [comment]
I've just looked at it very quickly but it looks like the cache is only trimmed if a request is made for an image that should be expired. So if an image is created once but then never requested anymore (or not requested after it's expiration) it will remain in the cache indefinitely?

**Comment by JimBobSquarePants** [comment]
Not quite, 

When an image is newly cached the system will find its parent directory and enumerate through any child directories deleting any files that are expired.

Since distribution of characters in an SH1 hash is fairly even this should ensure that for cleanup happens evenly across the cache.

https://github.com/JimBobSquarePants/ImageProcessor/blob/e986b06d010a4858b3a1442767d5ae8e329cc16f/src/ImageProcessor.Web/Caching/DiskCache.cs#L190

**Comment by ZNS** [comment]
I'm sure I'm wrong, because I don't have any understanding of how you build the cache paths. But it looks to me as a request is made for example "/cache/a/b/c/d/image.png" then the TrimCache() takes the parent directory of that image "/cache/a/b/c" and cleans the subdirectories?

So what if an image is created in "/cache/0/1/2/3/image2.png" and then after a year nothing is requested in "/cache/0/1/2" how would that get cleaned, or perhaps it shouldn't happen that no requests are made for that path?

**Comment by JimBobSquarePants** [comment]
Pretty much yeah.

In your first example the cached path would be something like
```
/cache/a/b/c/d/e/f/abcdefghijklmnopq.png
```
When that image is saved the cache will move up to the parent folder of the containing directory `/e/` and will search through all the subdirectories deleting any expired files.

This means that the cache cleaning mechanism is more active for websites that are constantly adding or updating their images. Basically scaling as the website does. 

If you don't add/update any images for a year then the cache cleaner will not kick in until a year has passed and it re-processes the request. There's really no need for it to do so until then.

All this was buggy until a few months back though.

**Comment by ZNS** [comment]
Ok, I like the idea but I'm not convinced :) Is the folder path randomly generated? 6 characters (1 per level) from a set of 16 characters? In that case imagine we cache one image. After it expires we cache another image. If my math isn't completely off it's about one in a million that it'd be generated in the same or a sibling directory to the first one. So we might have to cache a million new images, _after the first one expires_, for the first one to be cleaned? I apologize if my math is way off :)

**Comment by JimBobSquarePants** [comment]
Hmmm... You might well be correct here. Expecting a hash algorithm with a fairly even distribution and low collision rate to generate the same first 6 characters is a bit hit and hope.  I should probably go right up the root and clean down. That's only 1-36 then.

**Comment by ZNS** [comment]
Yes, however then I guess it becomes a question about if you want to go through the entire tree structure on each EndRequest? At least it should be optional through some setting. Personally I'd probably prefer having a job that cleans the cache every day or so.

**Comment by JimBobSquarePants** [comment]
Scheduled tasks are a nightmare though. I'll start doing the maths on sensible probability.

**Comment by ZNS** [comment]
Yes, I meant that if you could disable cache cleaning in ImageProcessor (if it'd be to processor heavy) you could create your own scheduled task outside of image processor to do it. It's pretty much one command line. Anyway,

**Comment by JimBobSquarePants** [comment]
@ZNS I've changed the behaviour.

The cache now jumps up to the root and runs through 1/36th of the cache cleaning up any orphaned or expired files whenever a new image is cached. The process will jump out quickly if it finds nothing to clean so I'm not worries about overhead.
