### ISSUE TITLE
Allow image cache folder to exist outside of the web root - so FCN doesn't become an issue

### ISSUE THREAD

**Issue by Shazwazza** [JimBobSquarePants/ImageProcessor#518]
I've tried setting the IP cache to something like:

~/../TEMP/App_Data/TEMP/IP/cache

But it throws an exception saying it cannot traverse past the web root. However, more and more people are reporting issues with FCN and before we used to just set it to Single but this is only a band aid in hopes that it fixes the problem. Part of the problem with Single is that it still monitors every folder with a single watcher and the buffer with Single will overflow causing app domains to restart. Alternatively as we know if we set it to Default it will create watchers for every directory and that can be worse.

As it turns out, storing stuff outside of the web root will resolve a lot of the problem since ASP.Net and IIS will not watch these files. It would be super helpful if we could store the IP image cache outside of the www root and in a folder just above it, or by specifying an absolute path. Of course the IIS user will need access to this but that is up to the implementer. 

IP creates a ton of folders and therefore a ton of watchers or paths to watch and I believe it would go a long way to help fix some of the recent issues we're seeing with app domain restarts due to FCN (things like overwhelming changes, etc... I can send  through the errors if you need)

We can probably make a PR for this soon but needed to write this info down here first. Similarly, I'll update CDF to allow this as well.

**Comment by JimBobSquarePants** [comment]
That sounds like both an excellent idea and one that you will have to create a PR for as I have literally no idea where to start. 😄 

Looking forward to seeing the PR!

**Comment by Shazwazza** [comment]
Working on this now, have also updated some of the FCN info and found out just how much is actually monitored, yikes! :/ fcn Single is better for Azure due to remote file systems and having far less watchers but the buffer is smaller and overflows more easily since every folder is still watched. Will report back more next week.

**Comment by JimBobSquarePants** [comment]
Ah good.... If you have the opportunity to log your findings somewhere please do. I'd be very keen to know more about how it works.

**Comment by Shazwazza** [comment]
Here's the PR with lots of details :)

**Comment by JimBobSquarePants** [comment]
Great to see this in action! 💯
