### ISSUE TITLE
An apparent change in ImageProcessor.Web 4.6.6 has broken the ability to alter the URL in a module before image processing.

### ISSUE THREAD

**Issue by dsargent3220** [JimBobSquarePants/ImageProcessor#519]
We use and HTTP Module that reads the query string and then sets certain defaults and changes the width based on screen resolution and breakpoints.
this worked fine in ImageProcessor.web 4.6.4 but does not work in 4.6.6
I'm not seeing an easy way to determine what all changed between these two versions (no changelog?)
Here's the beginning and ending of our HTTP Module so you can see how we are  doing it.
```cs
public void OnBeginRequest(object sender, EventArgs e)
{
	var context = ((HttpApplication)sender).Context;
	if (context.Request.RawUrl.ToLower().Contains("uploadedimages"))
	{
		string rawPath = context.Request.RawUrl;

		// Get the query string and set it to writable so we can change it later.
		NameValueCollection queryString = context.Request.QueryString;
		var readonlyProperty = queryString.GetType().GetProperty("IsReadOnly", BindingFlags.Instance | BindingFlags.NonPublic);
		readonlyProperty.SetValue(queryString, false, null);


                // Do work here, modify query string, etc, removed for brevity.


		// Set the changed query string back to the context.
		// path should end up bing the path to the image /sample.png
		var path = this.GetVirtualPath(context);

		// If there is no path or the path does not have an extension with a . then just return.
		if (string.IsNullOrWhiteSpace(path) || !path.Contains("."))
		{
			return;
		}

		context.RewritePath(path, string.Empty, queryString.ToString());
		readonlyProperty.SetValue(queryString, true, null);
	}
}
```

**Comment by JimBobSquarePants** [comment]
Yeah see #503 I need to do some work to reenable this kind of functionality. I had to switch to using the Request.RawUrl to handle some bizarre encoding issues that occur when people share urls on Facebook (Request.Url is corrupted and unusable,  See #478) 

Creating something that defaults to Request.RawUrl that can be overwritten, or maybe just making it a configurable setting would both be possible solutions.

**Comment by JimBobSquarePants** [comment]
See #503 for a workaround.
