### ISSUE TITLE
ImageProcessor should use RecyclableMemoryStream for better memory management

### ISSUE THREAD

**Issue by Shazwazza** [JimBobSquarePants/ImageProcessor#520]
ImageProcessor currently creates new memory streams for every request that it needs to handle. It should instead use memory stream buffers. A great library that already does this is:

https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream

It's super easy to use and is a drop-in replacement for MemoryStream. This could easily be used everywhere MemoryStream's are created, especially in the ImageProcessingModule.

I've tested this with my own projects when I use MemoryStreams for small processing and it doesn't yield many different results when running benchmarks in Benchmark.Net, however when processing large streams like images, this should yield some very good results with regards to better memory management and GC

**Comment by JimBobSquarePants** [comment]
I was actually looking at this last night for ImageSharp. Definitely keen to drop it in and give it a go.

**Comment by Shazwazza** [comment]
In.Net Core I think there's ArrayPool and some other stuff for memory stream pool's - I think that perhaps combined with Span<T> and Memory<T> is .Net Core is what David Fowler mentioned at the Summit should be used - which is how I found the RecyclableMemoryStream since he said things have been made outside of the core in the past but now these things will be built into .Net Core.

**Comment by JimBobSquarePants** [comment]
Yeah I've been using `ArrayPool<T>` desparate for `Span<T>` now.

**Comment by JimBobSquarePants** [comment]
Thanks for the advice here. Seemed pretty simple to setup and works well with the default values. Not sure how to test properly memory wise but certainly seems snappier visually.
