### ISSUE TITLE
Should add a throttle check anytime IsNewOrUpdatedAsync is accessed

### ISSUE THREAD

**Issue by Shazwazza** [JimBobSquarePants/ImageProcessor#522]
This would be much better for perf when Image Processor is under high load serving a lot of image requests.

I have code in a few projects that we do a very similar thing. We do this in Umbraco core and in Examine too. Using a thread timer we start the timer whenever this is called, there's 2 values that need to be checked: timer timeout (i.e. 5 seconds) and the max timeout (i.e. 30 seconds). This ends up being a sliding offset, the logic won't be executed if this method keeps getting executed until the timer reaches the max (30 seconds) or if the last request time is larger than 5 seconds.

This means that under high load the perf of this would be much better since it wouldn't have to read from the file system on every request just to check if its out of date. Of course there would be a max of 30 seconds under load if the file did change but that is OK.

**Comment by JimBobSquarePants** [comment]
Sounds good. If you can point me to an example I'll get that implemented.

**Comment by CasperTDK** [comment]
I can also confirm that if you do a stress loading test on a website that uses imageprocessor (500 visits/second for 3 minutes) will cause image loading to be the bottle neck.

I'd be willing to take up the task, if I am guided on how you would like the architecture.

IsNewOrUpdatedAsync  is going 2 critical things. 1 is returning the boolean status
The second is creating the cachedRewritablePath - which is needed later in the code flow.

My guess would be to split these things into several methods and perhaps saving both states above in a cache used when throttleing

**Comment by JimBobSquarePants** [comment]
@CasperTDK Is it those specific calls that causes the bottleneck (no new image requests)?

The reason I ask is that the calls take place within what I call a deduplicate lock which prevents more than one user requesting an image at a time. I do this as it prevents all sorts of potential file locking issues plus any memory issues with System.Drawing.

https://github.com/JimBobSquarePants/ImageProcessor/blob/7ddc33f028e974481203a57800a2f882b4433468/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L545

**Comment by CasperTDK** [comment]
@JimBobSquarePants Honestly not sure. However, i believe the stress-testing should only hit the cache module? and not the imageprocesser module managing system.drawing
