### ISSUE TITLE
AzureBlobCache RewritePath crash when context.Request.Headers["If-Modified-Since"] exists, but is not parsable

### ISSUE THREAD

**Issue by AnthonyCogworks** [JimBobSquarePants/ImageProcessor#523]
This crashes  when context.Request.Headers["If-Modified-Since"] exists, but is not parsable. It's not parsable for some reason when it comes from the Google Bot.

https://github.com/JimBobSquarePants/ImageProcessor/blob/badb62efe67879d5b76bdc8578f707efc5ccd015/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L408

I think the fix for this would be to make it a TryParse. If it returns false, then log the error and return like this:
ImageProcessorBootstrapper.Instance.Logger.Log<AzureBlobCache>("Unable to parse date " + context.Request.Headers["If-Modified-Since"]);

**Comment by JimBobSquarePants** [comment]
Fixed and released
