### ISSUE TITLE
Seemingly valid JPEG has dimensions "0x0" (should be 300x300)

### ISSUE THREAD

**Issue by kierenj** [JimBobSquarePants/ImageProcessor#524]
Here's the file: https://dl.dropboxusercontent.com/u/18385630/Autumn-Gold-sq-panel-cs.jpg

I'm reading it from a stream like this:

```c#
var image = new ImageProcessorCore.Image(byteStream);
```

Many hundreds of files are working fine, but this one gives a `Width` and `Height` of `0`.  No exception until I try to save / crop the image again.

**Comment by JimBobSquarePants** [comment]
Hi there @kierenj. Where did you download the library from?

ImageProcssorCore hasn't existed for months now and the correct repo is [ImageSharp](https://github.com/JimBobSquarePants/ImageSharp)

Bizarrely I've just pushed a fix for CMYK jpegs.

Cheers

James

**Comment by kierenj** [comment]
I'm using `"ImageProcessorCore": "1.0.0-alpha1095"` in my `project.json`, with `<add key="imageprocessor" value="https://www.myget.org/F/imageprocessor/api/v3/index.json"/>` in `MyGet.config`.  I guess I googled and found the lib on or around Sep 14th and perhaps missed the move since then?
I'll switch and give ImageSharp a go for this one perhaps!

**Comment by JimBobSquarePants** [comment]
@kierenj Ok, that's cool. There's just been a few rogue uploads from people to Nuget.

Yeah, definitely give it a go. A lot ha changed since then. All for the better 😄

**Comment by kierenj** [comment]
(This worked just fine, thank you)
