### ISSUE TITLE
FastBitmap memory leak

### ISSUE THREAD

**Issue by doktokto** [JimBobSquarePants/ImageProcessor#527]
I used this code:
```
void Main()
{
            for (int i = 0; i < 100; i++)
            {
                var rect = System.Windows.Forms.Screen.PrimaryScreen.WorkingArea;
                Bitmap Bmp = GDIGetScreenBitmap(rect);
                FastBitmap NewBMP = new FastBitmap((Bitmap)Bmp.Clone());
                Bmp.Dispose();
                NewBMP.Dispose();
            }
}
static Bitmap GDIGetScreenBitmap(Rectangle rect)
{
            Bitmap bmp = new Bitmap(rect.Width, rect.Height, PixelFormat.Format32bppArgb);
            Graphics g = Graphics.FromImage(bmp);
            g.CopyFromScreen(rect.Left, rect.Top, 0, 0, bmp.Size, CopyPixelOperation.SourceCopy);
            g.Dispose();
            return bmp;
}
```
It takes 700-800Mb of memory to 100 screen pictures.

I looked to Dispose() code in FastBitmap.cs and find that the bitmap is not disposed, so I am added:
`
        bitmap.Dispose();
`
to
```
/// <summary>
/// Disposes the object and frees resources for the Garbage Collector.
/// </summary>
/// <param name="disposing">If true, the object gets disposed.</param>
protected virtual void Dispose(bool disposing)
```

Now there is no memory leak anymore.

Sorry, I don't know how to make pull requests.

**Comment by JimBobSquarePants** [comment]
Hi @doktokto 

FastBitmap isn't designed to work like that. It's a wrapper for fast pixel access to the given bitmap. You are responsible for disposing of the given bitmap. If I disposed of the bitmap I would be destroying it before I could do anything with it like passing it off to another method. 

Here's an example of it in use.

https://github.com/JimBobSquarePants/ImageProcessor/blob/dcc2a9d31bfab818b335192e0dcd7b6fea1e516b/src/ImageProcessor/Imaging/Helpers/Effects.cs#L146

Cheers

James
