### ISSUE TITLE
Issue of URL mapping for ImageProcessor.Web

### ISSUE THREAD

**Issue by AndyFelton** [JimBobSquarePants/ImageProcessor#528]
Hi there,

I'm using ImageProcessor.Web with the following configuration:
```
      <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
                <settings>
                        <setting key="Container" value="media.englandhockey"/>
                        <setting key="MaxBytes" value="8194304"/>
                        <setting key="Timeout" value="30000"/>
                        <setting key="Host" value="https://s3.eu-west-2.amazonaws.com"/>
                </settings>
        </service>
```
If I request the following URL `http://www.englandhockey.andyf/library-media/images/brogdon_and_weir_celebrate_480_x_290.jpg?mode=crop&anchor=center&width=480&quality=85&rnd=291120151740` it's requesting the URL `https://s3.eu-west-2.amazonaws.com/media.englandhockey//library-media/images/brogdon_and_weir_celebrate_480_x_290.jpg`. This has a double slash in it which AWS does not respond to with the image.

Is my configuration wrong or does CloudImageService.cs line 98 need some additional code to prevent to double slash.

Thanks
Andy

**Comment by JimBobSquarePants** [comment]
Hi Andy,

Could you possibly supply some version numbers? 

Cheers

James

**Comment by JimBobSquarePants** [comment]
No worries. I'll have a look asap.

If you dig something up before I can get to it please let me know.

Cheers

James

**Comment by AndyFelton** [comment]
Hi James,

I've made a change (to my local copy) in CloudImageService.cs line 104 to do TrimStart('/') on relativeResourceUrl as container should always have a slash at the end as a result of line 101.

I can do a pull request if you want me to?

Thanks
Andy

**Comment by JimBobSquarePants** [comment]
That would be great thanks!

**Comment by JimBobSquarePants** [comment]
Beat you to the punch. Thanks for making it easy to fix with your detective work 😄 

https://www.nuget.org/packages/ImageProcessor.Web/4.7.1

**Comment by AndyFelton** [comment]
Thanks for fixing this and all your work on ImageProcessor
