### ISSUE TITLE
Has anyone had problems with image resizing after image processor 2.3.0?

### ISSUE THREAD

**Issue by abram27** [JimBobSquarePants/ImageProcessor#534]
If I update from 2.3.0 to 2.3.1 or 2.5.1 I get:
MissingMethodException: Method not found: 'Void ImageProcessor.Imaging.ResizeLayer..ctor(System.Drawing.Size, ImageProcessor.Imaging.ResizeMode, ImageProcessor.Imaging.AnchorPosition, Boolean, Single[], System.Nullable`1<System.Drawing.Size>, System.Collections.Generic.List`1<System.Drawing.Size>, System.Nullable`1<System.Drawing.Point>)'.

when calling imageFactory.Load(inStream)
                    .Resize(new ResizeLayer(newSize, resizeMode: resizeMode));

**Comment by JimBobSquarePants** [comment]
I think you must be referencing differences versions of the library at different points. I would recommend cleaning your solution, rebuilding and trying again.

**Comment by abram27** [comment]
Thanks, that seemed to do the trick: cleaned solution, removed folders referencing older packages, and restarted visual studio.
