### ISSUE TITLE
Transparent GIF rendered with black borders

### ISSUE THREAD

**Issue by rasmuseeg** [JimBobSquarePants/ImageProcessor#535]
Hi @JimBobSquarePants 

This might be a duplicate, but my image
http://www.stibographic.com/media/119155/Moelgaard-hvidt-papir.gif?width=940
http://www.stibographic.com/media/119155/Moelgaard-hvidt-papir.gif

Is rendered with black borders.
![GIF rendered with black background](http://www.stibographic.com/media/119155/Moelgaard-hvidt-papir.gif?width=941)

I'm running the lastest versions
```
  <package id="ImageProcessor" version="2.5.1" targetFramework="net45" />
  <package id="ImageProcessor.Web" version="4.7.2" targetFramework="net45" />
```

Any help is much appreciated 👍

**Comment by rasmuseeg** [comment]
Okay, forgot about the cache i think. Its resolved now.

**Comment by JimBobSquarePants** [comment]
Hi @rasmuseeg 

This looks to be the result of the resampling algorithm used by system drawing. That algorithm samples pixels from around those edge pixels which will lead to those borders. Unfortunately the quantizers used in gif and indexed png struggle with those kinds of images after resampling. I'll use your image a a test though now to see if I can tweak them to improve the result.

Cheers

James

**Comment by JimBobSquarePants** [comment]
Oh forgot to say. I really don't recommend upscaling images like this anyway. The quality loss is unpleasant to the eye and you are chewing up bandwidth. Much better if you are going to pains to save the image as a gif, to do so at the correct size.

**Comment by rasmuseeg** [comment]
Hehe, i know. But client don't always follow the rules. I told them i do not recommend gif format for pictures, only logo.

So i fixed it (for now) by converting &format=jpg&bgcolor=fff and upscaling. ;-)

**Comment by JimBobSquarePants** [comment]
Yeah. That's one way to do it. I'll have a look at the quantizers anyway to see if there is anything I can do.

**Comment by JimBobSquarePants** [comment]
I'm gonna have to close this as wontfix I'm afraid as I'd have to implement a new resampler to do this which is out of the scope of the project.
