### ISSUE TITLE
Image resize not correct

### ISSUE THREAD

**Issue by billsliu** [JimBobSquarePants/ImageProcessor#538]
I have an image from phone, the orginal image dimension is 1200px*1800px, width 1200px, height 1800px, the image contains EXIF defined rotation data. I want to resize the image to width 600px. But I got an image 400px*600px, the width is 400px, the height is 600px. It is not my expected. My code is:

```
string fullPath = "c://test.jpg"; // path for the image
using (ImageFactory imageFactory = new ImageFactory(true))
{
	ResizeLayer layer = new ResizeLayer(new Size(600, 0), ResizeMode.Max);
	imageFactory.Load(fullPath).AutoRotate().Resize(layer).Quality(80).Save(fullPath);
}
```

ImageFactory do respect EXIF data, the resized image shows correct in Windows Photos application. But the resize mixed width and height. I want the resized images always have 600px in width no matter what the EXIF data is?

**Comment by JimBobSquarePants** [comment]
Have you tried it without Autorotate? That method is there for rotating images to the correct format when you are not preserving EXIF data.

**Comment by billsliu** [comment]
I first tried without Autorotate, then I add Autorotate, both are same.

**Comment by JimBobSquarePants** [comment]
Well can then please share the image? There's nothing I can do without it.

**Comment by JimBobSquarePants** [comment]
Oh hold on! Take away the Max stuff, you should just be doing 

```
.Resize(600, 0)
``

**Comment by billsliu** [comment]
I simplify the code, it is still the same result, it is always 450*600, height is 600px. The link is the test image file [http://demo.clubclouds.com/test.jpg](url) 
```
string fullPath = "c://test.jpg"; // path for the image
using (ImageFactory imageFactory = new ImageFactory(true))
{
	imageFactory.Load(fullPath).Resize(new Size(600, 0)).Save(fullPath);
}
```

**Comment by JimBobSquarePants** [comment]
Thanks for providing the image. It was invaluable in making sure nothing was wrong with my library.

`System.Drawing` doesn't swap dimensions if the image has EXIF rotation data. Technically that is correct. 

Jpeg files have specific values in the file header which defines the width and height of the image. `System.Drawing`, like any other library will read those values to determine the correct dimensions and layout of the byte array to store that image data. EXIF metadata is additional, unrelated data that is sometimes used to determine how the image is displayed (i.e. rotation). 

This data does not determine how the width and height of an image is determined and calculated. Software like Photoshop might (I haven't tested) present the image in a rotated fashion with the dimensions swapped to make it less confusing for the end user but a graphics library will not.

To prove this I wrote the resizing method using `System.Drawing` API to test against the image. The result is the same. 

``` csharp
string fullPath = "c://test.jpg"; 
using (Image image = Image.FromFile(fullPath, true))
{
    int width = 600;
    int height = Convert.ToInt32(image.Height * 600 / (double)image.Width);

    Bitmap resized = new Bitmap(width, height);

    // Resize the image
    using (Graphics graphics = Graphics.FromImage(resized))
    {
        graphics.CompositingQuality = CompositingQuality.HighSpeed;
        graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
        graphics.CompositingMode = CompositingMode.SourceCopy;

        graphics.DrawImage(image, 0, 0, width, height);

        // Copy the EXIF metadata
        foreach (int id in image.PropertyIdList)
        {
            resized.SetPropertyItem(image.GetPropertyItem(id));
        }

        using (EncoderParameters encoderParameters = FormatUtilities.GetEncodingParameters(100))
        {
            ImageCodecInfo imageCodecInfo =
                ImageCodecInfo.GetImageEncoders()
                    .FirstOrDefault(ici => ici.FormatID == ImageFormat.Jpeg.Guid);

            if (imageCodecInfo != null)
            {
                // Save the results
                resized.Save(fullPath, imageCodecInfo, encoderParameters);
            }
        }
    }
}
```

**Comment by billsliu** [comment]
I found an easy way to rotate the image according the Exif orientation tag and remove Exif orientation tag. It is only thirty lines code. Thanks for your information about ImageProcessor library preserve the Exif data.

**Comment by JimBobSquarePants** [comment]
30 lines of code is a lot! Take a look in my [AutoRotate](https://github.com/JimBobSquarePants/ImageProcessor/blob/7a3247b0017c603229255d55025d547d455527ff/src/ImageProcessor/Processors/AutoRotate.cs) method to see a concise example.

Do you want to preserve the EXIF data or not?

**Comment by billsliu** [comment]
I just check your code, it is great, but I do not want to modify your library, I do not want to implement this function outside of your library and abandon your library. So I just keep this functionality out of my list and keep using your library. 

When web-server processing user upload images, and preserve the Exif data and rotation, it won't display correctly in newest version chrome, firefox, edge, they have their reasons to keep Exif data and rotation, and not display it accordingly. As a smaller player, what I can do, tell the end user open their image with MS Paint and save it, upload the images after saving by Paint.

**Comment by billsliu** [comment]
I just find out your library support remove Exif data and adjust rotation accordingly.

I change my code from
ImageFactory imageFactory = new ImageFactory(**true**)
to 
ImageFactory imageFactory = new ImageFactory(**false**)

Then everything is working perfectly.

**Comment by JimBobSquarePants** [comment]
Oh yeah, remove EXIF and use AutoRotate. Easy! 😄
