### ISSUE TITLE
High cpu usage with 4.7 (diskcache seems to blame)

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#539]
Hi.

Running some Umbraco sites and just released latest version with ImageProcessor 4.7.2 included. This caused 100% cpu usage on the server. Never had that issue before.  I downgraded Imageprocessor and that seems to have worked. My theory is that this was due to the new diskcache clearing. The image cache for a few of these sites are several GB (due to the bad cache cleaning in previous versions of image processor web). 

I ran debugdiag on one of the smaller sites, before downgrading imageprocessor for it. DiskCache seems to be eating alot of CPU.

http://prntscr.com/dv2ykh

Complete analysis is attached.
[MultipleDumps_PerfAnalysis.zip](https://github.com/JimBobSquarePants/ImageProcessor/files/704114/MultipleDumps_PerfAnalysis.zip)

**Comment by JimBobSquarePants** [comment]
Yeah I was worried about this. I'm not sure what to do. The cache wasn't cleaning before so I had to make changes but it's obviously too aggressive especially with larger sites.

The problem is fundamentally a maths one. The folders are nested six levels deep with 36 folder in each level so I have to dig down low enough to ensure there is a probability that the files are deleted but not too low. I'll have to do the maths to find the lowest reasonable value.

**Comment by ZNS** [comment]
I understand that. It'd be great to have an option to simply disable the cache cleaning for now. It's easy enough to clean the files using powershell or command line.

**Comment by JimBobSquarePants** [comment]
Hey @ZNS 

I've made a LOT of changes to the caching mechanism and I'd love your input if I could get it. 

Cheers!

**Comment by nul800sebastiaan** [comment]
For reference, the changes are in this PR: https://github.com/JimBobSquarePants/ImageProcessor/pull/541

**Comment by madsoulswe** [comment]
Could our issue be related to this? Images loads extremely slow after updating to Imageprocessor.Web 4.7.2 (umbraco 7.5.7) 

Example
http://gen-pep.se/media/1359/foretag.png?width=286&height=265
http://gen-pep.se/media/1361/foto-2017-01-16-22-23-34.jpg?mode=crop&quality=90&width=1200&height=600

**Comment by ZNS** [comment]
@madsoulswe It is possible. See this discussion on Umbraco https://our.umbraco.org/forum/using-umbraco-and-getting-started/82312-high-cpu-usage-with-757

**Comment by JimBobSquarePants** [comment]
It will be. A bug was somehow introduced causing the cache to cleanup on every request

**Comment by JimBobSquarePants** [comment]
v4.8.0 should fix all your issues and more. Get it while it's hot!

@ZNS Could you test the cache cleanup before turning it off. Your sites will be a could way to push it.
