### ISSUE TITLE
Feature:  Url parsing in service

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#542]
Hello.. again.

I'm getting quite busy at this project :) I have a request to somehow get the image service into the url parsing pipeline. For example I have a project where I'd like to be able to use image processor web with an url like "/{imageid}/{width}/{height}/" The only way to solve this today I think would be to do some url rewriting and create my own http module overriding the method that returns the request url. I think I'd also need to create my own IImageService to validate the url.

Instead I'd like to be able to perhaps add a new method to IImageService which takes the uri (raw or parsed?) and returns an image processor friendly querystring.

What do you think?

**Comment by ZNS** [comment]
After reading the manual, it seems this should be possible to implement using events. Sorry about that :)

**Comment by JimBobSquarePants** [comment]
No worries 😄
