### ISSUE TITLE
content-length not sent when storing images outside of web root

### ISSUE THREAD

**Issue by alindgren** [JimBobSquarePants/ImageProcessor#544]
Need to set the content-length when using `TransmitFile()` method.

**Comment by alindgren** [comment]
I'm testing a fix now - https://github.com/alindgren/ImageProcessor/commit/a11b32a2d13550793f5a873f4b8198f88d375537

**Comment by JimBobSquarePants** [comment]
Thanks... Disappointed I missed this.

**Comment by alindgren** [comment]
@JimBobSquarePants I think several people were looking at this code and missed it. But this is OSS in action.  PR just submitted :)

**Comment by JimBobSquarePants** [comment]
Fixed in ImageProcessor.Web v4.8.1
