### ISSUE TITLE
ERROR: could not be understood by the server due to malformed syntax

### ISSUE THREAD

**Issue by troyfulton** [JimBobSquarePants/ImageProcessor#547]
I upgraded to the latest nuget version last week, and now images with URL attributes that are not meant for Image Processor gives error:

https://www.screencast.com/t/SVwtIA0roUmW
http://dev-spurr.in2m.net/CMSAdminControls/CKEditor/Plugins/CMSPlugins/images/InsertLink.png?t=F99B

Can you please help.

303-378-5040
troy.fulton@kyamedia.com

**Comment by JimBobSquarePants** [comment]
Hi Troy,

You need to use an event to validate your request. `ImageProcessingModule.ValidatingRequest`

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

For details as to why, please read this epic discussion here https://github.com/JimBobSquarePants/ImageProcessor/issues/49

Hope that all makes sense

James

**Comment by troyfulton** [comment]
Ok, thank you and thank you for the quick response


On Jan 19, 2017, at 5:07 PM, James Jackson-South <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Troy,

You need to use an event to validate your request. ImageProcessingModule.ValidatingRequest

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

For details as to why, please read this epic discussion here #49<https://github.com/JimBobSquarePants/ImageProcessor/issues/49>

Hope that all makes sense

James

**Comment by troyfulton** [comment]
So, i’m using image processor.web in a .net website.

Do you have a more complete example of implementing an event in an asp.net<http://asp.net> website?

For example, which class should I put it in?  Do I just create a new partial class?  etc..

For example, can I just create a callus and

On Jan 19, 2017, at 5:07 PM, James Jackson-South <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Troy,

You need to use an event to validate your request. ImageProcessingModule.ValidatingRequest

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

For details as to why, please read this epic discussion here #49<https://github.com/JimBobSquarePants/ImageProcessor/issues/49>

Hope that all makes sense

James

**Comment by JimBobSquarePants** [comment]
No worries :smile: 

Stick it in Global.asax.cs within  Application_Start That way it is guaranteed to run.

e.g.

```
protected void Application_Start(){

// Register the event handler here.

}
```

**Comment by troyfulton** [comment]
Worked…thank you!


On Jan 19, 2017, at 5:57 PM, James Jackson-South <notifications@github.com<mailto:notifications@github.com>> wrote:


No worries 😄

Stick it in Global.asax.cs within Application_Start That way it is guaranteed to run.

e.g.

protected void Application_Start(){

// Register the event handler here.

}

**Comment by JimBobSquarePants** [comment]
Excellent! Glad I could help.

**Comment by troyfulton** [comment]
Ok, so it turns out that it’s not working.

In the envionrment I’m using some images get generated that I don’t have control over…like images in a WYSIWYG editor etc…and those images have query string params that are not ImageProcessor keywords.  A good example is we’re using CKEditor, and it appends a ?t=F599B at the end, and ImageProcessor causes it ti return a 404.

So, what i’m trying to do is look at the first query string parameter for the ImageProcessor commands I use, and if it is there, then process, if ti’s not, then don’t process.

However, in the code below, nothing gets processed…all images are rendered, but nothing gets processed by ImageProcessor.

Can you please provide any insight you have?

    protected void Application_Start()
    {
        // Register the event handler here.
        ImageProcessingModule.ValidatingRequest += (sender, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.QueryString))
            {

                //Make sure first query parameter is a ImageProcessor command or ignore it
                var queryCollection = HttpUtility.ParseQueryString(args.QueryString);

                if (queryCollection[0].ToString().ToLower().StartsWith("height")||
                queryCollection[0].ToString().ToLower().StartsWith("width") ||
                queryCollection[0].ToString().ToLower().StartsWith("h") ||
                queryCollection[0].ToString().ToLower().StartsWith("w") ||
                queryCollection[0].ToString().ToLower().StartsWith("mode"))
                {
                    return;
                }
                else
                {
                    args.Cancel = true;
                    return;
                }
            }
        };
    }

I also winder if ImageProcessor is interfering with the favicon.ico showing up.  Since I upgraded to latest, none of my sites favicon.ico images show up, however, I can browse directly to the favicon,ico file and it shows up. (could be totally unrelated)



On Jan 19, 2017, at 9:48 PM, James Jackson-South <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #547<https://github.com/JimBobSquarePants/ImageProcessor/issues/547>.

**Comment by chrissfoot** [comment]
I Too have this issue. I can't always control the query string parameters that are added onto my images (many of which I don't want image processor to touch at all) so having imageprocessor return an error whenever there is a query string parameter is completely unworkable in my sites!

**Comment by troyfulton** [comment]
Hi Chris,

James got back to me with this code and it works great.

I it goes in your Application_Start() event in global.asax page.



        ImageProcessingModule.ValidatingRequest += (sender, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.QueryString))
            {
                //Make sure first query parameter is a ImageProcessor command or ignore it
                NameValueCollection queryCollection = HttpUtility.ParseQueryString(args.QueryString);

                // Ignore all but allowed querystrings.
                string[] allowed = { "width", "height", "mode" };
                IEnumerable<string> match = queryCollection.AllKeys.Intersect(allowed, StringComparer.OrdinalIgnoreCase);
                if (!match.Any())
                {
                    args.Cancel = true;
                }
            }
        };




On Jan 26, 2017, at 6:21 AM, chrissfoot <notifications@github.com<mailto:notifications@github.com>> wrote:


I Too have this issue. I can't always control the query string parameters that are added onto my images (many of which I don't want image processor to touch at all) so having imageprocessor return an error whenever there is a query string parameter is completely unworkable in my sites!
