### ISSUE TITLE
When ResizeMode.Min proportionally - there is an aspect ratio problem

### ISSUE THREAD

**Issue by RoyiNamir** [JimBobSquarePants/ImageProcessor#549]
I Have  this   sample Image : 
![image](https://cloud.githubusercontent.com/assets/2842123/22177720/a0fee742-e02c-11e6-8b54-eb5cd886d8b3.png)

size is 300x400 as you can see

Now I wrote a code that should Resize .Min without loosing aspect ratio : 

```
void Main()
{

	byte[] photoBytes = File.ReadAllBytes(@"c:\r\1.jpg");
	// Format is automatically detected though can be changed.
	ISupportedImageFormat format = new JpegFormat { Quality = 100 };
	Size size = new Size(100,200);
using (MemoryStream inStream = new MemoryStream(photoBytes))
	{
		using (MemoryStream outStream = new MemoryStream())
		{
			// Initialize the ImageFactory using the overload to preserve EXIF metadata.
			using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
			{
				
				var r = new ResizeLayer(size,ResizeMode.Min);
				// Load, resize, set the format and quality and save an image.
				imageFactory.Load(inStream)
							.Resize(r)
							.Format(format)
							 .Save(@"c:\r\2.jpg");
			}
			// Do something with the stream.
		}
	}
	 
}
```

It does work but the new Image is distorted: 
![image](https://cloud.githubusercontent.com/assets/2842123/22177731/f815daa4-e02c-11e6-8412-fa09953801b3.png)
Notice that the new size is minus 200 in both X,Y.

And IIR - Resize.MIn should NOT distort the Image.

So I thought maybe it's becuase the rare case subtracting same number from both X,Y.

so No I thoguht lets resize it to  : 100,201 ( and not 100,200)

ANd the result was as expected : 

![image](https://cloud.githubusercontent.com/assets/2842123/22177744/495f3dc4-e02d-11e6-9277-f7faaf3cb600.png)

Please fix this rare case where it distort the image

**Comment by JimBobSquarePants** [comment]
Hi @RoyiNamir 

I had a look at this and I cannot replicate the issue at all. Could you please supply me some version numbers? Without that and a test image there is little I can do.

Cheers

James

**Comment by RoyiNamir** [comment]
Ver 2.5.1.0

Run this code : 

```

void Main()
{
	byte[] photoBytes = File.ReadAllBytes(@"c:\r\1.jpg");
	// Format is automatically detected though can be changed.
	ISupportedImageFormat format = new JpegFormat { Quality = 100 };
	Size size = new Size(100, 200);
	using (MemoryStream inStream = new MemoryStream(photoBytes))
	{
		using (MemoryStream outStream = new MemoryStream())
		{
			// Initialize the ImageFactory using the overload to preserve EXIF metadata.
			using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
			{

				var r = new ResizeLayer(size, ResizeMode.Min);
				// Load, resize, set the format and quality and save an image.
				imageFactory.Load(inStream)
							.Resize(r)
							.Format(format)
							 .Save(@"c:\r\2.jpg");
			}
			// Do something with the stream.
		}
	}
}
```

Against this picture : 

https://www.erdw.ethz.ch/content/specialinterest/erdw/d-erdw/en/personen/profil.person_image.jpeg?persid=206195

**Comment by RoyiNamir** [comment]
BTW , is there any option to "resize to file length" ? I mean People uploading images and I want to resize all pictures so that each will take 60K ( for example)  - is it possible?

**Comment by JimBobSquarePants** [comment]
@RoyiNamir I'll be pushing the fix very soon for your issue. Thanks for your persistence.

>BTW , is there any option to "resize to file length" ? I mean People uploading images and I want to resize all pictures so that each will take 60K ( for example) - is it possible?

No that's not possible with any built in mechanism. You would have to keep resizing and saving to get below your threshold. Only by saving the file to a stream and measuring the length would you know how big it is.
