### ISSUE TITLE
Using &amp; in querstring

### ISSUE THREAD

**Issue by ismailmayat** [JimBobSquarePants/ImageProcessor#550]
I have image url eg

xxx

works fine.

However occasionally in my logs i am getting errors for image urls like

xx
difference here is & has been replaced with &amp; not sure why the & is being replaced.  The error i get is

ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Crop ---> System.ArgumentException: Parameter is not valid.

Using ImageProcessor 2.5.1.

Anyone else seen this before?

Regards

Ismail

**Comment by dlemstra** [comment]
This looks like a bug in your own software? Crop fails because you are not specifying the correct arguments.

**Comment by JimBobSquarePants** [comment]
Hi Ismail,

You'll need to find the cause of your rogue url generation to find this. Looks like you are Html encoding something you shouldn't be.

ImageProcessor.Web (That's what handles the url api) relies on the querystring parameters not being encoded. 

There was an issue in Umbraco I'm sure where they were accidentally doing this but I would have to do a lot of digging to find it. 

Cheers 

James

**Comment by ismailmayat** [comment]
Guys,
Thanks for the reply.  We are definitely not encoding.  The error is intermittent not sure if its a bot or maybe firewall or something else like that mashing up the url.

Will dig a bit more in logs see if i can find anything.

Cheers

**Comment by JimBobSquarePants** [comment]
@ismailmayat Do you have a demo url that causes this?

**Comment by ZNS** [comment]
It's a bit unclear what your url looks like but an url like `www.mydomain.com?width=100&amp;height=100` is valid (since both & and ; are reserved characters) but probably incorrectly encoded and I think it should be treated as that.

**Comment by JimBobSquarePants** [comment]
It'd be HtmlEncoded which is incorrect. I've pushed code to handle it though.
