### ISSUE TITLE
Event Handler Issue/Question

### ISSUE THREAD

**Issue by troyfulton** [JimBobSquarePants/ImageProcessor#551]
Hello,

In the envionrment I’m using some images get generated that I don’t have control over…like images in a WYSIWYG editor etc…and those images have query string params that are not ImageProcessor keywords.  A good example is we’re using CKEditor, and it appends a ?t=F599B at the end, and ImageProcessor causes it ti return a 404.

So, what i’m trying to do is look at the first query string parameter for the ImageProcessor commands I use, and if it is there, then process, if ti’s not, then don’t process.

However, in the code below, nothing gets processed…all images are rendered, but nothing gets processed by ImageProcessor.

Can you please provide any insight you have?

```
    protected void Application_Start()
    {
        // Register the event handler here.
        ImageProcessingModule.ValidatingRequest += (sender, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.QueryString))
            {

                //Make sure first query parameter is a ImageProcessor command or ignore it
                var queryCollection = HttpUtility.ParseQueryString(args.QueryString);

                if (queryCollection[0].ToString().ToLower().StartsWith("height")|| 
                queryCollection[0].ToString().ToLower().StartsWith("width") || 
                queryCollection[0].ToString().ToLower().StartsWith("h") || 
                queryCollection[0].ToString().ToLower().StartsWith("w") || 
                queryCollection[0].ToString().ToLower().StartsWith("mode"))
                {
                    return;
                }
                else
                {
                    args.Cancel = true;
                    return;
                }
            }
        };
    }
```

I also winder if ImageProcessor is interfering with the favicon.ico showing up.  Since I upgraded to latest, none of my sites favicon.ico images show up, however, I can browse directly to the favicon,ico file and it shows up. (could be totally unrelated)

**Comment by JimBobSquarePants** [comment]
I think your logic is falling through. Here's a working, more robust example.

```
ImageProcessingModule.ValidatingRequest += (sender, args) =>
{
    if (!string.IsNullOrWhiteSpace(args.QueryString))
    {
        //Make sure first query parameter is a ImageProcessor command or ignore it
        NameValueCollection queryCollection = HttpUtility.ParseQueryString(args.QueryString);

        // Ignore all but allowed querystrings.
        string[] allowed = { "width", "height" };
        IEnumerable<string> match = queryCollection.AllKeys.Intersect(allowed, StringComparer.OrdinalIgnoreCase);
        if (!match.Any())
        {
            args.Cancel = true;
        }
    }
};
```

Do your favicons have querystring parameters? If not then definitely not.

Cheers

James

**Comment by troyfulton** [comment]
This is great…and working….thank you!


On Jan 24, 2017, at 7:04 PM, James Jackson-South <notifications@github.com<mailto:notifications@github.com>> wrote:


I think your logic is falling through. Here's a working, more robust example.

ImageProcessingModule.ValidatingRequest += (sender, args) =>
{
    if (!string.IsNullOrWhiteSpace(args.QueryString))
    {
        //Make sure first query parameter is a ImageProcessor command or ignore it
        NameValueCollection queryCollection = HttpUtility.ParseQueryString(args.QueryString);

        // Ignore all but allowed querystrings.
        string[] allowed = { "width", "height" };
        IEnumerable<string> match = queryCollection.AllKeys.Intersect(allowed, StringComparer.OrdinalIgnoreCase);
        if (!match.Any())
        {
            args.Cancel = true;
        }
    }
};


Do your favicons have querystring parameters? If not then definitely not.

Cheers

James

**Comment by JimBobSquarePants** [comment]
No worries happy to help 😄
