### ISSUE TITLE
Remote images not working for external.xx.fbcdn.net

### ISSUE THREAD

**Issue by bjarnef** [JimBobSquarePants/ImageProcessor#555]
I am running Umbraco 7.5.8, but have also upgraded `ImageProcessor` to **v2.5.2**, `ImageProcessor.Web` to version **v4.8.1** and Umbraco 7.5.8 already includes the latest version of `ImageProcessor.Web.Config` **v2.3.0.0**.

A similar issue was reported here, but it seems it is still and issue in latest version.
https://github.com/JimBobSquarePants/ImageProcessor/issues/487

Furthermore I have added the following to `security.config`.

```
<whitelist>
    <add url="https://fbcdn.net"/>
    <add url="http://fbcdn.net"/>
    <add url="https://external.xx.fbcdn.net"/>
    <add url="http://external.xx.fbcdn.net"/>
    <add url="https://scontent.cdninstagram.com"/>
    <add url="http://scontent.cdninstagram.com"/>
</whitelist>
```

I am showing a Facebook feed on a website and seems that posts of type "link" often includes external images, since they are referred to the original source, e.g. umbraco.com

For example an image like this from this post https://www.facebook.com/Umbraco/posts/1217147378333251

https://external.xx.fbcdn.net/safe_image.php?d=AQD5NGROUPnFzzxz&url=https%3A%2F%2Fumbraco.com%2Fmedia%2F1283%2Fimage-uploaded-from-ios-1.jpg%3Fanchor%3Dcenter%26mode%3Dcrop%26rnd%3D131305077120000000&_nc_hash=AQDjV6FU50n9gb4C

but when used with remote.axd it returns the following ysod for the request.
```
<img src="/remote.axd/external.xx.fbcdn.net/safe_image.php?d=AQD5NGROUPnFzzxz&url=https%3A%2F%2Fumbraco.com%2Fmedia%2F1283%2Fimage-uploaded-from-ios-1.jpg%3Fanchor%3Dcenter%26mode%3Dcrop%26rnd%3D131305077120000000&_nc_hash=AQDjV6FU50n9gb4C" alt="" />
```

![image](https://cloud.githubusercontent.com/assets/2919859/22591600/ae32bda6-ea15-11e6-9c03-8bf4db432a59.png)

I have no issues with the remote images from `scontent.cdninstagram.com` and `fbcdn.net`.

**Comment by JimBobSquarePants** [comment]
You're not adding any ImageProcessor.Web querystring parameters so the parser cannot recognize anything.

```
/remote.axd/external.xx.fbcdn.net/safe_image.php?d=AQD5NGROUPnFzzxz&url=https%3A%2F%2Fumbraco.com%2Fmedia%2F1283%2Fimage-uploaded-from-ios-1.jpg%3Fanchor%3Dcenter%26mode%3Dcrop%26rnd%3D131305077120000000&_nc_hash=AQDjV6FU50n9gb4C?width=100
```

should work.

I have to ask, why did you delete the issue template?

**Comment by bjarnef** [comment]
Well I also tried that with different parameters `?width=250&height=250&mode=crop&upscale=false` and just `?width=250`

With these querystring parameters it returns a different ysod.

![image](https://cloud.githubusercontent.com/assets/2919859/22592029/1189c474-ea18-11e6-8126-b48b252a1a71.png)

**Comment by JimBobSquarePants** [comment]
You'll also need to add your useragent setting to the security.config file.

http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig

See #487 for more details.

**Comment by JimBobSquarePants** [comment]
I get a blank 1x1 image when I navigate to the example url you gave me btw.

https://external.xx.fbcdn.net/safe_image.php?d=AQD5NGROUPnFzzxz&url=https%3A%2F%2Fumbraco.com%2Fmedia%2F1283%2Fimage-uploaded-from-ios-1.jpg%3Fanchor%3Dcenter%26mode%3Dcrop%26rnd%3D131305077120000000&_nc_hash=AQDjV6FU50n9gb4C

**Comment by bjarnef** [comment]
Which value should the `Useragent` key contain since http://www.useragentstring.com/ not is available at the moment.

A tried with some different useragent strings and different browsers, but it doesn't seem to make a difference.
```
<setting key="Useragent" value="Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"/>
```

I do see the image in from the url - if you go to the post here https://www.facebook.com/Umbraco/posts/1217147378333251 and inspect the DOM, you can get this image https://external.xx.fbcdn.net/safe_image.php?d=AQCFSAkXAFK4p_mK&w=476&h=249&url=https%3A%2F%2Fumbraco.com%2Fmedia%2F1283%2Fimage-uploaded-from-ios-1.jpg%3Fanchor%3Dcenter%26mode%3Dcrop%26rnd%3D131305077120000000&cfs=1&upscale=1&_nc_hash=AQDJ_OBV-1Gpf-7i (which is the resized and cropped version).

**Comment by JimBobSquarePants** [comment]
The useragent key is correct. I've had a dig and the issue is the following.

We are url-decoding the string before making the request to Facebook which it doesn't seem to like for that particular domain. Every other service including some Facebook ones doesn't seem to mind but this one does. I'll have to do some further testing to be sure that we can get away with just decoding the first part for all known services.

**Comment by JimBobSquarePants** [comment]
I've pushed some code that will cater for all scenarios. I will get a new build out in the next few days. It's 2am here now so I'm off to bed.

**Comment by ysidro** [comment]
on PHP i resolve this problem
`function lavadora($fbUrl)
{
  list($fakeUrl, $realUrl )  =   explode("url=", $fbUrl); // get varaible URL
  $lavadora = str_replace('%3A%2F%2F','://',$realUrl); // remplace code to this
  $lavadora = str_replace('%2F','/',$lavadora);
  $lavadora = str_replace('%3F','?',$lavadora);
  $lavadora = str_replace('%3D','=',$lavadora);
  $lavadora = str_replace('%26','&',$lavadora);
  return $lavadora ;
}`
