### ISSUE TITLE
Need to save an image without updating the last modified date/by

### ISSUE THREAD

**Issue by Cityonhill93** [JimBobSquarePants/ImageProcessor#556]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageProcessor
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently, after resizing an image, the image is show to have been modified by the user who ran whatever is doing the resizing. In most cases this is okay, however, my case requires the last modified by/date to remain the same as it was before the resizing. Ideally, the user who modified the file and the date it was modified would be optional params in the .Save method.

### Steps to Reproduce
N/A

### System Configuration
N/A

- ImageProcessor version: 2.5.2.0
- ImageProcessor.Web version (if applicable): N/A
- Other ImageProcessor packages and versions: N/A
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version: 4.5.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi there. That's functionality that you already control. Once you have saved the file you can change the created data and last write time of the original file using the File API in System.IO.
