### ISSUE TITLE
TestWebsite - Index.cshtml has invalid URL for rotate

### ISSUE THREAD

**Issue by Wolfiesden** [JimBobSquarePants/ImageProcessor#557]
views\home\Index.cshtml
Line 84:
`                <img src="/images/format-Penguins.jpg?width=300&rotate=angle-54|bgcolor-fff" />`

I believe the correct syntax for the url should be:
`                <img src="/images/format-Penguins.jpg?width=300&rotate=54&bgcolor=fff" />`

**Comment by JimBobSquarePants** [comment]
That's just the old legacy syntax. Please don't delete the issue template.
