### ISSUE TITLE
Change in smoothing quality (e.g. Rounded Corners) @v2.5.2

### ISSUE THREAD

**Issue by khiemtong** [JimBobSquarePants/ImageProcessor#558]
### Description
In this commit https://github.com/JimBobSquarePants/ImageProcessor/commit/d3aaab4f36d58949b03766576eb9b26987c18fc1#diff-9dc0ac7d60ebb80477dfc99ca385c8faL111

The image quality settings were centralized but it looks like smoothing was not carried over (perhaps intentionally?). This results in reduced quality for some processors. Not sure if this was intended or not.

#### With Smoothing (High Quality)
![image](https://cloud.githubusercontent.com/assets/1302588/22803924/e06b37a2-eee4-11e6-84ac-496a27997a4f.png)

#### After change (No smoothing)
![image](https://cloud.githubusercontent.com/assets/1302588/22803905/d1563708-eee4-11e6-87b6-2249b57c8d6d.png)

### Steps to Reproduce

* Run ImageFactory.RoundedCorners() at latest version

**Comment by JimBobSquarePants** [comment]
Will have a release out soon to fix this. Thanks for raising it.
