### ISSUE TITLE
Gif has background colours changed after resizing

### ISSUE THREAD

**Issue by Herman90** [JimBobSquarePants/ImageProcessor#563]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am using imageProcessor to resize images and recently I've added a .gif image and faced a problem. The problem is that after the .gif image are processed it displays some strange colors. The background colors are changed.
Original image: 
![original image](https://dl.dropboxusercontent.com/u/71159967/imageProcessorExamples/EL9000etc6.gif)
After Processing:
![original image](https://dl.dropboxusercontent.com/u/71159967/imageProcessorExamples/el9000etc6(processed).gif)
### Steps to Reproduce
Following parameters are specified: ?width=370&height=250&mode=crop&scale=both

### System Configuration

- ImageProcessor version: 2.5.2
- ImageProcessor.Web version (if applicable) 4.8.2
- Other ImageProcessor packages and versions: ImageProcessor.Web.Config: 2.3.0
- Environment (Operating system, version and so on): Windows 8.1 Enterprise, 64-bit os
- .NET Framework version:4.6.01055

**Comment by JimBobSquarePants** [comment]
Odd.... Thought I'd fixed that a wile back. Thanks for supplying the image I'll have a look asap.

**Comment by JimBobSquarePants** [comment]
Are you absolutely sure you are running those versions in your application? I've just done a test against those versions and cannot replicate. I fixed the issue you are seeing in v2.5.0 

https://www.nuget.org/packages/ImageProcessor/2.5.0

![ani](https://cloud.githubusercontent.com/assets/385879/23331297/1a4c01f2-fbb7-11e6-931a-50192f00550c.gif)

**Comment by Herman90** [comment]
You are right, it has already fixed. It's so embarrassing that I forgot about images caching. 
I've updated image processor to the latest version but forgot to clean the server images cache folder. I apologize that I have disturbed you. 
Thanks a lot for your quick reply!

I'd like to add that you are doing excellent job!

**Comment by JimBobSquarePants** [comment]
No worries 😄 Glad you figured it out. You had me worried for a moment!
