### ISSUE TITLE
Consider using mozjpeg instead of jpegtran in PostProcessor?

### ISSUE THREAD

**Issue by ryanlewis** [JimBobSquarePants/ImageProcessor#564]
Google PageSpeed flagged a couple of images as being more compressible then they currently are, even with PostProcessor installed. In some cases it was suggesting up to 60% savings on what was currently being served.

After further investigation, it seems that a lot of vendors have adopted mozjpeg instead of jpegtran. The following site allows you to test this for yourself:

https://imageoptim.com/mozjpeg

The following is an image that had been resized by ImageProcessor and with quality set to 80, coming in around 20KB
![jacobkhrist-jeff-mills](https://cloud.githubusercontent.com/assets/427747/23471946/149177da-fea3-11e6-8664-92bf96c0ccdb.jpg)

The following is the same image after being processed by mozjpeg at the URL above on the default settings, coming in at 8KB 
![jacobkhrist-jeff-mills 1](https://cloud.githubusercontent.com/assets/427747/23471958/1bf764b2-fea3-11e6-978f-da6297fb7813.jpg)

**Comment by JimBobSquarePants** [comment]
Yeah, been considering that for a while... Struggling to cope with time just now though.

**Comment by JimBobSquarePants** [comment]
Is the 20kb image postprocessed? I.e you cleared cache before installing postprocessor.  Diff seems awfully high if so. Jpegtran is better than that.

**Comment by ryanlewis** [comment]
Correct - went to the trouble of grabbing the embedded `jpegtran` and running the command below (same as source).

```
jpegtran -copy all -optimize img.jpg img.jpg
```

I suspect the image was already optimised, as it only saved me around 500 bytes. I was pretty shocked at the difference mozjpeg made to file size.

**Comment by JimBobSquarePants** [comment]
Seriously impressive then! I'll have a look asap... In the interim, if you get time and the opportunity to PR please let me know

**Comment by ryanlewis** [comment]
Will see if I can get it into the next sprint, as the savings do sound significant for JPEG-heavy sites.

**Comment by JimBobSquarePants** [comment]
Fixed with https://github.com/JimBobSquarePants/ImageProcessor/commit/871fa4a06b8784e85ca4f75cac8566387dd41dfb
