### ISSUE TITLE
about ImageProcessor.Web filter

### ISSUE THREAD

**Issue by g7rhythm** [JimBobSquarePants/ImageProcessor#567]
hello
i am reading the document about  ImageProcessor.Web filter .
What is "lostach histach"?
Can you  explain for me ? I need to translate into Chinese。

**Comment by JimBobSquarePants** [comment]
Hi @g7rhythm 

The filters mean the following.

losatch  = Low Saturation
hisatch = Hi Saturation.

Cheers

James
