### ISSUE TITLE
Service prefix is not case insensitive

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#569]
Hello again.

Just noted that the service prefix is not case insensitive. That is for example "remote.axd.." works but "Remote.axd..." throws an exception. I've made a pull request to fix this #568 Looking at the code https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L825 it seems it should be treated as CI?

**Comment by JimBobSquarePants** [comment]
Thanks. What was the error thrown? 

Ideally it should simply ignore incorrect prefixes, allowing both cases might mean someone can generate two cached files from different cased requests. I'd have to double check.

**Comment by ZNS** [comment]
It threw index out of bounds when doing the split and trying to acccess index 1 in the array. Didn't think of the possible cache-issues.

**Comment by ZNS** [comment]
Just came to think that the PR shouldn't directly affect caching. The code that fails simply tries to remove the prefix from the url and then return path and querystring. So if there is a cache issue it shouldn't have anything to do with the fix at least.

**Comment by ZNS** [comment]
The cache is based on the full url path including the prefix. So I guess fixing this exception would make the service work again which could create case sensitive cache items. But the solution can't be not to fix this exception. The fix should in that case should be in "GetImageServiceForRequest()" which do a case sensitive check, if that is what you want. Personally I really want case insensitive urls, but I guess it could be an option in the service.

**Comment by JimBobSquarePants** [comment]
Just pushed the code fixing this from your PR. Will have a release out asap. Thanks!
