### ISSUE TITLE
ImageProcessor: Processing gif Files Generates Server Error 500

### ISSUE THREAD

**Issue by drangus** [JimBobSquarePants/ImageProcessor#571]
ImageProcessor appears to work perfectly in our development setup. In our production setup it doesn't render gif images as expected in the back-end or in served pages.

For example, browsing the production server using a url similar to the following...
https:/ /prodserver/media/6600/sample.gif?anchor=center&mode=crop&width=500&height=200
...generates the following ysod.

```
Server Error in '/' Application.
Property is not supported.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Exception Details: System.ArgumentException: Property is not supported.
Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
Stack Trace: 
[ArgumentException: Property is not supported.]
   System.Drawing.Image.SetPropertyItem(PropertyItem propitem) +88
   ImageProcessor.ImageFactory.Save(Stream stream) +173
   ImageProcessor.Web.HttpModules.<ProcessImageAsync>d__34.MoveNext() +2430
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +60
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +9699833

```
This only happens with gif images (Example file attached below) 

Issuing the same request in the development environment...
http:/ /devserver/media/6600/sample.gif?anchor=center&mode=crop&width=500&height=200
...returns the image as expected.

Workaround:
Setting 'preserveExifMetaData' to false in processing.config fixes the issue.

Configuration:
- Umbraco 7.5.11
- ImageProcessor 2.5.2.0
- ImageProcessor.Web 4.8.2.0
- Windows Server 2008 / IIS 7 / .net 4.5
-- development 64bit (http)
-- production **32bit** (https)

Example gif file:
![img_0018](https://cloud.githubusercontent.com/assets/4834558/24521814/46c5bff6-1585-11e7-9764-0e7bfe25f18c.GIF)

**Comment by JimBobSquarePants** [comment]
Hi @drangus 

>ImageProcessor appears to work perfectly in our development setup. In our production setup it doesn't render gif images as expected in the back-end or in served pages.

That sends alarm bells ringing straight away. Are you absolutely 100% sure that you are running the exact same versions in both environments? If it works in development it will work on production. The bit depth will not affect image property items. They're just metadata.

On the note of bit depth? Why only run 32bit mode in your production server. You should be running the same depth, you're massively reducing the amount of non-fragmented memory available to you.

Do you have a public url to an image. I can easily check the version numbers from headers there. 

Cheers

James

**Comment by drangus** [comment]
Hi James,

I've checked the binaries and both the production and development environments are the same:
ImageProcessor.Web	4.8.2.0
ImageProcessor		2.5.2.0

Unfortunately, I can't provide a public url as the servers are not accessible externally.

I take on board what you say about our 32bit production environment: the server is legacy and is scheduled to be replaced, which should address the current issue in any case. The fact that this is an older server could itself be the problem as its configuration may be hiding some inappropriate and / or invalid settings - an inherited issue can not be discounted!  As a fix, setting 'preserveExifMetaData' to false in processing.config meets our immediate needs.

I appreciate your taking the time to look into this.

Thanks,
Angus

**Comment by JimBobSquarePants** [comment]
No problem at all.

Unfortunately it's going to be incredibly difficult for me to debug the issue really what with the image working on my local system. 

I know it's a long shot but if you have the opportunity could you create a custom build and wrap a try/catch around that code to determine what the property item id is, we'd probably be able to fix it quite easily.

Cheers

James
