### ISSUE TITLE
Issue  with DyanmicParameter with Null value

### ISSUE THREAD

**Issue by tbsAakshay** [JimBobSquarePants/ImageProcessor#576]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I check the code in that have issue in ProcessImage method which return exception in  GaussianLayer gaussianLayer = this.DynamicParameter;  line  57 for its null value in this.DynamicParameter. Can you please suggest me to resolve . 

### System Configuration
I have all latest DLL versions and .net 4.6 framework

**Comment by JimBobSquarePants** [comment]
>I have all latest DLL versions and .net 4.6 framework

Can you please supply the actual version numbers and some means to replicate the issue i.e a code sample.

**Comment by tbsAakshay** [comment]
ImageProcessor : 2.5.3.0 

And code as below
I need to sharpen my image for that I use ProcessImage method of ImageProcessor.Processors.GaussianSharpen class
and I converted my image in byte array and passing as in below method

```
public static void SharpenImage(byte[] ImageFile)
        {
            ISupportedImageFormat format = new JpegFormat { Quality = 70 };
            Size size = new Size(300, 150);
            using (MemoryStream inStream = new MemoryStream(ImageFile))
            {
                using (MemoryStream outStream = new MemoryStream())
                {
                    // Initialize the ImageFactory using the overload to preserve EXIF metadata.
                    using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
                    {
                        //imageFactory.ImagePath = @"C:\Users\techbrain\Downloads";
                        imageFactory.Load(inStream)
                                    .Resize(size)
                                    .Format(format)
                                    .Save(outStream);
                        ImageProcessor.Processors.GaussianSharpen gaussianSharpen = new ImageProcessor.Processors.GaussianSharpen();

                        using (Image image = gaussianSharpen.ProcessImage(imageFactory))
                        {
                            var i = image;
                            var i2 = new Bitmap(i);
                            i2.Save(@"C:\\Users\techbrain\Downloads\newImage.Jpeg", ImageFormat.Jpeg);
                        }
                    }
                    // Do something with the stream.
                }
            }

```

**Comment by tbsAakshay** [comment]
Hi I am Closing this issue as I resolve it by myself. The problem was I don't know what should I pass in DynamicParameter. I solved it by passing new `gaussianSharpen.DynamicParameter = new GaussianLayer(10);` In my code so It's working fine there. 

@JimBobSquarePants  Thank you for quick support.

**Comment by tbsAakshay** [comment]
a

**Comment by JimBobSquarePants** [comment]
@tbsAakshay You shouldn't be using the processor directly. Why are not use the [ImageFactory.GaussianSharpen](http://imageprocessor.org/imageprocessor/imagefactory/gaussiansharpen/) method?

**Comment by tbsAakshay** [comment]
Yes, you are right!  Thank you so much for help!!

**Comment by JimBobSquarePants** [comment]
My pleasure 😄

**Comment by JimBobSquarePants** [comment]
My pleasure 😄
