### ISSUE TITLE
Setting one pixel using fastbitmap with 8bpp pixel format

### ISSUE THREAD

**Issue by Yozer** [JimBobSquarePants/ImageProcessor#577]
### Description

When I try to set exacly one pixel to white color in a bitmap with pixel format: Format8bppIndexed I'm getting four white pixels . FastBitmap always operates on 4 bytes (even for 8bpp and 24bpp pixel formats).
Moreover when you try to set last pixel to some color you will get a heap corruption or access read violation.
### Steps to Reproduce

```
Bitmap bmp = new Bitmap(10, 10, PixelFormat.Format8bppIndexed);
using (FastBitmap fbmp = new FastBitmap(bmp))
{
	fbmp.SetPixel(0, 0, Color.White);
}
bmp.Save(@"D:\test3.bmp", ImageFormat.Bmp);
```
### System Configuration

- ImageProcessor version: 2.5.3.0
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version:  4.5

**Comment by JimBobSquarePants** [comment]
Sorry. Don't use FastBitmap directly. It should never have been exposed publicly and I wish I could hide it again. I'll put a warning on the class.
