### ISSUE TITLE
Caching ignores querystring when ValidatingRequest

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#578]
When hooking into the ValidatingRequest event and manipulating the querystring, adding new parameters, the cache isn't cleared. Example:

Request /image.jpg?width=320&height=320 ValidatingRequest adds "mode=crop".
Request /image.jpg?width=320&height=320 ValidatingRequest adds "mode=stretch" Will return the cached image with "mode=crop"

Is this by design?

**Comment by JimBobSquarePants** [comment]
@ZNS 

Please don't delete the issue template. There's a Gitter channel for questions. 

What you will be seeing is the browser cache since the only request url that the broswer knows about it your original one. ImageProcessor.Web's own cache has picked up on the difference. 

Ctrl+F5 is the only way to fix that. 

James

**Comment by ZNS** [comment]
Sorry, didn't know about the gitter channel. 

Are you sure, it seems to me the disk cache is based on the full url only, and ignores any modifications done to the querystring in processing.
https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/src/ImageProcessor.Web/Caching/CachedImageHelper.cs#L65

**Comment by JimBobSquarePants** [comment]
@ZNS No worries 😄 

Yeah, pretty sure. The validating event happens before the cache is initialized. So any changes to the querystring are passed on.

**OnValidatingRequest - L516** 

https://github.com/JimBobSquarePants/ImageProcessor/blob/2aaff7a60d8c287b56d262bea2052839a6e9bf8b/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L516

**Cache Instance - L545**

https://github.com/JimBobSquarePants/ImageProcessor/blob/2aaff7a60d8c287b56d262bea2052839a6e9bf8b/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L545

**Comment by JimBobSquarePants** [comment]
@ZNS You were definite right here. Pushed a fix, will have a new release out asap.

**Comment by Ron-Brouwer** [comment]
@JimBobSquarePants 
Thanks for fixing!
Do you know when we can expect the new release with this fix?
I have a project due to go live and this is a blocker. It doesn't feel right to use a custom build..

Let me know.
Ron

**Comment by JimBobSquarePants** [comment]
Hi Ron,

I'm planning a release in the next 24 hours. Need to run some final tests. Is that soon enough?

Cheers

James

**Comment by Ron-Brouwer** [comment]
Yes, thank for following up so fast!

**Comment by JimBobSquarePants** [comment]
No worries 😄
