### ISSUE TITLE
Resize center querystring is y,x instead of x,y

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#579]
Just something I noted when using ImageProcessor web and using resize with center parameter. It seems intuitive to pass center=x,y but the correct order seems to be center=y,x where x is horizontal and y is vertical. This should be added to the docs I think :)

Example:
http://jamessouth.me/images/imageprocessor/samples/balloon.jpg
http://jamessouth.me/images/imageprocessor/samples/balloon.jpg?width=300&height=300&mode=crop&center=0.5,0.1
http://jamessouth.me/images/imageprocessor/samples/balloon.jpg?width=300&height=300&mode=crop&center=0.5,0.9

**Comment by JimBobSquarePants** [comment]
Hi @ZNS 

Thanks for raising this but please stop deleting the issue template. It helps me gather much needed information to allow me to triage issues.

That said, it looks like you've uncovered what would seem to me a pretty serious bug. It should have never been Y,X. Unfortunately I don't think I can fix it without breaking a lot of dependent code. Umbraco, for example, use this functionality a lot.

@nul800sebastiaan How did we miss this? It's been iffy from day one. 😟 

https://github.com/JimBobSquarePants/ImageProcessor/blob/ae1ebe17653c064f157847d7a82226535a27a4c9/src/ImageProcessor/Imaging/Resizer.cs#L178 

Cheers

James

**Comment by ZNS** [comment]
Sorry about the template, I'll better myself :)

I didn't catch this on our umbraco sites, but I know we have had some issues with it.

**Comment by JimBobSquarePants** [comment]
No worries...

They must already deal with it somehow. I've updated the docs for now.
