### ISSUE TITLE
How to disable upscale feature for the resize option?

### ISSUE THREAD

**Issue by evdinursan** [JimBobSquarePants/ImageProcessor#583]
Hello,

Though I think I've read the documentation quite well, I'm missing one thing and I would like to ask you if this already exists in the current version of the resize option - I'm telling from the beginning that this is not an issue, is more like a question: do I have the possiblity to disable the UPSCALE feature by default from the one of the config files? I know that I can do it by adding &upscale=off but I don't want to give this possibility to the site visitor and I don't need it after all - I want to be sure 100% that this is disabled - meaning that if I request a resize of 500px for an image of 200px, that the image stays at 200px and don't do upscale.

Thank you very much and really appreciate your work with this tool.

Thanks,
Evdin

**Comment by JimBobSquarePants** [comment]
Hi Evdin,

The best way to do this would not be via configuration but actually via the event `ImageProcessingModule.ValidatingRequest`

You could use the event to add and upscale=false key/value pair to the queryCollection. 

The code sample in the docs here should be enough to get you started.
http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

Hope that makes sense, Any issues let me know.

Cheers

James

**Comment by evdinursan** [comment]
Thank you very much for your response. You put me on the right direction but somehow I think I'm missing something because I added this to the Global.asax Application_Start event and the code is being hit during debug process but it doesn't do what is supposed to do:
```

ImageProcessingModule.ValidatingRequest += (sender, args) =>
            {
                if (!String.IsNullOrWhiteSpace(args.QueryString))
                {
                    // Add upscale parameter if it wasn't added already
                    NameValueCollection queryCollection = HttpUtility.ParseQueryString(args.QueryString);
                    if (!queryCollection.AllKeys.Contains("upscale"))
                    {
                        queryCollection.Add("upscale", "off");
                        
                        // This performs the reverse of ParseQueryString since the result of ParseQueryString
                        // is actually an instance of System.Web.HttpValueCollection
                        args.QueryString = queryCollection.ToString();
                    }
                }
            };
```

I'm just calling an URL in the browser for an image:

/BinaryCache/13b7e2dcb81340a49ebed216cf16c27a.png?width=2500&height=2500 and the image is being upscale without any issues; if I manullay add to the querystring in the browser upscale=off - it does what is supposed to do.

Again, many thanks for your time.

Evdin

**Comment by JimBobSquarePants** [comment]
Hi Evdin,

It should be `"(upscale, "false")` as it's a boolean we are parsing. I've just tested that on my local machine and it's working well. Technically "off" will parse to false also but it's best to use the correct command.

You lack of change might be getting caused by #578 if you have already made that request before. I'll be pushing a fix asap for that which reflects my local working build. 

Cheers

James

**Comment by evdinursan** [comment]
Hi,

I updated the code as you suggested and everything is working perfectly. On the other hand I can confirm the other issue (#578) as I'm having it but Ctrl+F5 doesn't help - I have to change one of the parameters in order to get rid of the cache.

```
if (!String.IsNullOrWhiteSpace(args.QueryString))
                {
                    // Add upscale parameter if it wasn't added already
                    NameValueCollection queryCollection = HttpUtility.ParseQueryString(args.QueryString);
                    if (!queryCollection.AllKeys.Contains("upscale"))
                    {
                        queryCollection.Add("upscale", "false");
                        
                        // This performs the reverse of ParseQueryString since the result of ParseQueryString
                        // is actually an instance of System.Web.HttpValueCollection
                        args.QueryString = queryCollection.ToString();
                    }
                }
```

Thank you very much.
Evdin

**Comment by JimBobSquarePants** [comment]
Great! I've already written the fix for that and will push it soon.
