### ISSUE TITLE
Any reason to not use AutoRotate by default?

### ISSUE THREAD

**Issue by geordiemhall** [JimBobSquarePants/ImageProcessor#586]
Hi there,

This isn't an issue so much as a question – but not really sure where else to put questions than in an issue!

We've been using ImageProcessor for resizing images for a while, but have recently been hearing more reports of uploaded images being rotated incorrectly (since orientation tagged in EXIF), so I started looking into what we could do. 

The `AutoRotate` processor seemed to be what we wanted, and adding `autorotate=true` to the query string did indeed fix. 

I was wondering if there was any serious cost to just including this on all resized image URLs, or if we'd want users to turn it "on" per image after noticing they weren't rotated correctly? 

Looking through the source it seems to only actually apply a transformation on the image if the EXIF tag is present and one of a few orientations, so if an image didn't strictly _require_ rotation then it running it through the `AutoRotate` processor would be pretty cheap, right?

And if it _is_ fine to have `AutoRotate` on for all images, I was then wondering if there was a way to turn it "on" by default without having to add `autorotate=true` to every query string (since it feels cleaner, but also since image URLs already saved in HTML wouldn't need to be updated).

I couldn't find anything in the docs about setting default values for each processor in the config, so I'm guessing maybe this sort of thing would just have to be done in the `ValidatingRequest` handler (eg. you'd just add an extra param silently in there to enable autorotation)?

Thanks,
Geordie

**Comment by Wolfiesden** [comment]
Have you looked at the <presets> section of the processing.config ?

If there are a few commonly used settings, you could make a preset that contains them all and then add the preset to the url.
` 
  <presets>
   <preset name="fred" value="width=300&#038;height=150&#038;mode=crop&#038;"/>
  </presets>
`
Then in a url:
image.jpg?preset=fred

**Comment by JimBobSquarePants** [comment]
Hi @geordiemhall 

I wrote an answer to this ages ago. I've no idea what happened to it. Really weird. Sorry!

Basically adding autorotate by default adds an overhead to each image request I'd rather not have by default. You can however add it to your requests if you want using the `ImageProcessingModule.ValidatingRequest` event.

You can augment the querystring here for all requests removing the need to add it manually. 

``` c#
ImageProcessingModule.ValidatingRequest += (sender, args) =>
{
    if (!string.IsNullOrWhiteSpace(args.QueryString))
   {
        queryCollection["autorotate"] = "true";
            
        // This performs the reverse of ParseQueryString since the result of ParseQueryString
        // is actually an instance of System.Web.HttpValueCollection
        args.QueryString = queryCollection.ToString();
    }
};
```

Cheers

James

p.s Thanks @Wolfiesden for chipping in 👍
