### ISSUE TITLE
404 When using Azure Cache plugin

### ISSUE THREAD

**Issue by chadcjc** [JimBobSquarePants/ImageProcessor#587]
### Description
The issue I have is closest to the closed issue https://github.com/JimBobSquarePants/ImageProcessor/issues/365

That one was closed so I opened a new issue.

### Scenario:
I have a website hosted in Azure and want to use blob storage as the image store along with Image Processor to resize and cache the images.  I have setup an Image Server website, Azure Storage Account, and CDN (see below for Urls).

Azure Resources Info:
Image Server Url: http://inspireimageserver2.azureedge.net/
Blob Storage Url: http://inspireqastorage.blob.core.windows.net
CND End Point Url:  http://inspireqa2.azureedge.net/

Here are some images that are hosted in my blob storage 
http://inspireqastorage.blob.core.windows.net/images/system/6678c28f-4578-4593-9fa1-40eefda7047b.jpg
http://inspireqastorage.blob.core.windows.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg
http://inspireqastorage.blob.core.windows.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg

I would expect the following would serve up these images resized and pointing at the CDN but all I get is 404s
http://inspireimageserver2.azurewebsites.net/images/system/6678c28f-4578-4593-9fa1-40eefda7047b.jpg?width=100&height=100
http://inspireimageserver2.azurewebsites.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg?width=100&height=100
http://inspireimageserver2.azurewebsites.net/images/system/672e2692-860d-4785-a172-e5c03227f547.jpg?width=100&height=100

I created a new web project installed the plug-ins and configured it as follows.  So far this is no code solution.

cache.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <!-- Using AzureBlobCache so commented out disk cache option-->
    <!--<cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" browserMaxDays="7">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>-->
    <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=inspireqastorage;AccountKey=[Our Account Key]" />
        <!-- Container in storage account used for cache -->
        <setting key="CachedBlobContainer" value="cache" />
        <setting key="UseCachedContainerInUrl" value="true" />
        <!-- CDN Connected to blob storage account -->
        <setting key="CachedCDNRoot" value="http://inspireqa2.azureedge.net/" />
        <setting key="CachedCDNTimeout" value="1000" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache>
  </caches>
</caching>
```
security.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    <!--<service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web" />-->
    <!--Disable the LocalFileImageService and enable this one when using virtual paths. -->
    <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <!-- Container containing all images -->
        <setting key="Container" value="images"/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <!-- Blob Storage Url -->
        <setting key="Host" value="http://inspireqastorage.blob.core.windows.net"/>
      </settings>
    </service>
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="4194304" />
        <setting key="Timeout" value="3000" />
        <setting key="Protocol" value="http" />
      </settings>
      <whitelist>
      </whitelist>
    </service>
  </services>
</security>

```

I have attached CDN Configurations:
![cdn2](https://cloud.githubusercontent.com/assets/1395173/25871568/d6f4cee0-34bc-11e7-866b-c227316d30de.png)
![cdn1](https://cloud.githubusercontent.com/assets/1395173/25871567/d6f412de-34bc-11e7-9887-3bd834684381.png)

Any help is appreciated.

Thanks,
Chad

**Comment by JimBobSquarePants** [comment]
Hi Chad,

You configuration is incorrect for the `CloudImageService`

If you look at the configuration documentation [here](http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig) you 'll see that you have an old setting. `Container` which you should not use anymore and you are missing  a trailing slash `/` in your `Host` setting.

    <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        
        <setting key="Host" value="http://inspireqastorage.blob.core.windows.net/"/>
      </settings>
    </service>

That should get you up and running.

Cheers

James

**Comment by chadcjc** [comment]
Perfect that did it!  Thank you so much!

**Comment by JimBobSquarePants** [comment]
No worries, happy to help 😄
