### ISSUE TITLE
Case sensitive filenames and ImageProcessor.Web

### ISSUE THREAD

**Issue by SChubb** [JimBobSquarePants/ImageProcessor#589]
Hi,

### Description
I have a scenario where we have an AWS S3 bucket that is holding our images, we're then using TNTDrive to map that bucket to a Windows drive and then setting that up as a virtual directory in IIS. 

Now, S3 bucket objects/filenames are case sensitive and IIS seems to have a bug where it actually requests the uppercase version of the object so [http://34.253.129.36/media/1001/magazine-1236.jpg?width=1280](http://34.253.129.36/media/1001/magazine-1236.jpg?width=1280) becomes [http://34.253.129.36/media/1001/MAGAZINE-1236.JPG?width=1280](http://34.253.129.36/media/1001/MAGAZINE-1236.JPG?width=1280)

As a result, we store the filename on S3 in uppercase format.

If you try both those links, they'll both work - however, only one will be resized correctly. Any ideas what might be going on? Why would one case trigger the resizing code and one wouldn't?

### System Configuration

- ImageProcessor version: 2.5.4.0
- ImageProcessor.Web version: 4.8.4.0
- Other ImageProcessor packages and versions: None
- Environment (Operating system, version and so on): Windows Server 2016, IIS 10.0.14
- .NET Framework version: 4.6
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @SChubb 

That's an odd one!

I can only imagine that it has something to do with the case sensitivity and how the request is being sent. However I have no means to debug against your particular scenario. Would it be possible for you to use a build from this repo and attach a debugger?

Cheers

James

**Comment by SChubb** [comment]
Hi @JimBobSquarePants 

So took the dog for a walk and came up with the same theory - it's amazing what getting away from the desk can do! I suspect it's to do with then you're requesting the filename.

I'm checking on that now - but I can't get the current GitHub repository to compile. VS 2013 can't compile it because of the => notation e.g.

`public static IMatrixFilter BlackWhite => new BlackWhiteMatrixFilter();`

Any ideas?

Thanks
Simon

**Comment by JimBobSquarePants** [comment]
Hi Simon, 

VS 2013... Crikey! I feel for you!

You'll need 2015 to use C#6 The community edition does everything you need though and it's free.

Hope that's cool.

**Comment by SChubb** [comment]
OK, found the issue - it was indeed to do with the case sensitivity, I've added two new config settings to be able to handle this. `pathIsCaseSensitive` and `filenameIsCaseSensitive` to handle the cases where the path is case sensitive and the filenames are or not. The settings can be "original" "upper" or "lower". 

"original" leaves the requested file/path alone and the other two either upper or lower case the filename and/or path. This covers all use cases on AWS S3. 

I've only included this in the LocalFileImageService at the moment as that's just where I need it.

Do you want me to put this into a pull request for you to include in the main build?

Thanks
Simon

**Comment by JimBobSquarePants** [comment]
Thanks!

Do you think we could handle the issue in code rather than configuration? I.E strip anything out that is messing with the casing leaving only the original?

**Comment by SChubb** [comment]
Soory - but what do you mean by "strip out anything that is messing with the casing"? The problem comes in LocalFileImageService GetImage when the id passed is the original url request.  Normally that wouldn't be a problem but for S3 where filenames are case sensitive, the File.Exists(path) will fail unless cases match. Equally, the opening of the filestream will fail.

Only other option, other than making a config option would be to try finding the file with the original requst, if that fails, lowercase the path and try again, if that fails uppercase the path and try again.

Thought the config option was the better option.

Thoughs?

**Comment by JimBobSquarePants** [comment]
I was just thinking there... What's stopping you replacing the `LocalFileService` with your own implementation? 

Your particular setup is not what I would consider normal and the flexibility to use your own `IImageService` implementations is designed for scenarios just like this.

**Comment by JimBobSquarePants** [comment]
@SChubb Just reading through all this again. I realized you're adding the options to the service not elsewhere. I'm up for that so if you wanna share a code sample I can add it since you can't build C#6
