### ISSUE TITLE
New Function Suggestion

### ISSUE THREAD

**Issue by g7rhythm** [JimBobSquarePants/ImageProcessor#593]
Is it possible to add contour style  to watermark function?
because mostly pictrue have many color ，the watermark is not obvious .
But not the dropshadow style,Is similar with the shadow style.

**Comment by JimBobSquarePants** [comment]
Hi @g7rhythm 

I have literally no idea what you mean. Please use Gitter for feature suggestions as instructed in the contribution guidelines.
