### ISSUE TITLE
image can't show in html  on firefox53.0.2

### ISSUE THREAD

**Issue by zhujinhu21** [JimBobSquarePants/ImageProcessor#596]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

i download  ImageProcessor.Web form nuget, and update web.config to config ImageProcessor.Web.
add cache.config,processing.config,security.config to my project. i access my html with load image.
but the image can't show in firefox 53.0.2, it can be show in chrome.
my website is www.123369.com.cn

[Web.config.zip](https://github.com/JimBobSquarePants/ImageProcessor/files/1013477/Web.config.zip)

### System Configuration

- ImageProcessor version:2.5.2.0
- ImageProcessor.Web version (if applicable) 4.8.2.0
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): server 2008 r2
- .NET Framework version:4.5.4
- Additional information:

**Comment by JimBobSquarePants** [comment]
Which images? I can see all so far...

![ip-ff](https://cloud.githubusercontent.com/assets/385879/26238832/1bbab0d6-3cbe-11e7-816b-a11c1f92f286.jpg)

**Comment by zhujinhu21** [comment]
![index](https://cloud.githubusercontent.com/assets/4327149/26239170/8034cf7a-3cae-11e7-9abc-e522ff40c153.png)
![version](https://cloud.githubusercontent.com/assets/4327149/26239195/9bd82312-3cae-11e7-9c71-e21ed83f7e72.png)

**Comment by JimBobSquarePants** [comment]
That's very odd but I don't _think_ it's an ImageProcessor bug. What do the response headers say in the network tab?

**Comment by zhujinhu21** [comment]
i can't see load  url image in the network tab.but on the other computer i can see to load images.
is my firefox bug.
![network](https://cloud.githubusercontent.com/assets/4327149/26239694/a4e2822a-3cb0-11e7-9f8a-b8f145d50825.png)

**Comment by zhujinhu21** [comment]
i input this url=http://image.123369.com.cn/Upload/Service//d3ec005a448f4347aa7be2b6c3e9e8ce.jpg?height=500 in the firefox.  failed to load giving the url
![image](https://cloud.githubusercontent.com/assets/4327149/26240133/8d1fd636-3cb2-11e7-94bf-b2f88c67cc35.png)
