### ISSUE TITLE
 add BackgroundColor in Setting config

### ISSUE THREAD

**Issue by MajidSafari** [JimBobSquarePants/ImageProcessor#597]
Hi 

how i can set default BackgroundColor ,, in seting !!!!!

**Comment by JimBobSquarePants** [comment]
Use the ValidatingRequest event as described in the docs. http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

Don't delete the issue tracker. We have a Gitter channel for questions!!!

**Comment by MajidSafari** [comment]
that's right , 

but it's better to in config file ?

**Comment by JimBobSquarePants** [comment]
No.

**Comment by MajidSafari** [comment]
ok tanks
