### ISSUE TITLE
I see 404 error when i delete the cached files.

### ISSUE THREAD

**Issue by eupzry** [JimBobSquarePants/ImageProcessor#598]
### Description
I am using DiskCache Plugin.  Sometimes according to our internal requirements I need to be delete manually cached files on the file system.  After deleting, all the responses are 404. If i restart the application, system creating cache files successfully for each requests and everything work again.

### Steps to Reproduce
1. Enable disk cache plugin & run the application
2. Request an image form the application by using any browser
3. Delete manually Cached files on the file system.
4. You will see 404 Error (HTTP Error 404.0 - Not Found) for every request again with browser.
5. Restart your application, you will see that, log files created again and images will come instead of 404.

### System Configuration
**Cache Config**
```
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="DiskCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="7" browserMaxDays="7" trimCache="false">
      <settings>
        <setting key="VirtualCachePath" value="~/imagecache" />
      </settings>
    </cache>
  </caches>
</caching>

```
**IImageService implementation**
```
public class GalleryImageService : IImageService
{
    public string Prefix { get; set; }
    public bool IsFileLocalService { get { return false; } }
    public Dictionary<string, string> Settings { get; set; }
    public Uri[] WhiteList { get; set; }

    public bool IsValidRequest(string path)
    {
        return true;
    }

    public Task<byte[]> GetImage(object id)
    {
		....
    }
}
```

- ImageProcessor version: 2.5.4.0
- ImageProcessor.Web version: 4.8.4.0
- Environment (Operating system, version and so on): Windows 10 
- .NET Framework version: 4.6.1

**Comment by JimBobSquarePants** [comment]
Hi @eupzry 

That's actually expected behavior. Cached images are tracked in memory as well as on disk to reduce IO operations on the server. If you are deleting the cache you have to restart the application. 

Cheers

James

**Comment by eupzry** [comment]
Hi @JimBobSquarePants 

Can we find a way that i don't need to restart the application. For example if the cache file not exists, can we check and and create a new one by using an extension?

Best Regards,

**Comment by JimBobSquarePants** [comment]
Why are you deleting the cache?

**Comment by uggeh** [comment]
If there is a problem with an image and you instead serve a "missing-image"-image, which gets cached. Then you fix the underlying problem and can serve the correct image, but the "missing-image" is still shown since it's in the cache.

In that case you want to delete the cache.

**Comment by ronaldbarendse** [comment]
The default memory cache duration is 1 minute, but this can be configured:

https://github.com/JimBobSquarePants/ImageProcessor/blob/58e18acd42de65b02421a85dee5361c4d74ac2ff/src/ImageProcessor.Web/Configuration/ImageCacheSection.cs#L116-L128

However, setting it to `0` will automatically set it to 1 minute in the `CacheIndexer` and I'm not sure whether the minimum value of `-1` will ignore the cache here:

https://github.com/JimBobSquarePants/ImageProcessor/blob/58e18acd42de65b02421a85dee5361c4d74ac2ff/src/ImageProcessor.Web/Caching/CacheIndexer.cs#L69-L75

You can also enable `useFileChangeMonitors`, so changes to files (e.g. deletions) will invalidate the cache, but that might cause issues when you have a lot of cached images, as documented in the source:

https://github.com/JimBobSquarePants/ImageProcessor/blob/58e18acd42de65b02421a85dee5361c4d74ac2ff/src/ImageProcessor.Web/Configuration/ImageCacheSection.cs#L130-L147

A better approach would be to also manually call `CacheIndexer.Remove()`, so you keep the memory cache and not suffer from the FCN performance issues.
