### ISSUE TITLE
Case Sensitive Application Path prevents me to serve image

### ISSUE THREAD

**Issue by eupzry** [JimBobSquarePants/ImageProcessor#599]
Hi,

First of all, i want to thank you for this good lib.

I am using Application path to serve my application. As you can see below **Media** is application path. I can handle below sample correctly. But if i change Application path to **media** (totally same but lower) i am getting 404 Error. 

**Success**
/localhost/**M**edia/images/other/1/5/1/1/sample.jpg

**Failed (Http 404)**
/localhost/**m**edia/images/other/1/5/1/1/sample.jpg

I can serve image when i change the only path (not application path) to lower or upper, But one more image cache file will be generated (Yes i am using your DiskCache plugin). Actually this is strange, why i need to new cache file to handle this request. This is only a url and it must be case insensitive. Moreover this is a security gap. Some malicious softwares/persons can use this hole to crash me :)

**Success : first cache file created**
/localhost/Media/images/**o**ther/1/5/1/1/**s**ample.jpg

**Success : one more cache file created**
/localhost/Media/images/**O**ther/1/5/1/1/sample.jpg

**Success : one more cache file created**
/localhost/Media/images/other/1/5/1/1/**S**ample.jpg

- ImageProcessor version: 2.5.4.0
- ImageProcessor.Web version: 4.8.4.0
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.6.1

**Comment by JimBobSquarePants** [comment]
Hi @eupzry 

It's not a security gap. Urls are case sensitive in many servers. GitHub pages for example. 

The application path has nothing to do with ImageProcessor so I don't know what your issue is.

**Comment by eupzry** [comment]
hi @JimBobSquarePants 

I think, a new configuration paremeter about handling the case sensitive urls it will be great. What do you think about this option?

I checked everything about Application Path but see nothing. I beleive that if you can try this scenario you will meet this case.

**Comment by eupzry** [comment]
Hi @JimBobSquarePants ,

I found the problem. There is a small bug on the TrimStart extension (ImageProcessor.Web.Extensions/StringExtensions). Let me explain below.

You are using this Extension in GetImageServiceForRequest function (ImageProcessor.Web.HttpModules / ImageProcessingModule) to trim remove application path from rawurl. Check below.

`string path = url.Split('?')[0].TrimStart(applicationPath).TrimStart('/');`

But ! If i send the lower application path like my example, raw url will be same with the requested url but the application path is different. In that case you have to use IngoreCase option by using StartsWith.

**Your code**
```
public static string TrimStart(this string target, string trimString)
{
    string result = target;
    while (result.StartsWith(trimString))
    {
        result = result.Substring(trimString.Length);
    }

    return result;
}
```

**Required**
```
public static string TrimStart(this string target, string trimString)
{
    string result = target;
    while (result.StartsWith(trimString, StringComparison.InvariantCultureIgnoreCase))
    {
        result = result.Substring(trimString.Length);
    }

    return result;
}
```

For this reason, GetImageServiceForRequest function could not be find the service. Because TrimStart can't remove application path.

This is my finding. I hope you are available for a new version.

Thanks in advance.

**Comment by JimBobSquarePants** [comment]
Why are you changing your application path? I've had literally hundreds of thousands of downloads where no one has had this requirement or issue. 

Please don't **EVER** email me privately again to push me for more attention on an issue. Your "critical" issues are no more important than anyone else's. I do this project in my own, very limited time, for free, with almost no support so you should be patient. There are channels for communication that I have taken the time to set up; use them.

If you are in such a rush why haven't you created a PR?

**Comment by JimBobSquarePants** [comment]
I've made that change, will release soon as I have the time.
