### ISSUE TITLE
an incorrect value of image size (width and height) 

### ISSUE THREAD

**Issue by tie-ua** [JimBobSquarePants/ImageProcessor#601]
I have 2 images: 106_0620.jpg and P_20160401_101656.jpg.
Both images are in the cloud (see link below) and have a portrait orientation.

https://1drv.ms/f/s!Al6YxVND66gGqlXs4gpD40uz2OG6

I try to get a width and weight of images using an ImageFactory.Image.Width function and
ImageFactory.Image.Height.

For 106_0620.jpg i get the correct value of width and weight (width < height).
But for P_20160401_101656.jpg I get the wrong value of width and weight (width > height.).

Is it an error of ImageFactory or I'm doing something wrong?

System Configuration
ImageProcessor version: 2.54
Environment: Windows 10 Pro 64bit, Microsoft Visual Studio 2017 Community Edition v15.2, Microsoft C# 2017
.NET Framework version: 14.6.2

**Comment by JimBobSquarePants** [comment]
It's probably EXIF orientation. System.Drawing reports the physical height and width in pixels.  Are the values swapped?
