### ISSUE TITLE
Feature Request: Handle SVGs

### ISSUE THREAD

**Issue by skttl** [JimBobSquarePants/ImageProcessor#605]
I know, svg isn't really an image. But I think we will se more and more images on the web saved as SVG. Why have ImageProcessor handle them? Because, sometimes you want to crop an SVG file. If you crop an SVG file, ImageProcessor should take the svg file, and update the viewbox attribute accordingly, and thereby define a crop for the svg.

Is it doable? I'd like to help, if possible.

**Comment by JimBobSquarePants** [comment]
Hi @skttl 

That's way out of scope I'm afraid. SVG is such a different format that it would take me a massive amount of effort to do the work. The future is all about the ImageSharp family of libraries so I want to focus there. 

There are plans in the future to do some work with SVG though [over at our new org Six Labors](https://github.com/SixLabors/Svg) so if you were able to help out that would be awesome

Cheers

James

**Comment by dampee** [comment]
Because imageprocessor is bitmap based, you could write write a plugin to read the SVG, convert it to a bitmap, and let imageprocessor handle the output in JPEG/PNG/...  I've done [something similar for PDF](https://github.com/dampee/ImageProcessor.Plugins.Pdf/).

**Comment by JimBobSquarePants** [comment]
Still too much for me to do. ImageProcessor is not my focus now. It's solid and has a hefty feature set already.

**Comment by skttl** [comment]
@dampee I still want SVG output. I'll see if I can make my own then :)

**Comment by JimBobSquarePants** [comment]
You cats are crazy!
