### ISSUE TITLE
Questions about ImageProcessor

### ISSUE THREAD

**Issue by wuzhengzhou** [JimBobSquarePants/ImageProcessor#606]
Hi：
I want to use ImageProcessor in my project。
This project is based on the .NET 4.5，I used it successfully。
BUT!!!BUT!!!BUT!!! I want to use it on other project，this project is based on the .NET 3.5，I have never been able to use it successfully。
The ImageProcessor must be used to project what the project  is based on the .NET 4.5+？

please reply to me as soon as you can！
thanks very much！

**Comment by JimBobSquarePants** [comment]
HI @wuzhengzhou 

ImageProcessor works on .NET 4+ 

Not even Microsoft  supports .NET 3.5 (They don't even support .NET 4) so I would recommend to you that you upgrade your project. (I hope that is possible)

Cheers

James

**Comment by dlemstra** [comment]
If you need to keep your version at .NET 3.5 you might want to take a look at my project: https://github.com/dlemstra/Magick.NET. This supports .NET 2.0 and higher.
