### ISSUE TITLE
PNG post processing not configured correctly

### ISSUE THREAD

**Issue by tomvanenckevort** [JimBobSquarePants/ImageProcessor#610]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
With the release of ImageProcessor.Web.PostProcessor v1.2.x, you fixed an issue where pngout was reporting as a false positive on some antivirus programs, by replacing it with TruePNG.
However, it looks like this is not fully working as intended, due to some small configuration issues:

- The embedded resource for pngquant.exe has a resource key of optipng.exe, which means when extracted in the RegisterExecutables method it uses that name, instead of pngquant.exe (code [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessorBootstrapper.cs#L132)). Since the png.cmd file that gets run to optimise PNG files refers to pngquant, it will currently fail that command as it cannot find the executable (since pngquant.exe has been saved as optipng.exe).
_Suggested fix:_ rename the resource key in the PostProcessorBootstrapper class to `pngquant.exe` so extracted exe matches.
- The png.cmd batch file contains two commands: one for pngquant and one for TruePNG. Presumably both are intended to be run after each other to optimise the PNG file in the best possible way? However, the batch file commands both take the same input and output parameter paths (see [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/src/ImageProcessor.Web.Plugins.PostProcessor/Resources/Unmanaged/x86/png.cmd)). Which means that pngquant would take the source file and save the processed result in the destination path, but then TruePNG would also take the source file and save it in the destination path. So it would effectively bypass any work done by pngquant.
_Suggested fix:_ change the input parameter for TruePNG to `%2` so it will take the output of pngquant and use that to run the TruePNG optimiser. Would need a `/force` parameter as well to overwrite the output file.

### Steps to Reproduce
I first noticed it when using ImageProcessor.Web.PostProcessor on an Umbraco website and seeing that the loading of large PNG files would take longer than similar sized JPEG files. That led me to investigate and step through the code and noticing the issues raised above.

### System Configuration
Local development machine (Surface Pro 4, Windows 10).

- ImageProcessor version: v2.5.4
- ImageProcessor.Web version (if applicable): v4.8.4
- Other ImageProcessor packages and versions: ImageProcessor.Web.PostProcessor 1.2.2
- Environment (Operating system, version and so on): Windows 10, VS2017
- .NET Framework version: v4.6.2
- Additional information: -

**Comment by JimBobSquarePants** [comment]
Thanks for this, definitely an oversight on my part. 

>Suggested fix: change the input parameter for TruePNG to %2 so it will take the output of pngquant and use that to run the TruePNG optimiser. Would need a /force parameter as well to overwrite the output file.

That looks like the correct plan, do we need force though? We only want to overwrite if TruePng can reduce the file.

**Comment by tomvanenckevort** [comment]
Yes, you're right. I misread what the `force` parameter does. I though we needed it because the input and output path are the same, but it looks like `force` always generates the file, even if it's bigger.

**Comment by JimBobSquarePants** [comment]
Fixed it, will push a release today. Thanks for your help. 👍
