### ISSUE TITLE
How set watermark to RightTop/RightBottom

### ISSUE THREAD

**Issue by RaulSteven** [JimBobSquarePants/ImageProcessor#611]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I want to add TextLayer to the Image's RightTop or RightBottom with the method "Watermark",
How should I set the Position?

### System Configuration

- ImageProcessor version:2.5.4
- ImageProcessor.Web version (if applicable)
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:4.5.2
- Additional information:visual studio 2015

**Comment by JimBobSquarePants** [comment]
Hi @RaulSteven 

This question would have been better suited to our Gitter channel but I'll answer here for you.

If you look at the [documentation](http://imageprocessor.org/imageprocessor/imagefactory/watermark/) you will see that the watermark plugin accepts a `TextLayer` property which in turn has a `Position` property which is op type `System.Drawing.Point`. That's the only way to set the position and requires you to do the maths yourself.

Cheers

James
