### ISSUE TITLE
Whitelist validation for RemoteImageService: too permissive??

### ISSUE THREAD

**Issue by natwallbank** [JimBobSquarePants/ImageProcessor#615]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
For my purposes I think that there may be a small issue with the whitelist validation in RemoteImageService, in that it's too permissive with sub-domains.

See `IsValidRequest` method: https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/src/ImageProcessor.Web/Services/RemoteImageService.cs#L79

I was already implementing a custom version, so used the following variation:

```
            // Check the url is from a whitelisted location.
            var url = new Uri(path);
            var upper = url.Host.ToUpperInvariant();

            // Check for root or sub domain.
            foreach (var uri in ImageProcessingWhitelist)
            {
                var compareUri = uri;
                if (!compareUri.IsAbsoluteUri)
                {
                    compareUri = new Uri("http://" + compareUri.ToString().TrimStart('.', '/'));
                }

                if (upper.StartsWith(compareUri.Host.ToUpperInvariant())
                    || upper.EndsWith($".{compareUri.Host.ToUpperInvariant()}"))
                {
                    return true;
                }
            }

            return false;
```

I recognise that just blindly assuming that what's in the whitelist is a complete (sub-)domain and pre-pending a period may not be what everyone actually needs; it just suited my purpose.

### Steps to Reproduce

1. Add a sub-domain to the whitelist configuration, e.g. sub.domain.com
2. Request an image that is hosted at a different - but similar - subdomain, e.g. invalid-sub.domain.com
3. The image will be served, even though it's on a different sub-domain

### System Configuration

Local debugging / unit testing

- ImageProcessor version: 2.5.4
- ImageProcessor.Web version (if applicable): 4.8.4
- Other ImageProcessor packages and versions:
-- ImageProcessor.Web.Config v2.3.0
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.6.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @natwallbank 

The whitelist is specifically designed to be as permissive as you make it. the more detail you put in, the more restrictive. It needs to allow developers to be as loose as they need to also.

Cheers

James

**Comment by natwallbank** [comment]
Hi @JimBobSquarePants.  Thanks for the swift reply and thanks for the awesome library!

No problem, it was just something that surprised me after I'd configured a load of unit tests and one of them failed, testing a different sub-domain.  I thought it was worth mentioning but didn't want to presume that it was not by design!

Cheers,

Nat
