### ISSUE TITLE
Unrecognized attribute 'extensionLess'. Note that attribute names are case-sensitive.

### ISSUE THREAD

**Issue by Myster** [JimBobSquarePants/ImageProcessor#616]
### Description
**Parser Error Message**: Unrecognized attribute 'extensionLess'. Note that attribute names are case-sensitive.
**Source Error:** 
```
Line 29:         <add url="http://nzstatic.com" />
Line 30:         <add url="http://ytimg.com" />
Line 31:         <add url="http://maps.googleapis.com" extensionLess="true" imageFormat=".png" />
Line 32:       </whitelist>
Line 33:     </service>
```
### Steps to Reproduce
Include this item in the whitelist (as per [the documentation](http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig) )
`<add url="http://maps.googleapis.com" extensionLess="true" imageFormat=".png" />`

### System Configuration
- ImageProcessor version: 2.5.4
- ImageProcessor.Web version: 4.8.4
- ImageProcessor.Web.Config version: 2.3.0
- Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2046.0

**Comment by JimBobSquarePants** [comment]
Hi @Myster 

Yeah sorry, those docs need updating. You don't need either `extensionLess` or `imageformat` now. It's all worked out correctly automatically. 

Cheers

James
