### ISSUE TITLE
IImageService conditional disable

### ISSUE THREAD

**Issue by agrath** [JimBobSquarePants/ImageProcessor#618]
For Umbraco, we're redirecting our development media to a remote fileshare. 
This allows developers who have local installs to access the same, shared media.
We have this working by:
* replacing FileSystemProvider with our own that writes to UNC
* redirecting /media with a location node in web.config
* implementing a virtual file provider that intercepts physical file requests for /media and routes them to UNC
This is loosely based on AzureFileSystem.

We realised that the media served in development was not being transformed by image resizer, so I then implemented an IImageService with the prefix /media (following CloudImageService) and this works correctly.

Unforutunately, when we deploy to staging & production, I need a way to turn this service off (defined in ~/config/imageprocessor/security.config) and we don't transform this file as part of deployment.

The rest of our configuration for shared media in development is transformed to turn it off (roll back to default configuration)

Is there any way that I can conditionally disable the IImageService if a web.config setting is in place?
Remove it from the collection or similar?

I can't see anything in the interface and if I return false from IsValidRequest then no image processing kicks in, which would be bad - the service intercepts all requests but then IsValidRequest false means the full size image is served because it matches the prefix (I think; because LocalFileImageService did not get invoked)

I don't know if whitelist matches local or remote domain but the examples here seem to suggest https://github.com/JimBobSquarePants/ImageProcessor/blob/2f2044da7bf7f3960928a7ea47f5540975946062/tests/ImageProcessor.TestWebsite/config/imageprocessor/security.config it would be the remote URL in which case it can't be used to disable the IImageService conditionally in production.

We're not keen to rely on people remembering to remove the config when they deploy...

**Comment by agrath** [comment]
I've answered my own question...

```
 var imageServices = ImageProcessorConfiguration.Instance.ImageServices;
var mediaRedirectionService = imageServices.FirstOrDefault(i => i.Prefix == "media/");
 if (mediaRedirectionService != null)
 {
imageServices.Remove(mediaRedirectionService);
 }
```

**Comment by JimBobSquarePants** [comment]
Glad you figured it out. P.s what's Image Resizer? 😝

**Comment by agrath** [comment]
@JimBobSquarePants I have no idea what you're talking about :smirk_cat:
