### ISSUE TITLE
Adding whitelist URLs/Wildcard

### ISSUE THREAD

**Issue by Goofy10** [JimBobSquarePants/ImageProcessor#621]
Hello,

I have a strong named project (IIS Website), where I would like to process some images from random domains. Is there any chance I can write a Wildcard or edit the URLs Whitelist during its runtime (when I know these domains)?

**Comment by JimBobSquarePants** [comment]
Hi @Goofy10 

Actually, yes you can. The services are stored as a list in the `ImageProcessorConfiguration` class. It should simply be a case of finding the service within that list and assigning the whitelist

https://github.com/JimBobSquarePants/ImageProcessor/blob/7ddc33f028e974481203a57800a2f882b4433468/src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs#L83

Hope that's all clear
