### ISSUE TITLE
How to config web cache return 304 state code ?

### ISSUE THREAD

**Issue by MajidSafari** [JimBobSquarePants/ImageProcessor#622]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageProcessor version: last
- ImageProcessor.Web version (if applicable) last
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

![untitled](https://user-images.githubusercontent.com/5099564/29497760-391cd918-8603-11e7-969f-25b8ba531fe5.png)

**Comment by JimBobSquarePants** [comment]
It does it automatically via the static file handler built into Asp.NET

304 and 200 return codes are returned based on the cache status of the browser (E.g 304's are returned when a browser makes a request and the response hasn't changed, 200 will be returned on first request and when the response is already cached in the browser). Make sure when testing you do not have caching disabled in your developer tools also.

P.S Please don't use the issue tracker for questions. We have spoken about this before. There is a dedicated [Gitter](https://gitter.im/JimBobSquarePants/ImageProcessor) channel.
