### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by SergeBerwert** [JimBobSquarePants/ImageProcessor#639]
I Have a Question are you going to do a .Net Core version of Image Processor?

I have a question are you going to do a .Net Core version of ImageProcessor? I know it is not possible right now but according to the Blog post from Microsoft, the System.Drawing Namespace should be available soon for .net core

https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/#comment-414245

**Comment by Jeavon** [comment]
@SergeBerwert James and the team have been working on just that for quite some time! You can find it at https://github.com/SixLabors/ImageSharp

**Comment by JimBobSquarePants** [comment]
@SergeBerwert To Add to that, The System.Drawing namespace offered by Microsoft is for backwards compatibility only. There will be no optimization work performed on the library and some parts will not be fully shimmable. 

ImageSharp is where my focus is for netcore and it's nearly ready. I encourage you to check it out.

**Comment by SergeBerwert** [comment]
You can be sure I will. I hope it will be awesome.

**Comment by JimBobSquarePants** [comment]
It's my Sistine Chapel
