### ISSUE TITLE
Cropping Image With ImageProcessor not working on server

### ISSUE THREAD

**Issue by reza1mohammad** [JimBobSquarePants/ImageProcessor#643]
I use [this plugin][1]  for cropping image in my asp.net mvc 5 application. When I launch application in localhost every thing are right and I can crop image successfully. But I cant crop images on server. I don't get any error and image saved in original size. I also uploaded config folder at the root of website and my web config has default setting according to [ImageProcessor.Web configuration][2].

I don't know what the problem is and what should I check.

What's the problem and how can I fix that?

  [1]: http://imageprocessor.org/imageprocessor-web/
  [2]: http://imageprocessor.org/imageprocessor-web/configuration/

**Comment by JimBobSquarePants** [comment]
@reza1mohammad 

I don't have enough information from you to be able to tell you what is wrong but you should check the following. 

- Are your binaries actually deployed?
- Is your configuration properly deployed?
- Are you running in 64 bit mode?
- Does your server have correct permissions to save files?

The issue tracker for ImageProcessor should really be used only for bugs. You would be much better off asking the question on Stackoverflow using the ImageProcessor tag.
