### ISSUE TITLE
Some JPEG files getting larger at lower qualities

### ISSUE THREAD

**Issue by Dingus-Khan** [JimBobSquarePants/ImageProcessor#645]
I'm using ImageProcessor to crop and reduce the size of JPEG images shown on our website, and I'm having issues. I load an image into an ImageFactory, and run `.Quality(x)` on it, with various values for testing purposes. The example values I'm using are 60, 80, 90, and 100. However, I'm facing an issue where some of the files produced at a quality of 60 are considerably larger than files produced using 80, 90, or 100. I can't see any reason for this to happen.

I'm currently using Visual Studio Community 2017 (Version 15.5.3), .NET Framework version 4.7.02558, and ImageProcessor version 2.5.6 (Installed via NuGet).

![imagesizes](https://user-images.githubusercontent.com/8373776/34826627-3c01676a-f6cf-11e7-8b7b-db24c7935acb.png)

This image shows the file sizes, where the name is the quality passed into `.Quality(x)`. [This issue (#324)](https://github.com/JimBobSquarePants/ImageProcessor/issues/324), which is similar to mine, suggests that the issue is related to the JPEG encoder included in .NET, but also seems to state that there is a new encoder being used in its place.

**Comment by JimBobSquarePants** [comment]
Hi there, 

There's no additional encoder, you're looking at the default. .NET one. That issue relates to a very, very early version of ImageSharp which was originally ImageProcessorCore. 

In your screenshot the 60% output is the smallest of the newly encoded images at 61kb with the size incrementally increasing with the increase in quality.  

I cannot see any issue. 

Cheers

James

**Comment by Dingus-Khan** [comment]
I do apologise, I mis-wrote my issue. The issue is that the "compressed" files are larger than the original, where 60 is the first one to show up smaller. I'd imagine that this is something to do with the encoder, perhaps missing features that were originally used to compress the image to JPEG, but this is unclear.

**Comment by JimBobSquarePants** [comment]
No worries..

It'll be that the original encoder was optimized. Could be anything, specialized Huffman tables, Different Subsampling. The .NET one simply isn't that great. That's why I wrote the Postprocessor plugin for ImageProcessor.Web

**Comment by Dingus-Khan** [comment]
Ah, okay. In that case, is there a way to get the PostProcessor plugin working on standard ImageProcessor, or process images server-side only (and save them) with ImageProcessor.Web? I've not used ImageProcessor.Web before, and not sure of those capabilities. Alternatively, can I specify my own JPEG encoder when loading and saving images? Worst case, I'll fork the project and build in a new encoder, if possible.

**Comment by JimBobSquarePants** [comment]
The PostProcessor is designed specifically for use with ImageProcessor.Web. 

I would recommend having a [look at it](http://imageprocessor.org/imageprocessor-web/). It allows many different operations and is backed with a comprehensive caching system allowing great flexibilty within the responsive web. It's used by a couple of CMS systems and scales well.

>Alternatively, can I specify my own JPEG encoder when loading and saving images? Worst case, I'll fork the project and build in a new encoder, if possible.

You could create your own `ISupportedImageFormat` implementation wrapping round an existing encoder but I wouldn't recommend trying to write your own encoder - I've done it, it's really hard.
