### ISSUE TITLE
WuQuantizer.BuildPalette palette.Entries[0] is not guaranteed to be transparent.

### ISSUE THREAD

**Issue by hrishereforyou** [JimBobSquarePants/ImageProcessor#647]
### Description

I wanted to use ImageProcessor to convert a Png 32 to Png 8.
It worked correctly for around 99% of images I tried.
Few images converted transparent to black color

### Steps to Reproduce

Image image = Image.FromFile(Console.ReadLine());

PngFormat pngFormat = new PngFormat();

Bitmap bm = pngFormat.Quantizer.Quantize(image);

### Problem area

bm.Palette.Entries[0] <- Not a transparent color

### Hacky Fix

var pallete = bm.Palette;

pallete.Entries[0] = Color.Transparent;

bm.Palette = pallete;

### Part of where problem occurs

WuQuantizer.IndexedPixels

bestMatch = lookup.GetPaletteIndex(pixel);

Sometimes bestMatch will be 0.

### System Configuration

- ImageProcessor version:develop and nuget package v2.5.6
- .NET Framework version:4.5

### Image Used

![337](https://user-images.githubusercontent.com/35786207/35364818-3b15d690-013f-11e8-865c-ccd36691262d.png)

- Additional information: If this is not how I am supposed to use ImageProcessor would like to know proper way.

**Comment by JimBobSquarePants** [comment]
Hi @hrishereforyou Turns out there's a bug checking the pixel values against a transparency threshold. I'll get a new build out asap.
