### ISSUE TITLE
Installing via Package Manager error

### ISSUE THREAD

**Issue by RaviRamDhali** [JimBobSquarePants/ImageProcessor#648]
### Prerequisites

- [x ] I have written a descriptive issue title
- [ x] I have verified that I am running the latest version of ImageProcessor
- [ x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Installing package via nuget > Package Manager VS 2017.
Getting the following error: 

> Could not install package 'ImageProcessor 2.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the 
> package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
> 

ImageProcessor 2.6.0' from 'nuget.org

**Comment by dlemstra** [comment]
You will need to target .NETFramework 452

**Comment by RaviRamDhali** [comment]
worked. thanks
