### ISSUE TITLE
cache doesn't play nicely with filesystemproviders.azure useDefaultRoute setting for umbraco

### ISSUE THREAD

**Issue by cwjackso** [JimBobSquarePants/ImageProcessor#649]
If you use  a media blob container called anything other than media with "useDefaultRoute" set to true. Image processor breaks and stops cropping / caching images.

Not sure if there is any easy way to get them to work together, or add logic for when the blob isn't named media but the URL is?

See https://our.umbraco.org/forum/using-umbraco-and-getting-started/90588-azureblobcache-and-media-container-not-called-media#comment-286040

**Comment by JimBobSquarePants** [comment]
Cache works fine, you're not requesting the images properly.
