### ISSUE TITLE
Determine if image has transparency

### ISSUE THREAD

**Issue by dansiegel** [JimBobSquarePants/ImageProcessor#650]
### Description

I need to be able to determine if an image has a transparent background. In the event that it does I would then need to replace the transparency with a color. Is there a way to do this in the existing API? Basically something like this...

```cs
var imageFactory = new ImageFactory.Load(inStream);
if(imageFactory.HasTransparentBackground)
{
    imageFactory.ReplaceTransparency(Color.Black);
}
```

**Comment by JimBobSquarePants** [comment]
There's no way to tell whether an image has transparency without checking it pixels since all images are loaded with 32bit format.

I would use the `FastBitmap` class to check the `ImageFactory.Image` to avoid having to use pointers for decent performance..

``` c#
bool hasTransparent = false;
Image image  = imageFactory.Image;
using (var fast = new FastBitmap(image))
{
    for (int y = 0; y < image.Height; y++)
    {
        for (int x = 0; x < image.Width; x++)
        {
            if(fast.GetPixel(x, y).A < 255)
            {
                hasTransparent = true;
                break;
            }
        }
    }
}
```
