### ISSUE TITLE
HttpWebRequest.GetResponseAsync() does not respect the Timeout property

### ISSUE THREAD

**Issue by CameronWills** [JimBobSquarePants/ImageProcessor#651]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Our web site uses the `RemoteImageService` and for the most part it works fine. But occasionally, one of the servers hosting some of our remote images can experience excessive load and starts responding very slowly. So mitigate the effect we have set a timeout of 3000 (milliseconds) in the `<service>` configuration settings in Security.config.

But this timeout doesn't seem to be applying. And I _think_ I've figured out why:

The `RemoteImageService` uses the `RemoteFile` class to retrieve the file from origin, by building a `HttpWebRequest`, setting `HttpWebRequest.Timeout` and then calling `GetResponseAsync()`. See:
https://github.com/JimBobSquarePants/ImageProcessor/blob/963d8fd21badb3c0a9d58d3a486818c2683efce1/src/ImageProcessor.Web/Helpers/RemoteFile.cs#L176
and
https://github.com/JimBobSquarePants/ImageProcessor/blob/963d8fd21badb3c0a9d58d3a486818c2683efce1/src/ImageProcessor.Web/Helpers/RemoteFile.cs#L255

But according to the msdn documentation mentioned in in the link below, asynchronous requests on HttpWebRequest do not respect the Timeout property:

> The Timeout property has no effect on asynchronous requests

https://stackoverflow.com/questions/26214337/timeout-behaviour-in-httpwebrequest-getresponse-vs-getresponseasync

### Steps to Reproduce
Install ImageProcessor.Web Use /remote.axd with a URL that responds very slowly..

### System Configuration

.NET Framework 4.6.1
ImageProcessor 2.5.3.0
ImageProcessor.Web 4.8.3.0
ImageProcessor.Web.Plugins.AzureBlobCache 1.3.1.0
Running on Azure App Service

**Comment by JimBobSquarePants** [comment]
Good detective work! 👍 

Would it be possible to submit a PR updating the `RemoteFile` class to use `HttpClient`? I don't know when I'll get the chance to do it myself.
