### ISSUE TITLE
Updating a file successfully breaks cache, but doesn't resume using newly cached image

### ISSUE THREAD

**Issue by MellowArpeggiation** [JimBobSquarePants/ImageProcessor#653]
### Description
When updating an image on disk, the ImageProcessor succesfully returns the new image after processing and caching the new image.

However, all subsequent loads will miss the cache and process an entirely identical image every time.

I've made a fork, and I'm going to make a few changes that I've used in my dev environment, which I have verified as working. But the changes potentially have some far reaching implications so I want the owner of this project to be aware of what I'm doing and why. I'll make a PR related to this issue shortly

### Steps to Reproduce
1. Create and serve an image
    * Server runtime inspection shows the image being processed
2. Reload the image without browser cache to serve a new image from server cache
    * Server runtime inspection shows no processing, and the load is very fast
2. Modify the image in place
3. Reload the page without browser cache to serve the image anew
    * Server runtime inspection shows the image being processed
4. The image is successfully served as a new image, not the cached version
5. Reload the page once again
    * ISSUE: The server shows that the image is once again being processed, and this continues for every subsequent load indefinitely, this is incredibly slow, particularly in our case where we have hundreds of small sites split over very few servers

### System Configuration
- ImageProcessor version: Custom IImageCache implementation on ImageProcessor.Web - 4.9.1.2
- Environment (Operating system, version and so on): Dev server running on IIS 7 on Windows 10
- .NET Framework version: .NET 4.7

**Comment by JimBobSquarePants** [comment]
I'm having trouble following the issue here; maybe I need some coffee.

Are you saying that once you update a source image with a new one with the same file name every subsequent request is fully processed?

**Comment by MellowArpeggiation** [comment]
Ah, sorry, perhaps I could have phrased it better. But yes, that is what I'm trying to say
