### ISSUE TITLE
Redundant request when using Azure without a CDN

### ISSUE THREAD

**Issue by SteveVaneeckhout** [JimBobSquarePants/ImageProcessor#655]
A couple of weeks ago I launched a website that gets a lot of traffic. I noticed that when there are 30000 requests to the blob storage in 1 hour only 7000 of them are a GetBlob type request. All other requests are just retrieving metadata. During busy times the 302 Redirect respones become slow and even Azure storage becomes slow to respond (+1800ms).

One issue I've found is this: https://github.com/JimBobSquarePants/ImageProcessor/blob/963d8fd21badb3c0a9d58d3a486818c2683efce1/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L404
Is this request really necessary when `this.cachedRewritePath` and `this.CachedPath` are the same?

Another issue is the default expiration value of the internal cache of 1 minute and it's not configurable. https://github.com/JimBobSquarePants/ImageProcessor/blob/963d8fd21badb3c0a9d58d3a486818c2683efce1/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L200

Would you like me to create a pull request?

**Comment by JimBobSquarePants** [comment]
Yeah, totally, that would be great! 👍

**Comment by SteveVaneeckhout** [comment]
But wait, there's more!
If you insert this code [before the else statement](https://github.com/JimBobSquarePants/ImageProcessor/blob/bc14ee22b3bbb32f710290147673aa97fc6ab0f5/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L395) you can eliminate another request:

    else if (this.cachedRewritePath == this.CachedPath)
    {
        // CachedCDNRoot is the same as the cached Blob container, no need to check it again
        ImageProcessingModule.AddCorsRequestHeaders(context);
        context.Response.Redirect(this.cachedRewritePath, false);
    }

**Comment by JimBobSquarePants** [comment]
@SteveVaneeckhout I don't understand. The code already exists at the beginning of the else statement?

https://github.com/JimBobSquarePants/ImageProcessor/blob/bc14ee22b3bbb32f710290147673aa97fc6ab0f5/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L398

**Comment by SteveVaneeckhout** [comment]
Sorry, my bad! I was looking at the wrong commit.
Thanks for the change. I'll try to update my website later next month and share the results.

**Comment by SteveVaneeckhout** [comment]
![impact-update](https://user-images.githubusercontent.com/6131869/39418951-9d56f38e-4c5d-11e8-987a-be33040647a7.png)

The website was updated at the vertical bar. As you can see, the impact is pretty big.
