### ISSUE TITLE
Cached images not updated from remote source

### ISSUE THREAD

**Issue by MichaelNielsenDK** [JimBobSquarePants/ImageProcessor#656]
Hi

I'm not sure if this is en error, or just something ImageProcessor does not do. 

We are using remote.axd to request external images, i.e
`<img src="/remote.axd/domain.com/path/filename.jpg?mode=crop&width=200&height=200">`  

Which works perfectly fine. The first time an image is requested, it is processed and cached locally, and from that point, all future requests uses the cached image.  

However, if the image is changed/updated/overwritten on the external source, the cached files are not updated. 

My guess is that ImageProcessor only looks at filename, not bytesize, is that correct?

Is there a way to update the image, when the source image changes?

Right now our work-around is to include a unix timestamp,  in the file name, like this
`<img src="/remote.axd/domain.com/path/filename.jpg?mode=crop&width=200&height=200&cachebreak=1520937411">`  
The timestamp is then set to change every few hours, thus creating a new cached file.

This will however create new cached files for all images, it would be better to do it, for just those who have been changed/updated/overwritten. 

### System Configuration
- Umbraco version: 7.7.13
- ImageProcessor version: 2.6.0
- ImageProcessor.Web version: 4.9.1.2
- ImageProcessor.Config version: 2.4.0

**Comment by JimBobSquarePants** [comment]
Hi @MichaelNielsenDK 

In order to track changes we'd have to make two requests for remote files, first a head then a full request. That would be far too labor intensive and would probably annoy anyone on the receiving end of such requests.

The `RemoteImageService` is a service of last resort. If you control your image sources do not use it. Rather create your own `IImageService` implementation.

**Comment by MichaelNielsenDK** [comment]
Hi Jim

We have no control over the image source, so I guess the best 3 options would be:
1. Do as we do now with the timestamp
2. Delete the entire image cache now and then
3. Request images directly from the remote source

Thanks for the answer.
