### ISSUE TITLE
System.UnauthorizedAccessException when post processing PNG images

### ISSUE THREAD

**Issue by ronaldbarendse** [JimBobSquarePants/ImageProcessor#661]
We're getting exceptions only when PNG images are getting optimized, other images are getting optimized fine (e.g. permissions on the temp directory are correct)...

```
System.UnauthorizedAccessException: Access to the path 'C:\Windows\TEMP\tmp46F-out.png' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ImageProcessor.Web.Plugins.PostProcessor.PostProcessor.PostProcessImage(HttpContext context, MemoryStream stream, String extension)
   at ImageProcessor.Web.Plugins.PostProcessor.PostProcessorApplicationEvents.PostProcess(Object sender, PostProcessingEventArgs e)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__34.MoveNext()
```

Looking at the PostProcessor plugin, one of the differences is that for PNGs a batch file is called... I'll have to debug the code to see on which line the exception occours (`File.Create` before running the process or `File.OpenRead` after processing), but maybe the file is still locked by `pngquant` or `truepng` when the batch exits or is killed after the timeout.

A welcome addition would be to have 2 timeouts: the first for returning the original image if the processing takes too long and the other for killing the process. This way, the first request(s) gets the original image within a reasonable time, but the image is still optimized (and saved in the cache) for the next requests...

I'll update this issue when I have further details!

Used versions: ImageProcessor/2.5.6.0 - ImageProcessor.Web/4.8.7.0

**Comment by enkelmedia** [comment]
I have the same issue on my machine

**Comment by JimBobSquarePants** [comment]
We'll need to catch the exception and return the original image. Timeouts won't help here when you consider the end user.

**Comment by ronaldbarendse** [comment]
The problem seems to be that the parent and/or child processes are not (fully) killed before returning the result in `PostProcessor.RunProcess()`. As noted in the [MSDN page for Process.Kill](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.kill(v=vs.110).aspx):

> The Kill method executes asynchronously. After calling the Kill method, call the WaitForExit method to wait for the process to exit, or check the HasExited property to determine if the process has exited.

So that could cause the file to still be in use and therefore deny access in `PostProcessor.PostProcessImage()`. The `Kill()` method also doesn't kill the whole process tree, so any child processes should also be killed: this should at least be tested.

**Comment by JimBobSquarePants** [comment]
Yeah, you're absolutely right, we should be looking for and killing the child processes too.

https://stackoverflow.com/a/32405627

You got time for a PR?
