### ISSUE TITLE
ImageCacheBase.AugmentSettings not thread safe, crashing bug.

### ISSUE THREAD

**Issue by CameronWills** [JimBobSquarePants/ImageProcessor#663]
https://github.com/JimBobSquarePants/ImageProcessor/blob/bc14ee22b3bbb32f710290147673aa97fc6ab0f5/src/ImageProcessor.Web/Caching/ImageCacheBase.cs#L67

Hi Jim, 

The method `ImageCacheBase.AugmentSettings()` is protected virtual method designed to be overridden in custom cache implementations. However, this method is operating on a shared `Dictionary<string, string>` object taken from `ImageProcessorConfiguration.Instance.ImageCacheSettings`. 
This isn't thread safe when the constructor for a cache is run by two threads and one thread is updating the dictionary while the other thread is looking-up/enumerating on it.

Refer: https://blogs.msdn.microsoft.com/tess/2009/12/21/high-cpu-in-net-app-using-a-static-generic-dictionary/

**Comment by JimBobSquarePants** [comment]
I think we'll have to simply lock around this when setting as I can't change the dictionary type without introducing a breaking change.
