### ISSUE TITLE
Attempt to implement ImageProcessor.Web to nop commerce 4.0

### ISSUE THREAD

**Issue by Squalex1496** [JimBobSquarePants/ImageProcessor#667]
Hi,

There seems to be an issue with regards to the ImageProcessor.Web onto a .Net Core 2.0 Project. I've sucessfully installed, image processor and image processor.net on a Nop Commerce Template however when i append query strings to an image url nothing seems to be taking affect. I've used this before on an Umbraco site and the results were spectacular, and exactly as explained in the documentation and i would greatly like to implement it in the same way on Nop Commerce too. Normally a simple install would allow me to edit the pictures via querstring without doing anything extra i cannot seem to understand why its not the case with .Net Core 2.0. Any feedback would be greatly appreciated thanks.

**Comment by JimBobSquarePants** [comment]
Hi there,

ImageProcessor.Web doesn’t and will never target NetCore 2.0

HttpModules don’t even exist in ASP.NET Core so it won’t be intercepting requests. 

I wrote ImageSharp.Web for ASP.NET Core for precisely this reason. Check it out here, it’s lighter and faster than ImageProcesor.Web.

https://github.com/SixLabors/ImageSharp.Web
