### ISSUE TITLE
Access HttpContext in IImageService

### ISSUE THREAD

**Issue by chrno1209** [JimBobSquarePants/ImageProcessor#668]
Hi Jim,
Currently I am trying to use ImageProcessor in an EPiServer project, where I need to access HttpContext inside IImageService, is there any chance I can do it?

Regards,
Hieu.

**Comment by JimBobSquarePants** [comment]
Hi @chrno1209 

Sorry, I thought I'd answered this. You can probably get away with `HttpContext.Current`. 

Cheers

James

**Comment by chrno1209** [comment]
Hi @JimBobSquarePants ,
I did try to access HttpContext.Current but it's always NULL, that's why I dropped a question here :).

Thanks.

**Comment by JimBobSquarePants** [comment]
Odd. I see in the linked issue you were able to access it in the HttpModule instead. 👍

**Comment by chrno1209** [comment]
Yes, but anyway we can close this ticket :)
