### ISSUE TITLE
Metadata is stripped after image is processed: ImageProcessor.Web 4.9.2.19

### ISSUE THREAD

**Issue by juliangrahame** [JimBobSquarePants/ImageProcessor#669]
Hi James

Using: 

- ImageProcessor version: 2.6.1.19
- ImageProcessor.Web version: 4.9.2.19
- Environment: Windows 10, Windows Server 2012
- .NET Framework version: 4.6.1
- Umbraco 7.9.2

Got a call recently from a client (photographer) who stores licencing info in Image metadata according to the IPTC standard - http://www.controlledvocabulary.com/imagedatabases/iptc_naa.html. 
He mentioned that this metadata was being stripped out of any images that he uploaded to Umbraco. 

I tested this and indeed, before I upload the image to Umbraco, I can see the IPTC metadata section in PhotoShop - File Info (Windows properties never shows this stuff). After uploading and processing, when I save a copy off the site, the IPTC section is no longer there (all other metadata fields are persisted).

I have confirmed that this still happens after upgrade to latest version and setting `metaDataMode `to `All`.  

Perhaps you know more about IPTC than I do.  Personally I had never heard of IPTC and I am still pretty much in the dark. However,I am led to believe (by my client) that IPTC is very much a common standard so I have a few questions -

- Is this stripping of IPTC metadata by design?
- If it is then what was the reasoning? If not then is this something that is on the radar?
- Any plans to implement?

Can supply sample images if required.

Thanks in advance

Julian

**Comment by juliangrahame** [comment]
Thanks @JimBobSquarePants 

Although I think there may be an issue with the version we have upgraded to (IP: 2.6.1.19, IP.Web version: 4.9.2.19) because after upgrading it turns out that no metadata at all seems to be persisted.  Apologies I hadn't realised this was happening.

I have this in my processing.config: 
`<processing preserveExifMetaData="true" metaDataMode="All" fixGamma="false" interceptAllRequests="false" allowCacheBuster="true">`

Was previously using the following versions which did persist a fair amount of metadata (Copyright camera information etc): 
ImageProcessor: 2.5.6
ImageProcessor.Web: 4.8.7

So with the latest version, we are not getting any metadata persisted at all after uploading to Umbraco and saving off the website.
J

**Comment by JimBobSquarePants** [comment]
Can you do me a favour and check against the sample application in the repository? I want to make sure there's nothing overwriting setting in Umbraco.

**Comment by juliangrahame** [comment]
Found it - I see I can set as parameter in call to ImageFactory.  

Tested with one of our images and all seems good in fact - at least with MetaDataMode.All, the same metadata is being persisted as previously with IP version 2.5.6 (so the same data is being stripped out as well).  So maybe Umbraco is overwriting something?

**Comment by JimBobSquarePants** [comment]
Apologies.. I should have been more clear.

There's a test website that has uses customizable configuration files.

https://github.com/JimBobSquarePants/ImageProcessor/blob/74b37314037dc49b157fb5aa3e2af3a77806ff7b/tests/ImageProcessor.TestWebsite/config/imageprocessor/processing.config#L1

I would attach the debugger to it and what what parameters are passed to the ImageFactory within the ImageProcessingModule

https://github.com/JimBobSquarePants/ImageProcessor/blob/74b37314037dc49b157fb5aa3e2af3a77806ff7b/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L630

The parameters should match what you were passing in the playground. 

I would test that site against one of your images and check the cached output. It should preserve the metadata. If not, then we definitely have an issue.

**Comment by juliangrahame** [comment]
Hi James

Actually there is an issue.  All metadata is currently stripped out of any processed images on the test site.

The culprit is: 
https://github.com/JimBobSquarePants/ImageProcessor/blob/74b37314037dc49b157fb5aa3e2af3a77806ff7b/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L627

I think should be: 
`MetaDataMode metaMode = !exif ? MetaDataMode.None : metaDataMode.Value;`

Hope that helps :)

Jules

**Comment by JimBobSquarePants** [comment]
I think you may well be correct! How I missed that I don't know. I'll get a release out asap.

**Comment by juliangrahame** [comment]
Actually wanted to do this with a PR but if I'm reading instructions correctly I would have to fork first?  Never mind my first contribution to open source will have to wait a little longer :)

**Comment by JimBobSquarePants** [comment]
Thanks.... Yeah don't worry about it I'll try and get to it in the next 24 hours. 😄

**Comment by juliangrahame** [comment]
Hi @JimBobSquarePants 
So just opened a pull request for this.  First time so hope I've done it right :)
Jules

**Comment by JimBobSquarePants** [comment]
Fixed in https://www.nuget.org/packages/ImageProcessor.Web/4.9.3.25 
Thanks for your help!
