### ISSUE TITLE
Updating via Nuget doesn't honor existing cache settings. 

### ISSUE THREAD

**Issue by andersbrohall** [JimBobSquarePants/ImageProcessor#671]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When updating the ImageProcessor.Web.Config, Nuget doesn't honor any existing caching/caches/cache/settings/setting. Resulting in a duplicate that overrides the existing. 

IE: 
```
<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="DiskCache">
	<caches>
		<cache folderDepth="6" trimCache="false" name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" memoryMaxMinutes="1" browserMaxDays="7">
			<settings>
				<setting key="VirtualCachePath" value="~/ImageProcessor" />
			<setting key="VirtualCachePath" value="~/app_data/cache" /></settings>
		</cache>
	</caches>
</caching>
```

### Steps to Reproduce
Install any older version, update it via the Package Manager Command line: Install-Package ImageProcessor.Web.Config -Version 2.4.1.19 (or without specified version)

### System Configuration
VS 2017

- ImageProcessor version: 2.4.1.19
- ImageProcessor.Web version (if applicable)
- Other ImageProcessor packages and versions: .MVC .PostProcessor
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.5.2
- Additional information:

(y)

**Comment by JimBobSquarePants** [comment]
Thanks for raising this but unfortunately I can’t fix this. Nuget’s diff engine simply doesn’t work properly. The bug should be raised with them.
