### ISSUE TITLE
Using AzureBlobCache without a CDN

### ISSUE THREAD

**Issue by gdiazderadaa** [JimBobSquarePants/ImageProcessor#672]
Hi there,

First of all thanks for this awesome plugin!

This is more a question than a bug: Can I use AzureBlobCache without a CDN? If so what are the required settings apart from CachedStorageAccount and CachedBlobContainer? We've set up 2 blob containers in Azure, one for the media and one for the cache.

Thanks in advance

**Comment by JimBobSquarePants** [comment]
Hi @gdiazderadaa

Yeah you can. If you set the CloudImageService config to point at your blob storage url that will work fine. You won't need any additional settings.

Cheers

James
