### ISSUE TITLE
System.NotSupportedException in ImageProcessor.Web

### ISSUE THREAD

**Issue by ronaldbarendse** [JimBobSquarePants/ImageProcessor#675]
While debugging the code, I saw quite a lot of `NotSupportedException`s... Setting it to break on this exception type, I noticed it was coming from `QueryParamParser.ParseValue<bool>()` when trying to parse a `null` value. It should probably short circut on `null`, instead of throwing and catching the exception (or refactor it to e.g. `TryParseValue<bool>`).

The full stack trace for one of the exceptions is:
```
ImageProcessor.Web.Helpers.QueryParamConverter.GetConvertFromException(object value)
ImageProcessor.Web.Helpers.QueryParamConverter.ConvertFrom(System.Globalization.CultureInfo culture, object value, System.Type propertyType) Line 79	C#
ImageProcessor.Web.Helpers.GenericConvertableConverter<bool>.ConvertFrom(System.Globalization.CultureInfo culture, object value, System.Type propertyType) Line 55	C#
ImageProcessor.Web.Helpers.QueryParamParser.ParseValue(System.Type type, string value, System.Globalization.CultureInfo culture) Line 104	C#
ImageProcessor.Web.Helpers.QueryParamParser.ParseValue<bool>(string value, System.Globalization.CultureInfo culture) Line 74	C#
ImageProcessor.Web.Processors.Watermark.ParseVertical(System.Collections.Specialized.NameValueCollection queryCollection) Line 253	C#
ImageProcessor.Web.Processors.Watermark.MatchRegexIndex(string queryString) Line 74	C#
ImageProcessor.Web.ImageFactoryExtensions.GetMatchingProcessors.AnonymousMethod__0(ImageProcessor.Web.Processors.IWebGraphicsProcessor x) Line 66	C#
[External Code]	
ImageProcessor.Web.ImageFactoryExtensions.GetMatchingProcessors(string querystring) Line 65	C#
ImageProcessor.Web.HttpModules.ImageProcessingModule.ProcessImageAsync(System.Web.HttpContext context) Line 564	C#
ImageProcessor.Web.HttpModules.ImageProcessingModule.PostAuthorizeRequest(object sender, System.EventArgs e) Line 380	C#
```

**Comment by JimBobSquarePants** [comment]
Interesting. Will definitely need to investigate this and others to determine both why we're passing null to the parser and also the best approach to handle null values across all parsers. (i.e i'd like to handle it once rather than attempt to do it in each one.)

**Comment by ronaldbarendse** [comment]
Could be changed in 2 ways: `QueryParamParser.ParseValue()` or in every `IQueryParamConverter` implementation. Both should directly return the default value for any `null`...

Any reason it's not handled with [`Converter.ChangeType()`](https://msdn.microsoft.com/en-us/library/dtb69x08(v=vs.110).aspx) and the [`BooleanConverter`](https://msdn.microsoft.com/en-us/library/system.componentmodel.booleanconverter(v=vs.110).aspx)? You could even inherit from any of the built-in `TypeConverter`s and apply additional custom converting logic (e.g. "0"=False, "1"=True).

**Comment by JimBobSquarePants** [comment]
I'll have to double check the code. I chose not to inherit from built in type converters as I've had problems in the past with custom typeconverters interfering with results.

It's been a while...
