### ISSUE TITLE
An image becomes red after processing

### ISSUE THREAD

**Issue by kruno-mono** [JimBobSquarePants/ImageProcessor#677]
### Description
I processed image through the ImageProcessor without any custumization in settings. After processing through the ImageProcessor, my image becom red. It doesn't happend on all my images, but some of them have this strange result. Can you please advise me what was wrong?

This is my original image:

![155880223](https://user-images.githubusercontent.com/20225192/41653016-19e07994-7485-11e8-87f2-435683d090b9.jpg)

And this is result after processing:

![155880223_5awctz4mjobqkri2w70vi3](https://user-images.githubusercontent.com/20225192/41653069-3b529af8-7485-11e8-9f85-9a3bce30624c.jpg)

### Steps to Reproduce
`using (var imageFactory = new ImageProcessor.ImageFactory(preserveExifData: true))`
`                {`
`                    var imgFactory = imageFactory.Load(processingParams.InputStream);`
`                    imgFactory.Save(processingParams.OutputStream);`
`                }`

### System Configuration

- ImageProcessor version: 2.6.2.25
- Environment: Windows 8.1
- .NET Framework version: 4.7.1

**Comment by JimBobSquarePants** [comment]
You’ve probably got an icc profile in the image that System Drawing is not processing properly. I’d have to check the image with jpegsnoop or ImageSharp to be sure.

**Comment by kruno-mono** [comment]
Thank you for the response. 
I'm waiting for your feedback about image. :-)

**Comment by kruno-mono** [comment]
Thank you for help.
Do you know any tool (some small useful DLL :-) ) which can convert these kinds of ICC profiles to something "normal" what System Drawing can process properly?

**Comment by JimBobSquarePants** [comment]
[PhotoSauce](https://github.com/saucecontrol/PhotoSauce) can do this I think. I want to check something with SD also though to see if we can workaround without requiring a third party so I'll keep this open.

**Comment by rahulbpatel** [comment]
Is there a plugin that can remove the ICC profile before processing?

**Comment by JimBobSquarePants** [comment]
No, I’m afraid not. It relies on System.Drawing and as such is limited
