### ISSUE TITLE
Remove from cache when media item is deleted?

### ISSUE THREAD

**Issue by danwhite85** [JimBobSquarePants/ImageProcessor#678]
Hi @JimBobSquarePants - 

Is there a way I can remove cached items from the blob cache when the media item is removed from the recycle bin in Umbraco? If not, how long will they live in the cache and what other options are there for removing items that no longer have an Umbraco media node.

My issue is that files for deleted media items can still be found via search.

ImageProcessor version=2.6.1.19
ImageProcessor.Web version=4.9.2.19
ImageProcessor.Web.Config version=2.4.1.19
ImageProcessor.Web.Plugins.AzureBlobCache version=1.4.2.19

**Comment by JimBobSquarePants** [comment]
Hi @danwhite85 

Imageprocessor.Web has no knowledge of Umbraco. 

>My issue is that files for deleted media items can still be found via search.

That's nothing to do with Imageprocessor.Web. Umbraco doesn't have access to the cached file location, it seems to me something is wrong with Examine there.

There's comprehensive configuration options available to allow cleanup of cached images.

http://imageprocessor.org/imageprocessor-web/configuration/#cacheconfig
