### ISSUE TITLE
Manipulating ValidatingRequest querystring + cache

### ISSUE THREAD

**Issue by ptrocks** [JimBobSquarePants/ImageProcessor#682]
Hello all,

I am intercepting a url that contains a UserID, based on that userID i am adding some watermark overlays via the args.QueryString option.
FInding out that this way , with the url being manipulated, it does not get cached and is always looking up the origin file.

Any way around this or to force it entering cache with the real\full URL ?

### Steps to Reproduce
Inside: Application_BeginRequest\ImageProcessingModule.ValidatingRequest:

``` c#
if (queryCollection.AllKeys.Contains("userID"))
                    { gets option based on the user}

queryCollection.Remove("UserID");
args.QueryString = queryCollection.ToString();
args.QueryString += "overlay=" + option.Image;
args.QueryString += "&overlay.opacity=" + option.Opacity.ToString();
args.QueryString += String.Format("&overlay.size={0},{1}",
                            option.Width.ToString(),
                            "0");
```

Using version imageprocessor.web 4.9.2.19 

Thanks in advance.

**Comment by JimBobSquarePants** [comment]
I think you must be doing something wrong. The library definitely reevaluates the querystring following the event.

https://github.com/JimBobSquarePants/ImageProcessor/blob/68b40136d8a3d959a8d5108d6c2660de4ac32a27/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L515
