### ISSUE TITLE
Could you make the nuget dll be Strong Name?

### ISSUE THREAD

**Issue by minren118** [JimBobSquarePants/ImageProcessor#685]
I want to reference DLLS in my project and need a strong name reference.Currently, DLL in nuget are not published by strong names

**Comment by minren118** [comment]
My project is using .Net 4.0,So I need the  version 2.5 to be a Strong Name dll In nuget

**Comment by JimBobSquarePants** [comment]
Hi @minren118 

What you are asking for is impossible for the following reasons:

1. Nuget packages once released are immutable. I, nor anyone else cannot change the released binary.
2. NET 4.0 is not supported by either myself nor Microsoft. The minimum supported version is NET 4.5.2

I strongly recommend you upgrade to use that framework or else you are exposing potential users to security defects. I would personally never run software supporting less than 4.5.2.
