### ISSUE TITLE
Format not processed imperatively/in order

### ISSUE THREAD

**Issue by ronaldbarendse** [JimBobSquarePants/ImageProcessor#686]
Although the [documentation](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/) for `ImageProcessor.Web` states the API is imperative:

> The API for ImageProcessor.Web is imperative. This means that the order in which you supply the querystring parameters is the order in which the individual processors are implemented. This allows the API to be very flexible, allowing you to combine processes in any order. 

When passing multiple formats in the URL, only the first is used...

You could argue to just make sure to add a single `&format=` parameter and replace the existing format (instead of appending another). This makes it a LOT more complex to just change the resulting format. Also, presets can include a format, so that should also be taken into account, making it even more complex (and require copying the following private method):

https://github.com/JimBobSquarePants/ImageProcessor/blob/d37a8905b5c9b3c898056af8fcce3e779b5c7aed/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L777

This should at least be documented. Fixing the problem could be considered a breaking change, because the resulting file would be different for the same URL.

**Comment by ronaldbarendse** [comment]
Our workaround for now is to just prefix the format, so no further processing/replacement of existing format parameters is required...

**Comment by JimBobSquarePants** [comment]
> When passing multiple formats in the URL, only the first is used...

Yes that is because only one format is recognised which is the correct behaviour. The format command doesn't affect processing behaviour, only the output format.

**Comment by ronaldbarendse** [comment]
Yes, only one format should be used (it would be rather useless to convert between formats in the middle of processing), but I would expect the last defined format to be used, not the fist one. So for example:
- `/images/format-Penguins.png?width=300&format=jpeg`: JPEG format
- `/images/format-Penguins.png?width=300&format=jpeg&format=webp`: currently JPEG, but I would expect WebP format

While testing I also encountered another strange thing: when requesting `/images/format-Penguins.jpg?width=300&width=5` it returns an 305px wide image (instead of ignoring one or the other).
