### ISSUE TITLE
Multiple Security Services overriding Timeout

### ISSUE THREAD

**Issue by robertjf** [JimBobSquarePants/ImageProcessor#690]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using `CloudImageService` with AzureBlobStorage I am getting timeouts on large files resulting in `TaskCanceledException: A task was canceled` errors.

After stepping through in debug mode, I discovered that the shared Client in the `RemoteFile` class' Timeout property is being set every time a service configuration is read (https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/src/ImageProcessor.Web/Helpers/RemoteFile.cs#L84).

The only way I could retrieve the larger images (5MB) from Blob Storage was by setting the Timeout to -1 on all services (actually, just the last one in the list would probably do it)

### Steps to Reproduce
Attempt to create a crop on a large (> 5MB) file in Azure Blob Storage with the following configuration set:

```
<?xml version="1.0" encoding="utf-8"?>
<security>
<services>
    <!--<service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web" />-->
    <!--Disable the LocalFileImageService and enable this one when using virtual paths. -->
    <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <!--<setting key="Container" value=""/>-->
        <setting key="MaxBytes" value="81943040"/>
        <setting key="Timeout" value="60000"/>
        <setting key="Host" value="https://youritteam.blob.core.windows.net/media"/>
      </settings>
    </service>
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="4194304" />
        <setting key="Timeout" value="3000" />
        <setting key="Protocol" value="http" />
        <!-- Added version 4.7.0. Optional -->
        <!-- Sets a useragent value for the request. Useful for social networks.
             See http://www.useragentstring.com/ for available values. -->
        <!--<setting key="Useragent" value=""/>-->
      </settings>
      <whitelist>
      </whitelist>
    </service>
  </services>
</security>
```

### System Configuration
Umbraco 7.12.1

- ImageProcessor version: 2.6.2.25
- ImageProcessor.Web version (if applicable): 4.9.3.25
- Other ImageProcessor packages and versions:

  * ImageProcessor.Plugins.WebP 1.1.0
  * ImageProcessor.Web.Config 2.4.1.19
  * ImageProcessor.Web.Plugins.AzureBlobCache 1.4.2.19

- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
I don't understand the question nor the issue?

**Comment by robertjf** [comment]
The issue is that by because the second service (remote.axd) is setting the timeout last (to 3000 - 3 seconds - by default) the `BlobCacheService` times out on large images because it takes more than 3 seconds to download them as the global statically `HttpClient` instance is no longer configured for it's needs.

One way to resolve this would be to instantiate a separate HttpClient for each service perhaps.
