### ISSUE TITLE
factory.load method is slow

### ISSUE THREAD

**Issue by strongmuffin** [JimBobSquarePants/ImageProcessor#701]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am running the latest version of ImageProcessor
- [x ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x ] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Performance issue

I ran into an issue when trying to load large images, noticed that factory.load method was incredibly slow. 

7200 x 6900 (4.5mb) jpg
ImageProcessor Factory.load: ~400-600ms
C#'s Image.FromStream: ~100-175 ms

This is a big issue for web apis where you need to fetch images. It makes the server run slow and when you have to request many images it takes a long time for the page to load for the user.

### Steps to Reproduce
```C#
            using (var inStream = new MemoryStream(array)) // 1ms
            {
                using(var outStream = new MemoryStream()) // 1 ms
                {
                    using(var factory = new ImageFactory()) // 1ms
                    {
                        factory.Load(inStream); // ~400-600ms (try this with a very large resolution image)					
						
                        var image2 = Image.FromStream(inStream); // ~100-200ms
                    }

                    return outStream.GetBuffer();
                }
            }

```

### System Configuration

- ImageProcessor version: 2.6.2.25
- ImageProcessor.Web version (if applicable) : N/A
- Other ImageProcessor packages and versions: N/A
- Environment (Operating system, version and so on): Windows 10 64-Bit
- .NET Framework version: N/A
- Additional information: N/A

**Comment by JimBobSquarePants** [comment]
ImageProcessor's `Factory.Load` does a lot more when loading the image to make sure it can be processed by subsequent methods. (A brief look at the source code would have told you this)

https://github.com/JimBobSquarePants/ImageProcessor/blob/31a8c46a8556e3635273e025d435dbf593d093d3/src/ImageProcessor/ImageFactory.cs#L219

Format identification, PixelFormat conversion, metadata preservation, and cloning. 

400-600ms is not slow for an image that big.

**Comment by strongmuffin** [comment]
@JimBobSquarePants 
It is slow considering the fact that its 2-3x slower than C#'s method for reading an image. All that "extra" stuff should be specified if you need it. 

1. Format specification has no significant performance loss because you can read the signature to determine the file format.
2. You shouldn't be converting anything unless specified. (Pixel Format Conversion)
3. A lot of times we don't care about the metadata so that needs to be specified whether or not we care to read it when loading the image.
4. As far as cloning is that totally necessary upon loading?

If you're going to have an open-source project you need to be looking to improve. Because of this issue I have to switch to ImageResizer.
