### ISSUE TITLE
Add support for immutable cache header attribute

### ISSUE THREAD

**Issue by ronaldbarendse** [JimBobSquarePants/ImageProcessor#703]
Adding an `immutable` attribute to the `Cache-Control` header ensures no requests have to be done to revalidate the cache when reloading a page, see: https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/.

ImageProcessor already supports cache buster variables: https://github.com/JimBobSquarePants/ImageProcessor/blob/31a8c46a8556e3635273e025d435dbf593d093d3/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L700-L713

So should ImageProcessor add `immutable` to all responses when it detects a cache buster variable? Adding the attribute can be done using:
```c#
cache.AppendCacheExtension("immutable");
```

**Comment by ronaldbarendse** [comment]
As a workaround, IIS outbound rewrite rules can be used:
```xml
<configuration>
  <system.webServer>
    <rewrite>
      <outboundRules>
        <rule name="AddCacheControlImmutable">
          <match serverVariable="RESPONSE_Cache_Control" pattern=".*" />
          <conditions logicalGrouping="MatchAny" trackAllCaptures="false">
            <add input="{QUERY_STRING}" pattern="(\?|&amp;)rnd=" />
            <add input="{QUERY_STRING}" pattern="(\?|&amp;)v=" />
          </conditions>
          <action type="Rewrite" value="public,max-age=31536000,immutable" />
        </rule>
      </outboundRules>
    </rewrite>
  </system.webServer>
</configuration>
```
This however overwrites the configured `browserMaxDays`, so it would be nice if it played well with the ImageProcessor configuration...

**Comment by JimBobSquarePants** [comment]
I like this. Adds a feature without adding extra maintenance responsibility. 👍

**Comment by ronaldbarendse** [comment]
I've improved the outbound IIS rewrite rule, so it only matches the exact `Cache-Control` header from ImageProcessor (seems to always be `public, must-revalidate, max-age=*`).

This also makes sure it only rewrites the header if the request is already publicly cachable and allows capturing the `max-age` value (so the configured `browserMaxDays` is honored and is kept in-sync with the `Expires` header). The query string conditions now also correctly match the cache buster value on the beginning of the string (because `{QUERY_STRING}` does not start with `?`).

```xml
<rule name="AddCacheControlImmutable">
  <match serverVariable="RESPONSE_Cache_Control" pattern="public, must-revalidate, max-age=([0-9]+)" />
    <conditions logicalGrouping="MatchAny" trackAllCaptures="false">
      <add input="{QUERY_STRING}" pattern="(^|&amp;)rnd=" />
      <add input="{QUERY_STRING}" pattern="(^|&amp;)v=" />
    </conditions>
  <action type="Rewrite" value="public, immutable, max-age={R:1}" />
</rule>
```

Although I get your point on the maintenance responsibility, because it can indeed be fixed without changing ImageProcessor, it still feels like a hack and doesn't make ImageProcessor use best-performance cache headers by default.

I'm even willing to create a PR for this, just let me know whether you're prepared to merge it 😉

**Comment by JimBobSquarePants** [comment]
>Although I get your point on the maintenance responsibility, because it can indeed be fixed without changing ImageProcessor, it still feels like a hack and doesn't make ImageProcessor use best-performance cache headers by default.

I actually meant that adding this would mean no extra maintenance responsibility.
`cache.AppendCacheExtension("immutable");`
It's such a small change, so yeah, happy to add it.

**Comment by ronaldbarendse** [comment]
Ah, I thought you were referring to the rewrite rule ;-)

Adding it was indeed a small change: I just had to change `ParseCacheBuster` to a static method and change the `SetHeaders` method to add the immutable extension when cache busting variables are used 👍

**Comment by ronaldbarendse** [comment]
Just for reference:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Revalidation_and_reloading
- https://bitsup.blogspot.com/2016/05/cache-control-immutable.html

**Comment by JimBobSquarePants** [comment]
Merged
