### ISSUE TITLE
PostProcessor JPEG Compression Loses Quality Over Base ImageProcessor JPEG Compression?

### ISSUE THREAD

**Issue by Nicholas-Westby** [JimBobSquarePants/ImageProcessor#708]
# Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported (I saw a similar issue, but it wasn't quite the same, and didn't have much detail)

# Description
A few months ago, I asked you a question here: http://jamessouth.me/archive/announcing-imageprocessorwebpostprocessor/

Here is the question and answer:

![thread](https://user-images.githubusercontent.com/5933222/46643027-6997dc80-cb37-11e8-99aa-df67b4059101.png)

I've now had a chance to test that, and it seems that PostProcessor actually is lossy as compared to the compression done with ImageProcessor.Web. That is, for the same image and query string parameters, you get an image that is visually slightly different.

# Steps to Reproduce

I have an Umbraco website running on local in debug mode. It has ImageProcessor 2.6.2.25, ImageProcessor.Web 4.9.3.25, and ImageProcessor.Web.Plugins.PostProcessor 1.3.1.25 installed (all using NuGet). Doubt the version of Umbraco matters, but I think it's 7.10.4 (or thereabouts).

I upload an image to the media section of Umbraco. I then visit the URL for that media item to view and download the image. Let's call that "original.png". That URL might be /media/1234/image.png.

I then navigate to the URL with a query string parameter to convert it to a JPEG and to set the quality to 100%. That URL might be /media/1234/image.png?format=jpg&quality=100. I save that image as "with-post-processor.jpg".

I then uninstall PostProcessor, delete the bin and obj folders, delete the `App_Data/cache` folder, then rebuild the solution in Visual Studio and run it. I visit the same URL as before (/media/1234/image.png?format=jpg&quality=100) in Chrome, this time with the inspector open and caching disabled in the network tab. I save that image as "no-post-processor.jpg".

I then compare with-post-processor.jpg and no-post-processor.jpg with an online visual diff tool to get this:

![diff](https://user-images.githubusercontent.com/5933222/46643251-82ed5880-cb38-11e8-9a5e-f3b55351e7fb.png)

The red pixels occur when the pixels are very different (i.e., they differ significantly).

I also observe that when I then open both images side-by-side in different Chrome tabs and switch between those tabs rapidly, I can observe significant visual differences. The difference seem more pronounced near the top/center of the hair.

Here are each of the above mentioned images (hopefully GitHub doesn't recompress them).

### original.png (1.55MB)

![original](https://user-images.githubusercontent.com/5933222/46643373-027b2780-cb39-11e8-86bc-a8e34c266230.png)

### no-post-processor.jpg (804KB)

![no-post-processor](https://user-images.githubusercontent.com/5933222/46643407-23dc1380-cb39-11e8-8e71-e6583392417d.jpg)

### with-post-processor.jpg (162KB)

![with-post-processor](https://user-images.githubusercontent.com/5933222/46643420-35bdb680-cb39-11e8-9ad4-613113244661.jpg)

# Assessment

I'm not sure I'd call this a bug. It's nice that the image is so much smaller with post processing. However, for some situations, the extra compression is not desirable (some of my coworkers have noted the quality degradation and would like to avoid it). I still want to use ImageProcessor.Web for cropping and I still want to use PostProcessor for compressing PNG's (and some JPEG's), but there are edge cases where I'd like to turn off post processor (or otherwise find some way of avoiding this extra quality loss).

Some ideas:

* A configuration file to bypass post processing for certain file types (or to disable particular post processors).
* A query string to bypass post processing.
* A C# event that can inspect a request (e.g., URL and query string) and utilize custom logic to cancel post processing.
* Swap out a post processor to one that doesn't have quality loss.

# System Configuration

- ImageProcessor version: 2.6.2.25
- ImageProcessor.Web version: 4.9.3.25
- ImageProcessor.Web.Plugins.PostProcessor version: 1.3.1.25
- Windows 10
- Umbraco 7.10.4
- .NET Framework version: targetFramework="4.5" in the web.config

**Comment by Nicholas-Westby** [comment]
Here's another example that makes it super apparent.

### original

![original](https://user-images.githubusercontent.com/5933222/46686050-524b0480-cbb4-11e8-8a5f-930b995dd578.png)

### post-processed

![post-processed](https://user-images.githubusercontent.com/5933222/46686056-5aa33f80-cbb4-11e8-951c-e03f18ca97e1.png)

The post-processed one is with 100% quality. They're both PNG's because I just took a screenshot of a small portion of the images (don't want to reveal much about an in-progress client build).

As you can see pretty clearly in this example, the necklace and folds in the shirt become blurry even with 100% quality when using post processor. No resizing or cropping was done (i.e., I just used the format and quality query string parameters).

**Comment by JimBobSquarePants** [comment]
Hi Nick,

I'm gonna be really blunt here. I've said very clearly before (it's in the readme) that I am not adding any new features to the library.

That said....

I wasn't 100% accurate in my response there. In some cases there would be a change due to the difference in the huffman tables MozJpeg uses. By all accounts though, these changes should be acceptable and would not account for the blurriness of the second example. 

That would be caused by the System.Drawing encoder's shitty handling of sub pixel rendering. Even at 100% the output is subsampled when it shouldn't be. 

> The red pixels occur when the pixels are very different (i.e., they differ significantly).

No they have more than a 2% difference. That is all. 

I'm not going to make any changes to the library. The tools I'm using are industry standard and you would get the same results if you optimized them elsewhere.

**Comment by Nicholas-Westby** [comment]
> That would be caused by the System.Drawing encoder's shitty handling of sub pixel rendering.

That is odd that it's doing sub pixel rendering when I'm not cropping or resizing the image. Note that what appears to be a crop above is just me screenshotting a portion of the image (i.e., that crop wasn't created by ImageProcessor).

Also odd that it only has the sub pixel rendering issue only when PostProcessor is installed (i.e., I don't see it with just ImageProcessor installed). This to me implies that the issue is not with the way that System.Drawing is handling things (as System.Drawing is used by ImageProcessor rather than just by PostProcessor). Maybe I'm misunderstanding this somehow.

> No they have a 2% difference. That is all.

By "significant" I meant "different enough that this tool is showing there is a difference above the threshold I have configured" (i.e., the most significant of the differences). Wasn't meaning to imply that the pixel difference was super different.

> I'm not going to make any changes to the library.

No worries, that's about what I was expecting, but thought I'd at least explain what I was seeing. Keep up the good work with ImageSharp.
