### ISSUE TITLE
Overlay can't be placed above original dimension after AutoRotate

### ISSUE THREAD

**Issue by MrPostie** [JimBobSquarePants/ImageProcessor#709]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageProcessor
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When the AutoRotate() method is called, the image is rotated based on the Exif data. The image width and height are adjusted to the newly rotated image. For instance, an image taken in portrait mode with the camera with dimensions 800x600, will be autorotated and then the image width and height will be 600x800. However, it is then not possible to place an overlay beyond the original landscape dimension (800x600). It's only possible to place an overlay image at height 600 - height of the overlay image. Anything higher and the overlay will (start to) disappear.

### Steps to Reproduce

1. Create an overlay image to be used
2. Load an image and autorotate it (making sure it needs to be rotated)
3. Place the overlay image on the original autorotated image higher than the landscape height
4. Save the image.

Below is some example code to reproduce the issue. The files used have been attached.
```csharp
class Program
    {
        static void Main(string[] args)
        {
            using (ImageFactory imageFactory = new ImageFactory(false))
            {
                ImageFactory overlayImageFactory = new ImageFactory(false);
                imageFactory
                    .Load(@"d:\temp\trees.jpg")
                    .AutoRotate();

                overlayImageFactory.Load(@"d:\temp\overlay.png");

                // Bottom right
                ImageLayer overlayImage = new ImageLayer
                {
                    Image = overlayImageFactory.Image,
                    Position = new Point(
                            imageFactory.Image.Width - overlayImageFactory.Image.Width,
                            imageFactory.Image.Height - overlayImageFactory.Image.Height
                    ),
                };
                imageFactory.Overlay(overlayImage);

                // Top right
                overlayImage.Position = new Point(imageFactory.Image.Width - overlayImageFactory.Image.Width, 0);
                imageFactory.Overlay(overlayImage);

                // Top left
                overlayImage.Position = new Point(0, 0);
                imageFactory.Overlay(overlayImage);

                // Bottom left
                overlayImage.Position = new Point(0, imageFactory.Image.Height - overlayImageFactory.Image.Height);
                imageFactory.Overlay(overlayImage);
                imageFactory.Save(@"d:\temp\result.jpg");

                // Left half
                overlayImage.Position = new Point(0, imageFactory.Image.Width - overlayImageFactory.Image.Height / 2);
                imageFactory.Overlay(overlayImage);
                imageFactory.Save(@"d:\temp\result.jpg");

                // Right half
                overlayImage.Position = new Point(imageFactory.Image.Width, imageFactory.Image.Width - overlayImageFactory.Image.Height / 2);
                imageFactory.Overlay(overlayImage);
                imageFactory.Save(@"d:\temp\result.jpg");
            }
        }
    }
```
#### The original image
![trees](https://user-images.githubusercontent.com/10062082/46659526-5f1c2800-cbb5-11e8-8502-8e7f33282a93.jpg)

#### The overlay used
![overlay](https://user-images.githubusercontent.com/10062082/46659518-5cb9ce00-cbb5-11e8-83f4-61cd8d642a1e.png)

#### The result
![result](https://user-images.githubusercontent.com/10062082/46659992-57a94e80-cbb6-11e8-8d40-186cf9e44e1d.jpg)
A red dot in both bottom corners and full circles around the middle would be expected. However, this is not the case.

### System Configuration
- ImageProcessor version: 2.6.2.25
- Operating system: Windows 10 Pro
- .NET Framework version: 4.7.1

**Comment by JimBobSquarePants** [comment]
Thanks for raising this. Maybe we're not tracking the new dimensions properly, I'll investigate asap.

**Comment by uugan** [comment]
It works after setting rotated image width and height.
factory.Resize(new Size(rotated_width, rotated_height));

**Comment by JimBobSquarePants** [comment]
> It works after setting rotated image width and height.
factory.Resize(new Size(rotated_width, rotated_height));

I think that's because we've just discovered a bug in System.Drawing.

In the processor we can see the image dimensions are correctly reported at 853x1200. The point at which we ask System.Drawing to draw the image is [0, 753]

![image](https://user-images.githubusercontent.com/385879/52047656-94ea7f80-259d-11e9-8606-76ce261da3bf.png)

Basically we are tellign Sustem.Drawing to do the right thing, it's just not listening.

**Comment by JimBobSquarePants** [comment]
@MrPostie The correct output following the fix is as follows. 

Here's an updated sample of your code with fixes for factory disposal and middle overlay positioning.

``` c#

using (var imageFactory = new ImageFactory(false))
using (var overlayImageFactory = new ImageFactory(false))
{
    imageFactory
        .Load(Path.Combine(inPath, "autorotatebg.jpg"));

    Console.WriteLine($"{imageFactory.Image.Width}x{imageFactory.Image.Height}");

    imageFactory
        .AutoRotate();

    Console.WriteLine($"{imageFactory.Image.Width}x{imageFactory.Image.Height}");

    overlayImageFactory.Load(Path.Combine(inPath, "autorotateoverlay.png"));

    // Bottom right
    var overlayImage = new ImageLayer
    {
        Image = overlayImageFactory.Image,
        Position = new Point(
                imageFactory.Image.Width - overlayImageFactory.Image.Width,
                imageFactory.Image.Height - overlayImageFactory.Image.Height
        ),
    };

    imageFactory.Overlay(overlayImage);

    // Top right
    overlayImage.Position = new Point(imageFactory.Image.Width - overlayImageFactory.Image.Width, 0);
    imageFactory.Overlay(overlayImage);

    // Top left
    overlayImage.Position = new Point(0, 0);
    imageFactory.Overlay(overlayImage);

    // Bottom left
    overlayImage.Position = new Point(0, imageFactory.Image.Height - overlayImageFactory.Image.Height);
    imageFactory.Overlay(overlayImage);
    imageFactory.Save(Path.Combine(outPath, "autorotatebg-bl.jpg"));

    // Left half
    overlayImage.Position = new Point(0, imageFactory.Image.Height / 2 - overlayImageFactory.Image.Height / 2);
    imageFactory.Overlay(overlayImage);
    imageFactory.Save(Path.Combine(outPath, "autorotatebg-l.jpg"));

    // Right half
    overlayImage.Position = new Point(imageFactory.Image.Width, imageFactory.Image.Height / 2 - overlayImageFactory.Image.Height / 2);
    imageFactory.Overlay(overlayImage);
    imageFactory.Save(Path.Combine(outPath, "autorotatebg-r.jpg"));
}
```

![autorotatebg-bl](https://user-images.githubusercontent.com/385879/52049326-9c138c80-25a1-11e9-8bf8-1a328ec26b91.jpg)
![autorotatebg-l](https://user-images.githubusercontent.com/385879/52049327-9c138c80-25a1-11e9-83bc-eb6769d7c5dc.jpg)
![autorotatebg-r](https://user-images.githubusercontent.com/385879/52049328-9cac2300-25a1-11e9-9256-23609c5bf2e5.jpg)
