### ISSUE TITLE
Url corruption in ImageProcessingModule

### ISSUE THREAD

**Issue by rsabirov** [JimBobSquarePants/ImageProcessor#710]
Following `ValidatingRequest` handler is casuing an issue when ImageProcessor is serving request without querystring
```
ImageProcessingModule.ValidatingRequest += (sender, args) =>
{
    if (string.IsNullOrWhiteSpace(args.QueryString))
    {
        args.QueryString = "autorotate=true";
    }
};
```
`Regex.Replace` will be called by `originalQueryString = ""` and `queryString="autorotate=true"` here
https://github.com/JimBobSquarePants/ImageProcessor/blob/6bcfc369461c194c2c534405e9c54f4aa75bf8e7/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L500

As result place between each character will be replaced by `autorotate=true`. For example `url` equal to `"/1.jpg"` will change to `"/autorotate=true1autorotate=true.autorotate=truejautorotate=truepautorotate=trueg"`

`ImageProcessingModule` then passing this broken `url` parameter to constructor of Cache class.

**Comment by JimBobSquarePants** [comment]
Thanks for raising this, I'll investigate asap

**Comment by ronaldbarendse** [comment]
The query string is also corrupted when using multiple presets with the same prefix (e.g. `&preset=product&preset=product-sold`):

https://github.com/JimBobSquarePants/ImageProcessor/blob/21c4e284a80a8f3c63f89e0bdad2814740b4a0ba/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L780

The replacement should use the overload with a `MatchEvaluator`, so the lookup and replacement is done at the same time: https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace#System_Text_RegularExpressions_Regex_Replace_System_String_System_String_System_Text_RegularExpressions_MatchEvaluator_

**Comment by JimBobSquarePants** [comment]
@ronaldbarendse That's a separate issue. Happy to accept a PR there.
