### ISSUE TITLE
Seemingly Random 404 Errors

### ISSUE THREAD

**Issue by roblarky** [JimBobSquarePants/ImageProcessor#711]
Just wanted to report a very random issue I had the pleasure of spending half the day hunting down :)

I think the stuff below is pretty self-explanatory, but let me know if you need any further clarification.

URL Fails: http://localhost/ec/123/Deck.jpg?width=100
URL Works: http://localhost/ec/123/Dack.jpg?width=100

Route: 
`routes.IgnoreRoute("ec/{*url}");`

IImageService: 
`public string Prefix { get; set; } = "ec";`

ImageProcessor.Web/Helpers/UrlParser.cs > ParseUrl (current project code):
```
if (!string.IsNullOrWhiteSpace(servicePrefix))
{
    string[] split = Regex.Split(url, servicePrefix, RegexOptions.IgnoreCase);
    url = split.Length > 1 ? split[1].TrimStart("?") : split[0].TrimStart("?"); 
}
```
Since the string "ec" is in the failing URL ("Deck"), the split and URL get mangled, resulting in a 404.

I tried changing the servicePrefix to "ec/", but it looks like it gets cleaned up so servicePrefix in ParseUrl is still "ec".

I'm not familiar with the varying implementations, so my solution may not be a universal one, but this is what I changed the above code to and it's working fine for my usage needs.
```
if (!string.IsNullOrWhiteSpace(servicePrefix))
{
    if(url.TrimStart('/').StartsWith(servicePrefix))
    {
        url = url.Substring(servicePrefix.Length+(url.StartsWith("/") ? 1 : 0));
    }
}
```

Thanks,
Rob

**Comment by JimBobSquarePants** [comment]
Thanks for raising this I'll have a good look asap and put together a fix (could be as simple as switching out for your code).

**Comment by JimBobSquarePants** [comment]
@roblarky I'll get a fix out in the next few days for this.
