### ISSUE TITLE
GetImage() call missing SynchronizationContext

### ISSUE THREAD

**Issue by CameronWills** [JimBobSquarePants/ImageProcessor#718]
https://github.com/JimBobSquarePants/ImageProcessor/blob/1c65565c7f42fa5e9917fbe408d7df3827c607bb/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L581

The short: 
We can no longer access `HttpContext.Current` inside `IImageService.GetImage()`.

The Long: 
This line calls `IImageService.GetImage(object id)`, but with the update last year, now it sometimes (always for us) runs on a different thread to the original HTTP request thread. And since the async calls above this line are using `ConfigureAwait(false)` the execution of  this line is not marshaled back to the original thread, so SynchronizationContext isn't available - including, importantly for us, access to `HttpContext.Current`.

Which raises another point, the `requestPath` passed to `imageService.GetImage(requestPath)` is sometimes not enough information to get the correct image blob. In the case of EpiServer with multiple sites configured - we need to know the domain in the request URL, not just the sub-path. Up until now, we had a custom `IImageService` implementation and were using `HttpContext.Current` inside `GetImage`, but now I can't and have to roll back to an earlier version of ImageProcessor.Web 😢 

As far as a solution goes, perhaps we can add a true/false setting to indicate whether execution of ImageProcessingModule.ProcessImageAsync should marshall back to the original thread.
Or otherwise pass the `HttpContext context` into `IImageService.GetImage()` from `ImageProcessorModule.ProcessingImageAsync`

Thoughts?

**Comment by JimBobSquarePants** [comment]
Hi there,

In six years you’re the first person to ever require this. Since I’m unable to alter the interface I would not be able to pass any additional information to he method. 

Isn’t there an Episerver plug-in for ImageProcessor.Web? How does that handle it?

**Comment by ericnewton76** [comment]
`ConfigureAwait(false)` is standard for library calls.  

That being said, you should consider taking that code and working up your own ImageProcessingModule.cs that doesnt call `ConfigureAwait(false)`  Note that ASPNET and not using ConfigureAwait(false) is notorious for deadlocks... the cause was a catch-22 in that the thread scheduler could never schedule the async call on the correct thread because the correct thread was awaiting the thread scheduler to schedule... at least for a while, maybe they fixed it, but it was definitely a problem for a while.

Honestly instead of using async there, just call it nonasync and you'll have the correct HttpContext for coordinating the image process, and maybe inside of there, you can async/await

**Comment by CameronWills** [comment]
@ericnewton76 
Yep I agree, shouldn't remove `ConfigureAwait(false)` just for this scenario.

And like you said, If its not `async + await` all the way down the call stack then you will need to have `ConfigureAwait(false)` otherwise deadlock.

@JimBobSquarePants 
I haven't taken a good look at the EpiServer plugin for ImageProcessor. There were none around when I integrated ImageProcessor.Web. But from a cursory check of [this](https://github.com/vnbaaij/ImageProcessor.Web.Episerver/tree/master/src/ImageProcessor.Web.Episerver) one, it seems verbose compared to out integration: Implementing a subclass of `ImageProcessingModule`, custom `ImageCache` as well as an `IImageService`.

I think the use case is valid though, you can one web app handling multiple domains, each having different images for the same sub-path.
E.g.
http://www.mydomain.com/hero.jpg
http://www.myotheromain.com/hero.jpg

So suggest breaking changes in a future release, adding a second parameter added to `IImageService.GetImage(object id)`. Either the HttpContext object, or otherwise the full request URL (being more OWIN friendly and abstracted away). In the end this will make it more suited to integration with larger CMS's.

**Comment by JimBobSquarePants** [comment]
@CameronWills @ericnewton76 I'm adding an overload via a new `IImageService2` extension and filter the method call in the HttpModule
