### ISSUE TITLE
BackgroundColor not applied when resizing image with Pad

### ISSUE THREAD

**Issue by DocCaliban** [JimBobSquarePants/ImageProcessor#719]
### Description
I'm writing a batch processor that will convert portrait image to a 16:9 format, and everything is working fine, except the background color is always transparent, which I absolutely do not want.  My code is below.
```
            using (var currentImage = new ImageProcessor.ImageFactory())
            {
                currentImage.Load(fileName);
                int width = currentImage.Image.Width;
                int height = currentImage.Image.Height;
                if (height > width)
                {
                    int newWidth = (height / 9) * 16;
                    Size newSize = new Size(newWidth, height);
                    currentImage.BackgroundColor(Color.FromArgb(0, 177, 64));
                    ImageProcessor.Imaging.ResizeLayer rlayer = new ImageProcessor.Imaging.ResizeLayer(newSize, ImageProcessor.Imaging.ResizeMode.Pad, ImageProcessor.Imaging.AnchorPosition.Center, true);
                    currentImage.Resize(rlayer);
                }
                currentImage.Image.Save(fileName);
            }
```

### System Configuration
<package id="ImageProcessor" version="2.6.2.25" targetFramework="net452" />
Visual Studio 2017

**Comment by DocCaliban** [comment]
Interestingly this code works,  but isn't an ideal solution.
```
            string newFileName = Path.Combine(file.DirectoryName, "output", file.Name);

            using (var currentImage = new ImageProcessor.ImageFactory())
            {
                currentImage.Load(file.FullName).Format(new JpegFormat() { Quality= 100 });
                int width = currentImage.Image.Width;
                int height = currentImage.Image.Height;
                if (height > width)
                {
                    int newWidth = (height / 9) * 16;
                    Size newSize = new Size(newWidth, height);
                    ImageProcessor.Imaging.ResizeLayer rlayer = new ImageProcessor.Imaging.ResizeLayer(newSize, ImageProcessor.Imaging.ResizeMode.Pad, ImageProcessor.Imaging.AnchorPosition.Center);
                    currentImage.Resize(rlayer).ReplaceColor(Color.Black, Color.FromArgb(0, 177, 64));
                }
                currentImage.Save(newFileName);
            }
```

**Comment by JimBobSquarePants** [comment]
The API is imperative, you have to do things in the correct order. 

1. Resize
2. BackgroundColor

Doing the reverse makes no sense, you have to create the padding pixels before setting a background color.

P.S Don't delete the issue template, it's incredibly rude.

**Comment by DocCaliban** [comment]
Ridiculous, 

Have you ever used image editing software before?  

You always set the background color first when adjusting the canvas, which is essentially what I am doing here.  

That being said, I would have done so had the documentation actually mentioned it, but it doesn't.

> This does cause some additional problems though, as it replace some pixels in the actual image.
> > If you have transparent pixels in the original image I don't understand why you would expect them not to be filled in.

First of all, you should read before you comment, they were not transparent pixels being replaced it was Black, second of all it behaved exactly I as I expected and replaced all the black pixels which is why I said it was not ideal.

p.s. Your entire response was incredibly rude.

**Comment by JimBobSquarePants** [comment]
Ever used a fluent API before? 
Written a graphics library? 
Bothered to read the source code?


Look up what `Graphics.Clear` does, `Graphics.DrawImage` also and you’ll see you’re talking nonesense. 

Next time someone calls you out for ignoring obvious instructions don’t have a hissy fit.
