### ISSUE TITLE
Output bit depth inconsistent across output formats

### ISSUE THREAD

**Issue by macklinb** [JimBobSquarePants/ImageProcessor#724]
### Description
Saving an image with `ImageFactory.Save` seems to be inconsistent with the bit depth of the saved image. In testing, I loaded an image from file with a bit depth of 24, made no changes to it, and saved it to a number of formats using the code below. The bit depth of the outputted file was not the same across the formats tested. 
   
In addition to this, using the file path overload of `ImageFactory.Load` always properly detects the bit depth of the source file (via `ImageFactory.CurrentBitDepth`), but using the `Image` overload of `ImageFactory.Load` always results in a `CurrentBitDepth` of 32, regardless of the source image bit depth. The pixel format reported by `ImageFactory.Image.PixelFormat` always seemed to be `Format32bppPArgb` regardless of the input format.

I think it's pretty important to be able to save in the right bit depth, as 32-bit images are just unnecessary in most cases. Let me know if I'm not understanding how to use ImageProcessor properly, or if this is the intended effect.

### Steps to Reproduce
```
var formats = new ISupportedImageFormat[] { new GifFormat(), new JpegFormat(), new PngFormat(), new BitmapFormat(), new TiffFormat() };
var exts = new string[] { ".gif", ".jpg", ".png", ".bmp", ".tiff" };

using (var imageFactory = new ImageFactory())
{
    var sourceImage = Image.FromFile(@"C:\some\24bit\file\here.jpg");
    imageFactory.Load(@"C:\some\24bit\file\here.jpg");

    Console.WriteLine("Source pixel format is " + sourceImage.PixelFormat);
    Console.WriteLine("ImageFactory.Image.PixelFormat: " + imageFactory.Image.PixelFormat);
    Console.WriteLine("ImageFactory.CurrentBitDepth: " + imageFactory.CurrentBitDepth);

    for (int i = 0; i < formats.Length; i++)
    {
        var path = Environment.CurrentDirectory + "\\test" + exts[i];

        imageFactory.Format(formats[i]);
        imageFactory.Save(path);

        Console.WriteLine("\nSaved image in format: " + imageFactory.CurrentImageFormat);

        Image savedImage = Image.FromFile(path);
        Console.WriteLine("Saved pixel format is " + savedImage.PixelFormat);
        Console.WriteLine("Matches input? " + (sourceImage.PixelFormat == savedImage.PixelFormat).ToString());
    }
}
```

Results in the following output:
```
Source pixel format is Format24bppRgb
ImageFactory.Image.PixelFormat: Format32bppPArgb
ImageFactory.CurrentBitDepth: 24

Saved image in format: ImageProcessor.Imaging.Formats.GifFormat
Saved pixel format is Format8bppIndexed
Matches input? False

Saved image in format: ImageProcessor.Imaging.Formats.JpegFormat
Saved pixel format is Format24bppRgb
Matches input? True

Saved image in format: ImageProcessor.Imaging.Formats.PngFormat
Saved pixel format is Format32bppArgb
Matches input? False

Saved image in format: ImageProcessor.Imaging.Formats.BitmapFormat
Saved pixel format is Format8bppIndexed
Matches input? False

Saved image in format: ImageProcessor.Imaging.Formats.TiffFormat
Saved pixel format is Format24bppRgb
Matches input? True
```

Also note that specifying the `CurrentBitDepth` with `imageFactory.BitDepth(24)` before saving only changes the output bit depth when using TiffFormat.

### System Configuration

- ImageProcessor version: 2.6.2.25
- ImageProcessor.Web version (if applicable)
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): Windows 10 Pro (1809, 17763.253)
- .NET Framework version: 4.7.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
You're right, I should do a better job of supporting bit depth preservation. I can only do this within the limitations of the formats though. (For example Gif doesn't support 24bit images).

The running `Format32bppPArgb` is used to normalize code and performance across the API. 

With the changes I've just pushed the next release will preserve the information in your use case. 

However, this requires you to use the `Reset()` method between saves as System.Drawing alters the image on save.

e.g
this line:
``` c#
imageFactory.Format(formats[i]);
```

becomes 

``` c#
imageFactory.Reset().Format(formats[i]);
```

With these changes the following output is achieved.

``` bash
Source pixel format is Format24bppRgb
ImageFactory.Image.PixelFormat: Format32bppPArgb
ImageFactory.CurrentBitDepth: 24

Saved image in format: ImageProcessor.Imaging.Formats.GifFormat
Saved pixel format is Format8bppIndexed
Matches input? False

Saved image in format: ImageProcessor.Imaging.Formats.JpegFormat
Saved pixel format is Format24bppRgb
Matches input? True

Saved image in format: ImageProcessor.Imaging.Formats.PngFormat
Saved pixel format is Format24bppRgb
Matches input? True

Saved image in format: ImageProcessor.Imaging.Formats.BitmapFormat
Saved pixel format is Format24bppRgb
Matches input? True

Saved image in format: ImageProcessor.Imaging.Formats.TiffFormat
Saved pixel format is Format24bppRgb
Matches input? True
```

This codebase is getting a bit creaky now to be honest and combined with the limitations of System.Drawing doesn't offer you the absolute control that you might desire. I've been putting together another library [ImageSharp](https://github.com/SixLabors/ImageSharp) which offers total control of the image output and might be better suited to your needs.

**Comment by macklinb** [comment]
Thanks for the response, I'll check ImageSharp out.
