### ISSUE TITLE
Release notes / changelog availability

### ISSUE THREAD

**Issue by Zero3** [JimBobSquarePants/ImageProcessor#729]
Is there a release notes / changelog document available anywhere? In particular, I noticed that there is a version 2.7.0.100 available on NuGet, but I can't find a list of changes/fixes anywhere.

For example I'd like to know if there is any breaking changes in the upgrade, or if any known bugs are fixed.

**Comment by JimBobSquarePants** [comment]
No, not yet. It’s a lot of work. Please don’t use the issue tracker for questions
