### ISSUE TITLE
RoundedCorners seems to ignore background color

### ISSUE THREAD

**Issue by raznet** [JimBobSquarePants/ImageProcessor#730]
The code below produced transparent corners in previous version.
Now the corners are black no matter what color i choose for the background.

Btw. many thanks for this great library!

var result = new MemoryStream();
            using (var factory = new ImageFactory())
            {
                factory.Load(imageStream)
                    .BackgroundColor(Color.Transparent)
                    .Format(new PngFormat());
                factory.Resize(newSize);
                factory.RoundedCorners(radius);
                factory.Save(result);
            }
return result;

**Comment by JimBobSquarePants** [comment]
Ah yes, I know why. We’re now respecting the original input pixel format which would be 24bit. May have to revert that.

**Comment by JimBobSquarePants** [comment]
Just a heads up though. From the Readme: 

>ImageProcessor is in Soft Archive Mode.
Focus for the ImageProcessor libraries has switched to a new library ImageSharp. As such, no new features will be added to this library. Bug fixes will continue to be added and only via PR.

**Comment by raznet** [comment]
Yes, already got it. We use only some basic image manipulations so ImageProcessor is completely sufficient to our needs. But i will check ImageSharp when i got time. From what i saw it sounds very promising!
