### ISSUE TITLE
EntropyCrop error after update

### ISSUE THREAD

**Issue by srdjo** [JimBobSquarePants/ImageProcessor#731]
I updated my ImageProcessor package via NuGet to latest version and now I get the followng error

![image](https://user-images.githubusercontent.com/4582491/52851905-85c80d80-3117-11e9-9833-9fe32d7ffef0.png)

?entropycrop=128

I am targeting NetFramework 4.7.1
ImageProcessor 2.7.0.100
ImageProcessor.Web 4.10.0.100

What might be the problem ?

**Comment by JimBobSquarePants** [comment]
>What might be the problem ?

An invalid cast by the look of the stack trace.

However. From the Readme: 

>ImageProcessor is in Soft Archive Mode.
Focus for the ImageProcessor libraries has switched to a new library ImageSharp. As such, no new features will be added to this library. Bug fixes will continue to be added and only via PR.

**Comment by srdjo** [comment]
Downgrading to ImageProcessor v2.6.2.25 fixesthe problem

**Comment by JimBobSquarePants** [comment]
> Downgrading to ImageProcessor v2.6.2.25 fixes the problem

While introducing other issues. I never understand why people comment like this, not helpful to anyone.

**Comment by stevenbarker** [comment]
Just created a PR now to fix this issue: #746

**Comment by JimBobSquarePants** [comment]
Thanks, merged. Will do a release soon.
