### ISSUE TITLE
cachedFolderPath exception with AzureBlobCache plugin

### ISSUE THREAD

**Issue by shearer3000** [JimBobSquarePants/ImageProcessor#732]
Hi

We have an Azure Web App, so I have installed ImageProcessor.Web.Plugins.AzureBlobCache so that the cache resides in Azure blob storage rather than App_Data (for performance reasons).
I have configured it as per https://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/ but I get the following exception on Image Processor urls:

```
Value cannot be null.
Parameter name: cachedFolderPath

[ArgumentNullException: Value cannot be null.
Parameter name: cachedFolderPath]
   ImageProcessor.Web.Caching.CachedImageHelper.GetCachedPath(String cachedFolderPath, String cachedFileName, Boolean makeVirtual, Int32 depth) +210
   ImageProcessor.Web.Plugins.AzureBlobCache.<IsNewOrUpdatedAsync>d__12.MoveNext() +384
```

Where/how can I find info on how to configure this setting?

Versions are:
ImageProcessor 2.7.0.100
ImageProcessor.Web 4.10.0.100
ImageProcessor.Web.Config 2.5.0.100
ImageProcessor.Web.Plugins.AzureBlobCache 1.5.0.100

Thanks
Andrew

**Comment by JimBobSquarePants** [comment]
Hi Andrew 

You've definitely set both the `CachedBlobContainer` and `CachedCDNRoot` properties yeah?

https://github.com/JimBobSquarePants/ImageProcessor/blob/bab08e8f370989616d2283de1921cd41e3f04d41/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L176

Cheers

James

**Comment by shearer3000** [comment]
Hi James

Yes, both of those are set among others

```
        <setting key="CachedBlobContainer" value="cache"/>
        <setting key="UseCachedContainerInUrl" value="true"/>
        <setting key="CachedCDNRoot" value="http://storageaccountname.blob.core.windows.net/"/>
        <setting key="CachedCDNTimeout" value="1000"/>
        <setting key="SourceStorageAccount" value="storageaccountname"/>
        <setting key="SourceBlobContainer" value="clientsite-media"/>
        <setting key="StreamCachedImage" value="false"/>
```

I initially understood the main use-case for the AzureBlobCache plugin as being able to shift the Image Processor cache from the traditional App_Data folder location to an Azure blob instead, mainly for I/O performance reasons due to how Azure worker and file systems operate together. As you can see in the config above, I’m not trying to use a separate “CDN” as such, rather “CachedCDNRoot" is basically configured with the same url as the source of the image content. Is this interpretation incorrect?

What I was hoping for was a folder called “/cache” in the Azure blob that Image Processor would use instead of App_data/cache.

Cheers
Andrew

**Comment by JimBobSquarePants** [comment]
Yeah that parameter would be incorrect. If you don't want to use a CDN comment out or delete that setting. 

>What I was hoping for was a folder called “/cache” in the Azure blob that Image Processor would use instead of App_data/cache.

When set up correctly that is exactly what happens. Here's the config I'm using in my test repo cut down to the minimum required settings.

``` xml
<cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" 
        maxDays="365" browserMaxDays="7" folderDepth="6" trimCache="true">
  <settings>
    
    <!-- The Account, Container and CDN details -->
    <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=[AcccuntName]];AccountKey=[AccountKey]];EndpointSuffix=core.windows.net"/>
    <setting key="CachedBlobContainer" value="cache"/>
    <!-- The option BlobAccessType. Defaults to Blob -->
    <!-- <setting key="AccessType" value="Off"/> -->
    <!-- Whether to add the container name to the CDN url. Newer Azure formats require false. -->
    <!--<setting key="UseCachedContainerInUrl" value="true"/>-->
    <!-- Full CDN root url e.g http://123456.vo.msecnd.net/ -->
    <!--<setting key="CachedCDNRoot" value="[CdnRootUrl]"/>-->
    <!-- Optional setting for a timeout limit in milliseconds when attempting to communicate with the CDN url. -->
    <!--<setting key="CachedCDNTimeout" value="1000"/>-->
    <!-- 
        Optional settings for better identifcation of source images if stored in 
        Azure blob storage.
      -->
    <!--<setting key="SourceStorageAccount" value=""/>
    <setting key="SourceBlobContainer" value=""/>-->
    <!-- 
        Optional settings facilitate streaming of the blob resource directly instead of a redirect. This is beneficial
        for CDN purposes but caution should be taken if not used with a CDN as it will add quite a bit of overhead 
        to the site. 
      -->
    <!--<setting key="StreamCachedImage" value="false"/>-->
  </settings>
</cache>
```

**Comment by shearer3000** [comment]
Hi James 

thanks for that info! I commented out the settings as per your sample and got a step closer to things working.
NB I did need to set
`<setting key="StreamCachedImage" value="true"/>`
otherwise I noticed my image requests were being 302ed to the image processor cache url (e.g /6/8/9/5/7/0/6895702571e88a87c8441fc59c7426c2ee32c1bc.jpg) which would in turn result in a 400 OutOfRangeInput exception.

So at this point I can now see a “cache” folder in the Azure storage account, but ideally I still want this to be under the client blob folder rather than its own blob. i.e. at the moment I have these blobs:
cache
client-a-media
client-b-media

but I was expecting
client-a-media/cache
client-b-media/cache

I tired setting this but it didn't work
`<setting key="CachedBlobContainer" value="client-a-media/cache"/>`

thanks
Andrew

**Comment by JimBobSquarePants** [comment]
I’m afraid it doesn’t allow that level of nesting. However it’s fairly trivial to implement your own version based on mine and use that.

**Comment by shearer3000** [comment]
ok, thank you :)

An alternative idea is that i just give Image processor its own blob folder for cache content as there's no extra cost in doing so e.g.

client-a-media
client-a-cache
client-b-media
client-b-cache

I can only presume that sharing a image processor "cache" blob across multiple blob containers of client media content would only cause headaches? e.g

client-a-media
client-b-media
shared-cache

**Comment by JimBobSquarePants** [comment]
The cache should be able to store millions of images without hash collision so it might well be fine. I generally keep them separate though just for ease of recovery should something go wrong.
