### ISSUE TITLE
Format png, alpha channel

### ISSUE THREAD

**Issue by Masherak** [JimBobSquarePants/ImageProcessor#734]
Hello, I try to change the format of the image from a jpeg -> png and after that, I use resize with default resizeMode.Pad, so default behavior is that black sides are added. I can change the background color of this pad but how I can set it as transparent? 

Thank you very much for your help

Jarda

**Comment by JimBobSquarePants** [comment]
Use the following extension method. `public ImageFactory BackgroundColor(Color color)`

https://imageprocessor.org/imageprocessor/imagefactory/backgroundcolor/
