### ISSUE TITLE
nuspec files refer to missing ImageProcessor 2.7.0.0

### ISSUE THREAD

**Issue by dangrussell** [JimBobSquarePants/ImageProcessor#735]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageProcessor 2.7.0.0 doesn't exist in the NuGet Gallery, but three nuspec files refer to it. This creates this warning in Visual Studio on Build: "NU1603 ImageProcessor.Web 4.10.0.100 depends on ImageProcessor (>= 2.7.0) but ImageProcessor 2.7.0 was not found. An approximate best match of ImageProcessor 2.7.0.100 was resolved."  It seems updating the dependancies to `<dependency id="ImageProcessor" version="2.7.0.100" />` would fix this.

Apologies for any reporting protocol violations -- I'm relatively new to using GitHub (and NuGet).

### Steps to Reproduce
Using Visual Studio, build a Solution that uses ImageProcessor.Web 4.10.0.100

### System Configuration

- ImageProcessor version:
- ImageProcessor.Web version (if applicable)
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi there, 

No worries reporting, you did he right thing! 

However, It’s just a warning and doesn’t stop builds so I wouldn’t worry about it. 

My build system automatically appends the build number and I’d have to rewrite it to not do so which would be too much work now the library is archived. 

Cheers

James
