### ISSUE TITLE
Replace two colors, via querystring method

### ISSUE THREAD

**Issue by lcichanowicz** [JimBobSquarePants/ImageProcessor#736]
Greetings.  Is it possible to execute the same method twice, via the querystring?  I need to replace two colors.  My image is black text on a white background.  I want to change the white background to blue, and the black text to red.  (I am using simple colors for this example.)

I tried:
`http://mysite.local/label.jpg?replace=white,blue&fuzziness=100&replace=black,red`

I get a blue background, with black text (and some greyish noise pixels that were already there in the original).

When I use the ImageFactory, it works.
```
        using (var currentImage = new ImageProcessor.ImageFactory())
        {
            currentImage
                .Load(originalFile)
                .Format(new ImageProcessor.Imaging.Formats.PngFormat())
                .ReplaceColor(Color.White, Color.Blue, 100)
                .ReplaceColor(Color.Black, Color.Red, 100)
                .Save(@"F:\label.png");
        }
```
I added the conversion to PNG format to try a transparent background.  I noticed it cleaned up the noise around the black text so I left it, but it does not clean up the noise when I use the URL querystring method.

**Comment by lcichanowicz** [comment]
https://stackoverflow.com/questions/3081521/how-to-completely-remove-an-issue-from-github

**Comment by JimBobSquarePants** [comment]
@lcichanowicz I'm afraid not. The querystring parser will reduce each command to only on instance only.
