### ISSUE TITLE
Adding custom filters?

### ISSUE THREAD

**Issue by nhaberl** [JimBobSquarePants/ImageProcessor#740]
Hi,

is it possible to add custom filters, if yes is there any guide ?
Let's say I would like to add all Instgram filters as an extension?

Thanks

**Comment by JimBobSquarePants** [comment]
You can create any `GraphicsProcessor` implementation you like to extend `ImageFactory`.

Here's some examples of various filters
https://github.com/JimBobSquarePants/ImageProcessor/tree/024da44eabf493b4e628c00824c5e636f725f7ea/src/ImageProcessor/Imaging/Filters/Photo

And here's the accompanying docs/example output.
https://imageprocessor.org/imageprocessor/imagefactory/filter/
