### ISSUE TITLE
PostProcessor: how to compress png

### ISSUE THREAD

**Issue by esyorcho** [JimBobSquarePants/ImageProcessor#741]
Hi James,

We are using ImageProcessor with our Umbraco implementation. It was working fine with Azure, but now we are migrating to AWS and we are having time out issues with png images.
We were thinking that perhaps compressing the png could help with the issues.
I saw that your post processor does png compression, however I haven't found much documentation about how to implementing it.
Could you please give provide some guidance about how to implement it?

At the moment we have this:

AppStartedEventHandler.cs

 public void AppStarted()
        {
            ImageProcessingModule.ValidatingRequest += _validatingRequestEventHandler.AlterQryString;
...
}

ValidatingRequestEventHandler.cs

public class ValidatingRequestEventHandler : IValidatingRequestEventHandler
    {
        public void AlterQryString(object sender, ValidatingRequestEventArgs args)
        {
            if (args.Context.Request.RawUrl.Contains("media") 
                && args.Context.Request.RawUrl.Contains(".png") 
                && !args.QueryString.Contains("format"))
            {
                if (string.IsNullOrWhiteSpace(args.QueryString))
                {
                    args.QueryString += "format=jpg";
                }
                else
                {
                    args.QueryString += "&format=jpg";
                }
            }
         }
     }

I've tried things like:
ImageProcessingModule.OnPostProcessing += _postProcessingEventHandler.PostProcessImage;

and then

public class PostProcessingEventHandler : IPostProcessingEventHandler
    {
        public void PostProcessImage(object sender, PostProcessingEventArgs args)
        {
            using (var inStream = args.ImageStream)
            {
                using (var imageFactory = new ImageFactory(preserveExifData: false))
                {
                    imageFactory.Load(inStream).Save(args.Context.Request.PhysicalPath);
                }
            }
        }
    }

But it didn't stop when I put a breakpoint, so I think it wasn't being called.

Could you please tell me what would be the right way to implement it?

Thank you very much

**Comment by JimBobSquarePants** [comment]
From the [docs](https://imageprocessor.org/imageprocessor-web/plugins/postprocessor/).

>Once installed, the plugin requires no further configuration.

If you are having issues with pngs you're probably using an underpowered or badly configured environment. Post Processing happens after resize/crop etc so if your pngs are overly large then that will not help as they have to be transferred over the wire. 

>It was working fine with Azure, but now we are migrating to AWS and we are having time out issues with png images.

Is Umbraco even supported on AWS? I can't fathom why someone would choose to migrate from a well documented supported platform on which your applications are verified to work to the unknown.

**Comment by esyorcho** [comment]
Ok, we might take a different approach then.
Thank you very much for your answer. You must be very busy and I appreciate you taking the time to reply.
Cheers

**Comment by lcichanowicz** [comment]
> 
> 
> From the [docs](https://imageprocessor.org/imageprocessor-web/plugins/postprocessor/).
> 
> > Once installed, the plugin requires no further configuration.

The plugin does not require any further configuration, but your image URLs do.  That may seem obvious to the plugin creator, but it would be worth noting in the docs.
