### ISSUE TITLE
browserMaxDays cache setting ignored

### ISSUE THREAD

**Issue by jaandrews** [JimBobSquarePants/ImageProcessor#742]
### Description
I've set browserMaxDays to 365 in the cache.config file, but it continues to cache the cached crops for 7 days. I'm using chrome's audit tool to optimize website performance, and it's flagging the cropped images cache duration as too short.

Below is my current cache.config with the account name and account key replaced.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" browserMaxDays="365" trimCache="false">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache"/>
      </settings>
    </cache>
    <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365" browserMaxDays="365" folderDepth="6" trimCache="true" memoryMaxMinutes="1">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=[account name];AccountKey=[account key];EndpointSuffix=core.windows.net" />
        <setting key="CachedBlobContainer" value="cache" />
        <setting key="UseCachedContainerInUrl" value="true" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache>
  </caches>
</caching>
```
and this is my FileProvider configuration
```xml
<?xml version="1.0"?>
<FileSystemProviders>
  <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
    <Parameters>
      <add key="containerName" value="media"/>
      <add key="rootUrl" value="https://[account name].blob.core.windows.net/"/>
      <add key="connectionString" value="DefaultEndpointsProtocol=https;AccountName=[account name];AccountKey=[account key];EndpointSuffix=core.windows.net"/>
      <add key="maxDays" value="365"/>
      <add key="useDefaultRoute" value="true"/>
      <add key="usePrivateContainer" value="false"/>
    </Parameters>
  </Provider>
</FileSystemProviders>
```

### Steps to Reproduce
I changed the browserMaxDays to 365 from 7, but this change was not reflected in the cache durations of the crops.

### System Configuration
- ImageProcessor: 2.7.0.1
- ImageProcessor.Web: 4.10.0.1
- ImageProcessor.Web.Config: 2.5.0.1
- ImageProcessor.Web.Plugins.AzureBlobCache: 1.5.0.1
- .NET Framework: 4.6.1
- Our.Umbraco.FileSystemProviders.Azure: 1.0.3
- Umbraco: 7.14.0

Any ideas on why the setting wouldn't be working?

**Comment by JimBobSquarePants** [comment]
I think you are inspecting previously browser cached files without hitting Ctrl-f5 first to clear the old cache.

![image](https://user-images.githubusercontent.com/385879/60634602-d932c200-9e52-11e9-85a9-80272e2b7d11.png)

In the example above (ignore version numbers, they're just locally stored) I have set the `browserMaxDays` property to 21 days (60x60x24x21)
