### ISSUE TITLE
AutoRotate module dosn't rotate an image

### ISSUE THREAD

**Issue by ilia280** [JimBobSquarePants/ImageProcessor#744]
Hello @JimBobSquarePants 
Please correct me if I'm wrong.

If I set in the `processing.config` the value for **preserveExifMetaData** to **true** then AutoRotate won't work according to your code (see below)?
https://github.com/JimBobSquarePants/ImageProcessor/blob/c36a37d250432a6e93bc4b1a04410ddc2e193c02/src/ImageProcessor/Processors/AutoRotate.cs#L73
The value for **preserveExifMetaData** reverts.

So, I need to set this value to **false** to make it work, am I right?

**Comment by JimBobSquarePants** [comment]
Autorotate applies the correct rotation that represents EXIF instruction that is not preserved when metadata is not stored.
