### ISSUE TITLE
Azure CDN requires TLS 1.2 - If CachedCDNRoot url uses https set this to enable TLS 1.2

### ISSUE THREAD

**Issue by syska** [JimBobSquarePants/ImageProcessor#745]
Just a notice, so others don't waste there life ... 

Maybe should be placed in the cache.config ... 

Azure CDN(azureedge.net) requires TLS 1.2 ... maybe 1.1 is still supported ... 

We had an issue when `CachedCDNRoot` was set to `http://oursite.azureedge.net` to worked but when setting this to `https://oursite.azureedge.net` it just redirected to the blob storage ... 

To fix this, enabled TLS 1.2 ... place this 

    ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;

somewhere in a startup class that is only run once ... 

This fixed the issue for us else it would keep redirecting to the Blob Storage ...

**Comment by JimBobSquarePants** [comment]
I'm not sure whether implementing this directly in the library is a good idea as it might affect other services. Definitely good to note though!

**Comment by syska** [comment]
This was also purely as a notice if other searched the issue list for a solution.
