### ISSUE TITLE
Blacked out images

### ISSUE THREAD

**Issue by WRNeil** [JimBobSquarePants/ImageProcessor#747]
Using ImageProcessor version 2.7.0.100 and ImageProcessor.Web version 4.10.0.100.

Also using Azure cache/cdn, so using CloudImageService.

Some images are returning completely blacked out, for example:

https://wrpmp-prod-euw-imageserver.azurewebsites.net/Uploads/Property/2598/Logos/Trip-Advisor-Rating-5-star-1.png?width=270&quality=85

Changing the width to a different size may or may not return the correct image. The blacked out ones appear to have the outline of the correct image.

Any ideas? Can provide config files if required.

**Comment by JimBobSquarePants** [comment]
I'm not seeing this.

![image](https://user-images.githubusercontent.com/385879/60634182-6aa13480-9e51-11e9-854a-9e0fe4f218e6.png)

P.S. Please don't delete the issue template.

**Comment by ThomasSkyldahl** [comment]
We are having the same issue on Azure, in the local environment it works perfectly

**Comment by JimBobSquarePants** [comment]
@ThomasSkyldahl What version of the PostProcessor plugin are you using?

The image I shared above is the result of the following the exact link to the image listed by the OP so I'm assuming it is still on Azure

**Comment by mhesselberg** [comment]
I can answer on Thomas' behalf; we use version 1.4.0.100 of the PostProcessor.

**Comment by JimBobSquarePants** [comment]
Thanks. @mhesselberg I need to investigate the issue with the tool I use there.

**Comment by Reaction77** [comment]
Just to add another example. We've observed the same issue occurring on Azure with package versions:
<package id="ImageProcessor" version="2.7.0.100" targetFramework="net472" />
<package id="ImageProcessor.Web" version="4.10.0.100" targetFramework="net472" />

We had to downgrade to the following versions, which did not exhibit the issue:
<package id="ImageProcessor" version="2.6.2.25" targetFramework="net472" />
<package id="ImageProcessor.Web" version="4.9.3.25" targetFramework="net472" />

 From what we could find, only certain png images were affected.

**Comment by JimBobSquarePants** [comment]
Thanks @Reaction77 

The issue here is actually directly related to https://github.com/JimBobSquarePants/ImageProcessor/issues/713

I'm going to have to switch out the png optimizer (the orignal has currently disappeared from the web) for another one.

**Comment by WRNeil** [comment]
Apologies, I've been away... Thanks for the update (#713) - like @Reaction77 we also downgraded and it resolved our issue (hence the reason you got the image ok).

**Comment by JimBobSquarePants** [comment]
I wouldn't recommend downgrading the entire system. You would be better off uninstalling the postprocessor for now.

**Comment by JohnBergman** [comment]
We are also having this issue.

**Comment by JimBobSquarePants** [comment]
@JohnBergman I’m assuming you have the post processor installed?

**Comment by JohnBergman** [comment]
Yes, I do.  Is there other info you need, this is 100% reproducible in my dev environment as well as the live environments.

**Comment by JimBobSquarePants** [comment]
Ok. I have a plan for this but it may take me a week or so to do.

**Comment by mhesselberg** [comment]
@JimBobSquarePants Hey, I can see you have committed a fix for this issue. When do you think a new version including this fix will be published?

Just a rough idea.

**Comment by JimBobSquarePants** [comment]
@mhesselberg Next week I hope.

**Comment by trentbraidner** [comment]
@JimBobSquarePants Did their end up being a fix for this one? We are also having the same issue.

**Comment by JimBobSquarePants** [comment]
@trentbraidner No release as yet.

**Comment by gregwoodsit** [comment]
@JimBobSquarePants are you any closer to releasing an update to fix this issue?

**Comment by JimBobSquarePants** [comment]
I'll try and do it tonight (Sydney time). I cannot promise anything but will keep the ticket updated.

**Comment by gregwoodsit** [comment]
@JimBobSquarePants did you have any luck getting to this?

**Comment by JimBobSquarePants** [comment]
Fixed in 1.5.0

https://www.nuget.org/packages/ImageProcessor.Web.PostProcessor/

**Comment by gregwoodsit** [comment]
Awesome will give it a try today!

**Comment by JimBobSquarePants** [comment]
No worries, just remember to clear your cache.
