### ISSUE TITLE
Parameter is not valid-When passing a parameters whose value less than 0.

### ISSUE THREAD

**Issue by ashwinigawade007** [JimBobSquarePants/ImageProcessor#748]
When i am trying to access image with the crop values 
http://localhost:59720/media/5345/chrysanthemum.jpg?crop=0.001,0.00,0.222,0.00
less than zero then i get the below error
![image](https://user-images.githubusercontent.com/22345005/60243615-83897300-98b0-11e9-8925-98ef7c724636.png)
I am using umbraco version 7.7.8 and imageprocessor.web version 4.8.7.

**Comment by JimBobSquarePants** [comment]
You deleted the template which asked you to confirm you are using the latest version, which you are not.
