### ISSUE TITLE
NuGet depedency version is not an exact match

### ISSUE THREAD

**Issue by ronaldbarendse** [JimBobSquarePants/ImageProcessor#757]
I've getting some warnings in Visual Studio regarding the NuGet dependency versions:
> Warning - NU1603 - ImageProcessor.Web 4.10.0.100 depends on ImageProcessor (>= 2.7.0) but ImageProcessor 2.7.0 was not found. An approximate best match of ImageProcessor 2.7.0.100 was resolved.

When a new version is released, make sure a correct version is used in the dependencies 👍

**Comment by JimBobSquarePants** [comment]
When reporting issues make sure they are not duplicates :+1:

https://github.com/JimBobSquarePants/ImageProcessor/issues/735

**Comment by ronaldbarendse** [comment]
Didn't see the closed issue, my bad! 😉
