### ISSUE TITLE
WebP does not seems to work?

### ISSUE THREAD

**Issue by Killerkiwi2005** [JimBobSquarePants/ImageProcessor#759]
### Description
I've installed the latest nuget version 2.5.6
And webp 4.8.7
AzureBlob Cache 1.1.1

Converting to PNG works
https://localhost/media/1001/stock-photo.jpg?format=png&quality=19
https://acronymweb.blob.core.windows.net/cache/d/3/3/f/3/4/d33f34ec9705b5a0490cbdceb74c038f113e29b2.png

WebP returns a jpg
https://localhost/media/1001/stock-photo.jpg?format=webp&quality=19
https://acronymweb.blob.core.windows.net/cache/4/7/a/c/f/f/47acffa564aca2d84e57a80452c2dcaf5b0d1194.jpg

**Comment by JimBobSquarePants** [comment]
Latest ImageProcessor is 2.7.0.1 

https://www.nuget.org/packages/ImageProcessor/

**Comment by Killerkiwi2005** [comment]
Sorry your right.. changed target to .net 4.7 and updated still same issue
ImageProcessor 2.7.0.100
webp 1.2.0.100
ImageProcessor.Web 4.10.0.100
AzureBlob Cache 1.5.0.100

still get jpg 
https://acronymweb.blob.core.windows.net/cache/3/c/0/f/f/6/3c0ff65cb1e9fda9ae2f7465ac2fd3dc1c899f20.jpg

png still works
https://acronymweb.blob.core.windows.net/cache/d/3/3/f/3/4/d33f34ec9705b5a0490cbdceb74c038f113e29b2.png

**Comment by JimBobSquarePants** [comment]
@Killerkiwi2005 Do you have a raw request URL I can query? I want to ensure we are checking against an empty cache.
