### ISSUE TITLE
GIF to WebP strips Animations

### ISSUE THREAD

**Issue by Facius** [JimBobSquarePants/ImageProcessor#762]
Converting Animated GIF's to WebP strips animations.
Setting animationprocessmode=all doesn't make a difference.

Clean .Net 4.7.2 Solution with:
ImageProcessor - 2.7.0.100
ImageProcessor.Plugins.WebP - 1.2.0.100
ImageProcessor.Web - 4.10.0.100

Request any animated gif with ?animationprocessmode=all&format=webwep or just ?format=webp

**Comment by JimBobSquarePants** [comment]
Animated webp is not supported.

**Comment by JimBobSquarePants** [comment]
I wonder if it could be possible though.... I’ll do some research.
