### ISSUE TITLE
Question: is cleaning the diskcache folder allowed?

### ISSUE THREAD

**Issue by postback** [JimBobSquarePants/ImageProcessor#763]
We've setup DiskCache for an ImageProcessor implementation, we've noticed we haven't setup the configuration properly to cleanup the cache folder on a regular basis.

We've noticed it's slowly eating up hard disk space (our fault, of course), and were wondering if that folder can be cleaned (all subfolders deleted), or would that have unintended consequences.

We'd then go along and get our own configuration right. It's just a matter of being sure cleaning that folder would be OK.

**Comment by JimBobSquarePants** [comment]
Hi!

Deleting it should be fine, the system will automatically create any folders upon demand.
