### ISSUE TITLE
Cannot load libwebp.dll on Windows Server 2016 Datacenter

### ISSUE THREAD

**Issue by firstdivision** [JimBobSquarePants/ImageProcessor#764]
### Description
After deploying the software to a Windows 2016 Datacenter edition (in AWS), we get the error "Cannot load libwebp.dll".

On previous deployments to another server (a much older Windows Server 2008 R2) we were able to fix it by installing Visual C++ Redistributable Package for Visual Studio 2013 as indicated on https://imageprocessor.org/imageprocessor/plugins/webp/

Resize commands work, it is only when requesting webp that we get a problem.

Is there some other step we forgot?  Is it possible that Windows Server 2016 needs something else to get it working?

### System Configuration
- Installed via nuget
- ImageProcessor version: 2.7.0.100
- ImageProcessor.Web version (if applicable): 4.10.1.100
- ImageProcessor.Plugins.WebP version: 1.2.0.100
- Environment (Operating system, version and so on): Windows Server 2016 Datacenter
- .NET Framework version: 4.6.1
- Additional information:

**Comment by JimBobSquarePants** [comment]
Are you running the application in 32bit or 64bit mode? You have to make sure that the version you install matches the running mode.

**Comment by firstdivision** [comment]
Ok, that was it.  I needed to install the x86 version of the c++ redist.  Thanks!

**Comment by JimBobSquarePants** [comment]
Excellent! I would suggest moving to 64bit if you can though to help avoid out of memory exceptions.
