### ISSUE TITLE
Imageprocessor latest version format=webp returns 404

### ISSUE THREAD

**Issue by SkrypnikO** [JimBobSquarePants/ImageProcessor#765]
Strange issue - on local machine webp plugin works, but on the sever images return 404 

Looks like some settings or the issue?

**Comment by JimBobSquarePants** [comment]
Hi there, 

Can you please fill in the issue template and provide enough detail to diagnose the issue.

**Comment by SkrypnikO** [comment]
Hi Jim, I found that mimeMap config key is missing on the live site. I added and it works

<remove fileExtension=".webp" /><mimeMap fileExtension=".webp" mimeType="image/webp" />

Thank you so much for so awesome library

**Comment by JimBobSquarePants** [comment]
Ah perfect. Nice detective work, and thanks!
