### ISSUE TITLE
Resize/Crop are not working as expected

### ISSUE THREAD

**Issue by Porkechebure** [JimBobSquarePants/ImageProcessor#766]
I took the library for crop and resize since I was having 
[This problem](https://stackoverflow.com/questions/58026107/crop-image-zooms-resulting-image)

As you know and you can see, I can achieve crop with a few lines.

With this library I added the extra "Resize" step.

Now I get black bands on top and bottom (and the image is centered between the 2 bands, which is a good thing)

After reading here in issues, I see someone suggested "Also apply Background()"

I set background to white, and the image gets moved to bottom right like saying "Hey now bottom doesn't have a black band! let me move there in the right corner"

TEMPLATE REQUEST
### Description
you have it

### Steps to Reproduce
run the provided code

### System Configuration
windows 10

- ImageProcessor version: last
- Environment (Operating system, version and so on): above
- .NET Framework version: net core 2.2

Why?

**Comment by JimBobSquarePants** [comment]
Why has the code linked in the stackoverflow question got to do with this library? It’s all System.Drawing code

**Comment by Porkechebure** [comment]
> Why has the code linked in the stackoverflow question got to do with this library? It’s all System.Drawing code

Nothing. The code is basic, as it's basic what I was trying to do with ImageProcessor.

Anyway.....
Here's the code, since you ask for it

`using (Image barcodeImage = barcode.GenerateImage())
                using (MemoryStream stream = new MemoryStream())
                {
                    using (ImageFactory imageFactory = new ImageFactory())
                    {
                        imageFactory.Load(barcodeImage)
                    .Crop(new Rectangle(0, 15, 200, 75))
                    .Resize(new Size(200, 100))
                    .BackgroundColor(Color.White)
                    .Save(stream);
                    }
                    base64Barcode = Convert.ToBase64String(stream.ToArray());
                }`

**Comment by JimBobSquarePants** [comment]
Please fill in the issue template

**Comment by Porkechebure** [comment]
> Please fill in the issue template

If at least was written somewhere.... one would do it

**Comment by dlemstra** [comment]
You saw it when you created this issue: https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/.github/ISSUE_TEMPLATE.md

**Comment by Porkechebure** [comment]
> You saw it when you created this issue: https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/.github/ISSUE_TEMPLATE.md

My bad. Added everything which was missing.

**Comment by JimBobSquarePants** [comment]
Sorry, I deleted the comments, I thought we were overlapping and I misread your first question.

If you use three back ticks before and after your code sample it formats the code properly.

Can you please post the input image and result

**Comment by JimBobSquarePants** [comment]
How did you install this in a Net Core app? Shouldn’t be possible via Nuget as it’s not a supported target.

**Comment by Porkechebure** [comment]
> How did you install this in a Net Core app? Shouldn’t be possible via Nuget as it’s not a supported target.

Don't know I think you set wrong dependencies in package

Check attachment
![screen](https://user-images.githubusercontent.com/3466040/65327797-2eaa7f80-dbb5-11e9-8f66-e227a19a9bfb.png)

**Comment by JimBobSquarePants** [comment]
It has none. It’s built against net 4.52 though and is unsupported on net core. I recommend ImageSharp for that target framework

**Comment by Porkechebure** [comment]
Now from this code I get:
`` BarcodeSettings settings1 = new BarcodeSettings();
                settings1.Type = BarCodeType.EAN128;
                settings1.Data = codice;
                settings1.ImageWidth = 200;
                settings1.ImageHeight = 100;

                BarCodeGenerator barcode1 = new BarCodeGenerator(settings1);
                using (Image barcodeImage1 = barcode1.GenerateImage())
                using (MemoryStream stream1 = new MemoryStream())
                {
                    using (ImageFactory imageFactory1 = new ImageFactory())
                    {
                        imageFactory1.Load(barcodeImage1)
                    .Crop(new Rectangle(0, 15, 200, 75))
                    .Resize(new Size(200, 100))
                    .BackgroundColor(Color.White)
                    .Save(stream1);
                    }
                    base64Barcode = Convert.ToBase64String(stream1.ToArray());
                }
``

Not it gives me

ystem.ArgumentNullException: Value cannot be null.
Parameter name: encoder
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
System.ArgumentNullException: Value cannot be null.
Parameter name: encoder
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)

I know it's when image is in RawFormat but Save() has no parameter to set it as Imageformat.Bmp or something else.

Same code in the same block but with different image works fine

(I put 2 block of the same type as above but the other is called barcode2, barcodeImage2 etc etc

**Comment by Porkechebure** [comment]
Specifying like this:

                BarCodeGenerator barcode1 = new BarCodeGenerator(settings1);
                using (Bitmap barcodeImage1 = new Bitmap(barcode1.GenerateImage()))
                using (MemoryStream stream1 = new MemoryStream())
                {
                    using (ImageFactory imageFactory1 = new ImageFactory())
                    {
                        imageFactory1.Load(barcodeImage1)
                    .Crop(new Rectangle(0, 15, 200, 75))
                    .Resize(new Size(200, 100))
                    .BackgroundColor(Color.White)
                    .Save(stream1);
                    }
                    base64Barcode = Convert.ToBase64String(stream1.ToArray());
                }


So it knows it's a bitmap doesn't solve.

Damn... this library is a nasty fucking mass of bugs.... Horrible

Heading to imagesharp....

**Comment by Porkechebure** [comment]
Just put them in 2 separate methods and made them identical.... still same error
Ridiculous...
![Screenshot_2](https://user-images.githubusercontent.com/3466040/65334532-dbd7c480-dbc2-11e9-8a04-1604b4e08a3f.png)

**Comment by JimBobSquarePants** [comment]
>Damn... this library is a nasty fucking mass of bugs.... Horrible

Fundamentally untrue, downloaded millions of times and trusted by many. Run along.

**Comment by Porkechebure** [comment]
Fundamentally untrue but true:

` using (Bitmap croppedImage = new Bitmap(barcodeImage))
                        {
                            //ORIGINAL IMAGE IS 200 Width 100 HEIGHT
                            croppedImage.Clone(new Rectangle(0, 15, 200, 75), barcodeImage.PixelFormat).Save(stream, ImageFormat.Bmp);

                            imageFactory.Load(stream)
                             .Resize(new Size(200, 100))
                             .BackgroundColor(Color.White)
                             .Save(stream);
                        }`
Even with hacks no solution

**Comment by Porkechebure** [comment]
How you are going to deny it ahahah you have the proofs here man
