### ISSUE TITLE
Config Setting for Setting Upscale Default to False?

### ISSUE THREAD

**Issue by jjack-vertex** [JimBobSquarePants/ImageProcessor#767]
Is there a way to use a default of false for the Upscale option by setting something in a config file?

I haven't found any info on this in documentation or in the repo. I hope I'm not missing it.

I have the following in my processing.config file:
```xml
    <plugin name="Resize" type="ImageProcessor.Web.Processors.Resize, ImageProcessor.Web" enabled="true">
      <settings>
        <setting key="Upscale" value="false" />
      </settings>
    </plugin>
```

**Comment by JimBobSquarePants** [comment]
@jjack-vertex No config I'm afraid. Only settings for[ max values](https://github.com/JimBobSquarePants/ImageProcessor/blob/06ff61c1ef6c7b01523855ab91698a858c4797d7/tests/ImageProcessor.TestWebsite/config/imageprocessor/processing.config#L53)

You could create an `IWebGraphicsProcessor`  based on [`Resize`](https://github.com/JimBobSquarePants/ImageProcessor/blob/06ff61c1ef6c7b01523855ab91698a858c4797d7/src/ImageProcessor.Web/Processors/Resize.cs) processor though that implemented the functionality.
