### ISSUE TITLE
Cant do format=webp and quality=1 when source is PNG

### ISSUE THREAD

**Issue by kieronbos** [JimBobSquarePants/ImageProcessor#771]
### Description
I seem to be unable to use quality + webp on a png, i can convert a 500kb png down to a 27kb webp, which is amazing, but then if i do quality also, it makes no change. quality however does work on the other images which are jpg in source.

### Steps to Reproduce
I simply started a new .net web project using Umbraco 8.2.1, accepted the default starter kit, then added a large png (500kb) as a product image.

### System Configuration

- ImageProcessor version: 2.7.0.100
- ImageProcessor.Web version: 4.0.10.100
- Other ImageProcessor packages and versions: WebP plugin: 1.2.0.100
- Environment (Operating system, version and so on): Running Umbraco 8.2.1 locally on windows 10

I have both `<plugin name="Quality" type="ImageProcessor.Web.Processors.Quality, ImageProcessor.Web" enabled="true" />` & `<plugin name="Format" type="ImageProcessor.Web.Processors.Format, ImageProcessor.Web" enabled="true" />
`

Probably no help but this is my png: https://ibb.co/VNQ2P39

**Comment by ronaldbarendse** [comment]
I've just tested this on a similar setup and images with `image.png?format=webp&quality=1` are visibly impacted by the 1% quality...

The source image type shouldn't matter, as it's loaded into a bitmap anyway, so it makes no sense why it works on JPEG images, but not PNGs. Can you double-check your findings and post the resulting files (directly in GitHub please)?

**Comment by kieronbos** [comment]
Ive just span up a new instance from home and now im able too! Really not sure what I must of been doing wrong! Like you say its clear, I have it here:

https://kieron.codes/media/lsnkwlgj/webp.png 
https://kieron.codes/media/lsnkwlgj/webp.png?format=webp&quality=1

Sorry for raising the issue, I will try again next week back on my work machine and see if i can figure out why it was being funny on that machine!

Cheers

**Comment by ronaldbarendse** [comment]
It looks like the PNG images are already converted to WebP (even without the query string), so check whether you don't overwrite the query string in the `ValidatingRequest` event: https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events.
