### ISSUE TITLE
Azure Blob Storage Image optimization stops working invalid media ID

### ISSUE THREAD

**Issue by szabolcs-kadar** [JimBobSquarePants/ImageProcessor#772]
We get an issue after installing azureblobstorage plugin and changing the imageoptimizer config settings as described in the documentation here: 

https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure under combining with Imageprocessor. 

We changed security.config to: 

```xml 
<service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web"/>
    <service prefix="local/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="https://xx.blob.core.windows.net/local/"/>
      </settings>
    </service>
```

We have a container in there called local, development, etc.

When we try hitting reoptimize image, for an existing file, we get an error: 

An unexpected internal error has occurred; the image could not be optimized

after that, the folder and file disappears from the local media folder, and we get an invalid media id error on any subsequent calls to re-optimize. 

For new images, it's straight to Invalid Media Id. Feels like it's still looking for the image in the local path. 

What do you think we are doing wrong with this? Our cache config hasn't changed: 

```xml
 <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365" browserMaxDays="7" trimCache="false" memoryMaxMinutes="1">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
```

We use
- ImageProcessor version: 2.7.0.100
- ImageProcessor.Web version: 4.10.0.100
- ImageProcessor.Web.Config version: 2.5.0.100

Thank you

**Comment by JimBobSquarePants** [comment]
>We get an issue after installing azureblobstorage plugin and changing the imageoptimizer config settings as described in the documentation here:

What imageoptimizer config?

**Comment by keifling1** [comment]
wrong project?
