### ISSUE TITLE
Cannot extend IImageService Interface

### ISSUE THREAD

**Issue by rossdc02** [JimBobSquarePants/ImageProcessor#773]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am running the latest version of ImageProcessor
- [x ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x ] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I need to extend IIMageService so that I can create a SecureCloudImageService, providing the ability to pass in AWS access key/secret, and/or STS credentials to get images from s3. The RemoteFile class is internal and prohibits extension. Documentation states IImageService is open for extension, please advise.

### System Configuration

- ImageProcessor version:
- ImageProcessor.Web version (if applicable) 4.10.0.100
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.7.2
- Additional information:

**Comment by ronaldbarendse** [comment]
The `IImageService` doesn't reference the `RemoteImage` class in any way: https://github.com/JimBobSquarePants/ImageProcessor/blob/c7205e73a98f09f97071c16f4831e6ed97cc3def/src/ImageProcessor.Web/Services/IImageService.cs

My guess is you're trying to extend `CloudImageService`, which might indeed not be completely extendable (nor is it advertised as being so): https://github.com/JimBobSquarePants/ImageProcessor/blob/a1dc7f5e39968e7e1f7ada16b83a873049082308/src/ImageProcessor.Web/Services/CloudImageService.cs

The `AzureImageService` might be a good example to get started: https://github.com/JimBobSquarePants/ImageProcessor/blob/d545e8963fadb5b50026c350355f6436432d380f/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureImageService.cs
