### ISSUE TITLE
Use CloudImageService to get images without extentions

### ISSUE THREAD

**Issue by enkelmedia** [JimBobSquarePants/ImageProcessor#774]
Hi!

I was trying to use the great CloudImageService to fetch remote images from different sources, the sources where the images ended with an extension worked fine but one of the services had urls like:

https://cdn.foo.com/images/image111

An passing this to the CloudImageService would not work since it validates the request URL based on extensions.

https://github.com/JimBobSquarePants/ImageProcessor/blob/06ff61c1ef6c7b01523855ab91698a858c4797d7/src/ImageProcessor.Web/Services/CloudImageService.cs#L80

I solved this by creating my own service, 

```
 public class MyImageCloudService : CloudImageService
    {
        public override bool IsValidRequest(string path)
        {
            return true;
        }
    }
```

No sure if that is "right" but I was wondering if you see any value in getting a PR with either a setting or something on the CloudImageService to also support requests to images without extensions?

All the best!

**Comment by ronaldbarendse** [comment]
The additional check is probably for performance reasons, as this service doesn't use a prefix and we don't want to do all the processing for all requests. Always returning true might even cause this service to forward unwanted requests to the specified host.

Not having a file extension also means it can't infer the format to return, so it might even change PNGs to JPEG (default format)!

As you already found a solution/workaround and changing this might cause a lot of problems, I'm closing this issue.
