### ISSUE TITLE
.NET Core 3.1 Compatibility

### ISSUE THREAD

**Issue by shadowfox87** [JimBobSquarePants/ImageProcessor#776]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Hi, I'm using a program that utilizes the ImageProcessor package. This program was made using .NET Core 3.1. It says on the website that ImageProcessor is compatible with .NET Framework 4.5+, but I was wondering if it is also compatible with .NET Core 3.1?

The error I receive is this:
https://cdn.discordapp.com/attachments/605018191827173377/653968672469286912/unknown.png

### System Configuration

- ImageProcessor version: 2.7.0.100
- ImageProcessor.Web version (if applicable)
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by ronaldbarendse** [comment]
ImageProcessor is indeed only compatible with .NET Framework. For .NET Core you can try ImageSharp: https://github.com/SixLabors/ImageSharp
