### ISSUE TITLE
AzureBlobCache version compatible with Umbraco V7.15

### ISSUE THREAD

**Issue by c9mbundy** [JimBobSquarePants/ImageProcessor#779]
I just installed AzureBlobCache on a V7 Umbraco-Cloud site, and it automatically selected 1.6.0 
It the install changed a long list of files in the bin folder of what is the latest version of Umbraco-7, and so I'm naturally concerned to ensure this was actually a V7 package and that I have not inadvertently installed a V8 package.

**Comment by JimBobSquarePants** [comment]
ImageProcessor IS NOT an Umbraco package. It is a stand alone library that Umbraco consumes.

**Comment by c9mbundy** [comment]
Yeah, sorry - ImageProcessor.Web.Plugins.AzureBlobCache plugin installed using package manager - but my question was simply if 1.6.0 of this plugin was compatible with Umbraco-7 (i.e. .net 4.5.2) or if I should be installing an earlier version of it, as it it seems to swap out an awful lot of files in the bin folder.

**Comment by JimBobSquarePants** [comment]
Do you have a list? 

I would imagine most files are related to the Azure SDK version changes.
