### ISSUE TITLE
Exif Tag Support

### ISSUE THREAD

**Issue by phillip-haydon** [JimBobSquarePants/ImageProcessor#78]
Starting discussion on Exif tag support.

*Sorry this is late, been busy at work and I wrote up 3/4 of a post then my pc crashed and now need to start again. Will add to the list as we discuss.*

*I'm currently finding lots of  photos  to test with from different camera and phones, will add to this issue as we discuss*

### Problems:

I've been trying MANY different libraries to read Exif tags, almost all libraries supply an enum to get a tag. However they aren't helpful.

1) Only supplying an enum requires you to know what the Exif tag is and what its data type is. This can cause problems if a photo is showing you an int value, you assume its int, parse it out, then get exceptions when you find out it is actually a double.

2) The list is in complete and doesn't even give you information about the full list (link in resources)

3) The data types that Exif stores and the values the user would display are different. For example an Exif may have a value of 0.125, but does not tell you the fraction is 1/8 (or there about) 

### Libraries used:

- http://www.nuget.org/packages/photo.exif/
- http://www.nuget.org/packages/ExifLib/
- http://www.nuget.org/packages/ImageResizer

photo.exif does not remove null line endings so you end up persisting strange characters in the database and when rendered to a browser it shows a square. 

ExifLib works pretty well but it uses an enum, and is prone to throwing exceptions. If a file does not contain Exif data at all, it throws, it should be graceful and return an empty collection...

ImageResizer I thought had Exif support but it actually only strips Exif data...

### Resources:

http://www.digitalpreservation.gov/formats/content/tiff_tags.shtml

### Ideas:

- When resizing files Exif data is usually lost, would be good to copy that into the new file if the user requests to do so.
- Possible use of a contract to define each Exif attribute, allowing the user to implement their own if we don't implement all, giving a single simple API to work with Exif data without having to fall back to `ushort` values to query specific attributes.

**Comment by musukvl** [comment]
In my project I need to auto rotate uploaded jpg and use its EXIF and XMP metadata after that. 
So I'm interested in image metadata support by ImageProcessor and I can try to help you with it. 
I see XMP is not supported at all: XMP metdata is not copied even if preserveExifData: true. I can try to resolve this problem first. 
Now I see only one way how XMP or Iptc can be extracted: it is by using System.Windows.Media.Imaging.BitmapMetadata.
I think, metadata reading should be moved to ImageFormat.
If you have some ideas about that, please tell me.

**Comment by JimBobSquarePants** [comment]
I'm loath to do too much work on this at the moment as we don't know what is happening with imaging support in the upcoming .NET versions, especially on ASP. https://github.com/aspnet/Home/issues/192
We might not even be using `System.Drawing` or `System.Windows.Media.Imaging`

**Comment by nathanaeljones** [comment]
MetadataExtractor is the best solution for reading metadata. The .NET port is actually official, now!

**Comment by JimBobSquarePants** [comment]
@nathanaeljones Excellent thanks! I'd much, much rather use that than establish something of my own.

**Comment by JimBobSquarePants** [comment]
Just realised that library doesn't support editing metadata. I'll need to be able to do that. 

https://github.com/drewnoakes/metadata-extractor-dotnet/issues/23

**Comment by stbraley** [comment]
Hello,

Great project. On this issue. Have you looked at the [exiv2](http://www.exiv2.org/) project? Its cross platform C++, does reads and writes. Looks to be very comprehensive. The wiki has tones of information on this subject. Here is the link to the [documentation](http://dev.exiv2.org/projects/exiv2/wiki/The_Metadata_in_JPEG_files) for the algorithm they use (read/write) on jpeg metadata. Took a quick glance at the code which appears to be very clean. You can also compile and debug it with Visual Studio 2015.




Thanks for you hard work on this project. It's very interesting stuff.

**Comment by JimBobSquarePants** [comment]
Wow! There's a ton of information here to look into. Thanks! 

I don't know what the best approach would be. I'd like to do as much as possible in C# but it's a lot of work to do so. I need to clean up my jpeg code to make it easier to incorporate these kind of additions either way.

**Comment by stbraley** [comment]
Yes, given what this project is trying to do. A full blown C# solution is best and may be the only option given the CoreCLR restrictions.

I started dorking around with the ImageProcessor code last night. I started by adding support for the 'APP1' marker in the jpeg decoder thinking I will just use the exiv2 code as my guide.

From what I gathered in the short time I spent. The exif data is actually a TIFF image embedded in the 'APP1' segment of the jpeg. So naturally I thought; Need a TIFF decoder! Which leads me to my question? How do I share the buffer that contains the jpeg data with the TIFF decoder? 

For now, I think I'm just going to have the jpeg decoder read in the entire TIFF into a memory stream and pass that to the TIFF decoder. Just to keep moving and understanding how it all works.

**Comment by JimBobSquarePants** [comment]
I'm glad you agree. I'd much rather keep everything in one language.

I did not know it was stored in the TIFF format! I've been shying away from EXIF so far through development.

The individual core decoders can always be initialised so I would create a separate Tiff decoder then call an instance of that from within the Jpeg decoder to decode the EXIF data. Eventually we can write an encoder also to go with it.

I'm going to do some standardization across the (en/de)coders to ensure we can decode height/width etc without having to decode the whole stream. I'll leave cleaning up Jpeg for now so that you can work without worrying about merge conflicts

**Comment by stbraley** [comment]
Just put in a pull request for this  #357 .

Let me know your thoughts.

**Comment by dlemstra** [comment]
Just pushed another pull request for this: #450.

**Comment by JimBobSquarePants** [comment]
It's only taken 2 years but we have EXIF! 🎉 

Many thanks to everyone involved in the discussion and special thanks to @stbraley for his initial PR and effort and @dlemstra for providing a provable, workable PR that has been accepted and merged.  

I'm over the moon about this one 😸
