### ISSUE TITLE
Instagram Image with timestamp not working

### ISSUE THREAD

**Issue by dorofino** [JimBobSquarePants/ImageProcessor#780]
### Prerequisites
Image to crop
https://instagram.ftpa1-1.fna.fbcdn.net/v/t51.2885-15/e35/82568642_170478001026356_1775604057563561059_n.jpg?_nc_ht=instagram.ftpa1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=ZxDmFduQc0wAX9jUC5x&se=7&oh=c95cdc57c1c1c2653b871ed3745bee03&oe=5ECB86B9&ig_cache_key=MjIyNTc4NDQzOTUwODkxNDI5MA%3D%3D.2

### Description
When I try to crop this image I'm getting an error 
**_The resource you are looking for has been removed, had its name changed, or is temporarily unavailable._**

..../remote.axd?https://instagram.ftpa1-1.fna.fbcdn.net/v/t51.2885-15/e35/82568642_170478001026356_1775604057563561059_n.jpg?_nc_ht=instagram.ftpa1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=ZxDmFduQc0wAX9jUC5x&se=7&oh=c95cdc57c1c1c2653b871ed3745bee03&oe=5ECB86B9&ig_cache_key=MjIyNTc4NDQzOTUwODkxNDI5MA%3D%3D.2?crop=691,932,546,851&width=546&height=851

### System Configuration
C# 
ImageProcessor 2.7.0.100

**Comment by ronaldbarendse** [comment]
Looks like you didn't correctly configure the remote image service, especially the whitelist: https://imageprocessor.org/imageprocessor-web/configuration/#securityconfig. You're also using the legacy syntax to request the image: https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#remote.

**Comment by dorofino** [comment]
Hi Ronald, 

Yeah that maybe it, but if you noticed the Instagram image is not a direct image format(jpg,png,gif) and its used a timestamp to render it. 

This new implementation will allow me to crop this link?

https://instagram.ftpa1-1.fna.fbcdn.net/v/t51.2885-15/e35/82568642_170478001026356_1775604057563561059_n.jpg?_nc_ht=instagram.ftpa1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=ZxDmFduQc0wAX9jUC5x&se=7&oh=c95cdc57c1c1c2653b871ed3745bee03&oe=5ECB86B9&ig_cache_key=MjIyNTc4NDQzOTUwODkxNDI5MA%3D%3D.2

?crop=691,932,546,851&width=546&height=851

**Comment by ronaldbarendse** [comment]
The following URL works if you've correctly configured the remote image service. I'm just not sure why you're cropping that specific part of the image 🤡 

`/remote.axd/instagram.ftpa1-1.fna.fbcdn.net/v/t51.2885-15/e35/82568642_170478001026356_1775604057563561059_n.jpg?_nc_ht=instagram.ftpa1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=ZxDmFduQc0wAX9jUC5x&se=7&oh=c95cdc57c1c1c2653b871ed3745bee03&oe=5ECB86B9&ig_cache_key=MjIyNTc4NDQzOTUwODkxNDI5MA%3D%3D.2?crop=691,932,546,851&width=546&height=851`

**Comment by dorofino** [comment]
Got it. 
I will work on the upgrade. 

lol, yeah I know. Its for a client. 

Thank you
