### ISSUE TITLE
ImageProcessor Web convert .tif format

### ISSUE THREAD

**Issue by Ahmed-Sajjad** [JimBobSquarePants/ImageProcessor#783]
I'm using ImageProcessor.Web for rendering images of different formats to png. For most it works fine but I'm facing issues for tiff and tif.

I specified the format of a tiff file, (this is jpg coz it didn't upload tiff)
![Canary Islands](https://user-images.githubusercontent.com/30384042/73332148-aab18400-4287-11ea-8f4f-a68d961796b6.jpg)

And the result was this
![image](https://user-images.githubusercontent.com/30384042/73332202-cddc3380-4287-11ea-9591-9545ed0dcad9.png)

Also for tif file it throws an error
![image](https://user-images.githubusercontent.com/30384042/73332275-0f6cde80-4288-11ea-97cf-620f54da5982.png)

I'd highly appreciate any help for solving these issues.

Thanks in advance

**Comment by JimBobSquarePants** [comment]
Hi @Ahmed-Sajjad 

Could you please fill out the issue template indicating the running version etc. 

Thanks!

**Comment by ronaldbarendse** [comment]
The exception is thrown from `System.Drawing.Image`, so there's probably nothing ImageProcessor can do to fix that and it might be because of a corrupt/unsupported TIFF file or not enough contiguous memory (as that also causes this exception).
