### ISSUE TITLE
How to override ILogger?

### ISSUE THREAD

**Issue by vamone** [JimBobSquarePants/ImageProcessor#786]
Hi, I would like to know how to override ILogger, as I would like to pass a little bit more information to the event listeners. //Valentine

**Comment by ronaldbarendse** [comment]
You can use `ImageProcessorBootstrapper.SetLogger()` to replace the `DefaultLogger` with your own, but this is only used for writing the internal log messages of ImageProcessor to your own logging library/implementation.

There's no need to override/change this if you want to log additional information within the event listeners: just use your own logging library or `Trace.WriteLine()`/`Debug.WriteLine()` methods from the .NET Framework.
