### ISSUE TITLE
Uploading JPG breaks but works after editing in paint.

### ISSUE THREAD

**Issue by jeanpoelie** [JimBobSquarePants/ImageProcessor#788]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We uploaded an image we downloaded from google: https://www.brewtonstandard.com/wp-content/uploads/2018/05/golf-hole.jpg

This image gave us an error:
System.ArgumentException
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap.SetResolution(Single xDpi, Single yDpi)
   at ImageProcessor.Imaging.Quantizers.Quantizer.Quantize(Image source)
   at ImageProcessor.Common.Extensions.ImageExtensions.Copy(Image source, AnimationProcessMode animationProcessMode, PixelFormat format, Boolean preserveExifData)
   at ImageProcessor.ImageFactory.Load(Image image)

After editing the image with paint and adding 1 black dot it uploads without issue.
![broken](https://user-images.githubusercontent.com/10237926/74511836-2c9be100-4f07-11ea-8eb7-3865773a61db.jpg)
![works](https://user-images.githubusercontent.com/10237926/74511837-2d347780-4f07-11ea-803b-411e909f6aaa.jpg)

Any idea what might be the issue?

- ImageProcessor version: 2.5.6 (cannot upgrade because we use .net 4.5)
- Environment (Operating system, version and so on): Linux, AKS (Azure Kubernetes)
- .NET Framework version: 4.5
- Additional information: The API that calls the library with 4.5 is a .net core 3.0 application.

**Comment by ronaldbarendse** [comment]
The original image is probably corrupt or at least can't be read by `System.Drawing`, so there's nothing ImageProcessor can do to fix this.

If you're using .NET Core, you might want to transition to https://github.com/SixLabors/ImageSharp.

**Comment by JimBobSquarePants** [comment]
I just noticed the version number here. `ImageProcessor version: 2.5.6`

I'm sorry but I cannot possibly support such an old version. NET 4.5 is not supported by Microsoft so I suggest you make plans to upgrade.

**Comment by jeanpoelie** [comment]
For reference: We eventually moved the functionality to a different API (.NET Framework) because we were not able to upgrade our underlaying library yet, still have some projects in .NET Framework that depend on it.

We will upgrade to .net core soon and will than start using the newer version of ImageProcessor I have already played around with it without issue in .net core 3.1

**Comment by JimBobSquarePants** [comment]
> We will upgrade to .net core soon and will than start using the newer version of ImageProcessor I have already played around with it without issue in .net core 3.1

I'm afraid ImageProcessor isn't supported on NET Core. The cross platform implementation of System.Drawing is simply too buggy.
