### ISSUE TITLE
Security.Config query

### ISSUE THREAD

**Issue by NikRimington** [JimBobSquarePants/ImageProcessor#791]
Hi James,

Thanks for an amazing product. It's such a great plugin and it's integration/use in Umbraco is a life saver.

I was wondering if you could provide some advice, I'm trying to see how I can have different settings in the settings.config file for different environments. Ideally I would like to keep using the LocalFileImageService for local developers, but then on the deployed environments use the CloudImageService, or another service, such as a the blob storage one. However I'm not sure of the best way to go about achieving this so thought I'd reach out.

Hope you can help/provide an idea?

Do you think having both enabled but with different prefixes (and changing the prefix depending on environment) would be a sensible approach?

Thanks,

Nik

**Comment by ronaldbarendse** [comment]
You should use environment-specific config transforms for this, e.g. using [SlowCheetah](https://github.com/microsoft/slow-cheetah) or [Umbraco Cloud config transforms](https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/Config-Transforms/) (if you're hosting the live-environment on UC).

In the config transform, you'd remove the `LocalFileImageService` and add the `CloudImageService` (or other required services).
