### ISSUE TITLE
Resize Quality can be improved.

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#792]
See #790

Resize quality is far better in the v3 branch. We should backport some of that logic into the dev-v2 branch to improve quality.

e.g.
http://mb-website.com/prova.html

**Comment by vanessa1290** [comment]
Hi, thank you to open this thread, and again good job for the nice libraries that you developed.
Hope to have some good news about this improvement that we need, we wish to use it on our startup, thank you. Vanessa

**Comment by vanessa1290** [comment]
Hi, are there any updates? 

thank you very much
Vanessa

**Comment by JimBobSquarePants** [comment]
@vanessa1290 I'm investigating and working on the issue just now. I think, with the changes I'm implementing I've pushed it to the very maximum quality I can get System.Drawing (still not fantastic, but better) to deliver so will push the new code in the next 24-48 hours.

**Comment by vanessa1290** [comment]
Nice! I'm looking forward to trying, where could I download the updated version? Thank you

**Comment by JimBobSquarePants** [comment]
See https://www.nuget.org/packages/ImageProcessor/2.9.0 for latest release.
