### ISSUE TITLE
IO Errors with CacheTrimmer in Scaled Environment

### ISSUE THREAD

**Issue by jason-booth** [JimBobSquarePants/ImageProcessor#794]
We're using ImageProcessor in an EPiServer site that is scaled across 3 servers who share one image cache. We've been seeing sporadic IO errors with CacheTrimmer like DirectoryNotFoundException and UnauthorizedAccessException (example below).

After talking with @JimBobSquarePants indeed the cache trimmer is not robust enough for a scaled environment.

StackTrace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ImageProcessor.Web.Caching.ImageCacheBase.CacheTrimmer.TimerRelease(Func`2 trimmer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

InnerException: System.IO.DirectoryNotFoundException

Message: Could not find a part of the path '\\<our shared drive>\image-cache\7\0\0\2\f'.

**Comment by ronaldbarendse** [comment]
If multiple servers access the same cache directory, this could indeed happen (especially when you have a large amount of images, causing the trimming jobs to overlap). You can disable cache trimming entirely (`trimCache="false"` in the cache config) or only enable it on a single server as a temporary fix.

As trimming is done in a background task, the exception shouldn't affect the generation/caching of images: it could however stop trimming any further images.

The trimming code already does a check whether the directory exists, before enumerating the files:

https://github.com/JimBobSquarePants/ImageProcessor/blob/48bccd4e82e4ae51b53cdd79d9ecd9d34849e642/src/ImageProcessor.Web/Caching/DiskCache.cs#L224-L227

https://github.com/JimBobSquarePants/ImageProcessor/blob/48bccd4e82e4ae51b53cdd79d9ecd9d34849e642/src/ImageProcessor.Web/Caching/DiskCache.cs#L234-L236

If another server is already trimming the cache, it could delete that directory, causing the file enumeration to throw the exception you've posted:

https://github.com/JimBobSquarePants/ImageProcessor/blob/48bccd4e82e4ae51b53cdd79d9ecd9d34849e642/src/ImageProcessor.Web/Caching/DiskCache.cs#L268-L269

**Comment by JimBobSquarePants** [comment]
We'll close this based on #795 795
