### ISSUE TITLE
 overlay method

### ISSUE THREAD

**Issue by javagraf** [JimBobSquarePants/ImageProcessor#800]
Hello everyone. First of all, I want to say thanks for the wonderful library ! Now the question. Using the overlay, my overlay image can hide behind the left edge, but on the other three sides, the image rests on the edge and does not want to hide. So how do I get a picture off the edge? Thanks!

**Comment by ronaldbarendse** [comment]
Can you provide example code for this issue?

Also note that the overlay is resized to match the image dimensions: https://imageprocessor.org/imageprocessor/imagefactory/overlay/. From what I can gather from your question, it seems like you want to make the overlay bigger than the image, which is not supported.
