### ISSUE TITLE
How to determine loaded JPEG's quality?

### ISSUE THREAD

**Issue by burak-tarhanli** [JimBobSquarePants/ImageProcessor#802]
I'm minifying image disk sizes by resizing and saving them with 80 or less jpeg quality. But some images are already minified and if i re-save them, the quality drops very much. I want to determine if a JPEG is already compressed or is low quality. Can i achive that?

**Comment by JimBobSquarePants** [comment]
ImageProcessor is a wrapper around System.Drawing and as such is limited (mostly) by that platform. System.Drawing cannot tell you the quality of a jpeg file, you’d need something else like ImageSharp or Magick.NET
