### ISSUE TITLE
Poor quality after upgrade from 2.7.0.100/4.12.0.100 to 2.9.0/4.12.0

### ISSUE THREAD

**Issue by andersbrohall** [JimBobSquarePants/ImageProcessor#804]
We're experiencing a drop in quality on resized images since we upgraded to the latest versions of the ImageProcessor and sup projects. 

Upgrades:
ImageProcessor: 2.7.0.100 to 2.9.0
ImageProcessor.Web: 4.10.0.100 to 4.12.0
ImageProcessor.Web.Config: 2.5.0.100to 2.6.0
ImageProcessor.Web.PostProcessor: 1.1.2 to 2.0.0

We also have the ImageProcessor.Plugins.WebP 1.3.0 installed, but since we see the same problem without format=webp, I don't see how that would matter. 

When resizing https://www.obviuse.se/static/um.jpg to either 780 or 390 in width the text in the logotype get really poor jpg quality. We also see a big drop in file size.

https://www.wherever.com/um.jpg?width=390 results: 
https://www.obviuse.se/static/um-4.10-390.jpg 30k
https://www.obviuse.se/static/um-4.12-390.jpg 17k

https://www.wherever.com/um.jpg?width=780 results: 
https://www.obviuse.se/static/um-4.10-780.jpg 120k
https://www.obviuse.se/static/um-4.12-780.jpg 67k

Adding &quality=100 gives us the exact same result. 
Been trying to adjust the output with gaussian sharpen, but that wouldn't be the correct way of solving the problem. We would want quality=100 to be somewhat lossless, as expected. 

The lower file size is of course a really good thing, but we can't figure out how to force the resize to get the best quality possible. Is it a bug or a configuration issue?

We use .NET 4.72 on a Win 2012 R2 server (and Win 10 when developing). 

Cheers´
Anders Brohäll

**Comment by andersbrohall** [comment]
That said, we're not too happy about the quality of the previous version neither. Maybe there is a way of improving the quality all-in-all. 

When resizing the image - with all default settings and saved with max quality (12) - in Photoshop, the result is: 
https://www.obviuse.se/static/um-ps-390.jpg 135k
https://www.obviuse.se/static/um-ps-780.jpg 439k

Of course the file size is a lot bigger than the rendered ones, but i would prefer being able to adjust that myself with fiddeling with the quality setting in ImageProcessor. 

Without any record of it, I remember the older versions of the ImageProcessor being virtually lossless using quality=100. But i might be remembering it wrong?

**Comment by JimBobSquarePants** [comment]
> ImageProcessor.Web.PostProcessor: 1.1.2 to 2.0.0

Using a post processor will definitely reduce the file size vs Photoshop. The post processor uses MozJpeg under the cover to . 

Since there's no before before/after examples I cannot tell if there is a difference in the output with or without the post processor. If anything, the default output should be better with later versions as we've cranked up all the System.Drawing settings to maximum.

>Without any record of it, I remember the older versions of the ImageProcessor being virtually lossless using quality=100. But i might be remembering it wrong?

The main difference I see between the Photoshop version and the ImageProcessor version is chroma subsampling. System.Drawing always subsamples which is not great for high quality jpegs. That behavior has and will not ever change.

**Comment by ronaldbarendse** [comment]
If quality is important, you should uninstall the PostProcessor plug-in, as that will always lower the quality (even if ImageProcessor is saving the image with as quality of 100%). Like @JimBobSquarePants mentions, ImageProcessor depends on what System.Drawing can provide, which might not equal other programs like Photoshop.
