### ISSUE TITLE
Generate image

### ISSUE THREAD

**Issue by jueqing1015** [JimBobSquarePants/ImageProcessor#805]
I want to create a new 500 * 500 white image to generate watermark image. How can I operate it? I think the interface is only loaded

**Comment by JimBobSquarePants** [comment]
Use System.Drawing to create new images. `ImageFactory` is designed as a wrapper around existing System.Drawing images or images loaded from a source.

Once created you can then load that image into the `ImageFactory` for further processing.

https://github.com/JimBobSquarePants/ImageProcessor/blob/614af1b61978de1eca15c07f131e3bbdc8139c50/src/ImageProcessor/ImageFactory.cs#L426
