### ISSUE TITLE
Sign the assemblies

### ISSUE THREAD

**Issue by Sicos1977** [JimBobSquarePants/ImageProcessor#808]
Could you please sign the assemblies? I have a project that is signed and because of that does not accept unsigned assemblies. Signing an assembly is very easy and doesn't give any performance hits or whatsoever.

**Comment by ronaldbarendse** [comment]
Strong naming/signing the ImageProcessor assemblies would require all dependencies to also be signed and although it might not give any performance hit, it does add some [major issues](https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/Documentation/project-docs/strong-name-signing.md).

If you really need to, you can sign the assemblies yourself using https://github.com/dsplaisted/strongnamer. It looks like you're using ImageProcessor on a new project (or integrating it onto an existing one): just note ImageProcessor is in soft-archive mode!
