### ISSUE TITLE
Padding PNG with transparant color

### ISSUE THREAD

**Issue by LennardF1989** [JimBobSquarePants/ImageProcessor#813]
### Description
I have seen this working before, but I simply cannot get it to work now. I have a PNG which I resize using the "width" and "height" query-string attributes, I then apply a bgcolor transparent but it doesn't actually do anything. Weirdly, when I do something like bgcolor=255,0,0,64 the background actually becomes a dark shade of red, but it's drawn on top if the padded black. 

How can I set the padded space to transparent?

### Steps to Reproduce
See above.

### System Configuration
2.7.0 bundled with Umbraco 8.4.1

**Comment by JimBobSquarePants** [comment]
- [ ] I have verified that I am running the latest version of ImageProcessor

Please don't edit the issue template. 

You need to use the latest versions to receive support. I don't have the resources to support legacy versions.

**Comment by LennardF1989** [comment]
This was more so a question rather than a bug report to verify if ?width=x&height=y&bgcolor=transparent is the right approach to pad with a transparent background. If it is, then it also warrants attempting an upgrade :)

**Comment by JimBobSquarePants** [comment]
Yep, the approach is correct. 

Your issue reads like it's related to #730 where the bit depth was retained from the input image. I've since fixed that so please upgrade. 

If it's still an issue after upgrading (and clearing your cache) please let me know and I'll be happy to investigate.
