### ISSUE TITLE
having issues getting a transparent background

### ISSUE THREAD

**Issue by PaulRitter** [JimBobSquarePants/ImageProcessor#815]
My Code:
```
ImageFactory imgF = new ImageFactory();
imgF.Load(someBitmap);
imgF.BackgroundColor(Color.Transparent);
```

I then save the Image to a Memorystream and display it in my program, however:

when using `imgF.Save(stream);` i get a black background on my image.
when using `someBitmap.Save(stream, System.Drawing.Imaging.ImageFormat.Png);` i get a proper transparent background.

what am I doing wrong?

**Comment by JimBobSquarePants** [comment]
The format of your input image doesn’t support an alpha channel. The `ImageFactory. CurrentImageFormat` will confirm that.

**Comment by PaulRitter** [comment]
worked 👍 thanks alot for the quick help
