### ISSUE TITLE
Tiff image unexpectedly filled with red color

### ISSUE THREAD

**Issue by AlexeiNT** [JimBobSquarePants/ImageProcessor#816]
### Description
I use ImageProcessor for the conversion of image formats. All almost works well except Tiff format. When I try to save the image from the example below I get its red-colored copy. I tried to initialize ImageFactory with turned on and off preserveExifData and fixGamma parameters but it didn't give any results, converted image is always red.

### Steps to Reproduce
Source code to reproduce consitsts just from:
```
const string filePathWithoutExtension = @".\wrong_tiff";
var toFormat = new PngFormat();
using (var imageFactory = new ImageFactory())
{
    imageFactory
        .Load($"{filePathWithoutExtension}.tiff")
        .Format(toFormat)
        .Save($"{filePathWithoutExtension}.{toFormat.FileExtensions.First()}");
}
```
[Example of wrong tiff image](https://drive.google.com/file/d/1dDPDqtNHc3nczVbBd9b_kkY-ISSMVn2F/view?usp=sharing)
[Example of saving it as PNG](https://drive.google.com/file/d/1E9Gxut04XS1eqyqQWe5SO9tm4bDkGnrV/view?usp=sharing)

### System Configuration
- ImageProcessor 2.9.1
- No other image processor packages
- Windows 10
- net4.7.1 and netcoreapp2.2 gives the same results

**Comment by ronaldbarendse** [comment]
> netcoreapp2.2 gives the same results

.NET Core isn't supported and this is probably something that's caused by a corrupt TIFF file and/or limitations in `System.Drawing` (not ImageProcessor).

Could you check whether the same also happens when saving it to other output formats? And if you resave the TIFF from a graphics program (to make sure it's not corrupt)?

**Comment by JimBobSquarePants** [comment]
System.Drawing seems to mess up when using the following to create a copy of the image.

```
var copy = new Bitmap(source.Width, source.Height, source.PixelFormat);
copy.SetResolution(source.HorizontalResolution, source.VerticalResolution);
using (var graphics = Graphics.FromImage(copy))
{
    graphics.DrawImageUnscaled(source, 0, 0);
}
```

**Comment by AlexeiNT** [comment]
Hmm, looks like `System.Drawing` works well. I have written a sample:
```
const string filePathWithoutExtension = @".\wrong_tiff";
var wrongTiffData = File.ReadAllBytes($"{filePathWithoutExtension}.tiff");
var toImageFormat = ImageFormat.Png;

using (var inputStream = new MemoryStream(wrongTiffData))
using (var sourceImage = Image.FromStream(inputStream))
using (var copiedImage = new Bitmap(sourceImage.Width, sourceImage.Height, sourceImage.PixelFormat))
{
    copiedImage.SetResolution(sourceImage.HorizontalResolution, sourceImage.VerticalResolution);
    using (var graphics = Graphics.FromImage(copiedImage))
    {
        graphics.DrawImageUnscaled(sourceImage, 0, 0);
    }

    using (var fileStream = new FileStream($"{filePathWithoutExtension}.{toImageFormat}", FileMode.Create))
    {
        copiedImage.Save(fileStream, toImageFormat);
    }
}
```
and it works fine, the result looks good, without any red color issues:
![wrong_tiff](https://user-images.githubusercontent.com/2228730/93191023-7c70ae00-f75d-11ea-96d0-0d847dd3b72b.Png)
If you interested in, you can watch the full sample source code here: https://github.com/AlexeiNT/ImageProcessorSample

**Comment by JimBobSquarePants** [comment]
I'm able to replicate the issue every time using System.Drawing. 

The difference is that you are not passing `true` to the `useEmbeddedColorManagement` parameter on `Image.FromStream(stream, bool)`.

If you don't pass the second parameter then ICC profiles are often lost and many images are returned with incorrect color output. It's only on rare instances like this that the profile cannot be read during copying.

**Comment by ronaldbarendse** [comment]
@JimBobSquarePants So the real issue is a corrupt ICC/color profile, correct? Or should ImageProcessor expose the `useEmbeddedColorManagement` in the `Load()` method, so this can be disabled (for those rare instances)?

https://github.com/JimBobSquarePants/ImageProcessor/blob/058188103033b4147de43a0efa3e6fe5713f85e7/src/ImageProcessor/Imaging/Formats/FormatBase.cs#L79-L83

**Comment by JimBobSquarePants** [comment]
Yeah, corrupt profile. Exposing the option via a new overload would likely be the best approach yes.

**Comment by ronaldbarendse** [comment]
I've explored adding a new overload to `Load(...)` to disable color management, but that requires changes to `FormatBase` (and all inherited formats that override this method must also be updated) and `ImageFactory`. Not all formats will use this parameter (like `WebPFormat`) and it's basically only required to support corrupt images...

@AlexeiNT As a workaround, you can load the file using `Image.FromFile()` without using the embedded color management and pass that to ImageProcessor:

```c#
const string filePathWithoutExtension = @".\wrong_tiff";
var toFormat = new PngFormat();
using (var imageFactory = new ImageFactory())
{
    imageFactory
        .Load(Image.FromFile($"{filePathWithoutExtension}.tiff", false))
        .Format(toFormat)
        .Save($"{filePathWithoutExtension}.{toFormat.FileExtensions.First()}");
}
```
