### ISSUE TITLE
When loading and saving the png image it gets truncated

### ISSUE THREAD

**Issue by Sicos1977** [JimBobSquarePants/ImageProcessor#817]
### Description
When loading and saving the png image it gets truncated. The size 

```c#
### Steps to Reproduce
            using (var imageFactory = new ImageFactory(FrameProcessingMode.First, MetadataMode.All))
            {
                Logger.WriteToLog("Loading image");
                imageFactory.Load(imageStream);
                imageFactory.Save("d:\\test.png");
                Logger.WriteToLog("Image loaded");
....
```
### System Configuration
Windows 2012 R2 development server

- ImageProcessor version: 3.0

Original image:
![tekening](https://user-images.githubusercontent.com/6692947/94525142-e8f6ad00-0233-11eb-9810-c58ef3bb2bd8.png)

Truncated image:
![test](https://user-images.githubusercontent.com/6692947/94525281-22c7b380-0234-11eb-931f-36cd1ccfbf5a.png)

**Comment by JimBobSquarePants** [comment]
ImageProcessor 3.0 as in the unreleased code in the https://github.com/JimBobSquarePants/ImageProcessor/tree/release/3.0.0 branch?

**Comment by Sicos1977** [comment]
Yes

**Comment by JimBobSquarePants** [comment]
I'm only seeing color loss when quantizing the image to 8bit output. Looks like the old Wu Quantizer doesn't use enough precision for the RGB components. 

32bit
![issue-817_Bit32](https://user-images.githubusercontent.com/385879/94709577-be911680-033d-11eb-8f85-4eceb2ecd273.png)

24bit
![issue-817_Bit24](https://user-images.githubusercontent.com/385879/94709560-b9cc6280-033d-11eb-8948-acb4618053d5.png)

16bit
![issue-817_Bit16](https://user-images.githubusercontent.com/385879/94709551-b76a0880-033d-11eb-8cc8-4fc6a8249479.png)

8bit
![issue-817_Bit8](https://user-images.githubusercontent.com/385879/94709547-b6d17200-033d-11eb-98e7-615ca1ec7e59.png)

**Comment by JimBobSquarePants** [comment]
It's highly likely that you and I are the only people looking at this code.

I'm not really actively maintaining the library anymore with all my focus shifted to my other far superior [ImageSharp](https://github.com/SixLabors/ImageSharp) library. I would recommend moving to that unless you have specific limitations that prevent you from doing so.
