### ISSUE TITLE
Crop() can truncate oriented images

### ISSUE THREAD

**Issue by kruparker** [JimBobSquarePants/ImageProcessor#818]
### Description
When cropping a tiff image with exif orientation and EXIF preserved, Image Width and Height are not updated to reflect the orientation (they keep "not oriented" values).
Wouldn't be a problem if when  calling Crop() method, the image wasn't truncated.

In my case, Width is large than Height;  landscape 'définition' but 90° orientation (ccw), paint shows it landscape, but a good picture viewers (xnview) shows it portrait. 

So, after some proper calculations to offset x,y values of a Rectangles (because Crop() Method takes orientation into account and my first calculations were on the not oriented image)
the result image is truncated at "original Height", not "oriented Height". 

==> See attached picture, it should clear.

Maybe Width/Height don't need to be update, just the crop() method as to take orientation into account for oriented picture maximums.

### Steps to Reproduce
```

//Let's say you have an image of size 1500 x 800 ; with an orientation of 90°, so it's displayed as 800 x 1500.


Rectangle rectangle = new Rectangle(200,200,500,1000); 
// => effective crop points : 200,200 to 700, 1200 (On the ORIENTED picture)

ImageFactory imageFactory = new ImageFactory(true);

imageFactory.Load("some\path\to\image.tif");
Console.WriteLine("Before Crop "+ imageFactory.Image.Width+" x "+imageFactory.Image.Height);
// output : Before Crop  1500 x 800

imageFactory.crop(rectangle);
Console.WriteLine("After Crop "+ imageFactory.Image.Width+" x "+imageFactory.Image.Height);
// output : After Crop  500 x 600 
//instead of    500 x 1000

imageFactory.save("some\path\to\image2.tif");
// image is truncated but first corner and orientation are good.
```

### System Configuration
- ImageProcessor version: 2.9.1 (latest stable release)
- Environment (Operating system, version and so on): Windows 10 pro, Visual Studio 2019
- .NET Framework version: 4.7.2
- Additional information:
![crop_bug](https://user-images.githubusercontent.com/5137511/94704769-8f2fd900-0340-11eb-9915-684e99b8c36b.png)

**Comment by JimBobSquarePants** [comment]
See #559 Crop already takes orientation into consideration.

https://github.com/JimBobSquarePants/ImageProcessor/commit/3b6325e495830b28bcda12c3331a8fe0637c8bcb

**Comment by kruparker** [comment]
yup, I've already seen this post, and I did the math to crop the right (oriented) zone .
But the fact is that my crop rectangle is truncated by a false "max value" somewhere ...

Sad to ear the library is not maintained anymore, I'll try to do it otherwise.
Or I'll try to browse the code and see if I can find a fix, but I'm not so confident in my c# skills to do it

**Comment by JimBobSquarePants** [comment]
It'll be a case of attaching a debugger to the current code while working with your troublesome image and seeing what happens in the `CropProcessor`...  Not too difficult in the bigger scheme of things. The current fix certainly works with other images.

>Sad to ear the library is not maintained anymore

It's simply a case of time and effort. I have a much better library (ImageSharp - no Tiff support yet unfortunately, work in progress) that I am focused on. System.Drawing itself is a technological dead end and MS recommend ImageSharp over it for future use.
