### ISSUE TITLE
Disable disk cache - saving cache files - improve performance

### ISSUE THREAD

**Issue by wtct** [JimBobSquarePants/ImageProcessor#819]
I think that an option to disable disk cache is a must have functionality for this very popular package.

Please take into consideration this option because there is a lot more efficient caching strategies instead. In our scenario we have a lot of files shared via virtual directory and this cache causes a lot of files being created. We have two proxy servers HAProxy with varnish cacheing and ngnix. Creating cacheing files is unnecessary.

I was trying to set maxDays to 0 but caching files are still generated.

It would be very helpful that changing this option to 0 disable all cacheing logic to improve performance.

**Comment by ronaldbarendse** [comment]
This is already discussed in https://github.com/JimBobSquarePants/ImageProcessor/issues/155: ImageProcessor won't support disabling the cache, but you can write your own `IImageCache` if you really wanted to...

And keep in mind that setting maxDays to 0 and using cache trimming can result in file locking issues, as the file is still being downloaded while ImageProcessor is trying to the delete it: https://github.com/JimBobSquarePants/ImageProcessor/issues/793.

**Comment by JimBobSquarePants** [comment]
@wtct No we are not implementing any new features as focus has shifted to ImageSharp and accompanying libraries. 

https://github.com/JimBobSquarePants/ImageProcessor#roadmap
