### ISSUE TITLE
Constrain(Size) results in invalid ICC profile for CMYK JPEG

### ISSUE THREAD

**Issue by robertjf** [JimBobSquarePants/ImageProcessor#820]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm using the following code to produce a range of thumbnails from an image when it's saved to the server (via Umbraco Media Saved event):

```
    using (var image = new ImageFactory(MetaDataMode.All).Load(imageLocation)) {
        image.Constrain(new Size(thumbConfig.MaxWidth, thumbConfig.MaxHeight));
        string thumbPath = GenerateThumbnailPath(thumbDestFilePath, thumbConfig.Key, "jpg");
        image.Save(thumbPath);
    }
```

I've attached a copy of the original image for reference.

When I open the resulting image in PhotoShop, I get the following alert:

![image](https://user-images.githubusercontent.com/818101/95146048-84ee5e80-07c8-11eb-91e8-5b45de35adfc.png)

Attached images for you to play with:

Original:

![bt-symbol-cmyk-coated-fogra39-iso-12647-alpha-no](https://user-images.githubusercontent.com/818101/95146972-1c54b100-07cb-11eb-8d35-885372c70b67.jpg)

Generated Thumbnail:

![bt-symbol-cmyk-coated-fogra39-iso-12647-alpha-no_thumb_150](https://user-images.githubusercontent.com/818101/95146976-1f4fa180-07cb-11eb-919a-9f1e7f9a4d65.jpg)

### Steps to Reproduce
See the code above.

### System Configuration

Umbraco 7.15.x on Local dev machine as well as hosted virtual machine.

- ImageProcessor version: 2.9.1
- ImageProcessor.Web version: 4.12.1
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): Windows 10

- .NET Framework version: 4.7.2
- Additional information:

**Comment by ronaldbarendse** [comment]
Constrain will effectively only resize the image to fit the supplied size while keeping the aspect ratio, so it shouldn't be something specific to the `Constrain()` method.

Looking at the original image, it's has a CYMK color profile and the resulting image is saved as RGB, so that might cause the ICC profile to become invalid.

Maybe @JimBobSquarePants knows more about what's supported by `System.Drawing`, as it's likely CMYK support isn't great to start with and ImageProcessor won't be able to fix this issue.

**Comment by JimBobSquarePants** [comment]
I don't see anything here that confirms the original input file works with Photoshop. 

Is the linked generated thumbnail the one that is supposed to be corrupted? I can open it with every piece of software I have (I don't have Photoshop) and JpegSnoop reports no errors.

Either way, nothing we can do if System.Drawing mangles the profile.

**Comment by robertjf** [comment]
Thanks guys, @JimBobSquarePants out of interest, is saving with cmyk colour profile supported at all by IM?

**Comment by ronaldbarendse** [comment]
@robertjf A quick Google search indicates the `System.Drawing.Bitmap` stores the image data as (A)RGB-values. The only methods I can find that do something with color profiles are [`ImageAttributes.ClearOutputChannelColorProfile`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.imageattributes.clearoutputchannelcolorprofile?view=netframework-4.5.2) and [`ImageAttributes.SetOutputChannelColorProfile`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.imageattributes.setoutputchannelcolorprofile?view=netframework-4.5.2): maybe clearing the color profile gets rid of the corrupted format, although I don't see a way to save the image in CMYK-color format.

As CMYK images should only be used for print, I don't see why you would want ImageProcessor to support this: use specific print/design software to edit these images. But as you've mentioned Umbraco, I assume this image is used on a website and should be uploaded as RGB image in the first place.
