### ISSUE TITLE
RemoteFile: GetResponseAsync 132:The response status code doesn't indicate the success of the operation: 403 (Forbidden).

### ISSUE THREAD

**Issue by aammendola-athirat** [JimBobSquarePants/ImageProcessor#821]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
My web application uses the RemoteImageService and for the most part it works fine. Howevere, the error in title occurs when i show images from hrs. An example is:

`/remote.axd?https://foto.hrsstatic.com/fotos/0/3/256/256/80/FFFFFF/http%3A%2F%2Ffoto-origin.hrsstatic.com%2Ffoto%2F0%2F4%2F0%2F8%2F%2Fteaser_040827.jpg/0/750%2C500/6/Best_Western_President-Rome-Exterior_view-3-40827.jpg?width=180&height=115&mode=crop&anchor=bottomright`

I try to copy the image URL in the browser and i see it rightly. 
In security.config file, i added image URL to the whitelist:
`<whitelist>
        <add url="https://foto.hrsstatic.com" />
      </whitelist>`

Why i can't resize the remote image?

### Steps to Reproduce
Install ImageProcessor.Web Use /remote.axd with the same URL in the example.

### System Configuration

- ImageProcessor version: 2.9.1
- ImageProcessor.Web version (if applicable) 4.12.1
- .NET Framework version: 4.8

>

**Comment by JimBobSquarePants** [comment]
What happens when you try to request the file when running from the sample site in this repository?

**Comment by aammendola-athirat** [comment]
When my application is running and i try to request the file, i see an error page (HTTP Error 404.0 - Not Found). 
I open a new target black and i paste the following URL:
`localhost:port/remote.axd?https://foto.hrsstatic.com/fotos/0/3/256/256/80/FFFFFF/http%3A%2F%2Ffoto-origin.hrsstatic.com%2Ffoto%2F0%2F4%2F0%2F8%2F%2Fteaser_040827.jpg/0/750%2C500/6/Best_Western_President-Rome-Exterior_view-3-40827.jpg?width=180&height=115&mode=crop&anchor=bottomright`

I haven't this error with other remote image URLs.

**Comment by JimBobSquarePants** [comment]
That's not what is asked.

I asked what was the result when you downloaded the source code for the repository and ran the request using the sample website.

https://github.com/JimBobSquarePants/ImageProcessor/tree/a94fb903e49f6fa5f47c6ea58d27af55ce8ff89c/tests/ImageProcessor.TestWebsite

**Comment by aammendola-athirat** [comment]
Ok, i'm sorry for the issue. Thank you for your replies
