### ISSUE TITLE
Issue with query strings on images

### ISSUE THREAD

**Issue by RetoxChris** [JimBobSquarePants/ImageProcessor#823]
Hello,

I've recently bought a software called Flippingbook https://flippingbook.com/ which creates HTML 5 brochures. I have published a magazine and it works fine locally. 

However when I upload the magazine to my website, I am getting issues with accessing the files in the magazine and it's causing a server error. The software automaically adds query strings to the images in the magazine. Here is a link to the brochure:

https://www.s.co.uk/brochure-2/index.html

The console errors reveal the images have been set up as:

https://www.s.co.uk/brochure-2/files/assets/common/page-html5-substrates/page0001_2.jpg?uni=b5e7fd95e5123a5801a44906ede1a557

However, when you remove the query string the images show:

https://www.s.co.uk/brochure-2/files/assets/common/page-html5-substrates/page0001_2.jpg

We use the ImageProcessor on our site, and was told by the team at Flipping Book to as for your assistance.

**Comment by JimBobSquarePants** [comment]
You can use the ImageProcessingModule.ValidatingRequest  event to ignore those query strings.

https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

**Comment by RetoxChris** [comment]
While the original link i posted now works adding the fix you recommend my second link https://www.medburnhomes.co.uk/brochure-2/files/assets/common/page-html5-substrates/page0001_2.jpg?uni=b5e7fd95e5123a5801a44906ede1a557 doesnt. The console suggests a Bad Request and server gives the same error as before. Is there anything else i need to add/configure

**Comment by JimBobSquarePants** [comment]
Are you seeing `arg.Cancel` to `true`? If so, don't. Just chop the parameter off the request. ImageProcessor.Web will then ignore it and the static file handler will take over

**Comment by RetoxChris** [comment]
Here is my code based on your article and understanding of what you may want me to do. 

In debug mode i can see all the values, I try and remove the parameter from the collection but it doesnt make a difference. I set arg.Cancel = false but also noticed it never enters this block
 

        protected override void OnApplicationStarted(object sender, EventArgs e)
        {
            base.OnApplicationStarted(sender, e);
            ImageProcessingModule.ValidatingRequest += ImageProcessingModule_ValidatingRequest;
        }

 

        private void ImageProcessingModule_ValidatingRequest(object sender, ImageProcessor.Web.Helpers.ValidatingRequestEventArgs args)
        {
            if (!string.IsNullOrWhiteSpace(args.QueryString))
            {
                var queryCollection = HttpUtility.ParseQueryString(args.QueryString);
                queryCollection.Remove("uni");
                if (queryCollection.AllKeys.Contains("alpha"))
                {
                    args.Cancel = false;
                    return;
                }

 

                // If there's a crop parameter, force it to always just be a specific value
                if (queryCollection.AllKeys.Contains("crop"))
                {
                    queryCollection["crop"] = "10,10,10,10";

 

                    // This performs the reverse of ParseQueryString since the result of ParseQueryString
                    // is actually an instance of System.Web.HttpValueCollection
                    args.QueryString = queryCollection.ToString();
                }
            }
        }


Could you confirm what the final code should be?

**Comment by ronaldbarendse** [comment]
Maybe a better approch would be to completely [remove the ImageProcessorModule](https://stackoverflow.com/questions/28856991/removing-unused-http-handlers-for-better-performance-security/29060020) within the directory contains the static flipbook files?

This can be done by adding the following configuation into `brochure-2\Web.config`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.web>
        <httpModules>
            <remove name="ImageProcessorModule" />
        </httpModules>
    </system.web>
    <system.webServer>
        <modules>
            <remove name="ImageProcessorModule" />
        <modules>
    </system.webServer>
</configuration>
```

**Comment by RetoxChris** [comment]
My current config file is 

 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.web>
    <httpModules>
      <remove name="ImageProcessorModule" />
      <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </httpModules>
  </system.web>
  <system.webServer>
    <staticContent>
        <remove fileExtension=".svg" />
        <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
    </staticContent>
    <modules runAllManagedModulesForAllRequests="true">
      <remove name="ImageProcessorModule" />
      <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </modules>
  </system.webServer>
</configuration>

 

I have tried removing "<add name=...." but that didnt make a difference. Tried to remove httpModules and again that didnt work or threw a config error. I have tried reverting back to the orginal Global.asax and using the code i posted above but nothing worked. Is there something im missing or do i need a combination of things to match in order for this to work?

 

The web.config file is in the root directory of Test only.

 

Version of IIS is IIS version 8.5 (Win 2012 R2)

 

Test link https://www.medburnhomes.co.uk/test/index.html

 

Server error Exception message: The request /test/files/assets/common/page-html5-substrates/page0001_1.jpg?uni=340056c1ff306e38e3ec88b625214e28 could not be understood by the server due to malformed syntax.
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__32.MoveNext()

**Comment by JimBobSquarePants** [comment]
Why have you got all that extra code in your event handler?

**Comment by RetoxChris** [comment]
Sorry which section are you referring to? I copied the code from the link but can you confirm what you need me to change to so i can test?

**Comment by JimBobSquarePants** [comment]
The code in the link is a generic example of how the event can be handled. You need to write the code to handle your specific case.

**Comment by JimBobSquarePants** [comment]
```c#
private void ImageProcessingModule_ValidatingRequest(object sender, ImageProcessor.Web.Helpers.ValidatingRequestEventArgs args)
{
    if (!string.IsNullOrWhiteSpace(args.QueryString))
    {
        // Read
        var queryCollection = HttpUtility.ParseQueryString(args.QueryString);

        // Remove
        queryCollection.Remove("uni");

        // Update
        args.QueryString = queryCollection.ToString();
    }
}
```

**Comment by RetoxChris** [comment]
I just now made a change to the original code which is close to what you have posted once i understood that was a boiler template code :-( - looks to be working now though i'll test a few scenarios- Thanks

**Comment by JimBobSquarePants** [comment]
Hurrah! 🚀  Happy to help. Glad it's working
