### ISSUE TITLE
GetPixel and SetPixel functions in FastBitmap.cs assume that the image format is always 32bits per pixel, leading to errors when using 24bit images such as jpegs.

### ISSUE THREAD

**Issue by JonathanNorton** [JimBobSquarePants/ImageProcessor#825]
GetPixel assumes that the image format is 32bpp. If the format is only 24bpp, taking the alpha value will actually be sampling from the next adjacent pixel. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/a94fb903e49f6fa5f47c6ea58d27af55ce8ff89c/src/ImageProcessor/Imaging/FastBitmap.cs#L281-L296

Line 294 calls operator[,], which multiples the X coordiante by 4 instead of multipling by the pixelSize variable.

https://github.com/JimBobSquarePants/ImageProcessor/blob/a94fb903e49f6fa5f47c6ea58d27af55ce8ff89c/src/ImageProcessor/Imaging/FastBitmap.cs#L249

**Comment by JimBobSquarePants** [comment]
That's  by design. It's not for any other pixel format.
