### ISSUE TITLE
rewrite image url

### ISSUE THREAD

**Issue by newyhj** [JimBobSquarePants/ImageProcessor#828]
version:imageprocessor/imageprocessor.web/imageprocessor.plugin.webp latest version,mvc5

i want rewrite image url,so,write some test code ex:

source file path:/uploads-pv/2101/trunnion-ball-valve.jpg
rewrite url:/uploads-pv/2101/trunnion-ball-valve.webp

web.config 
 <httpModules>
      <add name="ImageProcessorModule" type="Zm.Web.Models.ImageProcessingModuleFix,Zm.Web" />
    </httpModules>

ImageProcessingModulefix.cs code
{

    public class ImageProcessingModuleFix:ImageProcessingModule
    {
        public ImageProcessingModuleFix()
        {
            ImageProcessingModule.ValidatingRequest += (sender, args) =>
            {
                var url=args.Context.Request.RawUrl.Replace(".webp", ".jpg")+"?format=webp&quality=70";

                args.Context.RewritePath(url, true);
                args.Cancel = true;
            };
        }
    }
}
question:
1.image no cache
2.image no compression

how should operatoe it?thanks

**Comment by ronaldbarendse** [comment]
Please use the issue template and include the used versions by number (not 'latest'). It's also not clear what your intention is, as it's missing a descriptive explanation of what you expected and what you think is the bug...

In the example code, you're changing the path to the original image from `.webp` to `.jpg`, but also always rewriting and cancelling ImageProcessor from processing the image, which makes no sense. This event can only be used to change the query string, as per documentation: https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events.
