### ISSUE TITLE
Converting to webp doesn't work in a standard .NET 5 docker container

### ISSUE THREAD

**Issue by elementhrobbie** [JimBobSquarePants/ImageProcessor#833]
### Prerequisites
I'm Using the latest Nuget packs and the latest .NET version.

### Description
I'm trying to use the ImageProcessor nuget package to convert jpeg images to webp images. When I run it locally on my Windows 10 dev machine, it works perfectly. When I run it in a (linux) docker container, it failes with an exception I can't place:
`System.TypeInitializationException: The type initializer for 'ImageProcessor.Plugins.WebP.Imaging.Formats.NativeMethods' threw an exception. ---> System.IO.IOException: The file '/location/of/my/release/ImageProcessor.dll' already exists. at System.IO.FileSystem.CreateDirectory(String fullPath) at System.IO.DirectoryInfo.Create() at ImageProcessor.Configuration.NativeBinaryFactory.<>c__DisplayClass7_0.b__0(String b) at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory) at ImageProcessor.Configuration.NativeBinaryFactory.RegisterNativeBinary(String name, Byte[] resourceBytes) at ImageProcessor.Plugins.WebP.Imaging.Formats.NativeMethods..cctor() --- End of inner exception stack trace ---`

### Steps to Reproduce
Put this in the code:
```
using (var imageFactory = new ImageFactory()) {

                    imageFactory.Load(imageFilePath+extension)

                                .Format(new WebPFormat())

                                .Quality(75)

                                .Save(imageFilePath + ".webp");

                    _logger.LogDebug($"Converted to webp.");

            }
```

And create a standard .NET 5 docker container to run the project.

### System Configuration
Docker on Linux (the host is Ubuntu 20.04 but I don't think that matters), and the Docker Image is the official ASP.Net 5 runtime docker image.

**Comment by JimBobSquarePants** [comment]
.NET 5 is based on the .NET Core runtime which is not supported.

See #830 #829 #826 and #806

If you had used the provided template to raise an issue instead of deleting it you would have noticed the part that said. 

```
- [ ] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
```

and realized this.
