### ISSUE TITLE
Using a 3000x3000 pixel image produce a System.ArgumentException: Parameter is not valid

### ISSUE THREAD

**Issue by marcocavanna** [JimBobSquarePants/ImageProcessor#837]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
While loading a Stream of an Image with 3000x3000 pixel I receive a System.ArgumentException: Parameter is not valid
```
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap.SetResolution(Single xDpi, Single yDpi)
   at ImageProcessor.Common.Extensions.ImageExtensions.Copy(Image source, AnimationProcessMode animationProcessMode, PixelFormat format, Boolean preserveExifData)
   at ImageProcessor.ImageFactory.Load(Stream stream)
```

### Steps to Reproduce
Image is coming from a Form and is a IFormFile instance
```c#
using var stream = new MemoryStream();
formFile.CopyTo(stream);

using var imageFactory = new ImageFactory();
imageFactory.Load(stream);
// Line above produce error
```

### System Configuration

- ImageProcessor version: 2.9.1
- ImageProcessor.Web version (if applicable) none
- Other ImageProcessor packages and versions: none
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: NET 5.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
ImageProcessor isn’t supported on .NET5. (See readme) you should be using ImageSharp.
