### ISSUE TITLE
SSRF Vulnerability

### ISSUE THREAD

**Issue by aammendola-athirat** [JimBobSquarePants/ImageProcessor#840]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
During the activity, it has been found an endpoint, which makes use of the ImageProcessor library that could expose the application to Server Side Request Forgery attacks.
With a server side request forgery (SSRF) an attacker is able to send a request created by a vulnerable web application.
The remote.axd endpoint allows processing an external image through the ImageProcessor library. An attacker could abuse this functionality in order to forge arbitrary HTTP request.
Although the library poses some validation to the host that can be specified in the address allowing to define a whitelist of trusted domains, it can be bypassed as the validation method only verifies that the first part of the string matches the allowed domain.
An attacker can define a subdomain like the following one in order to bypass such controls: alloweddomain.com.attacker.com

### Steps to Reproduce
The following code is extracted from the source of the ImageProcessor library and shows the validation routine.
URL: https://github.com/JimBobSquarePants/ImageProcessor/blob/master/src/ImageProcessor.Web/Services/RemoteImageService.cs
Function IsValidRequest.

### System Configuration

- ImageProcessor version: 2.9.1
- ImageProcessor.Web version (if applicable) 4.12.1
- Other ImageProcessor packages and versions: 
- Environment (Operating system, version and so on):
- .NET Framework version: 4.8
- Additional information:

**Comment by JimBobSquarePants** [comment]
What’s the actual risk here though?

**Comment by aammendola-athirat** [comment]
The following screenshot shows how to bypass the restrictions as stated before. As can be seen, a DNS query and an HTTP request have been sent to the attacker-controlled server.
![image](https://user-images.githubusercontent.com/73110304/127164669-9507607c-af7e-4b08-9a1d-cfde3bc46e8b.png)

**Comment by JimBobSquarePants** [comment]
That’s not what I mean. I mean what’s the repercussions? What damage can be done?

Any actual image decoding is performed by System.Drawing which is hardened against fuzzing or injection within encoded images.

**Comment by aammendola-athirat** [comment]
SSRF is usually used to hit internal firewall systems that are normally inaccessible to a malicious user from the outside network.
For references: https://portswigger.net/web-security/ssrf

**Comment by JimBobSquarePants** [comment]
I know what an SSFR is. I’m asking for specifics.

**Comment by aammendola-athirat** [comment]
I don't know what are the specific repercussions. A WAPT has found the Medium Risk vulnerability described above in your library.
I think that was correct to notify you. You will fix the vulnerability or you will ignore her?
