### ISSUE TITLE
Unable to access images on Azure Private Storage Account

### ISSUE THREAD

**Issue by TruyenMLe** [JimBobSquarePants/ImageProcessor#842]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We're using Umbraco 7 and deploy on Azure environment. Our storage account was public and images are working perfectly. Now we want to switch storage account to private and we follow the suggestion from this post (https://github.com/JimBobSquarePants/ImageProcessor/issues/699) but images are still using the cache urls and not displaying because of private access. However, It's working for newly uploaded images, only existing ones are having issue.  We don't want to re-upload the images because there's quite a few of them, in GBs. Here's the config setting below.

### Steps to Reproduce
![Screen Shot 2021-08-24 at 10 35 52 AM](https://user-images.githubusercontent.com/6933968/130656292-7d120ab5-9e52-42c7-865b-504ffdf809ea.png)
![Screen Shot 2021-08-24 at 10 48 58 AM](https://user-images.githubusercontent.com/6933968/130657576-c94db646-5c6b-4f07-9fb2-e6eef94784f2.png)

### System Configuration

- ImageProcessor version 2.8.0
- ImageProcessor.Plugins.WebP version 1.3.0
- ImageProcessor.Web version 4.11.0
- ImageProcessor.Web.Config version 2.6.0
- ImageProcessor.Web.Plugins.AzureBlobCache version 1.7.1
- .NET Framework version: 4.7.2
- Umbraco version 7.15.7

Any suggestions would be great, thanks

**Comment by JimBobSquarePants** [comment]
Ask in an Umbraco forum. Issue trackers are for issues.
