### ISSUE TITLE
Black image while creating a gif from a transparent image and a transparent gif

### ISSUE THREAD

**Issue by NoobyPilot** [JimBobSquarePants/ImageProcessor#843]
### Description

While combining a gif and an image to create a new gif, I end up getting a black background, even though both the gif and the image used to have a transparent background

### Steps to Reproduce

My code: 

`
using System;
using System.Drawing;
using ImageProcessor;
using ImageProcessor.Imaging;
using ImageProcessor.Imaging.Formats;

namespace ImageTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var fact = new ImageFactory();
            fact.Load("G:\\Bilder\\yuki_sip.png");

            var gifFact = new ImageFactory();
            gifFact.Load("G:\\Bilder\\petPetFrames.gif");

            gifFact.AnimationProcessMode = AnimationProcessMode.All;
            
            GifDecoder decoder = new GifDecoder(gifFact.Image, AnimationProcessMode.All);
            
            fact.Constrain(new Size(decoder.Width, decoder.Height));
            GifEncoder encoder = new GifEncoder(decoder.Width, decoder.Height, decoder.LoopCount);
            
            
            
            for (int i = 0; i < decoder.FrameCount; i++)
            {
                var frame = decoder.GetFrame(gifFact.Image, i);
                var imgFact = new ImageFactory();
                var testFact = new ImageFactory();
                imgFact.Load(fact.Image);

                testFact.Load(frame.Image);
                
                var squishX = Math.Sin(2 * Math.PI * i / decoder.FrameCount) / 20 + 1;
                var squishY = Math.Cos(2 * Math.PI * i / decoder.FrameCount) / 20 + 1;

                imgFact.Resize(new Size((int)Math.Round(imgFact.Image.Size.Width * squishX), (int)Math.Round(imgFact.Image.Size.Height * squishY)));

                ImageLayer layer = new ImageLayer();
                layer.Image = frame.Image;
                imgFact.Overlay(layer);
                
                var newFrame = new GifFrame();
                newFrame.X = frame.X;
                newFrame.Y = frame.Y;
                newFrame.Delay = frame.Delay;
                newFrame.Image = imgFact.Image;
                encoder.AddFrame(newFrame);
                imgFact.Dispose();
            }
            var editedGif = encoder.Save();
            gifFact.Load(editedGif);
            
            gifFact.Save("G:\\Bilder\\edt_yuki_pat.gif");
        }
    }
}'

![yuki_sip(The image)](https://user-images.githubusercontent.com/43069144/130687439-77921d23-ee86-4d6b-992f-0d2dfb45e9ce.png)
![petPetFrames(The gif)](https://user-images.githubusercontent.com/43069144/130687485-6d7618a0-9196-4195-9a8b-29bdebe68b7f.gif)

I have already been able to verify by simple saving each image, that the image factory is not the issue. As I read on here that this problem had only come to life as of a certain version of the library, I downgraded as far as possible without breaking the code, but all versions produced the same output for me, a gif with black background.

### System Configuration

- ImageProcessor version: 2.9.1
- Other ImageProcessor packages and versions:
- System.Drawing.Common 6.0.0-preview.7.21377.19 (Issue also persists with version 5.0.2)
- Environment (Operating system, version and so on):
- Windows 10 64 bit
- .NET Framework version:
- net5.0

**Comment by JimBobSquarePants** [comment]
ImageProcessor isn’t supported in .NET 5. Huge warning in the repository readme. 

Use ImageSharp instead
